### ISSUE TITLE
Map http status codes to OpenTelemetry status

### ISSUE THREAD

**Issue by danielkhan** [open-telemetry/opentelemetry-specification#100]
After the HTTP typed spans are part of the spec we have to map `status_code` to OpenTelemetry span status. 
Reference:
https://github.com/open-telemetry/opentelemetry-specification/blob/c4b7f4307de79009c97b3a98563e91fee39b7ba3/work_in_progress/opencensus/HTTP.md#status

**Comment by tedsuo** [comment]
This work has been completed in #263
