### ISSUE TITLE
Unclear OTEL_EXPORTER_OTLP_COMPRESSION values for environment variable support

### ISSUE THREAD

**Issue by wilguo** [open-telemetry/opentelemetry-specification#1001]
Hi everyone, 

As per spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md#opentelemetry-protocol-exporter 

It says that `OTEL_EXPORTER_OTLP_COMPRESSION` environment variable should be supported, however I'm unclear as to what values it should take on. Could someone clarify? Thank you!

**Comment by tigrannajaryan** [comment]
Only "gzip" and no compression are supported today.

**Comment by wilguo** [comment]
Thank you

**Comment by aabmass** [comment]
@tigrannajaryan the spec doesn't say specifically what `OTEL_EXPORTER_OTLP_COMPRESSION` should be for no compression. Should it be `no_compression`, or empty string, or un-set?

Also wondering why [GRPC `deflate`](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/core/lib/compression/compression.cc#L71-L72) is excluded. Is it not well supported across GRPC implementations or for compatibility with `http/json`?

**Comment by tigrannajaryan** [comment]
Spec only talks about compressions for otlp/http. It is an omissions that we don't define what is possible for grpc (I didn't know `deflate` supported. Let's make sure we have it in the spec.

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, allowing changes related to this issue for GA if editorial changes only
