### ISSUE TITLE
Define metric semantic conventions for FaaS

### ISSUE THREAD

**Issue by jgals** [open-telemetry/opentelemetry-specification#1013]
**What are you trying to achieve?**
Defined semantic conventions for function as a service (FaaS) metrics, often referred to as "serverless" metrics.

**What did you expect to see?**
FaaS metric semantic convention documentation in markdown generated from YAML definitions as per #547.

**Additional context.**
These should be roughly analogous to the trace semantic conventions for FaaS spans [defined here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/faas.md). For reference, metric semantic conventions for HTTP operations are already [defined here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/http-metrics.md).

**Comment by jgals** [comment]
Hey @jmacd, can we add @kolanos to the project so he can be assigned to this issue? I believe he's working on a PR.

**Comment by Oberon00** [comment]
@kolanos just needs to comment on this issue, then he can be assigned.

**Comment by kolanos** [comment]
@Oberon00 Commented. :)

**Comment by skonto** [comment]
@kolanos are you still involved in this issue? I am interested in defining the related faas metrics as I am working on defining these for [Knative](https://knative.dev/).

**Comment by kolanos** [comment]
@skonto If you want to pick up where I left off, I'm +1. Happy to provide feedback as well.
