### ISSUE TITLE
API: Consider having `GetEntry` instead of `GetEntryValue` in `DistributedContext`.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-specification#103]
Original discussion: https://github.com/open-telemetry/opentelemetry-specification/pull/97/files#r292227302.

The main advantage of `GetEntry` is it also returns the metadata associated with the key-value pair.

**Comment by jmacd** [comment]
There is a lot of ongoing work on this topic, please see https://github.com/open-telemetry/oteps/pull/66

**Comment by jmacd** [comment]
I believe the need for this is eliminated by #420 as the spec for context propagation has removed the `Entry` concept.
