### ISSUE TITLE
Baggage specification is not in line with the W3C specification; propagator mapping is not defined

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#1050]
**What are you trying to achieve?**
I'm starting to work on a W3C Baggage Propagator, and I'm finding that the mapping from W3C baggage headers it not specified for the OpenTelemetry Baggage. In particular, the W3C spec supports metadata associated with each key/value pair, and the OTel spec doesn't not specify any metadata.

What did you expect to see?

A specification of how to map W3C baggage header(s) to the OTel Baggage implementation (and back).

**Additional context.**
* Our current spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/baggage/api.md
* The W3C spec: https://w3c.github.io/baggage/

**Comment by arminru** [comment]
@open-telemetry/technical-committee should this be required-for-ga?
