### ISSUE TITLE
The Baggage API is not consistent with other APIs

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#1051]
**What are you trying to achieve?**
Implement the Baggage API in such a way that it's consistent with the other OTel APIs

What did you expect to see?
I expected the Baggage to be a thing that could be extracted, wholesale out of the Context, manipulated via an extra-Context API, then put back into the Context (if needed). Instead, the API requires all key/value interactions with the Baggage to be via the Context. So, to read and add some keys to the baggage, you have to do something like:

```java
Entry entry = BaggageContextUtils.getValue(context, "foo");
Context clearedContext = BaggageContextUtils.clearBaggage(context);
Context newContext = BaggageContextUtils.addValue(clearedContext, "foo", new Entry("stuff"));
Context yetAnotherNewContext = BaggageContextUtils.addValue(newContext, "boo", new Entry("other stuff"));
```

I was expecting to provide something like this, in Java:
```java
Baggage baggage = BaggageContextUtils.getBaggage(context);
Entry entry = baggage.getEntry("foo");
Baggage newBaggage = new Baggage();
newBaggage.setEntry("baz", new Entry("stuff"));
newBaggage.setEntry("boo", new Entry("other stuff"));
Context newContext = BaggageContextUtils.setBaggage(context, baggage);
```

These APIs are functionally equivalent, but it feels quite awkward to manipulate individual keys coming off the wire via the Context, rather than deal with Baggage as a unified construct.

**Additional context.** 

Current Baggage API spec is here:  https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/baggage/api.md

**Comment by andrewhsu** [comment]
@jkwatson from the issue triage mtg today, assigning to you to come up with a draft proposal

**Comment by jkwatson** [comment]
> @jkwatson from the issue triage mtg today, assigning to you to come up with a draft proposal

I sense I may have been thrown under the bus by a co-worker.  ;)
