### ISSUE TITLE
Additional Cassandra Attributes

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-specification#1058]
**What are you trying to achieve?**
I'd like to define more cassandra attributes, as requested by @trask in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1314#issuecomment-703134133
Additionally, some of these tags may apply to other DBs as well.

What did you expect to see?

I expected to see more detailed information, including table name, query execution information, etc. Listed below.
```java
  public static final String QUERY_PAGE_SIZE = "query.pageSize";
  public static final String QUERY_CL = "query.cl"; // consistency level
  public static final String DB_HOST_DC = "db.host.dc";
  public static final String DB_HOST_ID = "db.host.id";
  public static final String QUERY_SPECULATIVE_EXECUTION_COUNT = "query.speculativeExecutionCount";
  public static final String QUERY_IDEMPOTENCE = "query.idempotence";
  public static final String QUERY_TABLE = "query.table";
```
**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

Some of these tags already exist in the opentracing cassandra instrumentation https://github.com/opentracing-contrib/java-cassandra-driver/blob/master/opentracing-cassandra-driver-3/src/main/java/io/opentracing/contrib/cassandra/TracingSession.java#L500

**Comment by trask** [comment]
@open-telemetry/specs-approvers are new semantic attributes `allowed-for-ga`, or on hold until `after-ga`? thx

**Comment by arminru** [comment]
@trask If they don't extend existing conventions with required attributes but are either entirely new or only add optional attributes, they should be allowed-for-ga IMHO, since they won't produce any additional work for SIGs.
