### ISSUE TITLE
Missing spec for Span ID creation for dropped/record-only spans

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1060]
**What are you trying to achieve?**

I am trying to ensure that span ID creation for spans that are dropped or only recorded (but not sampled) is uniform across different language implementations.

**Additional context.**

As explained in https://github.com/open-telemetry/opentelemetry-specification/issues/864#issuecomment-689513021 the spec is silent on what to do for IDs of spans that are not sampled. #998 suggest to reuse the parent-span-id for dropped or use zero if there is none, but use a new span ID for everything else. A simpler alternative would be to simply add the sentence "A new Span ID MUST always be generated, even for dropped spans".

This is not purely an optimization issue, it impacts the observable behavior of the monitored application when the unsampled span is injected (and then potentially used as parent on the other side).

**Comment by Oberon00** [comment]
CC @alolita @anuraaga

**Comment by marcingrzejszczak** [comment]
Is this issue also related to being able to drop a span whatsover? That means that you're starting a span and after some time you decide not to record it. You want to end it but not report it anywhere. Currently I don't see that the spec allows it nor the java implementation.

**Comment by Oberon00** [comment]
> Is this issue also related to being able to drop a span whatsover? That means that you're starting a span and after some time you decide not to record it. 

No, not at all. This issue is only about the reaction to the existing (head-based) DROP sampling decision. If you want to discuss aborting/dropping a span later, please open a new issue.
