### ISSUE TITLE
API: Should we move the current span API to be part of Scope?

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-specification#108]
Original discussion: https://github.com/open-telemetry/opentelemetry-specification/pull/105#discussion_r292694745.

**Comment by lmolkova** [comment]
With named tracers it becomes even more relevant - Current span does not depend on Tracer.

I propose having static method/property on Span like `Span.getCurrent()` or `Span.Current`

**Comment by bogdandrutu** [comment]
I think it still belongs to trace package but probably not to Tracer. The reason to have it in the trace package is because it depends on the Span API and having context depending on trace will not probably be a good separation of concepts.

**Comment by Oberon00** [comment]
Be careful with static methods in the API. API-implementors won't be able to override them.

**Comment by carlosalberto** [comment]
I feel like this is solved by OTEP 66, or is there something we are missing still?

**Comment by lmolkova** [comment]
[OTEP-66](https://github.com/open-telemetry/oteps/blob/master/text/0066-separate-context-propagation.md#optional-automated-context-management) suggests to have `GetCurrent` and `SetCurrent` Context.

I probably miss something, but I cannot find what is relationship between `Span` and `Context`. I guess `Span` is just an item on the context and then it solves this issue,

**Comment by carlosalberto** [comment]
>  I guess Span is just an item on the context and then it solves this issue,

Yes, this is the case ;) Sounds like we can close this issue then? Or do you think there's something we still need to address?

**Comment by lmolkova** [comment]
Thanks for the explanation, it really helps. I agree this can be closed (but I don't have permissions to do it)

**Comment by carlosalberto** [comment]
Thanks! closing this issue.
