### ISSUE TITLE
Define API compatibility story

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#109]
We need to define the API compatibility story, particularly:
- How OpenTelemetry API evolves over time, what changes are allowed and how they should be made, how breaking and non-breaking changes are handled.
- How we ensure third party libraries that are instrumented using old OpenTelemetry versions remain usable after the API changes.
- How we ensure interoperability of application code and of multiple third party libraries that are instrumented using different OpenTelemetry versions.

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev please assign this to me, I will write the spec.

**Comment by tedsuo** [comment]
Closing as a duplicate of #129 and #128. Please reopen if you feel that this is a separate issue.
