### ISSUE TITLE
The use of `TraceState` together with `HttpTraceContext` seems to be problematic.

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#1091]
The use of `TraceState` together with `HttpTraceContext` seems to be problematic.

`HttpTraceContext` simply [serializes ](https://github.com/open-telemetry/opentelemetry-js/blob/be720b4f3eb7f3025888c9450cb3c6a2a7aecac3/packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts#L98) `spanContext.traceState`.

Therefore the caller of `inject` is responsible to get the needed data into `spanContext.traceState` before calling `inject()`.

But the spec tells that `SpanContext` is [immutable](https://github.com/open-telemetry/opentelemetry-specification/blob/f8ff8c36a53bb8255013406393db667ba1905de/specification/trace/api.md#spancontext) therefore it's not allowed to set a the new `TraceState`.

What is the correct way to get an updated `TraceState` into a span?

_Originally posted by @Flarna in https://github.com/open-telemetry/opentelemetry-js/issues/1596#issuecomment-708483796_

**Comment by bogdandrutu** [comment]
@dyladan I am confused, I see this as:
* Parse `traceparent` and save tid, sid, flags
* Parse `tracestate` and get the tracestate part (default empty)
* Construct the immutable object with all properties parsed from previous steps.

Is this an implementation detail, do I miss something?

**Comment by dyladan** [comment]
According to spec, `TraceState` is immutable and `set` operations create a new `TraceState`. `SpanContext` is also immutable. Therefore if I need to update the `TraceState` in the injection step of the propagator (something we wish to do at Dynatrace), it is not possible. The `SpanContext` cannot be updated with the new `TraceState` because it is immutable.

**Comment by bogdandrutu** [comment]
> Therefore if I need to update the TraceState in the injection step of the propagator (something we wish to do at Dynatrace), it is not possible. The SpanContext cannot be updated with the new TraceState because it is immutable.

Why not? you just need to create a new `SpanReference`, it is a bit slower indeed, but it is thread safe. If you make the object immutable you need to synchronize and leads to undefined behaviors when multiple threads try to change the SpanContext/TraceState

**Comment by bogdandrutu** [comment]
@dyladan Can I close this issue?
