### ISSUE TITLE
There is only a MAY requirement for W3C propagator

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1093]
The spec says in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#included-propagators that a W3C propagator MAY be included in the API. It says in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md#propagators-distribution that Jaeger and B3 MUST be available and maintained by OpenTelemetry.

It seems that the W3C propagator also needs to be included into the ~~first~~ second list, to make it a MUST for language SIGs.

(from https://github.com/open-telemetry/opentelemetry-specification/issues/1070#issuecomment-708572787)

CC @carlosalberto @SergeyKanzhelev

**Comment by carlosalberto** [comment]
Agreed that this needs more clarity. In general, the MAY is about API packages having the option to include it (as opposed to have in an official extension package). 

Summarizing, for both W3C and Baggage, we need to say that:

1) We MUST implement support for them and.
2) APIs MAY include them in their packages/modules (disabled by default, etc).

**Comment by andrewhsu** [comment]
from the issue triage mtg today, bumping up the priority since it seems like a significant change to get in before trace spec freeze

**Comment by andrewhsu** [comment]
@carlosalberto if you don't have time, unassign and we can find another owner at spec sig mtg

**Comment by carlosalberto** [comment]
@andrewhsu I will work on it ;)

**Comment by andrewhsu** [comment]
from the spec sig mtg, changing this to P2 since it was identified as an editorial change
