### ISSUE TITLE
Update YAML files for semantic conventions once supported by markdown generator

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1096]
YAML model for attributes seems to only have number type. But we have int or double as possible attribute types.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes
https://github.com/open-telemetry/opentelemetry-specification/blob/master/semantic_conventions/syntax.md

Once the YAML syntax and MD generator are updated (https://github.com/open-telemetry/build-tools/issues/13), we need to update our YAML files here accordingly.

**Comment by thisthat** [comment]
I would move this issue to https://github.com/open-telemetry/build-tools

**Comment by arminru** [comment]
@anuraaga There is a PR adding this functionality to the markdown generator: https://github.com/open-telemetry/build-tools/pull/30

If there is no opposition on this change (distinguishing int and double), we should be able to merge it and then adapt the YAML files in the spec accordingly.
cc @open-telemetry/technical-committee @open-telemetry/specs-approvers
