### ISSUE TITLE
Provide specification for cloud-provider-specific resource attributes

### ISSUE THREAD

**Issue by willarmiros** [open-telemetry/opentelemetry-specification#1098]
**What are you trying to achieve?**

The current resource specs define a broad range of useful attributes that exist for certain types of compute infrastructure regardless of the who provides it, like `container.id` or `faas.name`. However there are many other attributes that OpenTelemetry users would appreciate having in their spans which are specific to the cloud/infrastructure provider. For example, AWS Elastic Container Service (ECS) has metadata related to its "tasks" and "launch type" that do not fit neatly into the existing generic attributes.

In order to record these resource attributes in a consistent way across SDKs and the collector, I think their semantic conventions should live here in the [OTel spec for resources](https://github.com/willarmiros/opentelemetry-specification/tree/master/specification/resource/semantic_conventions) under a subdirectory like `cloud_provider` indicating these attributes are only present in a specified provider's resource. For example, `cloud_provider/azure` could host specific attributes about Azure Functions, `cloud_provider/aws` could host specific attributes about ECS, etc.

To avoid bloat, we can constrain the core spec to only contain provider-specific resources from the supported `cloud_provider`s, which are currently `aws`, `gcp`, and `azure`.

**Additional context.**

This is related to #968, except this issue is about vendor-specific resource semantic convention as opposed to those for instrumentation. I will be following up with a PR that proposes a solution shortly. Always open to feedback here and on the PR when open.

**Comment by carlosalberto** [comment]
Marking it as Allowed for GA, as it seems this would be an editorial change & reorganization to decrease bloat.
