### ISSUE TITLE
Declare freeze of Trace Specification 1.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#1120]
We want to freeze Trace specification 1.0 so that we no longer accept substantial changes (unless a fundamental problem is found in the spec).

**Comment by Oberon00** [comment]
May I plug one issue that I think should be reconsidered to be required-for-ga tracing: #1060. I think we are missing specification for when to generate span IDs for unsampled spans.

**Comment by andrewhsu** [comment]
Some action items I see that are desirable for this freeze to remain consistent with previous milestone and releases:
* git tag and push to repo
* update github milestone to represent what has gone into this release
* write changelog for github release

I'm willing to help out on these items.
