### ISSUE TITLE
Ability to limit length of values of attributes and metric values

### ISSUE THREAD

**Issue by jtmalinowski** [open-telemetry/opentelemetry-specification#1133]
To protect the backend which receives telemetry data it can be useful to set a limit on span attributes length (per attribute). Exceeding the limit causes truncation of given attribute value. By default, there would be no limit.

There is a precedent in Java implementation: https://github.com/open-telemetry/opentelemetry-java/pull/1484

**Comment by Oberon00** [comment]
The same probably applies to metric label values.

For key-like strings, there is a related issue #504.

**Comment by jtmalinowski** [comment]
I'll extend the PR to include metric label values as well then.

**Comment by andrewhsu** [comment]
from the spec issue triage mtg today, marking as after-ga to bring in changes after GA release

**Comment by jtmalinowski** [comment]
Based on @jmacd I've extended the scope of this to include all attributes (as in common).

@andrewhsu Does that mean we don't want to **merge the PR** until after GA?
