### ISSUE TITLE
Add a section on compatibility with OpenTracing to Compatibility doc

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#114]
We need a section on compatibility of OpenTelemetry with ~OpenCensus and~ OpenTracing and how the gradual transition for existing ~OpenCensus~/OpenTracing users will be handled.

**Comment by tedsuo** [comment]
@carlosalberto said he can tackle the OpenTracing side. Anyone from OpenCensus want to tackle that portion?

**Comment by andrewhsu** [comment]
from the spec sig mtg today, looks like this one would be more suited for v0.6 milestone

**Comment by andrewhsu** [comment]
Talked with @carlosalberto and this one should probably be split into 2: one for opentracing and one for opencensus.

**Comment by andrewhsu** [comment]
From the bug triage meeting today, splitting out OpenCensus into separate issue #766

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, allowing changes related to this issue for GA if editorial changes only
