### ISSUE TITLE
Determining OpenTelemetry API Compatibility

### ISSUE THREAD

**Issue by HaloFour** [open-telemetry/opentelemetry-specification#1152]
I am working on updating an older tracing library to implement the OpenTelemetry API interfaces.  I was interested in a way to evaluate how "compatible" any given implementation of these APIs would be to the specification.  I recognize that this would be difficult to quantify given that the API basically specifies inputs without outputs so there isn't a way to extract an "actual" result of a trace that could be compared to an expected result.  I am opening this issue to explore this space.

**Comment by arminru** [comment]
Duplicate of #1153 (more discussion on there already)
