### ISSUE TITLE
Complete the Metric SDK specification

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#1158]
**What are you trying to achieve?**

The metric SDK specification is unfinished. There are a number of TODOs in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/sdk.md

These have to be addressed before we can finish the SDK compliance matrix for metrics.

**Comment by hdost** [comment]
Is there a permalink to the SDK?

**Comment by SergeyKanzhelev** [comment]
> Is there a permalink to the SDK?

Answering the question: https://github.com/open-telemetry/opentelemetry-specification/blob/135d99df75beb66836673e0fadc9fd5c67abef03/specification/metrics/sdk.md (just before this PR: https://github.com/open-telemetry/opentelemetry-specification/pull/1401/)

However, if you want to work on it, please make sure to join the discussion of metrics API group. Easiest to join the meeting (see OpenTelemetry calendar), but also can reach out to @reyang for details on how to get involved

**Comment by reyang** [comment]
I'm closing this issue since it is too broad. We'll be using [milestones](https://github.com/open-telemetry/opentelemetry-specification/milestones) in this repo to track the items.
