### ISSUE TITLE
Editorial: Get rid of absolute links to opentelemetry-specification

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1167]
These absolute links will (usually) always go to master, even if you come from a specific version from the spec, which is IMHO something that is critical to avoid, especially once we have a GA.

Examples can be found in the compliance matrix or <specification/common/common.md>

**Comment by carlosalberto** [comment]
+1. We have seen this issue recurrently in many OSS projects and we should be careful on this regard.

**Comment by Oberon00** [comment]
I will look into this.
