### ISSUE TITLE
Tracing API 1.0 LTS for GA

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-specification#1172]
_This is a high-level tracking issue to track items across several github repos._

Definition of done: release of languages and spec targeted for GA and documentation of LTS support for these releases

No breaking changes between 1.0 and 2.0
* New features may be added
* New signals (logs) may be added

LTS versions
* Specific versions will be marked as being long-term supported, meaning that they will receive bug fixes and security patches even after higher versioned point releases are available

Related OTEP: https://github.com/open-telemetry/oteps/pull/143
Related spec issue: https://github.com/open-telemetry/opentelemetry-specification/issues/1267
Related spec PR: https://github.com/open-telemetry/opentelemetry-specification/pull/1291

Languages:
- [ ] Java
- [ ] JS
- [ ] Python
- [ ] Go
- [ ] C# .NET
- [ ] Erlang
- [ ] Ruby

**Comment by tedsuo** [comment]
Closed as unnecessary, we have a feature completeness checklist now.
