### ISSUE TITLE
OpenCensus Compatibility for GA

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-specification#1175]
_This is a high-level tracking issue to track items across several github repos._

Languages:
- [ ] Java
- [ ] JS
- [ ] Python
- [ ] Go
- [ ] C# .NET
- [ ] Erlang
- [ ] Ruby

**Comment by jsuereth** [comment]
@andrewhsu would you mind assigning this to me?

Additionally we should expand the description to include a Specification of what compatibility looks like.

**Comment by dashpole** [comment]
I have three changes that should complete the spec-portion of OpenCensus compatibility:

* https://github.com/open-telemetry/opentelemetry-specification/pull/2730: OpenCensus migration plan. This describes how metric and trace bridges should be used to migrate from OpenCensus to OpenTelemetry
* https://github.com/open-telemetry/opentelemetry-specification/pull/2722: Add a "MetricProducer" interface, which can be passed to a MetricReader as a source of metric data.
* https://github.com/open-telemetry/opentelemetry-specification/pull/2732: Add the OpenCensus metric bridge specification, which describes how to implement the MetricProducer interface using metrics from OpenCensus.

**Comment by dashpole** [comment]
I'm working on a golang implementation which follows the proposed spec: https://github.com/open-telemetry/opentelemetry-go/pull/3093

**Comment by aabmass** [comment]
David's PRs were all merged and I think we are looking good here. I am going to open a PR to mark the compatibility doc as stable and close this issue.

**Comment by aabmass** [comment]
From the original description

> * [ ]  C# .NET
> * [ ]  Erlang
> * [ ]  Ruby

I think its safe to say these are out of scope?
