### ISSUE TITLE
Clarification required for Resource attribute values.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-specification#1184]
The [ResourceCreation](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#resource-creation) section says the `Attributes` for Resource follows the common attributes rules, which means value can be  string,bool,double,float, array of these.

When [Merge](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#merge) faces a collision, it says if the primary has "empty string", override it. 
Question: What if primary is not even string? for eg: what if primary is array?

[RetrieveAttribute](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#retrieve-attributes) section says the attributes names and values are just strings.
"_The attributes should consist of the name and values, both of which should be strings._"

[Specify Resource from ENV variable](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable) says all attrubute values Must be considered strings.
"_All attribute values MUST be considered strings._"

Is the attribute value for Resource expected to contain just strings only?
Or should it support the [common Attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes)?
If common, then how should Merge handle collisions?
if common, then how to configure it using ENV variables?

**Comment by Oberon00** [comment]
> When Merge faces a collision, it says if the primary has "empty string", override it.

I think we should remove this wording. It makes less sense now that resources support different attribute types.

**Comment by Oberon00** [comment]
#1345 partially resolves this.

**Comment by cijothomas** [comment]
The current wording in the spec addresses the question in this issue. We can close this.
