### ISSUE TITLE
Consider allowing Trace's Context interaction to be non-static

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#1201]
As a follow-up to #1187 we need to consider allowing non-static methods to define the Trace's `Context` interaction. 

This is because IIRC OTel Ruby was considering having this functionality in `Tracer` specifically (and in general, the question stands for languages supported in the future).

cc @mwear

**Comment by mwear** [comment]
Ruby ended implementing these as static methods on the trace module, so we don't need this to be specified. Feel free to close this issue.

**Comment by carlosalberto** [comment]
Closing this.
