### ISSUE TITLE
Clarify why attribute order should be preserved

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#1203]
The specification around attributes says that "Attributes SHOULD preserve the order in which they're set." I do not understand why this requirement is in place. What is the use-case that would benefit from insertion order being preserved?

** What did you expect to see? **

Some sort of reasoning for *why* attribute order should be preserved. I suspect that this will not be something that Java users will expect, as attributes act much like a java `Map`, which does not preserve insertion order, in general. I don't understand the rationale for this requirement.

**Additional context.**

In the Java repository, we have done significant work to optimize the memory usage of attributes. They do not current preserve insertion order, but instead are sorted lexigraphically, which enables some optimizations. Introducing the preservation of insertion order would make this more difficult.

**Comment by Oberon00** [comment]
I think we should really remove this SHOULD for GA. We can add it back later (undefined order to any defined order is not breaking).

**Comment by Oberon00** [comment]
I created #1212 PTAL, I think this should be done before GA.
