### ISSUE TITLE
The HTTP semantic conventions reference CanonicalStatusCodes that no longer exist in the spec

### ISSUE THREAD

**Issue by justinfoote** [open-telemetry/opentelemetry-specification#1204]
I found [this block](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#http-client) in the HTTP trace semantic conventions:

```
For status, the following special cases have canonical error codes assigned:

| Client error                | Trace status code  |
|-----------------------------|--------------------|
| DNS resolution failed       | `Unknown`     |
| Request cancelled by caller | `Cancelled`        |
| URL cannot be parsed        | `InvalidArgument`  |
| Request timed out           | `DeadlineExceeded` |

This is not meant to be an exhaustive list
but if there is no clear mapping for some error conditions,
instrumentation developers are encouraged to use `Unknown`
and open a PR or issue in the specification repository.
```

But since PR #966, we've only had three statuses specified: `Ok`, `Unset`, and `Error`.

I propose that we remove this whole section from the HTTP semantic convention. 

But should we replace it with different guidance about these error conditions?  
I'd expect most languages to present these as exceptions or errors, which could be added to a span as events. Is that what we should suggest here?

Related: #965

**Comment by Oberon00** [comment]
I think we should just remove this block without replacement.
