### ISSUE TITLE
Support both push and pull based metrics at the same time

### ISSUE THREAD

**Issue by sagikazarmark** [open-telemetry/opentelemetry-specification#1207]
**What are you trying to achieve?**

I'm trying to migrate an existing application from OpenCensus to OpenTelemetry. The application exposes metrics for Prometheus and pushes metrics to the OpenCensus collector. This is because some environments have an established monitoring solution in place using Prometheus and we never really moved to the collector entirely.

**What did you expect to see?**

I'd like to keep the same behavior with OpenTelemetry, but unfortunately it's not trivial at all. It looks like I can't use a push and a pull controller at the same time.

**Additional context.**

I asked about this on Gitter and was pointed to this repo to raise an issue about the question.

Discussion on Gitter: https://gitter.im/open-telemetry/opentelemetry-go?at=5fa08bda8d286f2076862eb8

**Comment by evankanderson** [comment]
I'd like to do this, too. Is #1378 all that is required?

**Comment by reyang** [comment]
This is resolved by #1673.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricexporter
