### ISSUE TITLE
Declare relationships with OpenMetrics in Metrics section of terminology document

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#123]
Need to state what our relationships with the OpenMetrics are. Why our proto file is not exact copy for instance.

**Comment by naseemkullah** [comment]
Are opentelemetry metrics and openmetrics trying to solve the same problem sort of like opentracing and opencensus were?

**Comment by jmacd** [comment]
I believe we are waiting for OpenMetrics to publish a specification.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, when the document is published by openmetrics, looks like we can take next steps

**Comment by mhausenblas** [comment]
FYI: OM draft has been published, see https://github.com/OpenObservability/OpenMetrics/blob/master/OpenMetrics.md

**Comment by bogdandrutu** [comment]
We have documented this https://github.com/open-telemetry/opentelemetry-specification/blob/0c25570d8af8db1ec7843d5c822b3f807873db16/specification/metrics/semantic_conventions/openmetrics-guidelines.md
