### ISSUE TITLE
Define Aggregator Requirements in Metric SDK Spec

### ISSUE THREAD

**Issue by shovnik** [open-telemetry/opentelemetry-specification#1260]
**What are you trying to achieve?**

The Aggregator Functional Requirements are currently marked as ‘TODO’ in the metrics SDK spec. Will these requirements clearly define the aggregations each type of Aggregator is responsible for maintaining or is that left up to the interpretation of each language SDK.

The reason I am bringing this up is that I noticed that the Histogram aggregator in the Python SDK (https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/aggregate.py#L144) maintains only histogram buckets while the one in the Go SDK (https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/aggregator/histogram/histogram.go#L47) maintains histogram buckets, total count and total sum. The total sum cannot be derived from histogram buckets, which means the same aggregator does not necessarily provide the exact same information across language SDKs currently. Overall, since the specification doesn’t exist today, there is an inconsistency in how specific aggregators are being implemented in the language SDKs.

When will these details be clarified in the spec?

cc- @alolita

**Comment by reyang** [comment]
@victlu assigned this to you based on the discussion at [07/01/2021 Metrics SIG](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit#heading=h.q59ky1fzlp9).

Here are the breakdown:
* Built-in aggregators (**not** including the details of Exemplar and Histogram) - #1260, assigned to @victlu.
* Exemplar - @jsuereth offered to help, I'll create a separate issue and assigned to him.
* Histogram - @jsuereth offered to help, I'll create a separate issue and assigned to him. This one might have dependency on https://github.com/open-telemetry/opentelemetry-specification/issues/1776 which we plan to resolve next week (7/13/2021).

**Comment by victlu** [comment]
I'm working on #1804
