### ISSUE TITLE
Add a section on vendor API compatibility to Compatibility doc

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#128]
OpenTelemetry SDK will have an API that vendors can implement, such as Exporter API that allows SDK to call vendor specific exporters to deliver telemetry data.

We need to define the compatibility guarantees for this API. This can be tied to the guarantees for end-user API (instrumentation API) or it may have a different set of rules.

This issue needs to clarified and added to the compatibility doc after merging https://github.com/open-telemetry/opentelemetry-specification/pull/115

**Comment by jmacd** [comment]
@tigrannajaryan #115 has merged. Would you like to update the compatibility guidelines for exporters and SDK APIs?

**Comment by reyang** [comment]
I believe this is addressed by #1409.
