### ISSUE TITLE
Introduce a new resource attribute for AWS Lambda function alias

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-specification#1280]
**What are you trying to achieve?**

I propose adding a new optional resource attribute that will store the AWS Lambda function alias (if it's used at all), named `aws.lambda.alias`.

**Additional context.**

* [AWS Lambda alias docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html)

**Comment by thisthat** [comment]
Currently, the alias is caught inside the `faas.id` attribute.
Do you think it would be better to remove the alias from the id attribute and report it inside `aws.lambda.alias`?

**Comment by Oberon00** [comment]
I'm wondering about that: If a function has multiple aliases, would a request to one alias re-use an instance started by a request to another alias (or the un-aliased ARN)? If so, then we must not report the AWS alias in faas.id when used as resource attribute.

**Comment by Oberon00** [comment]
Relatedly, #1265 allows faas.id as span attribute.

**Comment by mateuszrzeszutek** [comment]
> I'm wondering about that: If a function has multiple aliases, would a request to one alias re-use an instance started by a request to another alias (or the un-aliased ARN)?

I don't know that -- I'll test it and come back here with the answer.
