### ISSUE TITLE
Should API be namespaced by version or not and how exactly

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#129]
The OpenTelemetry API can be namespaced by major version numbers, e.g. API 0.x.x is in io.opentelemetry, 1.x.x is in io.opentelemetry.v1, etc.

This allows one SDK to implement multiple major version APIs and one application to contain a mix of code that calls different API versions.

With a namespaced API SDK will typical implement lower version numbers are thin shims that map the API calls to the latest major version of API.

Actual mechanism of namespacing is language dependent, e.g. reverse domain notation for package in Java, [import paths in Go](https://github.com/golang/go/wiki/Modules#why-must-major-version-numbers-appear-in-import-paths), [namespaces](https://en.cppreference.com/w/cpp/language/namespace) in C++, etc.

We had a discussion about namespaces here: https://github.com/open-telemetry/opentelemetry-specification/pull/115#discussion_r293169930

**Comment by tigrannajaryan** [comment]
For some reason I can't self-assign issues. Can someone with admin rights have a look at the permissions?

**Comment by SergeyKanzhelev** [comment]
I suggest we give approvers a triager role. Any objections?

![image](https://user-images.githubusercontent.com/9950081/65057184-16bdcc00-d927-11e9-99f6-a77d0df645b4.png)

**Comment by Wanshell** [comment]
can read ,clone, and push to this repository. can also manage issues and pull requests.

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev can you check that the CODEOWNERS works with Triage? I think we need to give them Write and based on my understanding Write include Triager

**Comment by SergeyKanzhelev** [comment]
yes, my bad. every member of https://github.com/orgs/open-telemetry/teams/specs-approvers must have write permissions. Either @tigrannajaryan needs to be added to approvers or we need even broader triagers role for specs repo. I'd suggest we add Tigran to approvers

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev thank you, I am able to assign issues to myself.

**Comment by tedsuo** [comment]
@tigrannajaryan just followinig up on this. I believe we are not namespacing with a version number; at least, not with the initial version - who knows what OTel v2.0 would bring. If you agree it is resolved, can you close the issue?

**Comment by tigrannajaryan** [comment]
Agreed, closing.
