### ISSUE TITLE
Rename OTLP_EXPORTER_OTLP_INSECURE to OTLP_EXPORTER_OTLP_DISABLE_TLS

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1292]
**What are you trying to achieve?**

Better reflect the fact that disabling TLS is not necessarily insecure - in a sidecar deployment with localhost connections, it is secure and standard practice to disable TLS. Sidecar processes already add enough overhead without adding unnecessary encryption overhead.

**Additional context.**

The word `insecure` in the codebase triggers automatic security scanners, and it's difficult to explain to security teams that this is not a problem for sidecar deployments. I think the variable could be renamed to better reflect that an app that specifies it is not inherently insecure, it's a combination of many factors.

**Comment by alolita** [comment]
A name including "*DISABLE_TLS" wouldn't avoid getting flagged in a security scan. Using a non-triggerable name such as "OTLP_EXPORTER_OTLP_PLAIN" may work better.

**Comment by anuraaga** [comment]
Ah yeah, `OTLP_EXPORTER_OTLP_PLAINTEXT` sounds good too

**Comment by Oberon00** [comment]
I also don't like just "insecure", as it is unclear what it does. But I wonder what the purpose of this variable is: If I don't want to use TLS, can't I just use http without the s?

**Comment by anuraaga** [comment]
@Oberon00 I think this is because gRPC endpoints are generally provided without a scheme, just `localhost:1234` for example.

**Comment by Oberon00** [comment]
Then I think it would be important to include GRPC in the name.

**Comment by arminru** [comment]
Related: _Update endpoint for OTLP/HTTP to allow scheme_ #1234

**Comment by anuraaga** [comment]
Just a note that I might get paged over the holidays from our security team for the use of the word "insecure" in our docs. It's a catch-22 since a sidecar deployment, what we cover in our docs, very much should use plaintext. So appreciate if there's a relatively quick way to resolve this, #1234 seems sound.

**Comment by carlosalberto** [comment]
@anuraaga After #1234 is there anything to be done here?

**Comment by anuraaga** [comment]
Nope :)
