### ISSUE TITLE
Update system metrics semantic conventions with collector changes

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#1299]
**What are you trying to achieve?**

Have collector and spec use the same system metric names. [`system.process.count`](https://github.com/open-telemetry/opentelemetry-specification/blame/master/specification/metrics/semantic_conventions/system-metrics.md#L149) should be renamed to `system.processes.count` and `system.processes.created` should be added.

**Additional context.**

https://github.com/open-telemetry/opentelemetry-collector/pull/2311

**Comment by aabmass** [comment]
This can be assigned to me

**Comment by carlosalberto** [comment]
cc @open-telemetry/specs-metrics-approvers
