### ISSUE TITLE
Initial spec from java client

### ISSUE THREAD

**Issue by c24t** [open-telemetry/opentelemetry-specification#13]
Create a spec for the opentelemetry API and SDK in the style of [opencensus-specs](https://github.com/census-instrumentation/opencensus-specs).

The spec should describe the [opentelemetry java client](https://github.com/open-telemetry/opentelemetry-java) as it's implemented now. Where the API isn't well defined (as in issues labeled ["Agreement Required"](https://github.com/open-telemetry/opentelemetry-java/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agreement+Required%22)), the spec should note this.

This spec isn't meant to be authoritative yet, it's just meant to help the authors of other opentelemetry clients as we finalize the API.

**Comment by iredelmeier** [comment]
@mtwo would you mind reiterating your thoughts on this from the F2F discussion last week?

**Comment by bogdandrutu** [comment]
@c24t are you going to do the first draft? When?

**Comment by c24t** [comment]
I put up a WIP draft at #17, largely a copy of the OC and OT specs at this point.

@mayurkale22, @songy23, @rghetia, @dinooliva, and I will compare to the OC spec and clients today.

**Comment by mtwo** [comment]
> @mtwo would you mind reiterating your thoughts on this from the F2F discussion last week?

I think that my comments were mostly related to adding typed spans into the specs repo ... or were you referring to something else?

**Comment by c24t** [comment]
Closing this one in favor of moving docs individually from the work-in-progress dir.
