### ISSUE TITLE
OTEL_EXPORTER not consistent with other variables

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1309]
I noticed this when setting multiple variables at the same time, but `OTEL_EXPORTER` doesn't seem consistent with other variables. It accepts a list for multiple exporters but is singular. `OTEL_PROPAGATORS` (more importantly) and `OTEL_RESOURCE_ATTRIBUTES` are plural.

**Comment by Oberon00** [comment]
Also, since this has the "spec:trace" label, should there be separate `OTEL_TRACE_EXPORTERS` and `OTEL_METRIC_EXPORTERS` (and later maybe `OTEL_LOG_EXPORTERS`)?

**Comment by alolita** [comment]
+1 on this change.
