### ISSUE TITLE
otlp_span not consistent with trace, what we use for the signal / concept

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1313]
We have `otlp_span` exporter to specify an exporter of only traces over OTLP but it would be more consistent with others, including `otlp_metrics` as `otlp_trace` - trace is the corresponding signal to metrics, and it is an exporter of `trace`.

**Comment by carlosalberto** [comment]
Although I'm slightly in favor of this change, quite often we may be technically exporting Spans more than (full) Traces ;) Also, I'm a little bit curious of the impact of this change for SIGs and (and potentially, existing users - yes, even if we are still pre 1.0).

**Comment by carlosalberto** [comment]
Marked as required-for-GA as we either change it now or never.

**Comment by trask** [comment]
> Also, I'm a little bit curious of the impact of this change for SIGs and (and potentially, existing users - yes, even if we are still pre 1.0).

Java Auto-Instrumentation has implemented this, but I don't have concerns changing it prior to 1.0.
