### ISSUE TITLE
Numeric environment variables don't define limit

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1315]
Numeric environment variables currently don't define an upper limit on a value

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md

In Java, we currently read some variables as integer, others as long. I suspect none of these will ever need to be such huge values and we could state that all numbers have an upper limit of the maximum of a signed integer, otherwise we should document which are integer and which are long.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, punya can take this one (need comment on the ticket to have assignee)

**Comment by punya** [comment]
Thanks @andrewhsu .
