### ISSUE TITLE
Add Shutdown() to Metric Exporter interface

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-specification#1348]
**What are you trying to achieve?**

I propose adding a `Shutdown()` or `Stop()` method to the Metric Exporter SDK interface.

Currently, the `Exporter` for metrics in the SDK does not have a `Shutdown` method, whereas the trace `SpanExporter` **does** [require it
](https://github.com/open-telemetry/opentelemetry-specification/blob/c4fffd98adbdf2a9677fd14b94cca31fc68982a3/specification/trace/sdk.md#shutdown-2)

**Additional context.**

We have an in-house push-based metrics exporter which queues checkpointed records to an asynchronous batched sender.

In the `go` implementation, the pusher implementation has a `Stop()` method, which sends one final checkpoint of records to the metric exporter.  However, it has no way to notify the exporter that it is stopping - i.e. that the exporter should also at least flush/shut down itself as well.

It seems somewhat inconsistent that `SpanExporter`s have a `Shutdown()` method but metrics `Exporter`s do not.

**Comment by tedsuo** [comment]
Hi @evantorrie; FYI we're rebooting the metrics API WG. The current SDK spec has been removed from the spec, @reyang Is heading a working group that will add it back in once the prototypes are finished. Assigning this to him so we don't lose the requirement.

**Comment by reyang** [comment]
Fixed by #1864.
