### ISSUE TITLE
Use either SPAN or TRACES in all related environment variables

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#1352]
Currently we are still mixing `TRACE` / `SPAN` in our environment variables, i.e. `OTEL_TRACE_EXPORTER` vs `OTEL_EXPORTER_OTLP_SPAN_ENDPOINT`. Decide which one is better and stick to that.

**Comment by carlosalberto** [comment]
Marking as Required-for-GA as we will have to do this change now or never.

**Comment by tedsuo** [comment]
Let's go with TRACE, please, it matches the name of the signal and the other non-OTLP env vars we already have.

**Comment by obecny** [comment]
+1 for TRACE

**Comment by mtwo** [comment]
Following up from the maintainers meeting, we'll use TRACE
