### ISSUE TITLE
Consider removing jaeger thrift from compliance matrix (or marking it optional somehow)

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1356]
**What are you trying to achieve?**

From what I read on https://www.jaegertracing.io/docs/1.21/apis/#protobuf-via-grpc-stable, since Jaeger 1.11 gRPC is recommended for exporting spans to collector, or thrift UDP for an agent. Thrift HTTP seems to be sort of a legacy format for exporting spans to collector. Do we need to require OpenTelemetry implementations to support the format? 

**Additional context.**

I'd like to avoid supporting a legacy format, but it could be ok to require Thrift HTTP. But if we keep it, it needs to be specced out more fully. For example, we don't have any environment variables defined for Thrift HTTP.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md

**Comment by Oberon00** [comment]
I think we should strive for minimal requirements here. If up-to-date Jaeger backends support gRPC that should be enough. What is more, Thrift is a rather exotic library compared to gRPC and is probably not available in as many languages.

**Comment by carlosalberto** [comment]
I'd rather not throw away any existing Thrift HTTP exporter, so I definitely make it optional, while making the gRPC one the **preferred** one.

**Comment by anuraaga** [comment]
@carlosalberto How does that affect the compliance matrix? Should we add a column, optional? Or should we remove the row and let language SIG decide whether to support it completely independently from the spec. FWIW, my hope for Java is to maintain it in the SDK repo as contrib, and not include it in the default Java agent distribution. I am also ok with including it in the distribution if things like the env vars are spec'd out but someone who wants to champion it needs to take that on.

**Comment by carlosalberto** [comment]
I'd be up for either making a section at the bottom, with the optional components, or remove it altogether **from the** Matrix (which was expected to document the features needed for GA). Not a strong opinion though.

**Comment by tsloughter** [comment]
A big +1 to making it optional.

**Comment by tedsuo** [comment]
Optional please, +1
