### ISSUE TITLE
Turning on GH Discussions for the specification repo

### ISSUE THREAD

**Issue by jonatan-ivanov** [open-telemetry/opentelemetry-specification#1361]
It seems that there are quite a few repos under the open-telemetry org that are taking advantage of GH Discussions. From conversations on meetings and Gitter, it seems that the community would benefit from having  GH Discussions for the specification repo turned on.

/cc @alolita @SergeyKanzhelev @tedsuo @jmacd

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/technical-committee @open-telemetry/specs-approvers @open-telemetry/specs-logs-approvers @open-telemetry/specs-metrics-approvers @open-telemetry/specs-trace-approvers any objections to enable discussions for specs?

**Comment by alolita** [comment]
@SergeyKanzhelev We discussed in the Metrics SIG today and hence this formal request to turn on GitHub Discussions and deprecating Gitter over time. The community was in agreement with this move in the meeting. 

Thanks for your help in enabling this feature.

**Comment by SergeyKanzhelev** [comment]
enabled
