### ISSUE TITLE
Environment variables for OTLP client TLS key / certificate

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1363]
**What are you trying to achieve?**

Ability to set client key / certificate for mTLS.

**Additional context.**

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md#configuration-options

We currently only have a CERTIFICATE_FILE environment variable, which is a bit misleading since this only refers to trusted certificates. For mTLS, there would need to be two additional variables, one for the client certificate and one for the client private key. I think we should have three variables

OTEL_EXPORTER_OTLP_TLS_PRIVATE_KEY
OTEL_EXPORTER_OTLP_TLS_CERTIFICATE
OTEL_EXPORTER_OTLP_TLS_TRUSTED_CERTIFICATE

Reference: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1829

**Comment by anuraaga** [comment]
Well - looking at the documentation for `OTLP_EXPORTER_OTLP_CERTIFICATE` it seems to be indicating this is a client certificate, not a trusted one `Path to certificate file for TLS credentials of gRPC client. Should only be used for a secure connection.`- note "TLS credentials". But this can't be true since there would need to be another variable corresponding to the private key. So not even really sure how to implement that variable.

**Comment by anuraaga** [comment]
I'm a bit worried the current environment variable is misspecified so I think at least confirming that before GA would be good I think. Might be good to remove it for now if not adding all three

/cc @tedsuo

**Comment by edwardxia** [comment]
Just want to add even for normal TLS (no client certificate) we will need OTEL_EXPORTER_OTLP_TLS_TRUSTED_CERTIFICATE option to change the trusted CA file, as many companies use internal private CA to sign server certificate that is not in default CA.

**Comment by jack-berg** [comment]
Resolved in #2370.
