### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-specification#1373]
This is a tracking issue for the v1.0 release of the specification. Please post any concerns or blockers here.

Remaining issues required for v1.0 can be found here: https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aopen+label%3Arelease%3Arequired-for-ga+-label%3Aspec%3Ametrics+label%3Apriority%3Ap1

v1.0 PR: https://github.com/open-telemetry/opentelemetry-specification/pull/1372

**Comment by awssandra** [comment]
Hey tedsuo,

Where can we view the diff between 0.7.0 and the 1.0 spec?

**Comment by Oberon00** [comment]
There are a bunch of issues in with the label `area:ga-tracking` https://github.com/open-telemetry/opentelemetry-specification/labels/area%3Aga-tracking and without priority. What do we do about these? Some of them seem to be for tracking the GA of non-spec repos, maybe these should be transferred to the community repo.

**Comment by tedsuo** [comment]
@Oberon00 those are "non-spec" issues which are project wide. It's true, they could be in the community repo instead. Either way, we need to ensure progress is being made on them. (None are a blocker for releasing v1.0 of the spec). Let's review these in the maintainers meeting on Monday.

**Comment by tedsuo** [comment]
@awssandra you can check out the changlelog to see what was added. Everything currently marked as "unreleased" will be added to the v1.0.0 release: https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md#unreleased

If you want to see the actual text changes, you can check out the `main` branch and then use `git diff v0.7.0` to see the changes directly. (Apologies if that's a pedantic answer!)

**Comment by tedsuo** [comment]
I believe that all non-metrics issues which are required for GA are now resolved. At Monday's maintainer's meeting, I suggest we merge the PR (assuming the TC does not do so before then).

**Comment by bogdandrutu** [comment]
Waiting for one more TC member to sign on that :)
