### ISSUE TITLE
cloud.infrastructure_service incosistency

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-specification#1377]
**Current state**

[Cloud semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/cloud.md#cloud) specify fields such as:

* `cloud.provider` (e.g. `aws`, `azure`) 
* `cloud.infrastructure_service` (e.g. `aws_ec2`, `aws_ecs`, `azure_vm`, etc.)

As can be observed, the values for the latter start with prefix that matches `cloud.provider`

**Incosistency**

However, OpenTelemetry Collector [resourcedetection](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor) processor is [using the names without prefix](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/internal/aws/ec2/ec2.go#L76) for `cloud.infrastructure_service` (e.g. `EC2`, `ECS` rather than `aws_ec2`, `aws_ecs`). Other providers do not support the new tag yet

**Possible solutions**

* remove prefix from specification, since `cloud.provider` already provides this information
* add prefix to the implementation to make it match the specification 

This topic was [to be discussed](https://github.com/open-telemetry/opentelemetry-specification/pull/1112#issuecomment-718043825) in a separate issue but eventually [closed](https://github.com/open-telemetry/opentelemetry-specification/issues/1098)

**Additional context.**

#1059 suggests to make `cloud.provider` required if any other `cloud.*`attribute is set.

**Comment by Oberon00** [comment]
> This topic was [to be discussed](https://github.com/open-telemetry/opentelemetry-specification/pull/1112#issuecomment-718043825) in a separate issue but eventually [closed](https://github.com/open-telemetry/opentelemetry-specification/issues/1098)

This was discussed at https://github.com/open-telemetry/opentelemetry-specification/pull/1112#discussion_r524417409, i.e. on the PR that introduced this attribute. Quoting @arminru for why he suggested adding a prefix:

> to avoid naming collisions and to allow for better organized sorting (e.g. in IDE suggestions). The proper display name to be used in UIs is provided in the brief anyway.

E.g. `azure_vm` was named as being more clear than just `vm`.

**Comment by Oberon00** [comment]
I.e., I think the collector should follow the spec, and not the other way round.
