### ISSUE TITLE
Add start time and duration (or end time) options on Span

### ISSUE THREAD

**Issue by rochdev** [open-telemetry/opentelemetry-specification#139]
Right now the start time and end time are always calculated internally. While this works in most cases, there are cases where it needs to be set explicitly.

The most common use case is to reconstruct a trace from tracing metadata received from another process. This is how [apollo-tracing](https://github.com/apollographql/apollo-tracing) works for example.

This is also an option that is available with [OpenTracing](https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span) so it needs at the very least to be available internally. But as described above, it should also be part of the public API to enable use cases where tracing data was generated externally.

For the end time, it could either be provided explicitly or the duration could be provided instead and then the end time can be calculated. In general, I think the duration should be preferred since it will allow languages with less precise integer types to still have high resolution. This is assuming that exporters are sending the duration to the agent/backend and not the end time.

**Comment by jmacd** [comment]
I think we can merge the current `SpanData` concept with OpenTracing-style `StartSpanOptions` to address this issue and shrink the API surface, we're working on an RFC. @bg451

**Comment by SergeyKanzhelev** [comment]
This was completed. Events and Span Start/Stop APIs accept timestamps now
