### ISSUE TITLE
Clarify the name used for Lightstep's (ot-tracer-*) propagator

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#1391]
Currently in some repos this propagator is called `OpenTracingPropogator` in others is called `OtPropagator`. Couple suggestions:
* Use consistent names, probably `LightstepPropagator`, since this is not the official OpenTracing propagator (or maybe I am wrong, but if that is the case then we need to probably add it to the ot-shim).

**Comment by bogdandrutu** [comment]
See:
* https://github.com/open-telemetry/opentelemetry-go-contrib/pull/562
* https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracerPropagator.java
* https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/JaegerPropagator.java

**Comment by yurishkuro** [comment]
1. I am curious who is asking for this propagator and for what purpose
2. Agree that it should not be using the name OpenTracing
3. Is there even a spec for that format?

**Comment by austinlparker** [comment]
Conventionally the `ot-tracer-*` headers appeared in OpenTracing as part of the `basictracer` packages (see https://github.com/opentracing/basictracer-python/blob/master/basictracer/text_propagator.py, https://github.com/opentracing/basictracer-go/blob/master/propagation_ot.go, etc) and is conventionally referred to as 'OpenTracing' headers in 3rd party use (such as in Veneur - https://github.com/stripe/veneur/blob/master/trace/opentracing.go)

**Comment by codeboten** [comment]
> I am curious who is asking for this propagator and for what purpose

Users wanting to deploy new services using OpenTelemetry who have previously instrumented w/ OpenTracing, but aren't interested in updating their existing services.

> Agree that it should not be using the name OpenTracing

Happy to change it based on the conclusion of the discussion here.

**Comment by yurishkuro** [comment]
I recommend
```
// OTTracePropagator implements propagation format used by the "basic tracer" implementations from the OpenTracing project.
class OTTracePropagator
```

**Comment by austinlparker** [comment]
sgtm

**Comment by jmacd** [comment]
I agree this form is called "basic tracer" from OpenTelemetry.

> but if that is the case then we need to probably add it to the ot-shim

@yurishkuro and @austinlparker what do you think?

For the record, Lightstep has a distinct [single-header base64-encoded-protobuf representation of the OpenTracing "basic tracer" information](https://github.com/lightstep/lightstep-tracer-common/blob/master/lightstep.proto), but that form is not the subject of this PR.

**Comment by austinlparker** [comment]
What does adding it to ot-shim entail?

**Comment by jmacd** [comment]
I think that means requiring it to be implemented as part of an on-spec OpenTracing bridge?

**Comment by yurishkuro** [comment]
I don't think it needs to be in the shim or required. Basic tracer repos had explicit warning "sample implementation, not for production use". To my knowledge, they all had no trace export format, just in-memory collection. But it's fine to have the propagator in contrib for people who ignored that warning and used basic tracer in prod.

**Comment by carlosalberto** [comment]
Agreed, it doesn't need to become part of the shim.
