### ISSUE TITLE
Replace DistributedContext with more specific interfaces

### ISSUE THREAD

**Issue by rochdev** [open-telemetry/opentelemetry-specification#140]
The current `DistributedContext` API is trying to handle too many concerns, which is why an `EntryMetadata` needs to be added to every `Entry` which makes it a confusing and difficult to use interface.

These are the separate concerns that the current API is handling:

* Propagating context within the process
* Propagating context to the next process
* Propagating context across the entire trace

There is no use case for a TTL `>1 && <services`.

I propose to use more specific interfaces instead that will be cleaner and specific to the use case at hand. This will be much easier to use, and anything specific to a single use case will not be mixed with other properties in a single metadata object.

The new API would look like this instead:

* **DistributedContext**:  This would handle propagation to the next service (single hop).
* **LocalContext**: This would handle propagation within a single process.
* **TraceContext**: This would handle propagation across the entire trace. This is the equivalent of OpenTracing's [baggage items](https://github.com/opentracing/specification/blob/master/specification.md#the-opentracing-data-model)

All of them would be simple maps of strings (and any other types that make sense). They could be attached to the `SpanContext` to easily make them available everywhere, but another benefit of having different interfaces is that this doesn't have to be the case.

This API would also be much more idiomatic in dynamic languages, while still being strongly typed and easy to understand in more verbose languages.

**Comment by tedsuo** [comment]
This has work has been moved to an otep, closing for now: https://github.com/open-telemetry/oteps/pull/66
