### ISSUE TITLE
Should span creation operations raise exceptions?

### ISSUE THREAD

**Issue by c24t** [open-telemetry/opentelemetry-specification#141]
From https://github.com/open-telemetry/opentelemetry-python/pull/11#pullrequestreview-245809272.

The java tracer API docs note that calling `spanBuilder` with a null `spanName` arg should [raise a `NullPointerException`](https://github.com/open-telemetry/opentelemetry-java/blob/8520de558133c2e09f9f0de8b07f36c377b3555d/api/src/main/java/io/opentelemetry/trace/Tracer.java#L149). `NoopSpanBuilder` [does this](https://github.com/open-telemetry/opentelemetry-java/blob/8520de558133c2e09f9f0de8b07f36c377b3555d/api/src/main/java/io/opentelemetry/trace/DefaultTracer.java#L152-L153), but `SpanBuilderSdk` doesn't.

Two questions here:

Should we create a span with a default name (as @reyang and @carlosalberto suggest) instead of raising if the span name is null here? If we want to avoid exceptions in the API altogether this suggests we should also create a blank span current if the user calls `Tracer.withSpan` with a null `span`, but this seems less defensible than using a default name.

More generally, which errors should implementations raise? I could imagine letting the implementation be either more or less restrictive than the API, but if it can both raise exceptions that aren't listed in the API and choose _not_ to raise exceptions that are... then there doesn't seem to be much point to listing exceptions in the API.

**Comment by SergeyKanzhelev** [comment]
does this document looks good to be moved to spec? https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/docs/error-handling.md

I'm happy to generalize it

**Comment by c24t** [comment]
That looks great, especially

> Open Census SDK must not throw or leak unhandled or user unhandled exceptions

We still need to decide whether span creation should use a default name instead of raising an error though. If we do this in the python client we'll break with the java impl now, so we need to either mention this in the spec or decide that it's up to each language API to define defaults like this.
