### ISSUE TITLE
Add tls support for exporters

### ISSUE THREAD

**Issue by bputt** [open-telemetry/opentelemetry-specification#142]
We've extended opencensus to use tls for zipkin exporter and imagine it would be helpful to others if tls was an option for all exporters.

Should the spec include TLS for exporting? I know this doesn't matter for certain cloud providers, but for non-cloud native environments, it's required (whether we setup a local proxy that adds tls or if the exporter supported it out of the box (which would be ideal))

**Comment by SergeyKanzhelev** [comment]
What does TLS stands for in this context?

**Comment by bputt** [comment]
@SergeyKanzhelev for example, the zipkin exporter, it doesn't have an option to pass in an SSLContext where we could send the data to an https endpoint.

**Comment by flands** [comment]
@bputt whether an exporter supports TLS or not is up to the exporter. Agreed, depending on the configuration, TLS may be a requirement. Some exporters, such as the opencensus exporter, support TLS today. Is the purpose of this issue to standard the configuration parameters for TLS in an exporter?

**Comment by bputt** [comment]
Yes, have some standardization that allows TLS to be put into place within an exporter

**Comment by flands** [comment]
Got it -- to that end, there are multiple common parameters that exporters should standardize on beyond TLS. Some common ones today:

```
            compression: "gzip"
            endpoint: "foo.bar:443"
            headers: {"foo":"bar"}
            num-workers: 8
            reconnection-delay: 2s
            secure: true
```

Today, `secure: true` enables TLS -- the key/value can be debated.

@SergeyKanzhelev is the point of the specification for API definition only? If so, where should receiver/exporter standards live? If not, I will create a section for receivers and exporters and put up a PR.

**Comment by SergeyKanzhelev** [comment]
@flands that was the first iteration. The intention to specify SDK as well. This set of settings is a good one.

**Comment by bputt** [comment]
@SergeyKanzhelev @flands Not sure if it was implied or not, but if I added ```secure: true``` I would also want to provide a cert, key, and cabundle

**Comment by jmacd** [comment]
Closing this -- it's uncontroversial that we will support secure transport for TCP connections.
