### ISSUE TITLE
How to report going over limits on span data

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#1425]
`specification/trace/sdk.md` says in the section on limits:

> There SHOULD be a log emitted to indicate to the user that an attribute, event,
> or link was discarded due to such a limit. To prevent excessive logging, the log
> should not be emitted once per span, or per discarded attribute, event, or links.

I think this is not enough, it is even more useful to capture this information in the span. The proto has placeholders for such data, e.g. `dropped_attributes_count` and `dropped_events_count` fields, but the spec says nothing about them.

In addition, if these fields are exposed in the SDK Span, it would be useful to define semantic convention for converting them into plain attributes (e.g. `otel.dropped_attributes_count`) in the exporters to systems that do not have dedicated fields, to avoid having to document the conversion in every exporter.

* related to #1419
* cc @bogdandrutu

**Comment by carlosalberto** [comment]
Marked as after-ga as it seems this is an improvement that wouldn't break things.

**Comment by jmacd** [comment]
We have a general desire to report how many spans were dropped for reasons such as RPC errors, size limits, and so on. The same is true for reporting dropped metrics data. This seems to call for semantic conventional metrics about dropped spans and metrics. See also https://github.com/open-telemetry/opentelemetry-specification/issues/791

The OTel Prometheus sidecar and Lightstep needed to do something in this area, so we added Lightstep-specific response trailers that indicate the number of metrics or data points there were dropped and some of the reasons, see https://github.com/lightstep/opentelemetry-prometheus-sidecar/pull/157.

**Comment by austinlparker** [comment]
We believe this has been completed per https://github.com/open-telemetry/opentelemetry-specification/blob/39fd6d3ae49b53245037da9fa2eccdf233ec5794/specification/common/mapping-to-non-otlp.md?plain=1#L77

If more work is required, please comment on this issue to notify us.
