### ISSUE TITLE
Consider removing Async Instruments (Observers) from first Metric version

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1433]
Doing async instruments properly seems rather complicated to me (e.g. #1432). If we specify synchronous instruments (especially BatchRecorder) properly, users should be able to implement a functionally equivalent solutions on their own (e.g. with their own background thread). (The only extra thing that might be needed for that is some "last-chance to collect" callback before every export.)

**Comment by hdost** [comment]
I could agree that for the first version this might be a bit difficult specifically on the SDK side, and while it would definitely be handy to have such primitives in the SDK side of it will likely take some time to experiment more than the synchronous side. There are plenty of edge cases especially with how an async sum would work given:

> Asynchronous instruments are expected to record an observation for every label set that it considers "current". This means that asynchronous callbacks are expected to observe a value, even when the value has not changed since the last callback invocation. To not observe a label set implies that a value is no longer current. The Last Value becomes undefined, as it is no longer current, when it is not observed during a collection interval.

Source: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-observations-form-a-current-set
