### ISSUE TITLE
API: `record` should take a generic `Attachment` class instead of having tracing dependency.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-specification#144]
Original discussion: https://github.com/open-telemetry/opentelemetry-specification/pull/137#discussion_r295895301.

**Comment by bogdandrutu** [comment]
Pros:
* Decouple metrics API from trace API.
* Attachments can be used for other data besides SpanContext - for example extra tags or entries from the distrubutedcontext, or any other information.

Cons:
* May generate an extra allocation in some languages.

**Comment by jmacd** [comment]
@iredelmeier

**Comment by jmacd** [comment]
@bogdandrutu can you say what you're hoping for by decoupling the metrics and trace API? This feels like a lost opportunity to me. At LightStep, we want these to be coupled. Isn't that the point of an integrated diagnostics library?

I've been meaning to propose a specification requirement along the lines of "every recorded statistic should be associated with a span context, whether implicit or explicit". This allows an implementation to aggregate metrics by Span always/automatically. 

I am not familiar with other use-cases for this "attachment" concept.

**Comment by bogdandrutu** [comment]
@jmacd I meant package dependency not conceptually. What we want is to actually be able to record in the metrics the SpanContext but by doing it like this (not necessary the API like this one):
https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/stats/MeasureMap.java#L85

Then have an implementation of the AttachmentValue that encapsulates the SpanContext.

This way in the code the metrics package does not depend on the trace package.

**Comment by bogdandrutu** [comment]
In the new API proposal this is no longer a thing.
