### ISSUE TITLE
Handle metrics resource metadata without metric datapoint/stat?

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-specification#1444]
**Question**
Should resource metrics without any metric/datapoint be allowed to pass through the pipeline? 

**Context**
We get some resource attributes/metadata which become available only when a container dies. The OT receiver is passing these metadata setting them as resource attributes . However, data is being dropped in the processor/exporter as we don’t have any metric name/datapoint. Wondering, what’s the principal/ expected behavior here. Should the exporter drop them adding a validation or allow them to go to the destination?

**Comment by JohnWu20** [comment]
**Context**: 
For the stopped container, we get the metric descriptor data/resource attributes only but for the data part is null/empty, which means there won't have any metrics/datapoints (we don’t even have metric name).

**Proposed solutions:**

1, **Changing the exporter and processor to deal with the situation**

**Advantage:** Based on the [fundamental design rules](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md) (Checking the “Metrics data model and SDK” section): “Metrics puts minimal constraints on the data (e.g. which characters are allowed in keys), and **code dealing with Metrics should avoid validation and sanitization of the Metrics data.** Instead, pass the data to the backend, rely on the backend to perform validation, and pass back any errors from the backend.” The processors and exporters shouldn’t validate the Metrics data.
So the good thing for changing the processors and exporters will follow this design rule.
And for now only filter processor will drop the data as far as I know.

**Disadvantage:** All the current and future exporters and processors should deal with this situation.

**2, Adding one more Metrics for stopped container**

**Advantage:** We don’t need to change any exporters or processors, just solve this situation in the receivers part.

**Disadvantage:** Customer will pay for this new metric

**Comment by victlu** [comment]
I would think option 2 (sending a new metric) would be better for you guys.  You can control when and where to send your "dead" metric.  Otherwise, how would it trigger sending a metric (with 0 datapoint) in the API/SDK?  This will require adding/complicating the APIs or needing additional configuration for the SDK.

**Comment by hossain-rayhan** [comment]
@victlu yea, thats the path we are taking.

From the SIG meetings- maybe we can use the `up` metric whenver its ready to surve our purpose. For now, a dummy metric in receiver side is a good option considering our use case. Closing this issue. 

Follow the `up` metric discussion: #1078
