### ISSUE TITLE
Eliminate Measurement class to save on allocations

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#145]
Current API for recording raw measurements requires to create a measurement, create a list of measurements and, finally, record this list - which in many cases will result in allocation of an object to queue this list.

Even when no SDK present instrumentation will allocate objects. If allocation of a `Measurement` can be eliminated by returning empty measurement when SDK is not present or `Measure` is not being aggregated by any View, creation of a list is still required. 

A way to eliminate an allocation of a list, but still be able to implement batching may be to create a new class `MeasuresCollection` that can allow to `record` raw primitives - longs and doubles as a set of overridden methods with the different number of arguments.

This will also simplify API as `Measurement` class was causing a lot of misunderstanding and confusions. Measure can expose `record` method directly without the need to create another object

**Comment by jmacd** [comment]
@iredelmeier

**Comment by jmacd** [comment]
RFC 0003 would avoid this problem. See issue 169.

**Comment by tedsuo** [comment]
@SergeyKanzhelev I believe https://github.com/open-telemetry/opentelemetry-specification/pull/250 addresses this issue.

**Comment by SergeyKanzhelev** [comment]
I believe it is resolved via #299
