### ISSUE TITLE
ForceFlush missing from Exporter spec

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1454]
We currently have ForceFlush only specified in the SpanProcessor. #1452 adds the missing "helper" method to call this to the SdkTracerProvider. But we are also missing ForceFlush in the spec for exporters (some languages, e.g. Java, have it implemented already (https://github.com/open-telemetry/opentelemetry-java/blob/v0.17.1/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java#L69-L77).

In fact this was proposed in the original issue to add flush/forceFlush (#351) which was titled "Add flush API to processor/**exporter**". However it seems to have been glanced over in #370 (in turn, then some SIGs seemed to have glanced over the fact that it was never spec'd and implemented it anyway 😉).

In some languages, adding a new method to an interface might be a breaking change for existing implementers. However, there are simple workarounds for that such as adding Flush to an new interface like `FlushableExporter extends Exporter`. I think it is OK to leave this implementation detail to the language SIGs.

**Comment by bogdandrutu** [comment]
I think we need to add some text about this, languages should choose what is best for them that allows to extent the API (java8 has default implementation, go can rely o duci typing, etc.) that will allow them to extend the interfaces. And we should not consider breaking change adding a new functionality on an interface. Will file a separate issue.

**Comment by Oberon00** [comment]
@bogdandrutu I created #1457 for the interface versioning issue.
