### ISSUE TITLE
Implement three more types of Metric

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#146]
Proposed API only exposed two metric types: counter and gauge. Other types needs to be represented - histogram and summary

https://github.com/open-telemetry/opentelemetry-proto/blob/fe0fa0bd3ef0a42f3ccc6645f7b11e26418f96b1/src/opentelemetry/proto/metrics/v1/metrics.proto#L62-L97

**Comment by jmacd** [comment]
@iredelmeier and I are preparing several metrics RFCs and I would suggest we hold off on specifying Histogram and Summary until then.

**Comment by bogdandrutu** [comment]
Please make sure that this is backwards compatible with the OpenCensus which has all these types supported (directly or indirectly).

**Comment by jmacd** [comment]
See issue 169.

**Comment by SergeyKanzhelev** [comment]
@jmacd it seems like your metrics proposal addresses this issue

**Comment by bogdandrutu** [comment]
The protos that you refer to @SergeyKanzhelev are our exported data. For the API we record only 3 metrics see the #250 PR.

This can be closed for the moment and we can address the supported aggregations in the metrics SDK. Feel free to open if you think we need to track that.
