### ISSUE TITLE
rpc.system should be optional?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1462]
**What are you trying to achieve?**

When instrumenting a library such as the AWS SDK, I think the RPC semantic conventions generally fit. Actually, current instrumentation already follows the rules for the span name, and can fill `rpc.service` and `rpc.method`. But I can't think of a reasonable name for `rpc.system` - it's just a generic POST-based RPC API which I think many people have. Can we leave `rpc.system` optional to accomodate RPC that doesn't fit into any specific framework?

**Comment by Oberon00** [comment]
Could `peer.service` replace `rpc.service` for you? What would you put in `rpc.method`?
If it doesn't fit in any specific framework, not even a custom one, is it really an RPC call or just an HTTP request? If you *are* using a custom one, it is fine to just put the name of your custom RPC library there, even if it just `contoso.rpc`. I think there is value for you to standardize on a name, even if you don't have one yet. Do you actually know the service and method and build the URL from that, or is it the other way round?

**Comment by Oberon00** [comment]
Ah, I now saw that this is caused by https://github.com/open-telemetry/opentelemetry-specification/pull/1422#pullrequestreview-597066153. In that case, I think one can and should come up with a sensible name for `rpc.system`, e.g. `http.aws` or `aws-api` or just `aws`.

**Comment by anuraaga** [comment]
Thanks that makes sense - resolved it in the related PR.
