### ISSUE TITLE
Trace Messaging semantics to add example on Batch Send scenario

### ISSUE THREAD

**Issue by Kanwaldeep** [open-telemetry/opentelemetry-specification#1466]
The current specification has details on Batch Processing and Batch Receiving which is very helpful. Can we add example for Batch send scenario when multiple messages are added to the queue as part of Batch operation? In this case each message could be part of different traces but being added as a batch to the queue.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#examples

**Comment by ramthi** [comment]
Actually in Batch Processing section, the references to C1, C2 and C3 seem to appear in the explanation causing confusion.  Perhaps we can refer to them as Recv1, Recv2, Proc1 instead of C1, C2 and C3?

**Comment by Oberon00** [comment]
@ramthi What do you mean by "out of the blue"? They are in the diagram and in the table, and are named after the processes and I guess the C is for Consume. "Recv" would be a wrong name, as they are "process" not "receive" spans (see messaging.operation).

**Comment by Oberon00** [comment]
@Kanwaldeep 
> Can we add example for Batch send scenario when multiple messages are added to the queue as part of Batch operation? In this case each message could be part of different traces but being added as a batch to the queue.

In a send scenario, isn't usually the current span the correct parent for the send span? I.e. I think all the messages in a batch would usually not only have the same trace but even the same parent span. Or are you thinking of a more complex scenario?

**Comment by Kanwaldeep** [comment]
To make sure I understand you are saying the messages in the batch might have different trace or if within the same trace could have different parent span. That's the scenario I'm referring as well. So in this case when the Batch send operation happens should the Span generated have links to individual messages being sent as part of the batch.

**Comment by Kanwaldeep** [comment]
> @ramthi What do you mean by "out of the blue"? They are in the diagram and in the table, and are named after the processes and I guess the C is for Consume. "Recv" would be a wrong name, as they are "process" not "receive" spans (see messaging.operation).

This is an issue only for the Batch Processing example. Other examples are labelled correctly.

**Comment by ramthi** [comment]
> > @ramthi What do you mean by "out of the blue"? They are in the diagram and in the table, and are named after the processes and I guess the C is for Consume. "Recv" would be a wrong name, as they are "process" not "receive" spans (see messaging.operation).
> 
> This is an issue only for the Batch Processing example. Other examples are labelled correctly.

@Kanwaldeep Thanks for clarifying.  Apologies for not keeping an eye on this PR.  It got buried in all my github notifications
