### ISSUE TITLE
Autogenerate and publish semantic convention tables 

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-specification#1476]
The semantic convention YAMLs require https://github.com/open-telemetry/build-tools/tree/main/semantic-conventions to be generated into human readable tables.  Currently, it's very difficult for people who are not involved in OpenTelemetry to read the semantic conventions. It's affecting their engagement with the project and disserving the project because the references are not accessible.  Automate the generation by generating and publishing the tables after each PR.

**Comment by rakyll** [comment]
They seem to be already autogenerated in this repo, e.g. https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace/semantic_conventions.

Feel free to reopen this if there is anything else to do.

**Comment by anuraaga** [comment]
I would vote to move the current `semantic_conventions` folder to a subfolder somewhere. Even for someone involved in OpenTelemetry, I have a habit of accidentally opening that folder, and realizing I meant to go to the other one with the MD files. The yaml are too discoverable despite being mostly only used for producing, not consuming.
