### ISSUE TITLE
Add spec for handling baggage (ex. custom http headers)

### ISSUE THREAD

**Issue by bputt** [open-telemetry/opentelemetry-specification#148]
We need a spec to help address handling baggage for vendor specific information for its tracing ecosystem.

For example, we have a custom header called foo and this header is useful for client to client communication as we may sample differently based on what value is in that header (like preventing an upstream system from flooding a downstream system as we could offer a lower sampling rate for that specific value).

The spec would ideally allow vendors to identify header(s) that get intercepted and injected (to downstream systems) where some additional logic could take advantage of this header.

One could argue that a vendor could just make up a header and then add some custom code to inject / intercept it, but I feel that this would be helpful as a standardized approach towards sharing additional info that could affect tracing decisions.

Trace Context spec has tracestate which doesn't seem to address this: https://www.w3.org/TR/trace-context/#tracestate-field

**Comment by SergeyKanzhelev** [comment]
Additional headers can be handled using the [Propagators API](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/propagators-api.md). Is it what you are looking for?

**Comment by SergeyKanzhelev** [comment]
Moving to the "SDK revision" milestone in case it will turn out into the feature request

**Comment by jmacd** [comment]
We will use W3C Correlation-Context for this. This is part of the OTEP 66 specification work.

**Comment by carlosalberto** [comment]
Closing it as OTEP 66 was merged.
