### ISSUE TITLE
What should happen when you add an invalid span as a link?

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-specification#1486]
**What are you trying to achieve?**

What should happen when you add a link to the invalid span, e.g. in Java `spanBuilder.addLink(Span.getInvalid())`? Right now this situation is not described by the spec, and in Java SDK it turns out that a link to the invalid span is added and can be even exported.

**Additional context.**

* https://github.com/open-telemetry/opentelemetry-java/issues/2955

**Comment by anuraaga** [comment]
Oh noticed I sent #1492 before getting to this in my notification queue, it would fix this.
