### ISSUE TITLE
Configuring variables

### ISSUE THREAD

**Issue by bputt** [open-telemetry/opentelemetry-specification#149]
Not entirely sure if a spec is what's needed, but it would be nice if there was a way to configure as much as possible.

For example: https://github.com/census-instrumentation/opencensus-java/blob/master/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java#L99

This is a pretty simple example of something that we think should be configurable, but isn't. If everything wasn't declared as a Final, then we could extend. Which leaves us to diverge from the source code or just live with the value that's hard coded..

**Comment by bputt** [comment]
Adding the following as well: https://github.com/census-instrumentation/opencensus-java/blob/3cbeae0db312295781f39053164e68992f1b678e/impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java#L27

EXPORTER_BUFFER_SIZE
EXPORTER_SCHEDULE_DELAY

**Comment by tedsuo** [comment]
Hi @bputt, while I agree we need to allow for some amount of SDK configuration, I don't believe this is should be part of the cross-language spec, as it is very implementation specific. I would like to close this spec ticket for now. Please consider raising this in https://github.com/open-telemetry/opentelemetry-java. 

If you feel there should is some specific form of configuration that should be standardized across languages, please consider opening a new ticket.

**Comment by SergeyKanzhelev** [comment]
@tedsuo do you think it will be language specific? Things like buffer size and a retry delay may be universally specified and it may be even desirable to do to simplify ops. I believe the queue-ing behavior of SDK should be specified quite well as it may affect how exporters and back end should be optimized.
