### ISSUE TITLE
Remove active Span section in Tracer area from the spec-compliance-matrix

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-specification#1493]
In the [Tracer](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#traces) area, we have `Get active Span` and `Mark Span active`, but there is no place to describe these features in the [Tracer API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#tracer-operations). Should we remove these features from the spec-compliance-matrix?

**Comment by arminru** [comment]
These requirements come from this section of the tracing API spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#context-interaction

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#L155-L160

**Comment by arminru** [comment]
If you're concerned about Go in particular, there was a recent PR by @MrAlias that marked it as not applicable for Go due to its explicit context passing: #1487

**Comment by Oberon00** [comment]
I think the concern here is that it is in the **Tracer** section. We discussed some time ago that get/set active should rather not be a tracer method because users would get confused and think that each tracer has a separate active span.

**Comment by XSAM** [comment]
> These requirements come from this section of the tracing API spec:
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#context-interaction
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/d89f446368307fc80c3fad76ad17d5fbef1059f9/specification/trace/api.md#L151-L160

It looks like parts of the `Context interaction` but no related with the `Tracer` API. 

Also, the `Context interaction` section already has `Get active Span` and `Set active Span`, which makes features from the `Tracer` section seems duplicated requirements to me.

**Comment by arminru** [comment]
> It looks like parts of the `Context interaction` but no related with the `Tracer` API.


The context API is separate from the tracing API:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/context/context.md
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md

In the tracing API spec I linked above, it explicitly says that the methods mentioned there SHOULD be offered **by the tracing API**:

https://github.com/open-telemetry/opentelemetry-specification/blob/d89f446368307fc80c3fad76ad17d5fbef1059f9/specification/trace/api.md#L158-L160

I can now see, however, that the statement "_MAY be exposed as either X or Y_" can be interpreted as "_MUST be exposed, but it can be chosen from either X or Y_" or "_if it is (optionally) exposed, then it can be chosen from X or Y_". This is something we should clarify.

Also I think we should add "the **tracing** API SHOULD" here to make it clearer:

https://github.com/open-telemetry/opentelemetry-specification/blob/d89f446368307fc80c3fad76ad17d5fbef1059f9/specification/trace/api.md#L151-L153

**Comment by arminru** [comment]
> Also, the `Context interaction` section already has `Get active Span` and `Set active Span`, which makes features from the `Tracer` section seems duplicated requirements to me.

These are shortcuts/convenience methods for improved usability. It even mentions in the definition that "_This is equivalent to ..._" getting the context first and then calling the methods operating on that context:
https://github.com/open-telemetry/opentelemetry-specification/blob/d89f446368307fc80c3fad76ad17d5fbef1059f9/specification/trace/api.md#L155-L156

**Comment by XSAM** [comment]
@arminru Thanks for the detailed reply.

IIUC, `Get active Span` and `Mark Span active` that in the `Tracer` section from the spec-compliance-matrix means `Tracer` should call `Context` API to get active span or mark span as an active span; it does not say `Tracer` should expose a method for getting active span. Am I right?

**Comment by arminru** [comment]
@XSAM Sorry, I missed your reply.

> it does not say `Tracer` should expose a method for getting active span.

It actually does (line 152):

https://github.com/open-telemetry/opentelemetry-specification/blob/d89f446368307fc80c3fad76ad17d5fbef1059f9/specification/trace/api.md#L151-L156

Given the condition (line 151), we would just add a `N/A` for languages with no implicit context propagation like @MrAlias already did for Go in #1487.
