### ISSUE TITLE
Stabilizing service.name

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#1497]
Currently all attributes are experimental, for example we see the Experimental label.

https://www.github.com/open-telemetry/opentelemetry-specification/tree/main/specification%2Fresource%2Fsemantic_conventions%2FREADME.md

But `service.name` is required to use Zipkin or Jaeger - those exporters are also effectively experimental because of this dependency. Is it possible to mark this attribute stable? I guess we should add support to the yaml generator for stable attributes if so.

**Comment by anuraaga** [comment]
For reference this came up because we don't have a stable way is configuring the service name in Java

https://github.com/open-telemetry/opentelemetry-java/issues/2973

**Comment by Oberon00** [comment]
👍 for making it stable. But we should consider it together with `service.namespace`, as they are closely related. The instance ID stuff should not be made stable yet though, see #1034.

**Comment by rakyll** [comment]
+1 to considering to stabilize the name with namespace. We are thinking about representing service identifiers as a first-class thing in the backends. We should think about the service identity as namespace + name.

**Comment by anuraaga** [comment]
@thisthat Is this something we can add to the yaml tool?

**Comment by thisthat** [comment]
@anuraaga sorry for the late reply! Sure, this can be added to the tool! Currently, we support only **deprecated** attributes. It would be easy to add other markers!

**Comment by jsuereth** [comment]
Fixed by #3202
