### ISSUE TITLE
Add whitespace (and other markdown-specific) linter for PRs

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-specification#15]

**Comment by tylerbenson** [comment]
Perhaps we could at least start with an [editorconfig](https://editorconfig.org/) file for all the projects to share?

**Comment by SergeyKanzhelev** [comment]
Also from @iredelmeier on some PR:

> General comment: having hard wraps in Markdown files makes editing, changing, and tracking history a lot harder than having only natural breaks at paragraph ends with soft wraps in editors :/ (Most Markdown viewers - GitHub's included - are able to handle this decently.)

This is one of those tabs vs. spaces discussions that we need to solve with the linter

**Comment by iredelmeier** [comment]
Definitely, @SergeyKanzhelev.

I just came across [markdownlint](https://github.com/DavidAnson/markdownlint). Looks like it has support for some of what we want/might want, as well as the ability to add custom rules. Thoughts?

**Comment by arminru** [comment]
I'm using markdownlint as a VS Code plugin for my internal projects and found it to be working well so far. I've only been using the default config and didn't add any custom rules or enforce it in our CI yet, though.

**Comment by SergeyKanzhelev** [comment]
I also use markdownlint for VSCode. 

If it can be integrated with CI - it's great. As @yurishkuro suggested somewhere before - an option with the automatic formatter will make peoples life way better. Does mardownlint allows this? I believe Yuri was suggesting https://prettier.io/

**Comment by SergeyKanzhelev** [comment]
At one of the recent SIG meetings the decision was made to have a soft breaks for whitespaces rule. Also spell check is integrated now. If any other specific linters are required - please file a separate issues.
