### ISSUE TITLE
How can OpenTelemetry apply to the mobile applications (Android, iOS)?

### ISSUE THREAD

**Issue by Folyd** [open-telemetry/opentelemetry-specification#1501]
**What are you trying to achieve?**

Although there are so many **APM** solutions for mobile apps, I'd love to seek a possible way to have an integration with OpenTelemetry in the apps. As far as I know, we need a **collector** daemon to collect all trace and span data, which I don't think is feasible for a mobile app. 

**What did you expect to see?**

I can't find any related info about this, hope we can have some documentation instruct mobile apps on OpenTelemetry integration.

**Additional context.**

Nothing.

**Comment by Sherlouk** [comment]
Hi @Folyd,

I'm interested to understand what problems you believe exist in trying to support mobile applications as part of OpenTelemetry?

I've successfully prototyped an iOS application using this specification which hits the OpenTelemetry collector, it then exports data to Prometheus (metrics) and Elasticsearch (traces). While not in production quite yet, we've not run into that many problems.

We have yet to try this out in Android, admittedly, but do not currently foresee any problems. 

For context, we communicate using GRPC and have yet to migrate to the 'official' Swift OpenTelemetry library (we use our own package, currently, though they essentially do the same thing).

I do agree however, it would be great to add specific documentation for an end-to-end setup supporting both native and cross platform mobile apps. This might be something I look to do once my solution is finalised.

**Comment by kedare** [comment]
I am checking also how to do this.

My main question is: How to securely expose the opentelemetry collector publicly, what are risks and how to reduce them ?

**Comment by svrnm** [comment]
This is a question best asked with the Client Side Telemetry SIG, e.g. via slack [#otel-client-side-telemetry](https://cloud-native.slack.com/archives/C0239SYARD2)

**Comment by Sherlouk** [comment]
It doesn't address the comments above directly, but just thought I'd update to my previous comment that our team has now released OpenTelemetry into production in some of our biggest mobile products across iOS and Android. It's definitely doable, and we've had no real issues thus far.

Would certainly be good to see an increase in documentation and security practices etc around this though. We've been doing a lot of experimentation ourselves!

**Comment by mtwo** [comment]
OpenTelemetry has pre-1.0 support for web frontend, iOS, and Android instrumentation, and these are under active development.

Two comments about the questions here (taking into account that the questions are from several years ago and these things didn't exist when the questions were asked!):

- You do not need to run a Collector on each client.
- You can run a Collector within your backend services as a gateway to receive OTLP data from OTel SDKs on clients. You'll likely want to run it behind some kind of proxy.
