### ISSUE TITLE
Consistently format semantic convention enums

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-specification#1519]
Semantic convention enums currently have inconsistent formatting. For example, `os.type` values are all capital (https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/resource/os.yaml#L10) whereas `cloud.infrastructure_service` values are underscored lowercase (https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/resource/cloud.yaml#L45).

With the new requirement of [autogenerating the semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/pull/1515), formatting in the YAML files is important for the code generator developers. Bless a format and consistently use it everywhere.

**Comment by rakyll** [comment]
We decided to take the next steps to provide some consistency here in the SIG meeting. Each language has their own idiomatic way to define constants.

Given the different capitalization rules, it's important to be able to have a delimiter for keys that contains more than one word. I propose us to use all lower case with "_" and rely on autogenerators to produce idiomatic constant identifiers. 

For example, "infrastructure_service" can be autogenerated to:

```
kInfrastructureService
INFRASTRUCTURE_SERVICE
infrastructureService
infrastructure_service
```

**Comment by Oberon00** [comment]
I'm reopening this, since we have this problem again now. See open-telemetry/build-tools#59. Evidently, also need to enforce this
