### ISSUE TITLE
Clarify TraceIdRatioBased Sampler description

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#1524]
[From the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#traceidratiobased):

> Description MUST be `TraceIdRatioBased{0.000100}`

Does this mean this sampler should always return the static string `"TraceIdRatioBased{0.000100}"` even if the ratio is not `0.000100`?

Or should it return `"TraceIdRatioBased{$RATIO}"` with `$RATIO` replaced with a decimal representation of the sampling ratio? If so, what precision should this ratio be?

**Comment by MrAlias** [comment]
Based on what SIGs are doing (especially the ones that have a released a 1.0.0 version) it would follow the specification needs to be updated to reflect the description should be dynamic. E.g.

```
Description MUST return a string of the form `"TraceIdRatioBased{RATIO}"` with `RATIO` replaced with the Sampler instances' trace sampling ratio represented as a decimal number.
The precision of the number SHOULD follow language standards and SHOULD be high enough to identify when Samplers have different ratios.
For example, if a TraceIdRatioBased Sampler had a sampling ratio of 1 to every 10,000 spans it could return `"TraceIdRatioBased{0.000100}"` as its description.
```

**Comment by arminru** [comment]
I'm glad no one interpreted it as "it has to be this constant string regardless of the actual ratio" 😄 

Thanks for digging up the status-quo and presenting it here, Tyler!
Your proposal sounds good to me. Could you please create a PR for that?

**Comment by MrAlias** [comment]
> Your proposal sounds good to me. Could you please create a PR for that?

Sure thing :+1:
