### ISSUE TITLE
Describe built-in SpanProcessors

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#155]
SDK provides a few built-in span processors. These needs to be documented

**Comment by pavolloffay** [comment]
I am back from summer vacations.

@tigrannajaryan @bogdandrutu  I can take care of this, If nobody started working on this.

**Comment by tigrannajaryan** [comment]
@pavolloffay I didn't start working on this yet, so thanks for claiming it.
I unassigned from myself, but don't have permissions to assign to you.
