### ISSUE TITLE
Document Exporter API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#156]
Document API that exporters needs to implement. And how exporters MUST be registered with the TracerSDK

**Comment by hekike** [comment]
How do we think about the graceful shutdown? Should the exporter try to attempt reporting spans when `shutdown()` is called? Opportunistic attempt to report vs. waiting for a call to finish with a timeout.  Spec doesn't define the behavior today.

**Comment by tigrannajaryan** [comment]
We have the following wording in the spec [0]:

>Shutdown should not block indefinitely (e.g. if it attempts to flush the data and the destination is unavailable). Language library authors can decide if they want to make the shutdown timeout to be configurable.

I don't know if we need to specify this further, it seems that if we write more we may impose too much limitations on the implementations.

[0] - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-exporter.md#shutdown

**Comment by SergeyKanzhelev** [comment]
Seems to be comp;leted: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#span-exporter
