### ISSUE TITLE
B3 Propagation Config

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-specification#1562]
There are essentially three ways to configure b3. The b3 spec defines b3 single and multi-header formats. OTel has its own [flavor of b3](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#b3-requirements) where single and multi-header formats should be extracted, but only single-header should be injected. 

The environment variable specification only defines configuration for two of the three formats mentioned above. It defines `b3` as b3 single-header, and `b3multi` as b3 multi-header, but does not provide a value for the OTel flavor. It might be too late to change this, but in a perfect world, I think the following values would make sense:

* `b3` - OTel flavor b3
* `b3multi` - multi-header b3
* `b3single` - single-header b3

Is this change possible or is there an alternative that we can consider?

**Comment by anuraaga** [comment]
@mwear I think in practice, there's basically no situation you'd need to only support a single format on extraction - that would mean getting different data in the two b3 headers which no instrumentation should be doing really. That's probably why we have the current spec and it seems reasonable to me.

For `fields` it is a bit strange but Java currently returns all of them
https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3Propagator.java#L67

I've never actually needed / wanted to use the method before, but looking at the javadoc it seems wrong

https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java#L85

Fields is more to help injection, not extraction, so I guess that Java needs to be fixed to return different `fields`, the injection fields, for the different formats.

**Comment by tedsuo** [comment]
Isn't this OTel b3 the default? When you pick the b3 propagator, you get the otel flavor. Is this good enough?

**Comment by mwear** [comment]
> When you pick the b3 propagator, you get the otel flavor. Is this good enough? 

I think that sounds reasonable.

> Just for clarity, what is the pain point right now?

The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration) currently says this: 

Known values for OTEL_PROPAGATORS are:
    ...
    "b3": [B3 Single](https://github.com/openzipkin/b3-propagation#single-header)
    "b3multi": [B3 Multi](https://github.com/openzipkin/b3-propagation#multiple-headers)
    ...

I think we would need to clarify that `b3` means the OTel flavor in the environment variable spec and change the link from `https://github.com/openzipkin/b3-propagation#single-header` to `https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#b3-requirements`. I can prepare a PR if this makes sense.

**Comment by mwear** [comment]
We discussed this at the maintainers meeting this morning and the consensus is that we should always extract both b3 formats, and that the configuration should correspond to the inject format. We'll clarify this in the specification.
