### ISSUE TITLE
Describe the span class used by Exporters

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#158]
Describe the class used by Exporters: how to get it's instance and it's getters/setters

**Comment by carlosalberto** [comment]
Moving it to 0.4.0 for now.

**Comment by Oberon00** [comment]
Is this about "SpanData"?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev can you please revisit this issue, is it still valid?

**Comment by Oberon00** [comment]
I think we should indeed still define, in the SDK spec, the interface between the exporter and the SpanProcessor. I.e., we pass the Span interface, as specified in the API, that only contains setters, to the SpanProcessor, right? How do we get from that to something "readable" that can be exported? The spec could be as simple as:

> Language implementations must document an appropriate readable interface for the Span when passing them to the exporter. Whether this is a read-only-copy, or just an extended interface for the same object instance, is up to the languages.

But IMHO we should have at least *something*.

**Comment by andrewhsu** [comment]
From the SIG mtg today, sounds like this one would be suitable to be moved to the next milestone.

**Comment by carlosalberto** [comment]
@Oberon00 To me it sounds like we have all the pieces now (`ReadableSpan` and `SpanProcessor` sections). Could you confirm we can close this issue? If not, please list what things remain to be done, so we can start scheduling this part.

**Comment by Oberon00** [comment]
@carlosalberto Indeed my #669 seems to resolve this issue. A more detailed description would be nice (e.g. is the full parent span context required or just the parent ID + isRemote), but I will add a "resolves" link in #669 (which is not merged yet, so we can't close this just yet 😃)

**Comment by bogdandrutu** [comment]
Closing this because it looks resolved by #669

**Comment by Oberon00** [comment]
> Closing this because it looks resolved by #669

Yes, it will be auto-closed once #669 is merged 😉

**Comment by Oberon00** [comment]
As pointed out in https://github.com/open-telemetry/opentelemetry-specification/pull/669#discussion_r458142236, after #669 we still have to specify some details on the SpanData/proto.Span/ReadableSpan class, like that resources should be accessible, whether the full parent SpanContext should be accessible (cf. #366), etc.

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, allowing changes related to this issue for GA if editorial changes only

**Comment by Oberon00** [comment]
I think this was fully resolved with #756. Please reopen if you still see open points.
