### ISSUE TITLE
Log data model documentation terms: "key/value pair list" vs. "map"

### ISSUE THREAD

**Issue by jmm** [open-telemetry/opentelemetry-specification#1592]
Hello,

The [Log Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/ef4612dd0b1f4266e6eca7177290ee2a5f087199/specification/logs/data-model.md) uses both the terms "key/value pair list" and "map", seemingly interchangeably, as in:

> Note: below we use type `any`, which can be a scalar value (number, string or boolean), or an array or map of values. Arbitrary deep nesting of values for arrays and maps is allowed (essentially allow to represent an equivalent of a JSON object).

> Field: `Attributes`
> Type: key/value pair list.

In terms of JSON or languages like Python, "key/value pair list" could be interpreted to mean an array (described as "list" in JSON prose) of 2-element arrays or list of tuples:

```json
[
  ["key", "value"]
]
```

So I think it would be good for clarity to use one consistent term -- whether it's "map", "object" (as in JSON), "dictionary", "hash", "record", or even "key/value pairs" (omitting "list") or "name/value pairs" (as in JSON prose) -- and clearly define it (e.g. the JSON serialization is object [unordered]).

I think "map" is fine as long as the definition is clear, but since the document seems to use "array" to refer to lists as JSON prose does, perhaps it makes sense to underpin the terminology with JSON and use "object" to refer to key/value pairs. The only current usages of "object" refer to JSON objects.

Thanks

**Comment by reyang** [comment]
Discussed during the Friday issue triage meeting, the suggestion is to clarify in the spec that list / map is a language client decision, each language client can have freedom to decide what's the best/idiomatic/performant approach.

**Comment by reyang** [comment]
@tigrannajaryan would you take this?

**Comment by jmm** [comment]
Thanks @reyang.

So are you saying that current instances of "map" and "key/value pair list" would both be replaced by something like: "key/value collection", and at the client level that could be represented by, say, a map (a/k/a dictionary or object) and / or a list of key-value pairs?

To make it more concrete, let's say it's JavaScript, as far as the spec is concerned, something like `Attributes` could potentially be represented in either of the following ways at the client level?:

```js
someClient.log({
  Attributes: {
    key: "value",
  },
})

// or

someClient.log({
  Attributes: [
    ["key", "value"],
  ],
})
```

**Comment by reyang** [comment]
Yes, that's what folks discussed during the issue triage meeting and the general consensus is to allow individual client to decide what's the best way (e.g. in JavaScript/Python it might be convenient to use object/dict, in C++/C# it might be a perf/GC penalty to use std::map/Dictionary<string,object>).

**Comment by jmm** [comment]
Thanks!
