### ISSUE TITLE
Cloudwatch percentiles not working

### ISSUE THREAD

**Issue by CathalAherne** [open-telemetry/opentelemetry-specification#1626]
**What are you trying to achieve?**
Currently I use valueRecorder to record latency like so:

```
this.graphqlFieldResolverTime = this.meter.createValueRecorder("graphql-field-resolver-time");
this.graphqlFieldResolverTime.bind({ field }).record(resolverTime);
```

When I view this in AWS cloudWatch, I can see the average time, but all the percentiles just return 0.
Considering P95 is more useful for latency, I'm assuming its supported but cant see anything in the docs.
Is there something I'm missing or is this just not supported yet?

What did you expect to see?
Percentile values like p99

**Comment by Oberon00** [comment]
@CathalAherne This is almost certainly not a spec issue but an issue in the OpenTelemetry library you are using. Is this Node/JavaScript?

**Comment by CathalAherne** [comment]
Its the opentelemetry-js library. Here's how the metric data looks in the cloudWatch logs if that helps.
Ive tried "@opentelemetry/metrics" version 18.0.0, 18.0.1 and 18.0.2
```
{
    "OTelLib": "Meter",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "queryName",
                "Dimensions": [
                    [
                        "OTelLib"
                    ],
                    [
                        "OTelLib",
                        "query"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "graphql-total-query-time",
                        "Unit": "1"
                    }
                ]
            }
        ],
        "Timestamp": 1618905547657
    },
    "graphql-total-query-time": {
        "Max": 0,
        "Min": 0,
        "Count": 34,
        "Sum": 2215
    },
    "query": "queryName"
}
```

**Comment by CathalAherne** [comment]
Sorry, I should probably log this issue with the opentelemetry-js repo. Didn't realize I posted it in the spec.
