### ISSUE TITLE
Support binary data type for Attributes

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#1644]
It can be useful to allow recording opaque binary data in the Attributes and in the Log Record Body.

`Binary` is a supported data type in Jaeger: https://github.com/jaegertracing/jaeger-idl/blob/34396033ff11c60fced342ab2858ace278fedaa8/proto/api_v2/model.proto#L57 for Spans, Logs and Process.

This has come up a few times in the past and recently here https://github.com/open-telemetry/opentelemetry-specification/pull/1604#discussion_r619702433

I think it can be useful to add this to [AnyValue](https://github.com/open-telemetry/opentelemetry-proto/blob/a17f202fdae65e828ac29fb663b5bc5b64b13290/opentelemetry/proto/common/v1/common.proto#L27) in OTLP and allow it in the Attributes API.

**Comment by Oberon00** [comment]
Is this the same as #780?

**Comment by tigrannajaryan** [comment]
It is indeed a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/780. Closing.
