### ISSUE TITLE
Standardize how to record DroppedAttributeCount in protocols that have no equivalent

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#1656]
For [Jaeger](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md) we suggest to use `otel.event.dropped_attributes_count` tag for Events (Jaeger Logs). We say nothing about how to record the value of DroppedAttributeCount for Spans.

For [Zipkin](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md) this is not defined (the spec says TBD).

I believe we need one standard way to record DroppedAttributeCount in protocols that have no equivalent and do it the same way for Spans, SpanEvents, Logs, Records.

I suggest that we always use `otel.dropped_attributes_count` attribute name to represent DroppedAttributeCount field of Spans, SpanEvents, Logs, Records when the equivalent does not exist in the protocol.

**Comment by reyang** [comment]
@reyang  to follow up with @carlosalberto and create milestones for tracking.

**Comment by codeboten** [comment]
@tigrannajaryan it's unclear to me what generates these dropped attributes/events in the first place. Is that defined somewhere in the specification?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan it's unclear to me what generates these dropped attributes/events in the first place. Is that defined somewhere in the specification?
> 
> To be clear, I'm asking what would be causing this value to be non-zero

I believe they should be populated by SDKs when the limits are hit: https://github.com/open-telemetry/opentelemetry-specification/blob/5a19b53d71e967659517c02a69b801381d29bf1e/specification/trace/sdk.md#span-limits

It is not defined explicitly in the spec, worth adding.

**Comment by codeboten** [comment]
Thank you for clarifying! I can add this to the spec.
