### ISSUE TITLE
Representing events with no clear operation/span to map the event to

### ISSUE THREAD

**Issue by ivomagi** [open-telemetry/opentelemetry-specification#1682]
**What are you trying to achieve?**

Attempting to find a match in semantic conventions for events with no clear operation/span to map to the event. Three different categories of such events seem to currently be able to be represented only as spans for Real User Monitoring, which does not seem to be the correct approach. Possible solution for this category: create a virtual root span for this purpose, where such errors could be mapped as events. But creating such a “virtual span” has problems on its own - what would be the start and especially end criteria for such a span, or would it be just a 0-duration span to hold the event? In a sense we would introduce causality to the model, attempting to tie specific events and requests to a time range, starting from either a pageload or user interaction/route change.

- Javascript Errors. Such errors frequently can't be connected to a specific operation due to the ways errors are usually gathered in browsers ([error](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event) & [unhandledrejection](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) event listeners), so currently the only solution seems to be to send errors as events on zero-duration spans.
- User interactions (clicks, keyboard events, touches). Again, the only option as of now seems to be to represent these as spans with zero duration?
- Web Vitals (LCP, FID. CLS). While they're clearly related to the current `documentLoad` span in `document-load` instrumentation, since web vitals data usually isn't available until the user interacts with the page, the span has usually ended before this data is available. However the current structure and (likely caused by) all of the current exporter data formats not allowing for events to be added after a span has ended. Again, the only option as of now is to represent them as zero-duration spans (or events on such spans), but as opposed to the previous two, they could be considered metrics as well?

**Comment by yurishkuro** [comment]
Why should these events be part of traces at all? If they don't map to a notion of a distributed transaction (which is what traces are for), then these events can be simply logged into a structured log stream.

**Comment by MSNev** [comment]
I would proposed now that the event api spec is defined that what is being asked for here now exists? And therefore this issue could be closed with the recommendation that you should define your specific `events` and emit via the event api.

**Comment by danielgblanco** [comment]
@ivomagi I propose we close this after considering your comment, but you can leave a comment if you think otherwise.
