### ISSUE TITLE
Review Metrics API RFCs 1-4

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#169]
Please review https://github.com/open-telemetry/rfcs/pull/4

The four RFCs are summarized as:

001. Propose a new requirement that all metrics/stats support pre-defined labels
002. Propose a concrete implementation of the new requirement
003. Propose that `stats.Record` is not a requirement
004. Propose how to let the programmer suggest Metric aggregations at the point of definition.

These are intended as stand-alone issues, e.g., if you accept 001 and not 002 we can discuss other approaches. If 001 and 002 are accepted, 003 is an option. I see 004 as the key to making 001 and 002 work, but am open to other ideas.

**Comment by bogdandrutu** [comment]
We will have a meeting tomorrow (July 9) at 1pm PST. Please use https://lightstep.zoom.us/j/516112682
