### ISSUE TITLE
Tracer resolution default

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#171]
Currently the spec defines this as:

> Tracer provider is an internal class used by the global registry (OpenTelemetry) to get a tracer instance. The global registry delegates calls to the provider every time a tracer instance is requested. This is necessary for use-cases when a single instrumentation code runs for multiple deployments.

But there's no actual mention on what should be loaded if there's no explicitly defined Tracing component - should it try to no-op one (API only), or should it **try** the actual SDK? (My feeling is that the former should be the one)

 This came up in OpenTelemetry in Python (https://github.com/open-telemetry/opentelemetry-python/pull/29/).

**Comment by z1c0** [comment]
Having the no-op tracer as default seems like the most reasonable approach.
Trying to load the actual SDK would either mean tight coupling of API and SDK or having to rely on reflection, dynamic loading, ...

**Comment by jmacd** [comment]
See also https://github.com/open-telemetry/oteps/pull/45

**Comment by tedsuo** [comment]
Decision: observability APIs are write only, so a default implementation will be a No-op.

When context propagation becomes a separate layer, it may have a default implementation.  https://github.com/open-telemetry/oteps/pull/66
