### ISSUE TITLE
resource for runtime version

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-specification#1743]
Is there any resource attribute for the runtime version in the specification?
For example, if my service is running in nodejs I would expect to get "nodejs" in [`telemetry.sdk.language`](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#telemetry-sdk), but I need to also know the version of nodejs itself (for example: `12.18.3`)

Thanks

**Comment by kenfinnigan** [comment]
Take a look at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/process.md#process-runtimes it defines how a NodeJS process should be defined as a `Resource`

**Comment by blumamir** [comment]
Thanks, I missed this part :)
