### ISSUE TITLE
Question about handling partially-bad data

### ISSUE THREAD

**Issue by josh-endries** [open-telemetry/opentelemetry-specification#1745]
Reading through the [OTLP document](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) I came across this bit:

> Bad Data
If the processing of the request fails because the request contains data that cannot be decoded or is otherwise invalid and such failure is permanent then the server MUST respond with HTTP 400 Bad Request. The Status.details field in the response SHOULD contain a BadRequest that describes the bad data.
> 
> The client MUST NOT retry the request when it receives HTTP 400 Bad Request response.

Given that these requests are (or can be) batches, is there any guidance on what should happen if only some of the embedded items are bad, but others are valid? Should the whole batch be invalidated if any items are invalid, or partially-accepted and details on the bad items returned, something else, or is it simply unspecified?

Update: Based on this piece:

> Not-retryable errors indicate that processing of telemetry data failed and the client MUST NOT retry sending the same telemetry data. The telemetry data MUST be dropped. This can happen, for example, when the request contains bad data and cannot be deserialized or otherwise processed by the server. The client SHOULD maintain a counter of such dropped data.

It seems like if any item in a batch is invalid, then the whole batch must be invalidated and not retried, thereby losing any valid items in that batch. This seems unfortunate, but is that interpretation correct?

**Comment by tigrannajaryan** [comment]
> It seems like if any item in a batch is invalid, then the whole batch must be invalidated and not retried, thereby losing any valid items in that batch. This seems unfortunate, but is that interpretation correct?

Yes, that is the current spec. If we want more granular reporting of invalid data we need to extend the responses to describe what portion of the request is bad. It is likely doable, but requires an OTEP and careful consideration of backward compatibility.

**Comment by jsuereth** [comment]
+1 to OTEP.

I'd be a fan of having the response report:  

- # of data items accepted
- Identifier of rejected data.

**Comment by josh-endries** [comment]
Okay, thanks for the clarification.

That is basically what I did for our internal use case... just jammed into the InvalidArgument response message a count of accepted/rejected messages and a list of invalid items (as JSON). Sadly GRPC doesn't seem to have a good return code for an inconclusive/partialsuccess situation.

I'm going to close this as it's really just for clarifying the expected behavior and not really a request for implementing OTEP, which should probably go in its own issue. Thanks again!
