### ISSUE TITLE
"Semantic Conventions for System Metrics" uses outdated metric instrument types

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#1749]
The [Semantic Conventions for System Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/a5d34467b954866ffff90a1c0ef29a43a040b961/specification/metrics/semantic_conventions/system-metrics.md) document uses the outdated names for instrument types (SumObserver, ValueObserver...). It should be updated to the new metrics API.

**Comment by arminru** [comment]
Duplicate of #1788 which has a broader scope.

Thanks for bringing it up @mx-psi!
