### ISSUE TITLE
Make the specification more flexible

### ISSUE THREAD

**Issue by rochdev** [open-telemetry/opentelemetry-specification#175]
Right now a very specific API is enforced that is Java-centric and makes for a very poor API in most languages. The specification should focus more on concepts that should be implemented and not specific classes and methods.

So far, almost every time a change was proposed in `opentelemetry-js` that would make the API a lot better and idiomatic for the user was rejected as it doesn't conform to the spec. This means that we are currently forced to implement an API that makes no sense for JavaScript.

**Comment by arminru** [comment]
+1
This was already brought up in #165, you might want to join the discussion there.

**Comment by rochdev** [comment]
Thanks for pointing that out!

Closing in favor of #165
