### ISSUE TITLE
Span link and event count limits should have corresponding environment variables

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-specification#1750]
**What are you trying to achieve?**

Environment variables are defined for setting span attribute limits, but not span link and event attribute limits. These should exist to be consistent.

**Comment by carlosalberto** [comment]
Personally I'd be up for having all of it in a single environment variable (probably a new one), unless there's a technical reason to really want to have limits per Span/Event/Link.

**Comment by kubawach** [comment]
I believe that keeping this separated (per span attribute, span link, event) makes certain sense from eg backend processing point of view. Different backends may have certain limitations with eg rendering of operations or connected data, so having these configurable at the agent level may help customers and increase OTEL adoption.

**Comment by carlosalberto** [comment]
Yes, we do. In a perfect world we don't need that much level of detail in the public configuration and a single value should be fine ;) I'm ok with the proposed solution but I'd rather go for the simplest way :D
