### ISSUE TITLE
Limit types allowed for Log Record `Body`

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-specification#1752]
**What are you trying to achieve?**

Currently, `Body` is of `any` type, which allows for strings (actually, scalars), byte array, list of `any` values or a `map<string, any>`. In the last case, this brings confusion when to use `Attributes` (which is of `map<string, any>`)

This was discussed in https://github.com/open-telemetry/opentelemetry-specification/issues/1613 and https://github.com/open-telemetry/opentelemetry-specification/pull/1727

One of the [observations](https://github.com/open-telemetry/opentelemetry-specification/pull/1727#discussion_r642611355) was that we anticipate  either fully-structured or partially-structured logs and it's hard to anticipate a use case when `Body` coming from a logging library would contain a map or an array.

Perhaps the `Body` type should be reconsidered and limited to `string` and `bytearray`, which better fits the existing use-cases. This would also avoid the confusion when to use Attributes. The complex types could be still included as entries in `Attributes`.

**Comment by pmm-sumo** [comment]
My goal with this issue is to validate if we need to have complex types in `Body`. And concluding that we do (and the issue should be closed) is a fair answer.

When looking at the [example mappings](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#appendix-a-example-mappings) - the cases where `any` is needed are Splunk HEC and Google Cloud Logging. Perhaps it's important to retain it to keep the original data structure. If not, maybe the cases for complex types could be moved to Attributes or serialised as JSON into Body?

The other way to look at it is if end-user will want to discern between `Body` attributes (when it is a map) and regular `Attributes`. Maybe the answer is _we don't know_ and I believe in such case it's better to keep `any`

**Comment by SergeyKanzhelev** [comment]
I feel like keeping it make sense. Do you think the resolution for this issue might be some additional clarification on how it is used? Or it is clear enough already?

**Comment by pmm-sumo** [comment]
> I feel like keeping it make sense. Do you think the resolution for this issue might be some additional clarification on how it is used? Or it is clear enough already?

@SergeyKanzhelev this was actually sparked by the attempt to clarify it: #1727 :)

**Comment by SergeyKanzhelev** [comment]
Sorry, missed that.

**Comment by SergeyKanzhelev** [comment]
I actually think that https://github.com/open-telemetry/opentelemetry-specification/issues/1752#issuecomment-857915536 makes a lot of sense - it may be the best we can do from vendor-neutral data collection standpoint

**Comment by errordeveloper** [comment]
> ...maybe the cases for complex types could be moved to Attributes or serialised as JSON into Body?

I am not sure if JSON strings in `Body` are practically useable, it's quite likely that users would want to query fields inside the JSON string, but how would a backed know that these are to be index or not? Perhaps producer happens to use an encoding other then JSON, like a simple comma-separated k/v format or some binary encoding. Perhaps a well-know attribute will need to define to hint backends at what type of data is in the body...

**Comment by djaglowski** [comment]
I believe this issue should be closed now. #2096 clarifies that body can be structured.
