### ISSUE TITLE
Selecting multiple exporters via environmental variables

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#1755]
## What are you trying to achieve?

The [exporter selection environmental variables](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection) allow only to select a SINGLE one. It would be handy to allow selecting more than one e.g. `otlp,console`.

## Additional context

An issue where multiple exporters were also mentioned: 
- https://github.com/open-telemetry/opentelemetry-specification/issues/1309
- https://github.com/open-telemetry/opentelemetry-specification/pull/1318

### Allow adding more than one exporter

We can allow adding multiple exporters separated by `,`  via `OTEL_TRACES_EXPORTER` and `OTEL_METRICS_EXPORTER`.

The only problem is that it is not a forward-compatible change. However, it is backward-compatible.

Example: `OTEL_TRACES_EXPORTER=zipkin,otlp`

### Add new env vars 

We can add new  `OTEL_TRACES_EXPORTERS` and `OTEL_METRICS_EXPORTERS` env vars which could contain a comma-separated list of exporters.

This change is forward-compatible, however, it makes the API/specs longer. Moreover e,.g. if both `OTEL_TRACES_EXPORTER` and `OTEL_TRACES_EXPORTERS` are specified then the "result" should be concatenated. 

Example: if `OTEL_TRACES_EXPORTER=jaeger` and  `OTEL_TRACES_EXPORTERS=zipkin,otlp` then we should add all 3 exporters.

**Comment by pellared** [comment]
FYI @anuraaga @pjanotti

**Comment by carlosalberto** [comment]
I'd be up for the first approach. Certainly it won't work with _old_ versions but we keep things simple. Also, adding _more_ environment variables may create a lot of noise.

**Comment by kubawach** [comment]
Same as @carlosalberto with the first approach. Also, I've seen customer requests for this surfacing multiple times already, often to validate what's being sent with logger exporter.

**Comment by pellared** [comment]
PR for first approach: https://github.com/open-telemetry/opentelemetry-specification/pull/1758
