### ISSUE TITLE
`host` attribute key should be interchangeable with `device`

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/opentelemetry-specification#1765]
**What are you trying to achieve?**
@jkwatson brought up a good point in a mobile-related spec pr regarding the attribute key `host` feels weird when dealing with mobile devices. Here is a [link to the conversation for reference](https://github.com/open-telemetry/opentelemetry-specification/pull/1759#discussion_r652167670). 

It would be useful to allow for `host` and `device` to be used interchangeably in the spec depending on context, i.e. server vs mobile device. 

There is already some precedent to define `device` based attributes in [semantic_conventions/device.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/device.md) , but it might be easier to allow `host` and `device` to be mapped to the same semantic idea, rather than duplicate all attributes under a `device` header. 

some examples: 
in [resources/semantic_conventions/host.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md)
`host.id` could also be `device.id` 
`host.name` could also be`device.name`
... 

in [trace/semantic_conventions/span-general.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md)
`net.host.ip` could also be `net.device.ip`

**Comment by Oberon00** [comment]
I am against this change in the proposed form, I think it adds too much complications:
* What should the semantic convention generator generate? All combinations? How do you teach it that device and host are synonymous?
* You'd need to ensure that replacing host/device with each other still leads to unique names. I noticed that `host.id` and `device.id` indeed both exist and seem to describe the same concept. That is an issue and should be fixed (probably by removing one of them).
* On the backend, you'd probably need to normalize this again for normalization which should not be too hard (`string.replace_regex(r"(^|\.)device\.", r"\1host.")`) but will cost a bit performance. If you additionally want to store the original attribute names, this becomes more complex to store.
* How would this effect the recently introduced schema? Maybe that is covered by the above point already, maybe not.

I am open to renaming the `host`/`peer` suffixes inside of `net.` though, e.g. to `local`/`remote` or `this`/`other`. Note that I think it is important there is exactly one suffix per side here. If we add `device` to `host` and `peer`, it is not immediately clear that this is the "host device" and not the "peer device".

**Comment by arminru** [comment]
Thanks for your input, @Oberon00.
@bryce-b What do you think taking these concerns into consideration? I think we are likely better off with the current distinction but should certainly address the issue raised in the comment above (#1768).

As for the renaming within `net.*` @Oberon00's options sound reasonable to me. I would not be opposed to consider a (mobile) device a host in a host/peer scenario but local vs remote sounds clearer to me actually.

**Comment by bryce-b** [comment]
Excellent points @Oberon00! I think renaming `host`/`peer` to another pair of terms isn't really valuable in terms of resolving the device vs service confusion therein, and I agree adding `device` to the `host`/`peer` mix will make things confusing as well.  I think in terms of network activity, the relationship of `host`-`peer` is what is important.

**Comment by bryce-b** [comment]
I think the conversation around the resource semantic convention is were the focus should be. Let's take it to #1768
