### ISSUE TITLE
Google Cloud Logging specification:  log_name should not map to Name

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#1808]
**What are you trying to achieve?**

According to the logging data model: `Name: Short event identifier.`, and additionally in the [Google Cloud mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#google-cloud-logging), `Name` is set to `log_name`, which is documented [here](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#logentry).

TL;DR; `log_name` in cloud represents more of a "source file" of the log and not an event identifier.  It has values like: 

```
"projects/[PROJECT_ID]/logs/[LOG_ID]"
"organizations/[ORGANIZATION_ID]/logs/[LOG_ID]"
"billingAccounts/[BILLING_ACCOUNT_ID]/logs/[LOG_ID]"
"folders/[FOLDER_ID]/logs/[LOG_ID]"
```

Which does not seem to be in the spirit of the logging data model.

### Proposal

We should move `log_name` to either an Attribute or Resource.Attribute in the logging data model.

**Comment by djaglowski** [comment]
This was discussed today in the Log SIG as part of our effort to resolve any issues that may affect the log data model. PR #2092 potentially resolves the issue, pending review from @jsuereth.
