### ISSUE TITLE
Use same language as W3C TC spec

### ISSUE THREAD

**Issue by c24t** [open-telemetry/opentelemetry-specification#181]
Motivated by @mayurkale22 and @reyang's [comments on the trace state in the python client](https://github.com/open-telemetry/opentelemetry-python/pull/47#discussion_r302648314).

We use different language in the OT spec and W3C spec: "span ID" instead of "parent-id", `TraceOptions` instead of "trace-flags", and (in the java and js clients) "sampled" instead of "recorded". This is a minor issue at best, but may be confusing to newcomers.

Should we use the W3C terms or resolve to use our own?

**Comment by reyang** [comment]
`options` versus `flags` seems to be a personal taste, aligning with the W3C spec would be great.

Regarding `parent-id`, this is what we have in OpenCensus and it is sometimes confusing:

[SpanData(name='span1_child2', context=SpanContext(trace_id=5307201ee66cb0de85dc049c6470f046, **span_id=31101d982462798f**, trace_options=TraceOptions(enabled=True), tracestate=None), **span_id='dfd42fc07f7e519a'**, **parent_span_id='31101d982462798f'**, attributes=BoundedDict({}, maxlen=32), start_time='2019-07-12T01:04:21.347327Z', end_time='2019-07-12T01:04:21.347327Z', child_span_count=0, stack_trace=None, annotations=BoundedList([], maxlen=32), message_events=BoundedList([], maxlen=128), links=BoundedList([], maxlen=32), status=None, same_process_as_parent_span=None, span_kind=0)]

It might be better if it is:

[SpanData(name='span1_child2', context=SpanContext(trace_id=5307201ee66cb0de85dc049c6470f046, **parent_id=31101d982462798f**, trace_options=TraceOptions(enabled=True), tracestate=None), **id='dfd42fc07f7e519a'**, **parent_id='31101d982462798f'**, attributes=BoundedDict({}, maxlen=32), start_time='2019-07-12T01:04:21.347327Z', end_time='2019-07-12T01:04:21.347327Z', child_span_count=0, stack_trace=None, annotations=BoundedList([], maxlen=32), message_events=BoundedList([], maxlen=128), links=BoundedList([], maxlen=32), status=None, same_process_as_parent_span=None, span_kind=0)]

**Comment by bogdandrutu** [comment]
TraceOptions was already renamed to TraceFlags.
w3c uses sampled now.

Anything else to discuss here? May worth closing and open the parent discussion if you feel that way.

**Comment by SergeyKanzhelev** [comment]
seems to be fixed now
