### ISSUE TITLE
Collector and Specification http port do not match

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#1816]
The specification says the default OTLP/HTTP port is 4317 [[link](https://github.com/open-telemetry/opentelemetry-specification/blob/faae76d4c936143e5a163ea4ab45b007486cda4f/specification/protocol/otlp.md#otlphttp-default-port)]

The collector itself defaults to port 55681 [[code link](https://github.com/open-telemetry/opentelemetry-collector/blob/7e7ee8fb3a4b9535788ce484bfca1d27786433ab/receiver/otlpreceiver/factory.go#L34)] [[docs link](https://github.com/open-telemetry/opentelemetry-collector/blob/7e7ee8fb3a4b9535788ce484bfca1d27786433ab/receiver/otlpreceiver)]

**Comment by dyladan** [comment]
Should I open this in the collector?

**Comment by lonewolf3739** [comment]
Related issue on collector repo https://github.com/open-telemetry/opentelemetry-collector/issues/3617

**Comment by carlosalberto** [comment]
So currently the Spec indeed mentions 4317 is the default port for **both** gRPC and http - however (as @jmacd mentioned in the last Collector SIG call, IIRC), we at Lightstep had a few problems running different protocols in the very same port. Wondering _how bad_ would it be to change that now?

E.g. @bogdandrutu suggested to go with 4318 for http, which I'd support.

**Comment by anuraaga** [comment]
Doesn't seem like 4318 has been claimed by OTel yet

https://www.speedguide.net/port.php?port=4318

Unlike e.g. 4317

https://www.speedguide.net/port.php?port=4317

Not sure how that happens but probably would need it if using 4318.

**Comment by Oberon00** [comment]
> Not sure how that happens but probably would need it if using 4318.

This is described in #1148

**Comment by tigrannajaryan** [comment]
Some historical context: we wanted to make grpc and http use the same port and we had an open issue in the Collector to do so: https://github.com/open-telemetry/opentelemetry-collector/issues/1256
The conclusion appears to be that there are technical hurdles that make it unfeasible: https://github.com/open-telemetry/opentelemetry-collector/issues/1256#issuecomment-880048833

Because of that we need to keep grpc and http ports separate. I believe this means we need to change the spec to say that otlp/http uses port 4318 and also submit for port registration with IANA like we did previously with 4317.

**Comment by carlosalberto** [comment]
@tigrannajaryan Thanks, sounds like a plan to me. Can you take on that? Else I offer myself to do so, as this seems to be a rather important issue.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan Thanks, sounds like a plan to me. Can you take on that? Else I offer myself to do so, as this seems to be a rather important issue.

PR submitted.

**Comment by tigrannajaryan** [comment]
This is done now, closing.

**Comment by tigrannajaryan** [comment]
Created an new issue to register the new port with IANA https://github.com/open-telemetry/opentelemetry-specification/issues/1846
