### ISSUE TITLE
Define metric semantic conventions for OS processes

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#1817]
The list of process metrics TBD, but can possibly include things like process uptime, cpu and memory usage, etc.

We have an empty [Semantic Conventions for OS Process Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md) page where we intended to list the process metrics.

**Comment by jrcamp** [comment]
Note that we have some process metrics today in hostmetricsreceiver, see process.*: https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/hostmetricsreceiver/metadata.yaml#L100
