### ISSUE TITLE
Minimal implementation is unclear on context propagation

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#183]
I'm starting on the Erlang version of the API and minimal implementation and I find it unclear what exactly it should and shouldn't be doing.

On Gitter Tigran explained that it is not the same as the noop tracer because it is expected to do context propagation. And the spec makes clear it should not return a null span but a valid non-null span object.

What isn't clear is does having context propagation and non-null spans imply that a `startSpan` will create a new child span id as the current context? Or is it expected that the same context as was started with will be what is propagated? If the latter, what about when there is no parent span, then a new span id and trace id must be created?

**Comment by bg451** [comment]
I was wondering the same thing. If you have a noop span, should you still pass through a span context that was received out of band? e.g. service A and C have tracing enabled and service B has tracing disabled. A makes a call to B which makes a call to C. If the minimal noop span in B doesn't pass the context through to C the trace will break at A.

I guess it's a trade off of reducing allocations when tracing is disabled vs not breaking traces. I lean towards the latter being the case for a noop implementation.

> when there is no parent span, then a new span id and trace id must be created.

My gut says the answer is no, if you start a span with no parent and it's a no op implementation, you can leave the span context empty until you reach code that has tracing enabled, which can then determine the sampled flag and all the jazz.

**Comment by mtwo** [comment]
@bogdandrutu @SergeyKanzhelev

**Comment by tsloughter** [comment]
> My gut says the answer is no, if you start a span with no parent and it's a no op implementation, you can leave the span context empty until you reach code that has tracing enabled, which can then determine the sampled flag and all the jazz.

True, but the "minimal" implementation that is part of the API is not the same as the noop implementation.

**Comment by z1c0** [comment]
The "minimal implementation" that is referenced [here](https://github.com/open-telemetry/opentelemetry-specification/blob/41014a5a8329256eff10a19b602537c8dcec3331/specification/library-guidelines.md#api-and-minimal-implementation) is described as being "part of the API" and "incurring as little performance penalty as possible". This sounds a lot like a no-op implementation to me.

Is a there even a section in the specification that makes a clear distinction between:
* No-Op Implementation
* Minimal Implementation

This is a prerequisite for having this discussion about context propagation at all, I think.

**Comment by tsloughter** [comment]
@z1c0 I don't think there is a section that makes a clear distinction. I asked in gitter before creating this issue and that is where I learned it was distinct.

**Comment by carlosalberto** [comment]
> This is a prerequisite for having this discussion about context propagation at all, I think.

I suggest discussing this as part of #208 where I hope we can come to a resolution about this point ;)

**Comment by tedsuo** [comment]
Hi all, I'm closing this in an attempt to resolve this conversation in #208. Please reopen if you feel there is additional scope to this issue.
