### ISSUE TITLE
Clarification on when to capture http.client_ip

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#1845]
**What are you trying to achieve?**

Clarification whether or not to populate `http.client_ip` with the remote address (e.g. same value as `net.peer.ip`) when there is no `Forwarded` or `X-Forwarded-By` header.

**Additional context.**

The current definition of `http.client_ip` in the [HTTP Server semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions):

> The IP address of the original client behind all proxies, if known (e.g. from X-Forwarded-For). [2]
>
> [2]: This is not necessarily the same as net.peer.ip, which would identify the network-level peer, which may be a proxy.

**Comment by Oberon00** [comment]
I would say, you should fill it in when you have any source of information different from the one you use for net.peer.ip, even if that other source just confirms the net.peer.ip.
For net.peer.ip, you typically have no idea if it comes from a proxy, reverse proxy, or the actual client. Setting http.client_ip when it's the same as net.peer.ip would mean that you are at least somewhat confident that the address is not that of a proxy.

The mentioned X-Forwarded-For header might be such a source of information, the cognito source_ip in AWS (https://github.com/awsdocs/aws-lambda-developer-guide/blob/0f502cb6a2035d89d1e998f5f4dc5e75c64522d2/sample-apps/nodejs-apig/event.json#L87) might be another.

**Comment by trask** [comment]
> I would say, you should fill it in when you have any source of information different from the one you use for net.peer.ip, even if that other source just confirms the net.peer.ip.

this makes sense to me, any other thoughts?

**Comment by anuraaga** [comment]
This seems to make sense, but I wonder if the IP can be derived in a way that doesn't use http headers, should it be moved out of the http namespace? Guessing no mostly because that would be too tedious at this point.

**Comment by Oberon00** [comment]
> This seems to make sense, but I wonder if the IP can be derived in a way that doesn't use http headers, should it be moved out of the http namespace? Guessing no mostly because that would be too tedious at this point.

I had the same thought, e.g. a `net.client.*` namespace could make sense. Especially since the cognito stuff is not necessarily routed with HTTP to a Lambda function AFAIK? We can deprecate (theoretically also remove) `http.client_ip`, as semantic conventions are still experimental.
