### ISSUE TITLE
Register OTLP/HTTP port 4318 with IANA

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#1846]
We have recently added a new OTLP/HTTP port 4318 to the specification (in addition to previously existing OTLP/gRPC port 4317).

We need to register the new port with IANA. Port 4317 description currently says "OpenTelemetry Protocol". For port 4318 we can probably use "OpenTelemetry Protocol, HTTP Transport" or "OpenTelemetry Protocol, OTLP/HTTP". Ideally also change description for port 4317 to be uniform to something like "OpenTelemetry Protocol, gRPC Transport" or "OpenTelemetry Protocol, OTLP/gRPC".

@mtwo you did the IANA submission for port 4317, can you help with the new port as well?

**Comment by tigrannajaryan** [comment]
Apparently there is new evidence that one port may work after all: https://github.com/open-telemetry/opentelemetry-collector/pull/3765/files

I suggest we hold this issue and don't submit to IANA just yet until we have more clarity on this. Depending on the outcome we may need to do things a bit differently here in the spec.

**Comment by carlosalberto** [comment]
@tigrannajaryan We are expected to do a monthly release by EOW. What do you think we should do? Revert this change _for now_?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan We are expected to do a monthly release by EOW. What do you think we should do? Revert this change _for now_?

@carlosalberto yes, I think reverting is a good idea. Let's aim to settle this for the release after this one.

**Comment by tigrannajaryan** [comment]
I will submit a PR.

**Comment by tigrannajaryan** [comment]
Reverting PR submitted: https://github.com/open-telemetry/opentelemetry-specification/pull/1847

**Comment by tigrannajaryan** [comment]
Closing this issue for now to avoid accidentally moving forward with IANA. I will reopen if needed.

**Comment by tigrannajaryan** [comment]
IIRC, IANA did not want to register a second port.

**Comment by mtwo** [comment]
+1 to Tigran’s comment. He and I requested a second port a few years ago, and they told us to just use the first one for multiple purposes. We asked for reconsideration (with an explanation) and were told no.
________________________________

**Comment by jpkrohling** [comment]
Thank you for the extra context, I was not aware of those attempts.

**Comment by bogdandrutu** [comment]
This
