### ISSUE TITLE
How to know a parent is remote when starting a span

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#187]
Whether or not the parent of a span that is being started is remote is an attribute that must be passed to samplers.

[Span creation](https://github.com/open-telemetry/opentelemetry-specification/blob/0d255935cc6569a6f195daaaf361453dbd9cb5ac/specification/tracing-api.md#span-creation) docs do mention remote parents but it isn't clear how it is deciding it is remote:

>  tracer.StartSpan(options.WithNoParent(), options.WithParentContext(parentCtx)) will generate a new child span with remote parent parentCtx, and WithNoParent will be ignored.

Why is it assumed that `parentCtx` is remote here?

In OpenCensus we had a optional remote parent flag that could be set when calling `start_span`.

**Comment by tsloughter** [comment]
Based on the Java implementation it does appear the decision is based on if the parent is a Span or SpanContext. This doesn't work well for at least the Erlang implementation where the user will only ever have the context for use as a parent.

I think there should be a explicit `is parent` or similar option.

**Comment by mwear** [comment]
Typically, a `SpanContext` that has crossed a process boundary will have been **extracted** with a propagator. This could be solved by adding a boolean property to indicate that on the `SpanContext`. Possible names could be `Is/WasRemote`, `Is/WasExtracted`. Since `SpanContext` is a sealed class I assume this would require buy-in from the community and a change to the spec.

**Comment by tsloughter** [comment]
@mwear yea, that is what OpenCensus did. For now I'm adding a `is_remote` to span context to move forward.

How to propose adding this officially to the `SpanContext`? Just a PR to update the spec or does it belong in an rfc first?
