### ISSUE TITLE
Propagation Getter spec can't support W3C spec

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#1870]
The specification for Otel's TextMap propagator `Get` function and the W3C spec conflict in how to handle multiple of the same key in a list of pairs. The Otel spec has an optional `Get` that must return value, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#get, while in W3C in the case of `traceparent` a new trace should be started: https://github.com/w3c/trace-context/blob/main/test/test.py#L136-L137

For `tracestate` W3C says it must combine the values of the `tracestate` key.

I think `Getter` has to change to return every pair with the key being looked up. But this is not backwards compatible? Maybe it will have to be that the `get` function can return a single value if only one is found but a list if there are multiple? That way existing `Getter` implementations continue to work.

**Comment by mwear** [comment]
It would be possible to combine the multiple headers into one by concatenating the values separated by a `,`. This is briefly mentioned in the [W3C Trace Context spec](https://www.w3.org/TR/trace-context/#tracestate-header-field-values). It says:

 > When receiving multiple `tracestate` header fields, they MUST be combined into a single header according to [RFC7230](https://httpwg.org/specs/rfc7230.html#field.order).
 
 The relevant part of RFC7230 says:
 
 > A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma. The order in which header fields with the same field name are received is therefore significant to the interpretation of the combined field value; a proxy MUST NOT change the order of these field values when forwarding a message.

**Comment by tsloughter** [comment]
Yes, this is what we do in the Erlang W3C propagator implementation. But this became not possible in the propagator itself when adding support for a `Get` function that can be set by the user and only returns the first element.

An option instead of adding a `GetAll` or having `Get` return a list would be to define `Get` to have to combine duplicates using the method of RFC7230 if it is for a data structure that can have duplicates -- meaning if your `Get` is defined for a dictionary it wouldn't have to do anything special, but one that takes a list or array would have to search for all matches and combine them.

**Comment by tsloughter** [comment]
Closing because I found https://github.com/open-telemetry/opentelemetry-specification/issues/433 already exists from a year and a half ago and I've opened https://github.com/open-telemetry/opentelemetry-specification/pull/1884
