### ISSUE TITLE
OTEL_EXPORTER_JAEGER_ENDPOINT sdk env option has wrong default value

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-specification#1871]
[According to the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter), the default value for OTEL_EXPORTER_JAEGER_ENDPOINT should be `http://localhost:14250`.

According to [Jaeger website](https://www.jaegertracing.io/docs/1.25/getting-started/), port 14250 is used to send spans in `model.proto` format, where port 14268 "accept jaeger.thrift directly from clients".

In GO sdk, the default value is [different from the specification](https://github.com/open-telemetry/opentelemetry-go/blob/fd7c327b558f11bcaa4926390ecfc88da9ee51e6/exporters/jaeger/uploader.go#L154): "http://localhost:14268/api/traces". 

[This PR](https://github.com/open-telemetry/opentelemetry-go/pull/1898) changed it and explains why the value in the spec is not correct.

JS sdk is also mentioning the 14268 endpoint [here](https://github.com/open-telemetry/opentelemetry-js/blob/56c032ec71c0baa0120a5cc841c015a290fad654/packages/opentelemetry-exporter-jaeger/src/types.ts#L27) instead of the default 14250.

I suspect that the value should change in spec from `http://localhost:14250` to `http://localhost:14268/api/traces`

**Comment by carlosalberto** [comment]
cc @yurishkuro

**Comment by lonewolf3739** [comment]
I believe it is 14268 for thrift over http and 14250 for proto over grpc. See the related [exporter selection](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection) where known value `jaeger` for `OTEL_TRACES_EXPORTER` recommends using Jaeger gRPC.

**Comment by blumamir** [comment]
> exporter selection

Thanks for the reference. Wonder why GO and JS choose to export via thrift and not gRPC. 
Anyhow it's not related to this issue I suppose.
