### ISSUE TITLE
Is SpanContext the same during the entire Span lifetime?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#189]
Some implementations need to change the sampling flag during the lifetime of a span.

**Comment by SergeyKanzhelev** [comment]
And potentially add/modify `tracestate` collection

**Comment by jmacd** [comment]
This suggests to me that `tracestate` is not part of the `SpanContext`. We've changed the sampling API to return an immutable SpanContext once, so this is not needed.
