### ISSUE TITLE
Confused with SpanKind of Producer.

### ISSUE THREAD

**Issue by aaron-ai** [open-telemetry/opentelemetry-specification#1903]
I saw the span kind of producer was defined:

> A producer of a message should set the span kind to PRODUCER unless it synchronously waits for a response: then it should use CLIENT.

AFAIK, most of sending action of messaging system is synchronous, therefore which kind of span should be defined as producer ?

Thx.

**Comment by Oberon00** [comment]
The meaning of this spec statement is that client should be used if the sender waits for a response from some recipient of the message, not some return value of the send function (which may asynchronous or synchronous). I was under the impression that many messages are sent in a "fire-and-forget" fashion.
