### ISSUE TITLE
Reword metrics spec to clarify what "client" means

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#1918]
In both the metrics API and SDK specs, I see a mix of "[the API](https://github.com/open-telemetry/opentelemetry-specification/blob/09944db81a980b40e25b3d1bfd247b30596272da/specification/metrics/api.md#:~:text=Thus%2C%20the%20API%20SHOULD%20provide%20a%20way%20to%20set/register%20and%20access%20a%20global%20default%20MeterProvider)", "[the client](https://github.com/open-telemetry/opentelemetry-specification/blob/09944db81a980b40e25b3d1bfd247b30596272da/specification/metrics/api.md#:~:text=the%20counter%20creation%2C-,the%20client%20MAY%20allow%20attribute%20values%20to%20be%20passed%20in%20using%20a%20more%20efficient%20way,-(e.g.%20strong )", and "[individual language client](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#:~:text=Individual%20language%20client%20MAY%20choose%20to%20support%20more%20criteria)" which are all referring to a hypothetical implementation of the spec. I think "client" is a bit overloaded and it's unclear if this refers to an implementation or the developer using the implementation. In the tracing spec, I do also see "[OpenTelemetry client authors](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#:~:text=or%20an%20event.-,OpenTelemetry%20client%20authors%20can%20decide%20if%20they%20want%20to%20make%20the%20flush%20timeout%20configurable.,-Built-in%20span)".

I'm happy to take make a PR trying to refine the wording @reyang.

**Comment by reyang** [comment]
@aabmass I suggest that we align with "OpenTelemetry client authors".

**Comment by aabmass** [comment]
@reyang do you mean changing "the client" and "individual language client" to "OpenTelemetry client authors"? I personally like "the API"/"the SDK" the most. It is the most clear to me, highlights the different responsibilities of API vs SDK, and is the most widely used in the tracing spec.

**Comment by reyang** [comment]
@aabmass I've created a PR #1930 combining the ideas from the discussion here. Please help to review.
