### ISSUE TITLE
Add semantic conventions for CloudEvents

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry-specification#1949]
The [CloudEvents](https://cloudevents.io/) Go SDK exposes an interface that is used by the CloudEvents client to add observability to the actions performed by it. For example: The client [invokes the observability service when sending an event](https://github.com/cloudevents/sdk-go/blob/e1371d2928c5269f7fb6b3ad4ee152edbd75cabf/v2/client/client.go#L132).

Currently, the SDK offers an implementation of the interface that works with OpenCensus. In there, a [couple of CloudEvents specific attributes](https://github.com/cloudevents/sdk-go/blob/main/v2/observability/keys.go) are added [to the spans](https://github.com/cloudevents/sdk-go/blob/e1371d2928c5269f7fb6b3ad4ee152edbd75cabf/observability/opencensus/v2/client/observability_service.go#L47).

I've opened a PR to add a new [implementation for OpenTelemetry](https://github.com/cloudevents/sdk-go/pull/717) and I thought that it would be good if these attributes could be part of the OpenTelemetry semantic conventions.

**Comment by pyohannes** [comment]
As discussed in today's messaging WG, please add CloudEvents attributes as separate semantic convention. This way it can be utilized as an add-on for both messaging and HTTP scenarios.
