### ISSUE TITLE
Feature Request: configure reporting period separately for each metric

### ISSUE THREAD

**Issue by ssmall** [open-telemetry/opentelemetry-specification#197]
Per [discussion](https://gitter.im/census-instrumentation/Lobby?at=5d3f4216ce271b4acd2c3efc), it would be useful to be able to configure the reporting period separately for individual metrics. For applications that emit a multitude of metrics, it is not necessarily desirable to report every metric with the same period.

**Comment by jmacd** [comment]
I suggest `label:SDK`

**Comment by tedsuo** [comment]
@ssmall I believe https://github.com/open-telemetry/opentelemetry-specification/pull/250 addressed this

**Comment by bogdandrutu** [comment]
I think this should be configure at the exporter layer, and the MetricsProcessor should have a way to support this.

**Comment by jmacd** [comment]
This is covered in issue #382. Closing this.
