### ISSUE TITLE
Allow UpDown counters to be 'set'

### ISSUE THREAD

**Issue by RichardWright** [open-telemetry/opentelemetry-specification#1987]
Currently Updown counters can only go up or down. They cannot be set to a specific value. The current node.js 'prom-client' implementation allows this. It would be very useful and means we wouldn't have to maintain the current state to be able to increment/decrement. It's the main blocker for us using opentelemetry everywhere

**Comment by reyang** [comment]
@RichardWright could you provide a real-world scenario when this is needed?
Check out this https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md#instrument-selection and see if any of the instrument would meet your need.

**Comment by reyang** [comment]
@RichardWright I'm closing this issue, please reopen if needed.
