### ISSUE TITLE
Consider to rename this to opentelemetry-specs?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#2]
Pros: Shorter

**Comment by iredelmeier** [comment]
Alternatively, just `specification`?

**Comment by bogdandrutu** [comment]
We had this argument before, if the name is too generic when people fork this repo will not make sense inside their account.

**Comment by iredelmeier** [comment]
@bogdandrutu mind linking that discussion in here?

**Comment by austinlparker** [comment]
my 0.02 is that `opentelemetry-specification` is more explicit and preferable. additionally, it's a word that's highly unlikely to ever be overloaded (unlike the word `spec/s, which could be used as a language or library name - i would point to spec# or the spec package in npm as examples of this.)

**Comment by yurishkuro** [comment]
My preference, in the decreasing order:
  1. close this issue as bikeshedding
  2. `specification`
  3. `opentelemetry-specification`

**Comment by austinlparker** [comment]
Closing as bikeshedding.
