### ISSUE TITLE
Confirm that HTTP instrumentations can provide sampling-relevant attributes at creation time

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#2011]
In https://github.com/open-telemetry/opentelemetry-specification/pull/1916 we require (MUST) sampling relevant attributes to be provided at span creation time:

https://github.com/open-telemetry/opentelemetry-specification/blame/f34abb07ee8b8e102ab4693d9d6cef1aad95fb2b/specification/trace/semantic_conventions/http.md#L94

We do it under assumptions:
- it's feasible
- reasonably efficient (assuming #620 is fixed)

If there are more than a few (1-2?) instrumentations where these assumptions are wrong, we will change MUST to SHOULD for sampling-relevant attributes.

This issue is a blocker for HTTP semantic conventions stability.

**Comment by bogdandrutu** [comment]
Per the SIG meeting discussion, assign this to @lmolkova

**Comment by lmolkova** [comment]
This can be closed, we changed MUST to SHOULD in https://github.com/open-telemetry/semantic-conventions/issues/422
