### ISSUE TITLE
Explicitly distinguish between client side issue and server side issue in a span of kind 'client'

### ISSUE THREAD

**Issue by scheler** [open-telemetry/opentelemetry-specification#2033]
**What are you trying to achieve?**
On the backend I was trying to count the number of 'client' spans that failed due to an issue on the client vs an issue from the server, and there doesn't seem to be an easy way to determine this. The only way possible is to interpret the recorded exception but it is not reliable and not straightforward.

What did you expect to see?
I dont know, but some kind of a flag in the "Span" to explicitly denote client side failure.

**Additional context.**

Here are the two 'client' spans, one that received a 401 from the server and one that failed to connect to server due to DNS error.

Span for the case the client received 401 from the server - 

> otel-collector    | Resource labels:
> otel-collector    |      -> service.name: STRING(delta)
> otel-collector    |      -> cloud.zone: STRING(zone-1)
> otel-collector    |      -> host.name: STRING(sample-container)
> otel-collector    |      -> service.namespace: STRING(ot-sample-app)
> otel-collector    |      -> appdynamics.controller.host: STRING(ec2-123-123-123-123.us-west-2.compute.amazonaws.com)
> otel-collector    |      -> appdynamics.controller.port: INT(8080)
> otel-collector    |      -> appdynamics.controller.account: STRING(customer1)
> otel-collector    | InstrumentationLibrarySpans #0
> otel-collector    | InstrumentationLibrary opentelemetry.instrumentation.requests 0.15b0
> otel-collector    | Span #0
> otel-collector    |     Trace ID       : 06151306cd1d136d1d5ad58429f99440
> otel-collector    |     Parent ID      : 2943ca1546fc5939
> otel-collector    |     ID             : c1583447f7cfe19a
> otel-collector    |     Name           : HTTP POST
> otel-collector    |     Kind           : SPAN_KIND_CLIENT
> otel-collector    |     Start time     : 2021-10-19 05:40:07.939645027 +0000 UTC
> otel-collector    |     End time       : 2021-10-19 05:40:07.946335494 +0000 UTC
> otel-collector    |     Status code    : STATUS_CODE_ERROR
> otel-collector    |     Status message : 
> otel-collector    | Attributes:
> otel-collector    |      -> component: STRING(http)
> otel-collector    |      -> http.method: STRING(POST)
> otel-collector    |      -> http.url: STRING(http://py-echo:5000/echo)
> otel-collector    |      -> http.status_code: INT(401)
> otel-collector    |      -> http.status_text: STRING(UNAUTHORIZED)

Span for the case the client failed to connect to server - 

> 
> otel-collector    | Span #5
> otel-collector    |     Trace ID       : dea28aa168d05dc29ce347734d373be1
> otel-collector    |     Parent ID      : d9195105d0c312f3
> otel-collector    |     ID             : 2ba5239e08758beb
> otel-collector    |     Name           : HTTP POST
> otel-collector    |     Kind           : SPAN_KIND_CLIENT
> otel-collector    |     Start time     : 2021-10-19 05:43:08.343388728 +0000 UTC
> otel-collector    |     End time       : 2021-10-19 05:43:08.354821284 +0000 UTC
> otel-collector    |     Status code    : STATUS_CODE_ERROR
> otel-collector    |     Status message : ConnectionError: HTTPConnectionPool(host='py-echo1', port=5000): Max retries exceeded with url: /echo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7b2b3f070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> otel-collector    | Attributes:
> otel-collector    |      -> component: STRING(http)
> otel-collector    |      -> http.method: STRING(POST)
> otel-collector    |      -> http.url: STRING(http://py-echo1:5000/echo)
> otel-collector    | Events:
> otel-collector    | SpanEvent #0
> otel-collector    |      -> Name: exception
> otel-collector    |      -> Timestamp: 2021-10-19 05:43:08.354779371 +0000 UTC
> otel-collector    |      -> DroppedAttributesCount: 0
> otel-collector    |      -> Attributes:
> otel-collector    |          -> exception.type: STRING(ConnectionError)
> otel-collector    |          -> exception.message: STRING(HTTPConnectionPool(host='py-echo1', port=5000): Max retries exceeded with url: /echo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7b2b3f070>: Failed to establish a new connection: [Errno -2] Name or service not known')))
> otel-collector    |          -> exception.stacktrace: STRING(Traceback (most recent call last):
> otel-collector    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
> otel-collector    |     conn = connection.create_connection(
> otel-collector    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
> otel-collector    |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
> otel-collector    |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
> otel-collector    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> otel-collector    | socket.gaierror: [Errno -2] Name or service not known
> otel-collector    | 
> 

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by iNikem** [comment]
Cannot you achieve that by looking at `http.status_code` attribute?

**Comment by cruisehall** [comment]
> On the backend I was trying to count the number of 'client' spans that failed due to an issue on the client vs an issue from the server, and there doesn't seem to be an easy way to determine this

@scheler We built some manual instrumentation to close this gap (i.e. to help engineers build mental models for the failure modes that can occur _before_ a server responds to an HTTP request). In the end we found it useful to define some additional attributes about the outcome* of the HTTP request, which seems to clarify the otherwise ambiguous `span.status=Error` in the case of "client-side errors".

Having gone through that design exercise (and flip-flopped on a few key design decisions that I'm not even 100% comfortable with today) I think it might be difficult to build consensus on a solution that tackles this problem directly in a single enumerated attribute like `span.status`. For instance in java if an HTTP request throws a `javax.net.ssl.SSLHandshakeException`, it's not always clear if this should be classified as a "client error" or a "server error".

----
*FWIW for the time being our manual instrumentation assigns the attributes based on the outcome of the HTTP request:
- `peer_connected` (bool) - did the client successfully connect to the peer?
- `peer_responded` (bool, optional) - did the peer respond? (null if `peer_connected == false`)
As you might imagine this requires us to maintain a lookup of exception types to `peer_connected`, `peer_responded` values. This feels clunky but our reasoning is that an on-call engineer is going to have to make that judgement call anyway, might as well eliminate that cognitive load.

**Comment by scheler** [comment]
@cruisehall Curl does this pretty well - for all client-side errors it exits with a non-zero exit code and for server errors you are required to examine the response.  See: https://gist.github.com/scheler/19fa9cd307b3d293ffc2e8660937392f

For `peer_responded`,   maybe we can go with the convention that when you don't get a response the issue is on the side which gave up and closed the tcp connection. Luckily curl provides this info, again via the exit code.

SSLHandshakeException is a tricky one, curls falters on it. It classifies https://expired.badssl.com/ as a client side error.

So, I feel this is certainly a space that deserves standards on HTTP client, for the observability companies to take up.

I filed this issue from the perspective of RUM (mobile apps and browser apps used by real users on Internet) where DNS and Internet connectivity/flakiness are more likely the causes of http client issues. I am hoping they could be reported at the next opportunities when the client connects successfully to the monitoring backend. For SSL issues on the server and server apps failing to respond in time, there could be monitoring setup on the servers. Having a visibility into the pure client issues gives an indication of missed opportunities for our customers.

**Comment by scheler** [comment]
Thinking further, all I care is to bring visibility to just these two issues - DNS and network connectivity - from the RUM clients. The rest all can be derived from the server side, including the client terminating the connection early. The network connectivity should include issues with any intermediaries such as forward proxies.  

I realize the terms 'client side issue' vs 'server side issue' can be controversial, so I am okay with either of these two - 
1. A new span status of CLIENT_ERROR, or (both would be ideal)
2. the attribute `http.status_code` MUST NOT BE set if the connection never reached the server.

On the second one, I see that some SDK set the attribute `http.status_code` to 0.

**Comment by scheler** [comment]
Just noticed that the semantic convention for the attribute http.status_code already mentions that it should be set if and only if it is available. I will close this ticket; will take up the issue with JS sdk for web separately.

One case that remains unaddressed is when a forward-proxy is used (like squid or envoy proxy in case of istio), they will respond with some status_code to the client when the upstream is unavailable, typically 504. Please suggest if there are any ideas on this issue, otherwise we can have a guidance that each intermediate/proxy should be monitored separately.
