### ISSUE TITLE
Add service to the glossary

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-specification#2050]
**What are you trying to achieve?**

The term `service` is an important term used at a lot of places within the spec, but there is no definition in the glossary what a service is (and what it is not). Maybe it's somewhere else in the spec and just needs to be referenced?

**Additional context.**
For example in k8s a service is defined the following:

> In Kubernetes, a Service is an abstraction which defines a logical set of Pods and a policy by which to access them (sometimes this pattern is called a micro-service). ([source](https://kubernetes.io/docs/concepts/services-
networking/service/))

Does this definition also apply for OpenTelemetry, so it could be referenced or are there nuances, since a service could also run outside k8s and outside a container? 

It would also be good to include:

* what the difference is between a `service` and a `service.instance` (following that definition form k8s above a service instance is then one pod in that logical set?)
* what is the difference between a `service` and an `application` or are those words synonyms?

(I am happy to come up with a draft for the definition, but I would like to understand first if there is a need or if there is an existing definition that just needs to be linked/moved into the glossary)

**Comment by jsuereth** [comment]
I'd be a fan of including this in the specification if you submit a PR adding it.

**Comment by svrnm** [comment]
Sure! Let me do that.
