### ISSUE TITLE
Replace http.target with http.path and http.query?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#2056]
**What are you trying to achieve?**

Less confusion for end users who are writing/configuring samplers and processors by replacing the confusing `http.target` with the much more commonly understood `http.path` and `http.query`.

**Additional context.**

`http.target` is confusing to end users because "target" is not a commonly understood part of the url (for example it's not mentioned anywhere in https://en.wikipedia.org/wiki/URL or https://datatracker.ietf.org/doc/html/rfc2616#section-3.2.2).

At the same time, it's one of the most important attributes for end users who are writing (or configuring) samplers and processors (e.g. [the common health check suppressing sampler](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060)).

**More additional context.**

Most (but not all) Java server libraries already expose `http.path` + `http.query` separately instead of as the combined `http.target` (and in the couple of cases where `http.target` is exposed directly, it's - also confusingly - called "uri" or "path", not "target").

I'm not sure what the situation is for other languages, but in cases where the full `http.target` is exposed, at least parsing to `http.path` + `http.query` is not complex, since you only need to look for the first `?` and split.

**Comment by ericsampson** [comment]
I landed on this issue because I read through the http semantic conventions document and was unable to find the standard name for query params.
So you can treat this as another user experience report :)

**Comment by trask** [comment]
Closing, this will either happen in #3181 as part of [ECS alignment](https://github.com/open-telemetry/oteps/pull/222) or not at all (due to high bar for breaking changes at this point).
