### ISSUE TITLE
[http-plugin] Include trace ID in response headers for incoming requests

### ISSUE THREAD

**Issue by OlivierAlbertini** [open-telemetry/opentelemetry-specification#206]
Hello

I would like to add the trace id in the response headers for incoming requests.
We would like to move the discussion in this repo (ref: https://github.com/open-telemetry/opentelemetry-js/issues/166).

**Is your feature request related to a problem? Please describe.**
- Having trace id in headers can help to debug slow requests we see in
the browser by looking up the trace ID found in response headers.
- It can help the propagation

**Describe the solution you'd like**
- Inject trace id in the response header and only for incoming requests.
- Make this feature optional and disabled by default

Thanks. Let me know if I can help.

**Comment by mtwo** [comment]
FYI @bogdandrutu @AloisReitbauer @discostu105 @SergeyKanzhelev @iredelmeier

We've discussed this before at meetings of the W3C TraceContext group (which is mostly composed of OpenTelemetry contributors) and I think that it's a good idea, though we need to think through the implementation. Returning a trace context header in responses benefits the following scenarios:

- It enables a basic case of delegated sampling, where the outermost layer of an application (typically a load balancer) can defer sampling decisions to the layer beneath it while still generating spans
- This can assist with debugging across organizational / trust boundaries, where the caller of an API can record the trace ID returned to them by the API provider

I believe that there are a few unresolved conversations around whether TraceState should be returned as well.

**Comment by SergeyKanzhelev** [comment]
I triaged this as "future for now", meaning likely not in 1.0. Please reply back if this needs to be addressed earlier

**Comment by jmacd** [comment]
The W3C committee is moving forward with a proposal, see https://github.com/w3c/trace-context/pull/365
Closing for now.
