### ISSUE TITLE
Request for comments: aim to declare Logs data model and logs in OTLP stable by the end of the year

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2060]
Hello @open-telemetry/specs-logs-approvers and @open-telemetry/specs-approvers.

We are preparing an OpenTelemetry roadmap update and this is a good opportunity to discuss our plans for logs. We currently have [14 open log-related issues](https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aopen+is%3Aissue+label%3Aspec%3Alogs) in the spec. I went over the list and it does not seem there are any hugely complicated items there.

I want to suggest to set a goal for us to declare Logs data model and logs in OTLP protocol by the end of 2021. Doing so will allow us to start actively write logging related code for Logging SDKs without fearing that we will break a lot of code if we need to change the data model. I think it is important this active work commences early in 2022, since by then we will have feedback from prototyping the Logging SDKs by at least 2 languages (Python, Java).

What do others think about it? Any concerns about our ability to achieve this?

**Comment by tigrannajaryan** [comment]
Log SIG frequency changed to weekly. Let's see what we can do.

**Comment by jsuereth** [comment]
@tigrannajaryan I realize this is auto-assigned to me. I'm 100% on board with this, let me know if you need something from me or if you'll be owning this decision/force going forward.

**Comment by tigrannajaryan** [comment]
I think we can close this. We discussed in Log SIG and the plan is to do as much as we can by the end of the year, but more realistically it will be Q1 2022. This is already reflected in the Otel roadmap.
