### ISSUE TITLE
Set preferred aggregation temporality for the periodic exporting metric reader via environment variable

### ISSUE THREAD

**Issue by pirgeo** [open-telemetry/opentelemetry-specification#2065]
**What are you trying to achieve?**

I want to be able to set the preferred aggregation temporality for an periodic exporting metric reader via an environment variable, e.g. `OTEL_METRIC_EXPORT_PREFERRED_TEMPORALITY`. If set, This would take precedence over the preferred temporality specified in the `MetricReader`/`MetricExporter` (see [temporality override rules](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#temporality-override-rules)).

**Additional context.**

Similar to #2021/#2038, but for aggregation temporality.
Also affects the precedence created in #2031/#2032.

**Comment by jack-berg** [comment]
Just to clarify, this is different than the ability to configure temporality for the OTLP exporter? I.e. [OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md)

**Comment by pirgeo** [comment]
I was thinking about it in more broad terms, i.e. every exporter that supports that environment variable can read it and set the preferred temporality. The mechanism would be the same, but the scope would be a bit bigger. I guess setting it for each exporter individually is also a way to go, and gives you more granular control. These two paths do not interfere with each other, I'd use the more specific (`OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY`) over the more general variable (`OTEL_METRIC_EXPORT_PREFERRED_TEMPORALITY`).

I'd envision this as a more general guidance that exporters that don't want to specify their own env var could use.
