### ISSUE TITLE
Limit Body to string in logging library APIs

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2068]
We cannot think of a good use of a structured Body in the logging APIs. All of the logging libraries that we are aware of produce log body (message) as a string. Because of this we think that it is reasonable to limit logging APIs to accept the body as a string only and the structured data that logging libraries allow should go to the attributes.

This limitation likely needs to be added as an amendment to [OTEP0150](https://github.com/open-telemetry/oteps/blob/main/text/logs/0150-logging-library-sdk.md).

**Comment by djaglowski** [comment]
This was discussed in the Log SIG today and it was agreed the issue can be closed. See [#188 (comment)](https://github.com/open-telemetry/oteps/pull/188#issuecomment-983944628).
