### ISSUE TITLE
Clarification on model metric of exporter.export(batch)

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-specification#2073]
**What are you trying to achieve?**

> ##### Export(batch)
> Exports a batch of `Metrics`. Protocol exporters that will implement this function are typically expected to serialize and transmit the data to the destination.
> **Parameters:**
> batch - a batch of `Metrics`. The exact data type of the batch is language specific, typically it is some kind of list.
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exportbatch

The type name `Metrics` is not mentioned anywhere else (as far as I can tell, I didn't find anything at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md) and it is unclear what it contains.

**Comment by reyang** [comment]
It is not specified, but it has to be a stable API. It is "based on" the data model, it should not be based on the Proto generated data types.

**Comment by reyang** [comment]
@legendecas based on the discussion from [11/2/2021 Spec SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.erc0axt1ayqq), I've added clarification in #2106. Please take a look.
