### ISSUE TITLE
SDK env var for trace processor selection

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-specification#2110]
**What are you trying to achieve?**
Thinking about tracing, there are environment variables defined to allow configuring a trace exporter, choosing an exporter, and choosing a sampler. It feels like one is missing, choosing span processor(s). I think that if this could be defined, then a trace provider could have all of the information it needs to configure itself if somebody sets all of the right environment variables.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection

What did you expect to see?
I would like to see an env var such as `OTEL_TRACES_PROCESSOR` or `OTEL_TRACES_SPAN_PROCESSOR`which accepts a comma-separated list of span processors (eg `batch,simple`).

**Additional context.**

Most APM implementations I've seen will automagically configure themselves in this way, which I think lowers the barrier to entry and removes some boilerplate startup code for users.

**Comment by brettmc** [comment]
Closing this issue, per comment https://github.com/open-telemetry/opentelemetry-specification/pull/2172#issuecomment-982312473 - SIG group do not want to create too many env vars, and suggest `BatchSpanProcessor` is a sensible default (eg for Java implementation)

**Comment by jackmpcollins** [comment]
I have a specific use case for this. I am deploying a python FastAPI app to Google Cloud Run using OTEL auto-instrumentation configured using environment variables. All-together this has been extremely simple and has required no code change to my app.

1. Install required opentelemetry python packages
1. Set OTEL environment variables (following [Google Cloud OpenTelemetry’s documentation](https://google-cloud-opentelemetry.readthedocs.io/en/latest/))
    ```sh
    OTEL_PROPAGATORS="gcp_trace"
    OTEL_TRACES_EXPORTER="gcp_trace"
    ```
1. Prepend `opentelemetry-instrument` to the command to run the app

The only piece of configuration I am missing is the ability to set the span processor to simple, which is the guidance from the [Cloud Run documentation](https://cloud.google.com/trace/docs/setup/python-ot#import):

> To send spans with a background process, use the BatchSpanProcessor processor. We recommend that you use this processor **unless you are using Cloud Run. Cloud Run doesn't support background processes.**
>
> To send spans with a foreground process, use the SimpleSpanProcessor processor. **If you are using Cloud Run, then you must use this processor.** This processor might slow your application.

Without an `OTEL_TRACES_PROCESSOR` or similar environment variable I have to define this configuration in code. This is admittedly not hard to do, but definitely not as elegant as auto-instrumentation which I think should be able to handle this simple case.

**Comment by brettmc** [comment]
Hi @jackmpcollins 
I'd be happy to re-open this PR and/or the related issue, if somebody wants to try again with the specifications SIG. Having a documented use-case like this might strengthen the argument for it to be added.
Failing that, you can also ask in the language-specific SIG to support it just for that language. That's what we ended up doing for PHP.
