### ISSUE TITLE
Process ID should be a required attribute

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-specification#2116]
**What are you trying to achieve?**

[Semantic conventions for a Process resource](-runtimes) currently state (emphasis mine):
> "At least one of `process.executable.name`, `process.executable.path`, `process.command`, `process.command_line` or `process.command_args` is required to allow back ends to **_identify the executable_**." 

Although this guideline may be sufficient to differentiate executables from one another, it seems to be insufficient for the purpose of differentiating processes. Without a PID, process related signals may be ambiguous in origin, such as when originating from concurrent executions of the same executable. 

I suggest that `process.pid` should be a required attribute. 

**Additional context.**

This question is being [discussed](https://github.com/open-telemetry/opentelemetry-specification/pull/2061#discussion_r740526965) as part of an effort to specify semantic conventions for process metrics.

**Comment by tigrannajaryan** [comment]
@jsuereth do you mind taking this? You had some good thoughts on this (particularly the cardinality increase).
