### ISSUE TITLE
Allow specifying timestamp for span time events in `addEvent`

### ISSUE THREAD

**Issue by draffensperger** [open-telemetry/opentelemetry-specification#213]
The current spec for [adding events to a Span](https://github.com/census-instrumentation/opencensus-web#span-annotations-for-dom-and-network-events) specifies that "Events have a time associated with the moment when they are added to the Span."

However, in order support tracing use cases in the browser, I would like to modify this to say something like "Events have a time associated with when they occurred. By default this is the moment they were added to the span, but implementations may allow an optional argument for the time when the event occurred."

The use case for web tracing is that there are some events that are measure by the browser and accessible in the Performance Timing API, and so we would like to be able to make those events become timed events on a span, but with the time stamp of when the event actually occurred as measured by the browser rather than the time when the event is being attached to the span (which for the initial page load could be a long time after). See https://github.com/census-instrumentation/opencensus-web#span-annotations-for-dom-and-network-events

This is along the lines of the RFC by @bg451 to [remove SpanData in favor of allowing time stamps to be specified when starting/ending a span](https://github.com/open-telemetry/rfcs/blob/master/text/0002-remove-spandata.md)

**Comment by bg451** [comment]
Big++, I realize that it would be impossible to add events for out of band spans without allowing an optional timestamp. I included it in the Future Work section of that RFC but I think it's something that will have to happen in the specification change.

**Comment by SergeyKanzhelev** [comment]
This is done: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#add-events
