### ISSUE TITLE
Clarify the need and the difference between supported and preferred temporality?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#2130]
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#temporality-override-rules it seems that if there is a "preferred" use that -> it can translate into I support only the "preferred". No need for the both concepts if setting the "preferred" means will produce that anyway.

**Comment by reyang** [comment]
@bogdandrutu had a question if we need both - if we need both and later we remove one, it'll be a breaking change.
