### ISSUE TITLE
Clarify if MetricReader would ever be implemented by the user

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#2139]
**What are you trying to achieve?**

Implement the SDK spec in Python.

**Additional context.**

It is not clear to me from the spec if `MetricReader` is supposed to be implementable by the user or if they would only ever use the two provided implementations (for push and pull).

1. Would a user ever subclass `MetricReader`? What would they gain from this, or is it intended that they can only use MetricReader for pull and PeriodMetricReader for push?
2. Should a user be able to override `MetricReader.Collect()`, or should it be considered a final method? I was conceptualizing this method as the hook into the internals of the SDK, so it doesn't make sense for a user to override this to me.

My take is that there should only be two impls of `MetricReader`, one for pull based exporter to call `Collect()` on and one that passes metrics to a push exporter periodically. We only call out the latter in the spec.

**Comment by reyang** [comment]
Discussed during the SIG meeting - the suggestion is to call out the `Collect` is expected to be provided by the SDK, and supposed to be provided by the SDK user.
