### ISSUE TITLE
Clarify what happens if a View matches with multiple instruments

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#2141]
**What are you trying to achieve?**

Implement the SDK spec in Python.

**Additional context.**

The spec isn't clear what happens if a view matches multiple instruments, for example if it selects all counters.

@jsuereth in chat:
> the view selector can apply to multiple instruments
> but you get one "instance" per instrument
> If you select multiple instruments and set a name, you've effectively got a bug
> but it’s not explicitly called out in the spec

In other words, because the view’s output stream name [defaults to that of the instrument](https://github.com/open-telemetry/opentelemetry-specification/blob/5418462162aeabc7b13b10545554226d4da1d1e8/specification/metrics/sdk.md#:~:text=If%20not%20provided%2C%20the%20Instrument%20name%20would%20be%20used%20by%20default.), there is no single-writer violation if you create one view “instance” per instrument. However if you specify the name, there is a conflict.

**Comment by reyang** [comment]
Right, this is already covered by the SDK spec although we didn't call out this specific case explicitly:

_If there is an error (e.g. the View asks for extra dimensions from the Baggage, but the Instrument is asynchronous which doesn't have Context) or **a conflict** (e.g. the View requires to export the metrics using a certain name, but the name is already used by another View), provide a way to let the user know (e.g. expose self-diagnostics logs)._

Maybe we could add another example for the conflict? (There are many specific cases, I'm trying to figure out what's the right balance here)

**Comment by reyang** [comment]
@jsuereth suggests that if the view is specified with multiple types, we simply disallow rename.
@bogdandrutu +1.
