### ISSUE TITLE
Are invalid SpanContexts allowed as Links? Needs spec clarification.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#2176]
I was trying to create a link to an invalid SpanContext in opentelemetry-java, but there was no link created. It seems that the Java implementation ignores attempts to add links with invalid SpanContexts. I think the spec is unclear here if this should be allowed. I think it should be allowed to avoid creating edge cases.
E.g. one might want to put certain attributes describing an incoming call on a link (e.g. a batch receive for messaging). For some incoming messages, there might be no information about the parent context, but other link attributes might still be available. In that case, it could be useful to add a link to the invalid SpanContext with additional attributes.

Tagging this with messaging because that was the use case I came up with, feel free to remove if you feel this does not apply.

EDIT: A bit related is the general definition of an "invalid" SpanContext which is rather broad and can lead to information loss: #753

**Comment by yurishkuro** [comment]
I'd say it should not be allowed, because it creates a dangling reference that cannot be followed, causing more special case handling elsewhere. Since this is already a special case and is not actually pointing to another trace/span, the information can be captured using other constructs, such as span event.

**Comment by pyohannes** [comment]
It seems to me the [spec is deliberately unclear](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links) in that regard:

> Implementations MAY ignore links with an invalid SpanContext.

The use case is a valid one, but I'm a bit skeptical about using dangling links as a tool to model it. As mentioned above, it will also require adding special logic to indexers and visualization tools.

**Comment by carlosalberto** [comment]
I'd also be up for completely ignoring them. Btw, the wording came from https://github.com/open-telemetry/opentelemetry-specification/pull/1492 regarding API/SDK separation. Any opinion on this @bogdandrutu ?

**Comment by Oberon00** [comment]
The link would not be dangling (pointing to a non-existent span) but a null-link (pointing to the all-zero trace+span ID).

**Comment by Oberon00** [comment]
I did not see that null-links were already mentioned, but I think this is a case where leaving it undefined is harmful.

**Comment by lmolkova** [comment]
@Oberon00 definitely! thanks for bringing it up.

The use-case for span links  with invalid context is attributes.

e.g. I publish or receive a batch of two messages and want to record some essential things about the message:
- number of times it was delivered
- message id
- time it was published
- etc

Even if the message does not have trace-context, recording these attributes is still important. If links can't be used if there is no context, the alternative is an event/log. This brings are back to links vs events discussion, but regardless of underlying concept, capturing links without context should be allowed.

**Comment by carlosalberto** [comment]
Notes from today's Spec call:

* There was general, initial agreement on allowing this, given the value of having attributes, even without a valid `SpanContext`.
* As a complementary feature, we want to allow opting-out and instead drop `Links` with invalid `SpanContext`, in case the backends don't support invalid `SpanContext` instances well . This could be explored as either a SDK configuration option or a `SpanProcessor`, for example.

@lmolkova to follow up with a proposal.

**Comment by Oberon00** [comment]
Since I just found that one again: A bit related is the general definition of an "invalid" SpanContext which is rather broad and can lead to information loss: https://github.com/open-telemetry/opentelemetry-specification/issues/753
