### ISSUE TITLE
[Semantic Conventions] Http metric semantic conventions don't use semantic convention for defining units.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#2186]
HTTP semantic conventions define units like "microseconds".  According to [this](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#instrument-units), the unit needs to be on [ucum](https://ucum.org/ucum.html)

**Comment by pichlermarc** [comment]
This seems to be related to #705 and #1794.

The same sees to be the case for 
- [FaaS Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/faas-metrics.md)
- [http Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md)
- [RPC Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md)

while [System Metrics Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md) seem to do it as the [General Metric Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#general-metric-semantic-conventions) suggest.

It seems like changing this in the conventions I listed above would just be an editorial change. I'd be interested in picking this up.
