### ISSUE TITLE
Clarify SumAggregation on asynchronous counter

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-specification#2187]
**What are you trying to achieve?**

In the SDK spec on DefaultAggregation, it suggests that for AsynchronousCounter a default SumAggregation is used for aggregation.

> Instrument Kind | Selected Aggregation
> -- | --
> Counter | Sum Aggregation
> Asynchronous Counter | Sum Aggregation
> UpDownCounter | Sum Aggregation
> Asynchrounous UpDownCounter | Sum Aggregation
> Asynchronous Gauge | Last Value Aggregation
> Histogram | Histogram Aggregation
>
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation

When implementing the SumAggregation for the asynchronous counter, I found that in the SumAggregation:

> SumAggregation informs the SDK to collect:
> The arithmetic sum of `Measurement` values.
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#sum-aggregation

Whilst to the asynchronous counter, the `Measurement` values mean:

> The callback function is responsible for reporting the Measurements.
> Note: Unlike Counter.Add() which takes the increment/delta value, the callback function reports the absolute value of the counter. 
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter

That's been said, the `Measurement` values in asynchronous counters are absolute values and not increments. To SumAggregation, the arithmetic sum of `Measurement` values of asynchronous counters doesn't seem to be meaningful.

This issue also applies to the Asynchronous UpDownCounter.

**Comment by jsuereth** [comment]
This is a good callout.

In the Java (early) prototype I actually had two types of measurements:  Delta + Cumulative, where Async instruments (and Histogram) provided Cumulative measurements and Sync *Counter provided Delta measurements.   This helped clarify what aggregation should do by default when it sees these measurements.

However, one thing that may *not* be clear, is that Sum-Aggregation *is* meaningful in the presence of `View`s.   If I configure a `View` that removes a label from measurements of `Async` instruments, then I need to "sum" together any measurements I'm "joining" when removing the label.

So a quick table of Instrument => Measurement Type => Default Aggregation:

| Instrument | Measurement Type | Default Aggregation |
| --- | --- | --- |
| Async* Gauge | Cumulative | Last Value |
| Async* Counter | Cumulative | Sum |
| Async* UpDownCounter | Cumulative | Sum |
| Histogram | Cumulative | Explicit Bucket HIstogram |
| Counter | Delta | Sum |
| UpDownCounter | Delta | Sum |

So, in all these cases, `View` can muck with how many measurements are seen.  The Aggregation determines what to do, and it's the same regardless of measurement type.  Might be worth a more in-depth discussion.

**Comment by jmacd** [comment]
I thought this topic had been covered in the supplementary guidelines, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md, but I see that no such example is given. I will take this issue to update the guidelines to explicitly cover removal of an attribute from a cumulative counter.
