### ISSUE TITLE
Support sampler attributes in SDK Built-in samplers

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-specification#2198]
**What are you trying to achieve?**

[According to the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler), the SamplingResult can return attributes in addition to the sampling decision. However, the [Build-in Samplers](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers) in the specification has no way to use these attributes. A user who wishes to have a sampler that returns attributes has to implement one on his own.

What did you expect to see?

I expect OTEL SDKs to have some built-in samplers that enable the use of sample results attributes.

**Additional context.**

I can think of 2 ways to support this:

## Add optional attributes parameter to the existing samplers

For example - when a user create a new `AlwaysOn` sampler, he can optionally pass in the constructor an attribute map, which will be returned on the sampling result of each invocation of `ShouldSample`:

```js
const sampler = new AlwaysOnSampler({attributeName: 'attribute value'});
```

## AttributeSampler
Add another sampler to the specification, which is used for adding static attributes on the result of another sampler. This sampler is initialized with an attribute map and another sampler, and upon invocation, it runs the configured sampler takes the sampling result, merges the static attributes into the result and returns.

```js
const sampler = new AttributeSampler(new AlwaysOnSampler(), {attributeName: 'attribute value'});
```

**Comment by blumamir** [comment]
link to issue in opentelemetry-js: https://github.com/open-telemetry/opentelemetry-js/issues/2649

**Comment by yurishkuro** [comment]
Attributes returned by the sampler are meant to describe the sampler itself. You seem to be interested in adding arbitrary attributes, but what does it have to do sampling? You can add them directly.

**Comment by yurishkuro** [comment]
> That is my need - to describe the sampler itself.

Which is what built-in samplers already do, you don't need them to add any additional attributes. If you do, then looks like you're describing something more specific to your use case, not the default behavior of the built-in samplers, in which case implementing a wrapper sampler with any custom behavior w.r.t. attributes that you want seems a valid path.

**Comment by blumamir** [comment]
> If you do, then looks like you're describing something more specific to your use case, not the default behavior of the built-in samplers, in which case implementing a wrapper sampler with any custom behavior w.r.t. attributes that you want seems a valid path.

I want to use the build-in samplers for the decision logic, but set the attribute semantic myself based on the specific use.
It is true that I can implement a wrapper sampler, which only invokes another sampler and merge attributes to the result. This is what I am currently doing. 
I think the use case is general enough to be supported in the SDK instead of being implemented again and again when needed.

**Comment by yurishkuro** [comment]
can you show concrete example of code & attributes?

**Comment by blumamir** [comment]
> can you show concrete example of code & attributes?

Sure, here is a simplified example of my need in js:

```js
import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node-tracer";
import { AlwaysOnSampler, TraceIdRatioBasedSampler } from "@opentelemetry/core";
import { Sampler } from "@opentelemetry/api";
import axios from "axios";

class RemoteConfigSampler {
  private sampler: Sampler;

  constructor() {
    this.sampler = new AlwaysOnSampler({ "sampling.initialized": false });
    this.fetchRemoteSamplingConfig();
  }

  shouldSample(...params): SamplingResult {
    this.sampler.shouldSample(...params);
  }

  private async fetchRemoteSamplingConfig() {
    const res = await axios.get("http://my-config-service/sampling-config");
    const samplingConfig = res.data;
    // update the sampler when remote config arrives after service started
    this.sampler = new TraceIdRatioBasedSampler(samplingConfig.ratio, {
      "sampling.initialized": true,
      "sampling.config.id": samplingConfig.id,
      "sampling.ratio": samplingConfig.ratio,
    });
  }
}

const provider = new NodeTracerProvider({
  sampler: new RemoteConfigSampler(),
});
```

**Comment by blumamir** [comment]
> Seems like you can trivially solve your use case by creating a (single) delegating sampler class that accepts extra params in constructor and after invoking the delegate sampler merges the attributes before returning (you could also implement that behavior in your Remote sampler). I think compositionally this is much cleaner solution than requiring **all samplers** to support extra attributes which have nothing to do with those samplers' functionality.

I like this idea, and this is what I am currently doing in my code.

Thanks @yurishkuro  for your feedback and for the help crafting the right solution for this use case

My question is if maybe this kind of wrapper sampler that only enriches attributes on the sampling result of another sampler is something that should be implemented by every user, or is it general enough to be offered as a common and standard sampler in the specification and various SDKs.

For me, the built-in SDKs samplers are great and it's very convenient that I know I can find them in every supported language and get a uniform interface and behavior. I imagine how people can also find this enrichment sampler usable directly from the SDK. The sampler attributes are specification feature by opentelemetry, but a user who wishes to leverage them find no "off the shelf" components similar to the common decision samplers.
