### ISSUE TITLE
Zipkin exporter mappings

### ISSUE THREAD

**Issue by hekike** [open-telemetry/opentelemetry-specification#220]
While working on the `opentelemetry-javascript` Zipkin exporter, I run into a couple of questions around expected mapping between OpenTelemetry Span(s) and Zipkin Span(s).

Here is the list of things I found:

- `SpanKind.INTERNAL` doesn't exist in Zipkin
-  `Status` concept doesn't exist in Zipkin
- `Event` doesn't support `Attribute`(s) in Zipkin

Related PR: https://github.com/open-telemetry/opentelemetry-js/pull/192

I also took an initial stab on a spec proposal: https://github.com/open-telemetry/opentelemetry-specification/pull/221

**Comment by SergeyKanzhelev** [comment]
@hekike do you think you can work on your PR this week? Do you need help?

**Comment by jmacd** [comment]
This will close with #380.

**Comment by carlosalberto** [comment]
Moving this to the next milestone.

**Comment by mtwo** [comment]
Closing, as #380 is closed
