### ISSUE TITLE
Parent-based Sampling docs

### ISSUE THREAD

**Issue by nelzkiddom** [open-telemetry/opentelemetry-specification#2216]
On https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md:

```
  * Remote parent (`SpanContext.IsRemote() == true`) with `SampledFlag` equals `true`
  * Remote parent (`SpanContext.IsRemote() == true`) with `SampledFlag` equals `false`
  * Local parent (`SpanContext.IsRemote() == false`) with `SampledFlag` equals `true`
  * Local parent (`SpanContext.IsRemote() == false`) with `SampledFlag` equals `false`
```

Something's amiss here. Lines 1&2 have the same input, with a different output... And the same problem exists between the 3rd & 4th lines.

**Comment by arminru** [comment]
Thanks for raising this, @nelzkiddom. This is actually not a definition of input and output but both "remote parent" and "sampled flag" are the inputs. The output is defined by the respective child samplers (see "optional parameters") just below.

**Comment by arminru** [comment]
@nelzkiddom I created #2220 to clarify this, `==` vs `=`/`:=` instead of just "equals" should do the trick 🙂
