### ISSUE TITLE
Document what OpenTracing API versions are supported

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#2218]
We need to document what versions are supported for each language, in order to avoid confusion.

* **Java**: OpenTracing supports Java 7, whereas OpenTelemetry supports Java 8+. Users will need to update to Java 8 before using the OT Shim.
* **Python**: OpenTracing supports Python 2.x whereas OpenTelemetry supports 3.x, which as done as Python 2 is **now fully deprecated**. Likewise, users will need to update to Python 3 before using the OT Shim.
* **Go**: OpenTracing supports [1.13+](https://github.com/opentracing/opentracing-go/blob/master/.github/workflows/go.yml#L19) whereas OpenTelemetry supports [1.16+](https://github.com/open-telemetry/opentelemetry-go/blob/main/README.md#compatibility)
* **Javascript/Node**: OpenTracing supports [6+](https://github.com/opentracing/opentracing-javascript#contributing--developer-information) whereas OpenTelemetry supports [8.5+](https://github.com/open-telemetry/opentelemetry-js-api#you-will-need)
* **CPP**: Not a problem, both support C++11 or later.

cc @yurishkuro

**Comment by tigrannajaryan** [comment]
@yurishkuro or anyone else from @open-telemetry/opamp-spec-approvers who know OpenTracing better than me, can I reassign this to one of you?

**Comment by carlosalberto** [comment]
@yurishkuro @tedsuo @jmacd Updated the version diff. Please take a look and let me know what you think. Otherwise, I will add a section in the Spec itself about this part.

**Comment by yurishkuro** [comment]
Lgtm but I would also add a note that users should look not only at the OT API version compatibility, but also at the SDK they are using, which are typically further along. Eg Jaeger Python SDK is py3 only, etc.
