### ISSUE TITLE
Document the level of support exist for OpenTracing JS

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#2219]
OpenTracing JS never implemented `ScopeManager`, which supports in-process context propagation. This means that only explicit context/`Span` propagation is supported, even if OpenTelemetry offers this.

cc @yurishkuro @mwear @open-telemetry/javascript-approvers

**Comment by bogdandrutu** [comment]
@dyladan ?

**Comment by dyladan** [comment]
This appears to be true. There was an issue in opentracing to add a scope manager, but it doesn't look like it was ever implemented https://github.com/opentracing/opentracing-javascript/issues/112

What is our action item here? Should we just document on the shim that there is no scope manager so we have no shim for it?

**Comment by yurishkuro** [comment]
Yes, we simply need to be compatible with existing status of OT

**Comment by carlosalberto** [comment]
Closing, this was all addressed by #2230 (now we only need to document this in each related SIG, e.g. Javascript SIG)
