### ISSUE TITLE
Tracer API: What is the API for LinkFormatter / EventFormatter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-specification#222]
The tracer API specifies that there should be a method to add a lazy link and that:

> This can be implemented by providing a Link interface or a concrete Link definition and a LinkFormatter

It does not specify the API or behavior of a `LinkFormatter`. If a language wants to provide a concrete `Link` implementation, what should should it provide as a `LinkFormatter`.

This is the same situation for `Event` / `EventFormatter`. 

I searched through the repos for several other languages and found that all of them were providing an interface. Can anyone elaborate on what a solution using a concrete class and a formatter would look like?

**Comment by mwear** [comment]
We covered this in the spec meeting, but for posterity, I'll make a note here. A `LinkFormatter` is a function that returns a `Link`. For languages such as Go, the function can return a concrete object that will be stack-allocated, whereas an interface would be heap-allocated. 

The underlying message the spec is trying to convey is that a lazy link should be created in a way that is as memory efficient possible for a given language. This might include other possibilities that aren't explicitly stated in the spec, and perhaps this should be clarified.

**Comment by bogdandrutu** [comment]
@mwear can you please make a PR to clarify that :) I wrote the current text and I thought that is clear that we allow any other option (but I am not a native English speaker so that may affect my understanding).
