### ISSUE TITLE
Clarify relationship between IsSampled and IsRecordingEvents

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-specification#223]
The relationship between `IsSampled` and `IsRecordingEvents` is not clear. For instance span builder in java allows providing sampler but also setting `setRecordingEvents`. What is the relationship between these two? Which API should be used when? 

* `IsRecordingEvents` - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#isrecordingevents
samping
 * `IsSampled` - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-sampling.md#issampled

**Comment by carlosalberto** [comment]
(Side note: https://github.com/open-telemetry/rfcs/pull/24/files throws a little bit of light into this topic)

**Comment by tsloughter** [comment]
My understanding of it is that they mean the same when it comes to what happens with the current span and the only difference is that `IsSampled` is propagated so it can influence the samplers run for children.

So the span builder has it separate as a way to enable recording just this span even if it isn't sampled, which means likely (though depends on the sampler used) its children won't be recorded.

**Comment by pavolloffay** [comment]
@tsloughter that is also my understanding. 

Related is this change in java https://github.com/open-telemetry/opentelemetry-java/pull/503#discussion_r317234668. The processors in java by default do not send spans which have `isRecodingEvents=true` flag. I think that is something for reconsideration. As end-user I would expect those spans to be sent to backed by default.

**Comment by tsloughter** [comment]
Oh, hm, that I didn't realize.

So the reporters must have a configuration for whether to report only sampled spans or to also report spans that have been recorded but not sampled?

**Comment by bogdandrutu** [comment]
The logic for default is kind of simple. For the exporters we want to export only traces that are likely to be sampled entirely not just one span.

The use-case for the one span recording is to support things like what we had in OpenCensus called z-pages. Where for these spans we don't want them to get to the exporter pipeline, but want them to be visible to the SpanProcessor.

**Comment by tsloughter** [comment]
Ok, makes sense.
