### ISSUE TITLE
Typo in metrics data model (basic point kinds)

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-specification#2231]
**What are you trying to achieve?**

Metrics data model spec [says](https://github.com/open-telemetry/opentelemetry-specification/blob/9216eb8ff1832ae790369e49ce326cb6bc3d1c80/specification/metrics/datamodel.md?plain=1#L277)

> A metric stream can use one of **three** basic point kinds ...

However, right after that there is a list of **four** kinds

**What did you expect to see?**

It should either be

> A metric stream can use one of four basic point kinds ...

or doesn't mention number of kinds at, simply providing the list

**Comment by jsuereth** [comment]
Looks like this was never updated when Exponential Histograms were added.  Thanks for raising.
