### ISSUE TITLE
Specify whether keys in attribute lists are expected to be unique

### ISSUE THREAD

**Issue by achille-roussel** [open-telemetry/opentelemetry-specification#2245]
Hello,

I'm opening this issue as a follow up to a discussion in https://github.com/open-telemetry/opentelemetry-proto/pull/346#issuecomment-1004270981 where it appeared unclear whether processors of telemetry data should be designed to support repeating keys in attribute lists.

I do not know what the right answer should be, but I couldn't find a definitive statement in the [Attributes Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md) to help guide design decisions that would depend on this information.

There is one mention of _"unique keys"_ in the [Attributes Limits](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attribute-limits), but it is unclear whether _"unique"_ refers to keys being unique or the number of keys in the attribute lists:

> * set a limit of unique attribute keys such that:
>   * for each unique attribute key, addition of which would result in exceeding the limit, SDK MUST discard that key/value pair.

Let me know if I can provide any more context that could help address this issue.

**Comment by bogdandrutu** [comment]
@tigrannajaryan do you remember this?

I remember for sure that we said we have a map "semantic" there https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/resource/v1/resource.proto#L28, if that is not the case we have huge problem in the collector :))

**Comment by Oberon00** [comment]
I remember (actually I just saw it by accident when I opened my Thread list) we had a short Thread on Slack 4 months ago: https://cloud-native.slack.com/archives/C01N7PP1THC/p1630920628020600?thread_ts=1630790115.020300&cid=C01N7PP1THC

At that time I wrote:

> There is https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-attributes
>
>> Setting an attribute with the same key as an existing attribute SHOULD overwrite the existing attribute's value.
>
> Which currently only applies to Span.SetAttribute. IMHO we should move that to the overall attribute definition, otherwise it doesn't even apply to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-creation

Would not be surprised if it is still unspecified for Span Creation, Resources, Metric attributes (at least I did not follow up at that time).
