### ISSUE TITLE
faas.instance missing from faas semantic conventions

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#2247]
in https://github.com/open-telemetry/opentelemetry-specification/blob/d5fca3f1d858f5a584acaa5b044c73c6af2d7a8d/specification/trace/semantic_conventions/faas.md#difference-between-execution-and-instance the spec disambiguates between `faas.execution` and `faas.instance`, but `faas.instance` is not defined anywhere in the document. It also shows up in the example at the bottom.

It is also missing from https://github.com/open-telemetry/opentelemetry-specification/blob/d5fca3f1d858f5a584acaa5b044c73c6af2d7a8d/semantic_conventions/trace/faas.yaml

**Comment by Oberon00** [comment]
It's a resource attribute: https://github.com/open-telemetry/opentelemetry-specification/blob/d5fca3f1d858f5a584acaa5b044c73c6af2d7a8d/semantic_conventions/resource/faas.yaml#L53-L60

**Comment by arminru** [comment]
Thanks, @Oberon00! I added a link in #2256 to make this harder to miss.
