### ISSUE TITLE
Inconsistency between Spec and Prometheus Translation with regards to Resource.

### ISSUE THREAD

**Issue by cevian** [open-telemetry/opentelemetry-specification#2251]
**What are you trying to achieve?**

There seems to be a conceptual inconsistency between the spec and the code in the in the Prometheus translation.

In the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#opentelemetry-protocol-data-model) both the Resource and the Attributes seem to be part of a stream (time-series). In Prometheus, a stream is represented by the labelset associated with the sample. However in the [PrometheusWriteExporter code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/df66030e1cdc723917abdde8397359d7e3bde431/exporter/prometheusremotewriteexporter/helper.go#L178) only a subset of the Resource tags get converted to labels. 

I guess my question is, conceptually, which interpretation is correct? Are all resource tags part of the stream or not? 
Also, Is the Exporter code wrong? 

Thanks in advance.

**Comment by cevian** [comment]
Related to #1782 (is it a duplicate of that). Sorry didn't see that one before.

**Comment by jmacd** [comment]
Closing in favor of #1782, which I just updated following toyda's Prometheus-WG SIG discussion.
