### ISSUE TITLE
Confused by Lack of Implementations of the 3 "Dropped Count" Sections in the Non-OTLP Exporter Spec

### ISSUE THREAD

**Issue by Grunet** [open-telemetry/opentelemetry-specification#2268]
**What are you trying to achieve?**

Understand whether or not OTEL-PHP needs to implement the 3 "Dropped XXX Count" sections of the [OpenTelemetry Transformation to non-OTLP Formats spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-attributes-count) for the Jaeger (and other) exporters

[Dropped Attributes Count](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-attributes-count) section -[current implementations](https://grep.app/search?q=otel.dropped_attributes_count) based on a key search
[Dropped Events Count](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-events-count) section - [current implementations](https://grep.app/search?q=otel.dropped_events_count) based on a key search
[Dropped Links Count](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-links-count) section - [current implementations](https://grep.app/search?q=otel.dropped_links_count) based on a key search

What did you expect to see?

AFAICT Java is the only language that has made some progress in implementing these sections, when I expected to see most languages having implemented the sections.

This made me doubt if they should be implemented or not.

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by Grunet** [comment]
I'm experiencing a similar confusion when it comes to the [Jaeger-specific spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#summary) and the mappings in the table for the 3 OTEL fields Span.DroppedAttributesCount, Span.DroppedEventsCount, and Span.DroppedLinksCount

**Comment by ahayworth** [comment]
We have a PR open for it in Ruby: https://github.com/open-telemetry/opentelemetry-ruby/pull/1235

**Comment by Grunet** [comment]
Oh interesting, then I'm guessing it was grep.app not finding the Erlang and Python (or others I assume?) implementations that led me astray back then? (if there's a better way to search code across all the OTEL repos please let me know!)

Good to know about these other examples! I'll go ahead and close this and mention about it in the PHP issue

**Comment by lalitb** [comment]
C++ doesn't support it. As I understand, the attributes/links/events are dropped only if collections limits are imposed by implementation. C++ doesn't impose any such limit, so these counts are zero, and so not added to span tags.
