### ISSUE TITLE
Prometheus Exporter default port is confusing and inconsistent

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-specification#2275]
The [default Prometheus Exporter port](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#prometheus-exporter) is documented as "All addresses" but the example value is `"0.0.0.0"` - which is "all IPv4 addresses" rather than "all addresses". This was introduced by PR #1021.

Another related question - bind on `localhost` by default is the common practice, because it is much more secure. Also, Jaeger and Zipkin exporters both bind to `localhost` from the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter). (_maybe Prometheus is more intended for production, while Jaeger/Zipkin more for dev inner loop?_)

**Comment by tigrannajaryan** [comment]
> The [default Prometheus Exporter port](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#prometheus-exporter) is documented as "All addresses" but the example value is `"0.0.0.0"` - which is "all IPv4 addresses" rather than "all addresses". This was introduced by PR #1021.
> 
> Another related question - bind on `localhost` by default is the common practice, because it is much more secure. 

I agree, I think "localhost" should be the way to go due to security considerations. The localhost endpoint can be scraped by locally running Collector.


>Also, Jaeger and Zipkin exporters both bind to `localhost` from the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#jaeger-exporter). (_maybe Prometheus is more intended for production, while Jaeger/Zipkin more for dev inner loop?_)

Similarly, this assumes that there is a locally running Collector that's why it sends to localhost. We can make the same assumption for Prometheus exporter.
