### ISSUE TITLE
Proposal: Generate a Trace ID for even unsampled requests and add to Logs

### ISSUE THREAD

**Issue by nadundesilva** [open-telemetry/opentelemetry-specification#2284]
**Motivation**
In my opinion, one major downfall in sampling strategies is that we are making always making a choice between performance and a system being fully observable. In production systems, we cannot know at the start of a request whether it will end up in an error or have unusually high latency. Since there can be intermittent errors and performance issues, it can be a gamble to enable sampling for tracing.

Since the trace IDs are injected into logs only when there is a trace context, when a request is not sampled it will not add any IDs to logs and we completely lose the correlatability of logs we can get across a distributed deployment.

**Suggestion**
Create and propagate a trace ID even when a request is not sampled so that it can be injected into logs. Then we can query all the logs for a given request across multiple distributed components. It would be better to make this part of the spec and encourage/enforce this behavior, since it will improve the observability and debugging experience using logs immensely.

**Comment by Oberon00** [comment]
> Create and propagate a trace ID even when a request is not sampled so that it can be injected into logs. 

I think this is already the case. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sdk-span-creation

> 3. Generate a new span ID for the Span, independently of the sampling decision. This is done so other components (such as logs or exception handling) can rely on a unique span ID, even if the Span is a non-recording instance.

Of course, unsampled spans also need to be propagated, otherwise you can't tell downstream that the sampling decision was negative (sampled flag in the traceparent header).

This exact point was changed for the exact reasons you mention here: https://github.com/open-telemetry/opentelemetry-specification/pull/1225

**Comment by nadundesilva** [comment]
Ah ok my mistake. I have also missed it. I will take a look at the Otel Implementation and check whether I have done something wrong or if there is something wrong with the implementation itself. I will raise it with relevant implementation if it is the case.

Sorry for the noise.
