### ISSUE TITLE
Clarify host.name applicability

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-specification#2302]
I want to ask for clarification about [host.name semantic attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md).

Should SDK set this attribute when a process runs inside a container? And if yes, should SDK set it to the hostname as returned by the OS running inside that container or should it try to find a hostname of the underlying host that this container runs on?

**Comment by Oberon00** [comment]
I think this is a part of #1894

**Comment by bogdandrutu** [comment]
Closing this as duplicate to #1894
