### ISSUE TITLE
Client configuration provided by the environment

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-specification#232]
Created as a follow-up on https://github.com/open-telemetry/opentelemetry-specification/issues/231#issuecomment-524368087.

I am proposing that clients would provide a consistent ability to store configuration in the environment (env variables, configuration file).

In Jaeger clients the configuration via environmental variables was proven to be very useful especially in K8s deployments. The users don't have to recompile apps to change the behaviour of the tracer. Also the configuration was easily accessible on the website https://www.jaegertracing.io/docs/1.13/client-features/.

**Comment by austinlparker** [comment]
Is there a way we can write this in such a way that it allows for languages that offer a well-supported method for runtime config files to use that? In .NET Core, for example, appsettings.json is the standard location for defining configuration values such as this.

**Comment by carlosalberto** [comment]
> Is there a way we can write this in such a way that it allows for languages that offer a well-supported method for runtime config files to use that?

Besides this, offer alternative configuration options. For example, in the LS Java Tracer we accept external configuration through a `tracer.properties` file ;)

**Comment by yurishkuro** [comment]
I agree, both env and files are useful sources of configuration, but I think a more critical ask in this ticket is that the _naming of the configuration properties_ is standardized across languages. Jaeger clients have a pretty consistent set of env variables they all support, although there are some differences due to historical reasons, and sometimes unique implementation details.

**Comment by pavolloffay** [comment]
> Is there a way we can write this in such a way that it allows for languages that offer a well-supported method for runtime config files to use that? In .NET Core, for example, appsettings.json is the standard location for defining configuration values such as this.

I think the configuration means could slight differ from language to language e.g in java also support Java system properties, C# .json if It is supported by the language. 

Most importantly the property names should be the same and perhaps all languages should offer configuration by environmental properties.

In golang I really like https://github.com/spf13/viper and cobra. When properly configured it allows to consume the configuration from different sources - evn vars, files, flags https://github.com/spf13/viper#why-viper. In java there is a similar project https://github.com/eclipse/microprofile-config

**Comment by tedsuo** [comment]
@pavolloffay traiging issues, has there been any further work on what ENV vars and configuration patterns OTel will support? Please update, or close this issue if it is no longer needed.

**Comment by jmacd** [comment]
Please merge this discussion with https://github.com/open-telemetry/opentelemetry-specification/issues/172

**Comment by pavolloffay** [comment]
@tedsuo no work on our side. This is also related to "extra features supported by Jaeger clients" https://github.com/open-telemetry/opentelemetry-specification/issues/231. We are using this functionality in Jaeger and once migrating to OTeL we would like to continue using it.
