### ISSUE TITLE
Clarify how the default value of OTEL_EXPORTER_JAEGER_ENDPOINT should work

### ISSUE THREAD

**Issue by abe545** [open-telemetry/opentelemetry-specification#2331]
**What are you trying to achieve?**
My organization is trying to switch from opentracing to opentelemetry, and currently the .net exporter will not work with our infrastructure, because our jaeger collector listens on a different path than `/api/traces`. With the [opentracing jaeger client](https://github.com/jaegertracing/jaeger-client-csharp), we were able to specify the endpoint and have everything wired up correctly. With the current spec, the default value of the `OTEL_EXPORTER_JAEGER_ENDPOINT` env var makes it seem like libraries need to append `/api/traces` themselves to correctly send spans over http. 

What did you expect to see?
I'd like it to be clear in the spec how this should behave - should libraries append `/api/traces` - or should the default value include the path in the uri, and expect developers to configure the full url to export to. If libraries *should* append the path, can we add another configuration option to override it (this is what my organization needs to adopt otel in .net).

**Additional context.**
The .net sdk is currently implemented to append `/api/traces` to the endpoint, but the golang, javascript, and ruby sdks all default the value of the endpoint to include the path, and require users to specify the path in the value.
I opened a PR to try to make the .net sdk configurable: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2847
This led to a discussion where one of the maintainers felt that the golang implementation is wrong: https://github.com/open-telemetry/opentelemetry-go/issues/2599

**Comment by carlosalberto** [comment]
Re-assigning this to @yurishkuro who may know better.

**Comment by yurishkuro** [comment]
The environment variable should be assumed to contain the actual URL, including the path. The SDK SHOULD NOT append anything to the URL, except, in come cases, the parameters in the query string, such as `?service=***` for remote sampling URL.

If this is not clear in the spec, we should make it clear, and I think the .NET implementation is incorrect.

**Comment by yurishkuro** [comment]
I am creating one now, will tag you for review.

**Comment by yurishkuro** [comment]
Actually, something is odd here. The default value in the spec is `http://localhost:14250`, which is a gRPC port number in Jaeger and thus does not need the path. The default Thrift over HTTP endpoint is `http://jaeger:14268/api/traces`, which does need the path. Which one are you (@abe545) and the spec are referring to?

**Comment by abe545** [comment]
Yeah - I'm trying to configure it to for HTTP.

**Comment by pellared** [comment]
Can we also document the `OTEL_EXPORTER_JAEGER_PROTOCOL` env var?

Origin https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/355#issuecomment-1034862461
