### ISSUE TITLE
Global accessor for LogEmitterProvider

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#2332]
Should there be a global accessor for LogEmitterProvider? In java (discussed [here](https://github.com/open-telemetry/opentelemetry-java/issues/4081)) we think the answer is no because the global accessor is reserved for API components (i.e. MeterProvider, TracerProvider) and there is no log API. 

Instead, each appender we publish has a global setter for configuring the `LogEmitterProvder`. For example, [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.16/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_16/OpenTelemetryAppender.java#L86-L95) is the setter for the log4j appender.

**Comment by wallezhang** [comment]
Why doesn't the appender use auto configured `LogEmitterProvder` in `GlobalOpenTelemetry` directly? I think the global setter in appender is used for configure `LogEmitterProvider` manually.

**Comment by jack-berg** [comment]
@wallezhang `GlobalOpenTelemetry` doesn't have accessors for `SdkLogEmitterProvider` because `GlobalOpenTelemetry` is part of the API package, and there is no otel logging API. `SdkLogEmitterProvider` is part of the logging SDK.

**Comment by wallezhang** [comment]
@anuraaga Yes, of course I will use slf4j to print log in application. But I think the appender provided in the instrumentation library is a little complicated to use. When I use java agent to initialize whole SDK, I need to inject a `SdkLogEmitterProvider ` into log global setter to make the configured appender effective.

Maybe we can simplify usage by injecting the autoconfigured `SdkLogEmitterProvider` to the appender.

**Comment by anuraaga** [comment]
Oh if you're trying to use the javaagent to add an appender to logback or log4j to send OpenTelemetry logs, that injection should indeed be happening automatically here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/963b5cc087bcc546fe777b2d4df6cbfca8d72d04/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/OpenTelemetryInstaller.java#L58

Are you seeing the appender not get initialized fully automatically when using the javaagent? If so we can file an issue in the java instrumentation repo for that.

**Comment by wallezhang** [comment]
Thanks for reply. I'll try it first.

**Comment by pranavmarla** [comment]
> Should there be a global accessor for LogEmitterProvider? In java (discussed [here](https://github.com/open-telemetry/opentelemetry-java/issues/4081)) we think the answer is no because the global accessor is reserved for API components (i.e. MeterProvider, TracerProvider) and there is no log API.
> 
> Instead, each appender we publish has a global setter for configuring the `LogEmitterProvder`. For example, [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.16/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_16/OpenTelemetryAppender.java#L86-L95) is the setter for the log4j appender.

FYI, the following link from the original post is now dead:
> For example, [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.16/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_16/OpenTelemetryAppender.java#L86-L95) is the setter for the log4j appender.

So here is an updated permalink: [setter for the log4j appender](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5ed0551537362bb6b4603261c8d9b553eacf69c3/instrumentation/log4j/log4j-appender-2.17/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/OpenTelemetryAppender.java#L151-L160)

**Comment by jack-berg** [comment]
This was resolved in #2676. There's now [explicit text](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/logs/api.md#L52-L54) stating: 

> Normally, the LoggerProvider is expected to be accessed from a central place.
Thus, the API SHOULD provide a way to set/register and access a global default
LoggerProvider.
