### ISSUE TITLE
Clarify if Views must always specify Meter name

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#2337]
**What are you trying to achieve?**

Implement View specification.

**Additional context.**

There is a [requirement in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#:~:text=In%20order%20to,card%20instrument%20name\)) which was recently tweaked in #2306:

> the SDK MUST NOT allow Views with a specified name to be declared with instrument selectors that select more than one instrument (e.g. wild card instrument name).

The problem is every instrument selector that doesn't specify the Meter name can "select more than one instrument" because identical instruments may be created on any Meter. For example:

```py
meter_provider = MeterProvider(
    views=[View(instrument_name="foo.bar", name="baz")],
)
meter1 = meter_provider.get_meter("library1")
meter2 = meter_provider.get_meter("library2")

meter1.create_counter("foo.bar")
meter2.create_counter("foo.bar")
```

Given the spec wording, the view in the example is invalid even though it doesn't create a conflict in the output metrics. In fact, you would need to specify Meter name on any view that changes the output metric `name`. I'm guessing the intention was:

> the SDK MUST NOT allow Views with a specified name to be declared with instrument selectors that select more than one instrument **in the same Meter** (e.g. wild card instrument name).

**Comment by jack-berg** [comment]
> The problem is every instrument selector that doesn't specify the Meter name can "select more than one instrument" because identical instruments may be created on any Meter

Yes but in the example the metrics are still distinct because they are associated with different meters, so there isn't a conflict. The language is meant to avoid views that produce duplicate metric streams.

**Comment by aabmass** [comment]
Right I agree. But that's not what the "SDK MUST NOT" statement says. We could loosen the wording to say "in the same Meter".

**Comment by jack-berg** [comment]
Right, got it. Read your description more closely and I'm tracking. 👍

**Comment by ocelotl** [comment]
Regarding the way this requirement may be written:

> The SDK MUST NOT allow Views with a specified name to be declared with instrument selectors that select more than one instrument in the same Meter.

This requirement disallows the _declaration_ of a view that match more than one instrument in the same meter. But at the moment of declaration, it is not possible to know if such view will end up matching with more than one instrument in the same meter or not.

I think the requirement should say something like _a view with a specified name MUST NOT match more than one instrument in the same meter_.

**Comment by ocelotl** [comment]
> I think the requirement should say something like _a view with a specified name MUST NOT match more than one instrument in the same meter_.

Following up with this, if we follow this approach, we should also define which one of the instruments that match is the one who gets selected.

@lonewolf3739 adding this comment to address your comment in today Python SIG :+1:
