### ISSUE TITLE
Include sensor elements in system metrics (hardware temperature, humidity, etc).

### ISSUE THREAD

**Issue by odsod** [open-telemetry/opentelemetry-specification#2340]
**What are you trying to achieve?**

Trying to replace the [Prometheus Node Exporter](https://github.com/prometheus/node_exporter) with the [Host Metrics Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver) in an IoT edge environment where temperature monitoring in crucial.

**What did you expect to see?**

Expecting there to be rudimentary metrics for monitoring the hardware temperature of the host, like the [`node_hwmon_temp_celsius`](https://www.robustperception.io/temperature-and-hardware-monitoring-metrics-from-the-node-exporter) metrics from the Node Exporter.

Perhaps something like this:

### `system.sensor.` - Sensor metrics

**Description:** System sensor element metrics.

| Name                   | Description | Units | Instrument Type      | Value Type | Attribute Key(s) | Attribute Values |
| ---------------------- | ----------- | ----- | ---------------------| ---------- | ---------------- | -----------------|
| system.sensor.temp     |             | C     | Asynchronous Gague   | Double     | element          | ...              |
| system.sensor.humidity |             | 1     | Asynchronous Gauge   | Double     | element          | ...              |

**Additional context.**

See [hwmon_linux.go](https://github.com/prometheus/node_exporter/blob/master/collector/hwmon_linux.go) for a reference implementation.

**Comment by odsod** [comment]
@bertysentry Huge thanks for taking this one all the way!

**Comment by svenfoo** [comment]
I am facing the same problem as initially reported. I am trying to replace the Prometheus Node Exporter with the Host Metrics Receiver and I am missing the `hwmon` temperature and humidity metrics. I see that [hardware metrics](https://opentelemetry.io/docs/specs/semconv/attributes-registry/hardware/) have been added to the spec. But I do not see any code that is actually scraping the `hwmon` interface. Can you point me to it, please?

**Comment by bertysentry** [comment]
Hi @svenfoo 

There is [MetricsHub Community Edition](https://www.metricshub.com/downloads) that you can use. It collects hardware and system metrics from [many sources](https://metricshub.org/community-connectors/metricshub-connectors-directory.html) and pushes these metrics through OpenTelemetry following its semantic conventions.

There is also the [Enterprise Edition](https://metricshub.com/docs/latest/metricshub-connectors-directory.html) that collects data from more "enterprisey" systems, but it's for pay and not open source (it's "enterpricey" 😅)

Thanks!
