### ISSUE TITLE
Is LogEmitter.flush necessary?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2342]
Is LogEmitter.flash necessary or it is sufficient to have LogEmitterProvide.ForceFlush?

See also [discussion](https://github.com/open-telemetry/opentelemetry-python/pull/1916#discussion_r659945290) in Python prototype which [currently calls](https://github.com/open-telemetry/opentelemetry-python/blob/44e9b5531d91c8c52f58cd4ea3930cda5c1ed662/opentelemetry-sdk/src/opentelemetry/sdk/_logs/__init__.py#L354) LogEmitter.flash.

Is LogEmitterProvider.ForceFlush accessible at the call sites that currently call LogEmitter.flash? If yes then we can delete LogEmitter.flash.

**Comment by srikanthccv** [comment]
> Is LogEmitterProvider.ForceFlush accessible at the call sites that currently call LogEmitter.flash

Yes, this can access the global log emitter provider and directly call on provider `flush`. I see there is another open issue #2332 if we should have the global provider set/get. If we decide to not allow that then I think python sdk should update the Handler (analogous to appender) to be initialised with a provider.

**Comment by tigrannajaryan** [comment]
@srikanthccv will you be able to take this issue and submit a PR to fix this in the spec?

**Comment by srikanthccv** [comment]
Sure, please assign to me.
