### ISSUE TITLE
Inconsistency for reporting "error" tag in OpenTracing compatible systems

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#2349]
For Jaeger:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/trace/sdk_exporters/jaeger.md#error-flag

For OpenTracing compatibility:
https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/compatibility/opentracing.md#set-tag

In the OpenTracing compatibility the Status.OK corresponds to "error" == false, but in the Jaeger transformation that is not the case, even though Jaeger is an OpenTracing compatible system (which I think follows the same conventions).

**Comment by yurishkuro** [comment]
Jaeger does not distinguish between error=false and error being unset, it only recognizes error=true. So there's no issue here imo. Also, the linked specs address different transformation layers, such that OTEL->Jaeger will take priority over OT->OTEL.

**Comment by bogdandrutu** [comment]
Question is, should Otel -> Jaeger also set "error: false" when status OK or not?

**Comment by yurishkuro** [comment]
I prefer it didn't, because it's pointless data that only takes space & bandwidth. Not setting it has the same meaning to Jaeger.

**Comment by bogdandrutu** [comment]
That means, if I have this setup for the moment:

`OpenTracing` -> `OpenTracingBridge` -> `OtelSdk` -> `Jaeger Exporter`

A call in OpenTracing to add `"error": true` will not be visible in the Jaeger. Or I am missing something

**Comment by yurishkuro** [comment]
`"error": true` will be visible, `"error": false` will not be

**Comment by bogdandrutu** [comment]
You are correct, but the question still stands, is that something we should be concern about?

**Comment by carlosalberto** [comment]
Maybe _not quite_ what you are asking, but I'm wondering whether, for the sake of clarity and to avoid confusion, we should play conservative and do in the OT Shim:

* `error=true` -> `Status.Error`
* Anything else -> `Status.Unset` (as this is technically the equivalent)

**Comment by yurishkuro** [comment]
When I look at it from a user perspective, irrespective of whether the status was set by default instrumentation or by the application code, if it was not `Status.Error` I would treat it as success. I don't think if a UI were to do breakdown of some span metric by span status it would break out Unset as a separate category - it's just not that useful during analysis. Afaik the only reason Unset exists is as a kludge for solving set-by-default vs. set-by-app issue, not because there is external value when processing spans.

**Comment by carlosalberto** [comment]
@bogdandrutu Ping ;)

**Comment by carlosalberto** [comment]
Closing as we decided to keep the current behavior, and OT has been marked stable also. Feel free to re-open @bogdandrutu in case you want to do a follow up.
