### ISSUE TITLE
Proposal: Service/Component Version Labels

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-specification#235]
Currently in the OpenTelemetry design, there's no convention for specifying the version of a service or component. This is a pretty basic piece of information that is very useful for consumers of telemetry data (to understand, specifically, what version of a given component/service produced a given iota of telemetry data) that we should support as a first-class citizen.

Would it make the most sense to add these to the Standard Resources once that's updated, and treat them as semantic versions (thus, `service.semver`, `component.semver`, etc.) and allow for other resources to attach the `.semver` field? Alternately, we could create a `Version` semantic resource that had different types of versions that would be useful for different resource types (for example, client OS versions, hardware revisions, etc.)

**Comment by z1c0** [comment]
Should this go into an RFC?

**Comment by austinlparker** [comment]
See https://github.com/open-telemetry/oteps/pull/38 for the RFC.

**Comment by SergeyKanzhelev** [comment]
@austinlparker can you please move the OTEP's description to the spec, please.
