### ISSUE TITLE
Clear layering of context propagation

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#237]
Early on we decided to make context propagation (both in-process and inter-process) to be a separate layer that other verticals (metrics, traces) are build upon. I wrote the following document that outlines this approach, which was originally linked to some issue in the Java SDK repo.

https://docs.google.com/document/d/1UxrEYOaQlF_E4gtiPoFmcZ4YKKe1GxohvCvQDuwvD1I/

**Comment by tedsuo** [comment]
This work has continued in an OTEP, closing this issue for now: https://github.com/open-telemetry/oteps/pull/66
