### ISSUE TITLE
Security in Prometheus exporter

### ISSUE THREAD

**Issue by fmhwong** [open-telemetry/opentelemetry-specification#2400]
**What are you trying to achieve?**
In the current spec for the Prometheus exporter https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/prometheus.md, it doesn't mention anything about securing the metrics endpoint.

When using the automatic instrumentation opentelemetry-javaagent.jar and the Prometheus exporter is enabled, the metrics endpoint (e.g. http://localhost:9464/) is not protected.

**What did you expect to see?**
There should be an option to use https and have the metrics endpoint protected by
- username/password
- OpenShift service account token

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by sandeepsharat** [comment]
Under which version is this fix released?...

**Comment by dyladan** [comment]
@sandeepsharat it is no released. This is a feature request

**Comment by mtwo** [comment]
Chiming in during triage - this seems very useful. Tagging @open-telemetry/wg-prometheus for their comments.

**Comment by dashpole** [comment]
This is a good idea, but might only apply to auto-instrumentation.  From looking at manual instrumentation in a few languages, it looks like most allow you to either [replace the HTTP handler](https://github.com/open-telemetry/opentelemetry-java/blob/0bc74744cb3c00f5551c3c062bddbfc20390c62d/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java#L123), [serve the endpoint using the prometheus client library](https://github.com/open-telemetry/opentelemetry-python/blob/b596734d15c267984f8f302306dffc1cf7683e6c/exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py#L37C5-L37C22), or [require you to serve the http endpoint yourself](https://github.com/open-telemetry/opentelemetry-go/blob/4816927e03283dee4aa2d9b6c8dd852000f80e2d/example/prometheus/main.go#L89).

**Comment by trask** [comment]
> This is a good idea, but might only apply to auto-instrumentation. From looking at manual instrumentation in a few languages, it looks like most allow you to either [replace the HTTP handler](https://github.com/open-telemetry/opentelemetry-java/blob/0bc74744cb3c00f5551c3c062bddbfc20390c62d/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServerBuilder.java#L123), [serve the endpoint using the prometheus client library](https://github.com/open-telemetry/opentelemetry-python/blob/b596734d15c267984f8f302306dffc1cf7683e6c/exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py#L37C5-L37C22), or [require you to serve the http endpoint yourself](https://github.com/open-telemetry/opentelemetry-go/blob/4816927e03283dee4aa2d9b6c8dd852000f80e2d/example/prometheus/main.go#L89).

@dashpole do you think there's something we should add to the spec to support this, or should people open issues directly with various implementations to support it? thanks

**Comment by dashpole** [comment]
> @dashpole do you think there's something we should add to the spec to support this, or should people open issues directly with various implementations to support it? thanks

I would recommend people open issues directly with implementations, since most prometheus exporters don't directly configure the endpoint.  I'm generally a in favor of using prometheus client libraries (which is recommended by the current spec) for serving, and think any additional capabilities around securing the endpoint probably belongs there, rather than in OTel.  For things like auto-instrumentation, where we configure the endpoint, we should try and "pass through" configuration to prometheus clients as much as possible.  Otherwise, people should open issues directly with various implementations.

**Comment by trask** [comment]
Thanks, makes sense, let's try this and people can loop back here as needed.
