### ISSUE TITLE
Add Arm64 Support in all language libraries 

### ISSUE THREAD

**Issue by odidev** [open-telemetry/opentelemetry-specification#2418]
Hi Team, 

**What are you trying to achieve?**
I'm working on building various opentelemetry language libraries for arm64 platform. 

**What did you expect to see?**

I have explored the different repositories and CI being used in language libraries, arm64 builds can be added in the respective CIs to test the libraries.  

**Additional context.**

Do you have any plans for supporting arm64 platform? 

It will be very helpful if arm64 support is available in all the language libraries. If interested, I will raise a PR.

**Comment by reyang** [comment]
@odidev Thanks! Would you clarify which language are you considering? (e.g. Python, JavaScript might care less about CPU architectures).

**Comment by odidev** [comment]
@reyang Thanks for the quick response, I am considering cpp and go libraries. Please share your thoughts on this.

**Comment by odidev** [comment]
Hi @reyang,

I have also tested Opentelemetry Java & Python and they aren't working on arm64 platform.   

Do you want me to open separate issues for Java in the java library repository and python too now that I tested and it doesn't work on arm64 platform. 

Please share your thoughts on this, I will be happy to help.

**Comment by reyang** [comment]
> @reyang Thanks for the quick response, I am considering cpp and go libraries. Please share your thoughts on this.

I'm 99% sure that OpenTelemetry C++ works for ARM64, please open issue in the opentelemetry-cpp repo if that's not the case. FYI @open-telemetry/cpp-maintainers.

**Comment by reyang** [comment]
@odidev I'm closing this issue as the spec currently doesn't put any restriction on the CPU architecture. I believe most language implementations should work for ARM64, if that's not the case, please file issue in specific language implementations.
