### ISSUE TITLE
DistributedContext specification is incomplete

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#242]
* The distributed context specification talks about scope (in the [conflict resolution section](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-distributedcontext.md#entry-conflict-resolution)) but does not define it.
* Relatedly, there is no notion of a current context and consequently no way to get it.
* The API, as defined in the spec, provides no way to add values to the distributed context.

In Java, all of this is implemented in the `DistributedContextManager` (it seems that Tracer : Span ~ DistributedContextManager : DistributedContext).

**Comment by Oberon00** [comment]
Should this be rectified in a simple PR (that simply follows the Java "reference" implementation) or is an OTEP required?

**Comment by songy23** [comment]
`DistributedContext` may be renamed. See https://github.com/open-telemetry/oteps/pull/36.

**Comment by Oberon00** [comment]
I assume that was just a side note, since renaming would not change anything about the points I raised 😃

**Comment by tedsuo** [comment]
@Oberon00 in short, the current API is half baked and we hope to finish baking it this week. :)

There's was a lot of discussion last week to hammer out details around DistributedContext. You can find the notes here, under "Context Propagation Discussion": https://docs.google.com/document/d/1rgXZik2_-2fU1KpVi7nze5ygWA8NhaLE8VmD20H4P8M/edit#heading=h.o5slz8bi8org

We hope to get some proposals out this week, based on this discussion, which will hopefully provide a cleaner proposal for context propagation in general.

**Comment by tedsuo** [comment]
This work has continued as an OTEP: https://github.com/open-telemetry/oteps/pull/66
