### ISSUE TITLE
Clarify TLS/Secure default behavior

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#2420]
The [configuration options](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options) for the OTLP gRPC exporter are a little unclear what to do if no endpoint is configured. By a strict reading of the current spec it seems like a secure connection to localhost:4317 should be made, but it seems likely that certificate validation will fail in this case most of the time if a certificate is not supplied to the client. I would propose a secure connection is only the default here if a certificate is provided for validation, or we should specify that if no endpoint is provided TLS certificate validation should be disabled.

**Comment by tigrannajaryan** [comment]
I believe the default connection to localhost should be insecure (I am not aware of any benefits of using encryption for localhost connections). If we agree on this then the spec needs to be clarified.

**Comment by dyladan** [comment]
There are still a couple open questions in https://github.com/open-telemetry/opentelemetry-js/pull/2827

Specifically:

>> * if user sets http scheme and no other items (like providing credentials or env insecure settings) return insecure channel
>
>This is not as clear. I'll ask Tigran. The spec says insecure is false by default, but http implies insecure.

> > * if user wants to use all defaults, return secure channel
> 
> According to @tigrannajaryan [open-telemetry/opentelemetry-specification#2420](https://github.com/open-telemetry/opentelemetry-specification/issues/2420) it should be _insecure_ to localhost. Tigran agrees spec should be clarified.

> > * if user sets http scheme and env insecure = false, return secure channel
> 
> Yes. I think this will also be the answer for "user sets http scheme and no other items" but we'll wait for Tigran.

Would appreciate some clarification/guidance here.

**Comment by tigrannajaryan** [comment]
> > * if user sets http scheme and no other items (like providing credentials or env insecure settings) return insecure channel
> 
> This is not as clear. I'll ask Tigran. The spec says insecure is false by default, but `http` implies insecure.

The [spec says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md) that "insecure" option is ignored for OTLP/HTTP. So, with the default protocol of `http/protobuf` and default destination of `http://localhost:4318` I believe there is no ambiguity. It means: use OTLP/HTTP, insecure.

**Comment by dyladan** [comment]
This is specifically for the gRPC exporter

**Comment by tigrannajaryan** [comment]
For gRPC the spec says:
```
Endpoint (OTLP/gRPC): Target to which the exporter is going to send spans or metrics. The endpoint SHOULD accept
 any form allowed by the underlying gRPC client implementation. Additionally, the endpoint MUST accept a URL with 
a scheme of either http or https. A scheme of https indicates a secure connection and takes precedence over the 
insecure configuration setting.
```

I think we need to modify it to say that if the "http" or "https" scheme is used in the endpoint then that takes precedence over the insecure configuration setting (so, not just the "https" as it says currently, but also "http").

I think that should remove the ambiguity.

**Comment by dyladan** [comment]
So the insecure config is only used if there is no scheme in the URL?

**Comment by tigrannajaryan** [comment]
> So the insecure config is only used if there is no scheme in the URL?

Yes, I think so.
