### ISSUE TITLE
Batch span processor support for multiple pending exports

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#2434]
**What are you trying to achieve?**

Higher throughput from the batch span processor when using an asynchronous exporter (especially when talking to a remote backend as opposed to a local collector).

Having discussed this with the Java folks, I believe this boils down to:

* Clarity on whether the [batch span processor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor) should allow multiple pending exports, and if not, I'd like to propose a new configuration parameter `maxPendingExports` in the spec to support multiple pending exports.

**Additional context**

The Java SDK's span exporter returns a promise, and the batch span processor waits up to `exportTimeoutMillis` for the promise to complete before proceeding to export the next batch.

It would be great to hear if other language SDKs have had any different interpretation and have implemented the batch span processor to already allow multiple pending exports, since that will help in planning a path forward here.

@open-telemetry/cpp-approvers @open-telemetry/dotnet-approvers @open-telemetry/erlang-approvers @open-telemetry/go-approvers @open-telemetry/javascript-approvers @open-telemetry/python-approvers @open-telemetry/ruby-approvers

**Comment by tsloughter** [comment]
I went looking into this at one point as well and found that the OTLP spec actually does support pipelining requests: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-concurrent-requests and https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-concurrent-requests

At first I thought this conflicted with how the batch processor says: "Export() will never be called concurrently for the same exporter instance. Export() can be called again only after the current call returns." But pretty sure I realized `Export` technically can return before the request it sent has gotten a response, and was how I planned to implement it -- similar to what you mention with the Java `Export` implementation returning a promise.

So there may just need to be a note in the batch processor spec to say that `Export` not being called concurrently is not meant to mean a restriction on concurrent sending of batches.

**Comment by lalitb** [comment]
In C++ SDK, the export is sequential, so the batch processor waits for the completion of the ongoing request before creating a new one. 

And during our tests, significant performance/throughout improvement was observed with concurrent HTTP requests, and multiple ongoing exports (https://github.com/open-telemetry/opentelemetry-cpp/pull/1209#discussion_r812732985). Changes couldn't be incorporated as it seems to deviates from specs - "Export() will never be called concurrently for the same exporter instance. Export() can be called again only after the current call returns"

Adding a configurable number of ongoing exports would be definitely useful.

 @owent @DebajitDas - fyi

**Comment by MrAlias** [comment]
The Go SDK explicitly states that calls to the exporter from the BSP will be done synchronously based on what the specification stated. The Go SDK and its exporters would be able to support this concurrency pattern, but there would need to be some flag as mentioned. The existing exporters we provide do not offer any concurrency guarantees and would need to be refactored. If there was no flag and the behavior was introduced it would indeed cause race conditions based on the current implementations.

**Comment by tsloughter** [comment]
@MrAlias but can it be done with only refactoring the exporters and not touching the batch processor?

Like with retry logic that is not allowed in the batch processor but must be done in the exporter itself I think it makes the most sense to leave the batch processor spec as it is (except for adding a note similar to how it says retries must be done in the exporter).

I guess the line about `Export` not being called concurrently should also be clarified in the spec but I don't think it has to or should change. If all the responsibility for concurrent sending is in the exporter then the batch processor should be limited in how it calls `Export` -- the same as you wouldn't want the batch processor to start doing retries if the exporter has that logic as well.

**Comment by tsloughter** [comment]
My attempt to improve the spec for this: https://github.com/open-telemetry/opentelemetry-specification/pull/2452

**Comment by trask** [comment]
@tsloughter @reyang I don't think #2452 resolved this

**Comment by lalitb** [comment]
Agree, this is not resolved with #2452.

**Comment by tsloughter** [comment]
@trask because it doesn't define a setting for the max number of pending exports?

I'd argue against it but in doing so I'd be arguing to also remove the returning of sucess/failure and the existing timeout :). So it is a tough one. 

Adding a pending limit further adds concurrency control to the processor when it is meant to be in the exporter, along with retry logic. The fact retries are in the exporter is another reason I've not seen the need for success/failure being passed to the processor, what can it do with this information? I guess log it.

My plan had been to have `export` block when the exporter has reached its max pending requests, so the batch processor would not need to know about it.
