### ISSUE TITLE
Define OTLP -> Prometheus metric name conversion rule

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-specification#2437]
**What are you trying to achieve?**

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#otlp-metric-points-to-prometheus defined OTLP -> Prometheus metric conversion on instrument type, attributes, exemplars and resource attributes. But the conversion rule for instrument name is missing.

Like, [Prometheus](https://prometheus.io/docs/practices/naming/#:~:text=...should%20have%20a%20suffix%20describing%20the%20unit%2C%20in%20plural%20form.%20Note%20that%20an%20accumulating%20count%20has%20total%20as%20a%20suffix%2C%20in%20addition%20to%20the%20unit%20if%20applicable.) defines that instrument units should be concatenated to the metric name. Should this apply in the conversion of OTLP -> Prometheus?

**Additional context.**

Originally posted by @aabmass https://github.com/open-telemetry/opentelemetry-js/pull/2824#pullrequestreview-919670937

**Comment by aabmass** [comment]
The official python prometheus client library actually accepts the unit and [concatenates it into the metric name](https://github.com/prometheus/client_python/blob/789b24a47148f63109626958fe2eb1ad9231f9c3/prometheus_client/metrics_core.py#L24-L26).

**Comment by dashpole** [comment]
Good catch.  I think we are required to do this to be compatible with the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#unit): `Unit specifies MetricFamily units. If non-empty, it MUST be a suffix of the MetricFamily name separated by an underscore. Be aware that further generation rules might make it an infix in the text format.`.

It does mean the OTLP -> Prom -> OTLP round-trip is even further from the original name in OTLP, but I think we just have to accept that consequence.

**Comment by aabmass** [comment]
@dashpole I noticed the python prometheus client also adds `_total` suffix for CounterMetricFamily. See OM spec [here](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#counter-1).

Looks like there was some previous OTel discussion about this for the receiver https://github.com/open-telemetry/opentelemetry-collector/pull/3603, but I don't see anything about this in the [datamodel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#sums-1) right now.

**Comment by dashpole** [comment]
We should also note that in the datamodel spec.

**Comment by dashpole** [comment]
I opened a PR to clarify those aspects.  LMK if I missed anything else
