### ISSUE TITLE
Semantic convention for database driver name needed

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#245]
For all existing semantic conventions, the `component` attribute is set to a fixed strings (`"http"` , `"grpc"`). But [the database `component`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-semantic-conventions.md#databases-client-calls) should be

> Database driver name or database name (when known) "JDBI", "jdbc", "odbc", "postgreSQL".

This is inconsistent. I suggest changing this to

* component: Always the string `"db"` (or leave it out entirely)
* db.name: The database name (when known) (Should be more explicitly specified)
* db.clienttech: The name of the database client library (e.g. JDBC driver name, Python module name, ...) which is used.

**Comment by cbandy** [comment]
Agreed. The database semantics seem rather different from the others.

> - component: Always the string "db" (or leave it out entirely)

I like consistency of the value in `component` being a prefix/section of related attributes.

> - db.name: The database name (when known) (Should be more explicitly specified)

This sounds a bit like the already defined `db.instance` and similar/related `peer.service`.

(off topic: not all databases have this concept, so it should probably be an optional attribute. e.g. a MySQL server allows a single TCP connection access multiple "databases;" PostgreSQL, on the other hand, limits a single TCP connection to a single "database.")

> - db.clienttech: The name of the database client library (e.g. JDBC driver name, Python module name, ...) which is used.

1. This idea of "client library" feels sufficiently general enough that it might not need to be limited to `db` attributes.
2. Elsewhere in the semantic convention document, two-word attributes are separated by an underscore, e.g. `http.status_code`.

**Comment by Oberon00** [comment]
FYI: I'm currently working on resolving this, and generally upgrading the semantic conventions. After we hash this out internally a bit more here at Dynatrace, we will submit a PR (expected to land tomorrow (late Friday CEST) or next Monday.)

**Comment by tedsuo** [comment]
I agree with this change. I wonder: how do you see the `component` tag relating to the new named tracer components?

**Comment by Oberon00** [comment]
Not related at all.

**Comment by SergeyKanzhelev** [comment]
@tedsuo there is a similar comment here: https://github.com/open-telemetry/opentelemetry-specification/pull/264/files#r330156117 I wonder if this is something that can be unified.

**Comment by jmacd** [comment]
I propose that `component` be set to the name of the named `Tracer` or `Meter`. I can't imagine why we would want to specify a list of these values, they are intended as just names of a piece of code. OpenTracing specifies these as: "The software package, framework, library, or module that generated the associated Span. E.g., "grpc", "django", "JDBI"."

**Comment by SergeyKanzhelev** [comment]
@jmacd one thing though. Do we need a property saying "it's definitely HTTP". While component may say "OKHTTP" for java. Or we will go with some sort of namespacing for component?

**Comment by kbrockhoff** [comment]
The existing approach for component is very useful in branching logic of code handling trace data. Requiring the value to be 'db' for database spans makes this branching much easier.

**Comment by bogdandrutu** [comment]
#271 decided to remove the component attribute, so this will become obsolete after.

**Comment by Oberon00** [comment]
@bogdandrutu I disagree. While this does affect this issue, it leaves the question open where to store the info that is stored there for DB now (because it is *not* a constant string for db).

**Comment by dyladan** [comment]
Perhaps rename this issue to "semantic convention for database driver name" or similar so it is not confused?

**Comment by carlosalberto** [comment]
Hey @Oberon00 would you mind changing the name of this issue (probably going with the suggestion done by Dylan) so we can track this one?

Also, moving it to the next milestone.
