### ISSUE TITLE
Define version labeling schema for API and SDK

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#246]
We need to have a well-defined schema for API and SDK versioning. The PR here https://github.com/open-telemetry/opentelemetry-specification/pull/115 got stalled because I haven't yet been able to find a satisfactory approach to API and SDK version decoupling.

I am raising this issue to seek feedback and proposals.

### Problem Description

We assume that API specification will have a version number. We also assume that SDK's will implement a particular API version.

Library authors may want to make multiple SDK releases that are implementing a particular API version. For example, we may start with API version 1.0.0 and make an SDK release 1.0.0 that implements that particular API.

Later library authors may want to make a bug fix in the SDK and release 1.0.1. Note that this release implements the same API version, there are no changes from API perspective. Now we are in a situation when API and SDK versions diverged.

This diverging seems inevitable because most likely API versions will change much less frequently than library authors will want to make SDK releases that implement those particular API versions.

One possible solution is to declare that an SDK will be tagged by 2 version numbers: 
1) the API version that the SDK implements
2) the release version of the SDK itself.

These version numbers are decoupled and can be changed independently. So for example one may have an SDK 1.0.10 that implements API 1.0.0, or have SDK 1.5.10 that implements API 1.1.0.

However, I and @yurishkuro do not really like this approach, it is far from being elegant and is confusing.

Better suggestions are welcome.

**Comment by tigrannajaryan** [comment]
See proposal here https://github.com/open-telemetry/opentelemetry-specification/pull/280

**Comment by jmacd** [comment]
Closing this as #280 has merged.
