### ISSUE TITLE
Record instrumentation_scope attribute in Prometheus export

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#2493]
Currently, instrumentation_scope is not used in the documentation for converting OTLP metrics to Prometheus. However, because it is part of identity for the OTLP model, it should be added as an attribute. Otherwise, the OTel SDK can record two metric streams with the same name and attributes, but different instrumentation scope, and the prometheus exporter will output them as identical streams causing a failure to scrape.

**Comment by anuraaga** [comment]
@open-telemetry/wg-prometheus

**Comment by arminru** [comment]
Related to #1906.

**Comment by anuraaga** [comment]
Ah this is mostly a dupe of #1906 so feel free to close this if it makes sense. We need to prioritize it though, while we don't intend to publish Prometheus exporter as stable next month, with metrics going stable we expect a lot of bug reports for this since it's easy to run into.

**Comment by jack-berg** [comment]
#2703 should close this.
