### ISSUE TITLE
Run on k8s failed but successed on VM.

### ISSUE THREAD

**Issue by Jungle666** [open-telemetry/opentelemetry-specification#2498]
agent version is 1.10.0,Run on k8s failed but successed on VM.

run commad:
java -javaagent:/usr/local/agent/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://**:4317 -Dotel.resource.attributes=tps.tenant.id=**___apm,service.name=demo -Dotel.javaagent.extensions=/usr/local/agent/ -Dotel.metrics.exporter=none -Dotel.traces.sampler=parentbased_traceidratio -Dotel.traces.sampler.arg=1 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/demo.jar

error info:
Failed to find Premain-Class manifest attribute in /usr/local/agent/opentelemetry-javaagent.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by trask** [comment]
hi @Jungle666! it looks like you are asking about the opentelemetry-javaagent, in which case can you open an issue instead at https://github.com/open-telemetry/opentelemetry-java-instrumentation?

**Comment by Jungle666** [comment]
oh,sorry.

**Comment by arminru** [comment]
--> https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5876
