### ISSUE TITLE
Request: Use abbreviated cloud provider prefixes in log attribute key naming conventions

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-specification#2503]
The current specification for mapping fields in the logs data model recommends prefixing company-specific fields with FQDN-style identifiers, for example `com.google.*` for [GCP-specific attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#google-cloud-logging).

It was explained in the log sig meeting that this is based on the existing [attribute naming conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#recommendations-for-application-developers).

However, it would be easier to use abbreviated attribute prefixes for cloud providers, eg `gcp.*`, `aws.*`, `azure.*`, etc. There are already some conventions for doing this in [logs for AWS](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud_provider/aws/logs.md) and [tracing](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-sdk.md#dynamodb). It is also noted elsewhere in the [semantic conventions that cloud providers may have specific key names](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#cloud-provider-specific-attributes).

So, to make this more consistent it would be nice if we could officially update the [logs data model mappings](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#appendix-a-example-mappings) to use that same style of prefix rather than the reverse-FQDN for cloud providers.

**Comment by pmm-sumo** [comment]
Also, there is a bit on [resource semantic conventions on cloud providers](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#cloud-provider-specific-attributes)

**Comment by damemi** [comment]
Opened a PR to make the model changes for GCP attributes: https://github.com/open-telemetry/opentelemetry-specification/pull/2514
