### ISSUE TITLE
Add semantic convention attributes for capturing the application layer protocol

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-specification#2548]
**What are you trying to achieve?**

Currently, the `net.transport` attribute allows capturing the transport layer protocol used (like TCP, UDP, or IP). However, there is no generic attribute to capture the application layer protocol (like AMQP, DNS, SSH, NTP). Where it is currently captured, it is done so via attributes specific to certain areas, e. g. as `messaging.protocol`, or somehow obfuscated in `http.flavor`.

Having a general way to capture the application layer protocol would allow cleaning up HTTP and messaging semantic conventions and allow for more alignment between the different areas.

**Additional context.**

I would propose to add two new attributes:
`net.protocol.name`
`net.protocol.version`

The first would capture the name of an application layer protocol according to the OSI Model, the second would capture a version of the protocol. The naming is consistent with ECS, where [`network.protocol`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-protocol) is used.

Those general attributes could be used to replace the existing `messaging.protocol`, `messaging.protocol_version`, and `http.flavor`.

If that sounds feasible, I'm happy to submit a PR.

**Comment by Oberon00** [comment]
OK, maybe all the examples I picked would not be considered "protocols" (although I think that's bikeshedding in these cases), but there are indeed "things" that call themselves "protocols" and use HTTP as their transport-layer, e.g. https://en.wikipedia.org/wiki/SOAP, https://en.wikipedia.org/wiki/Universal_Plug_and_Play (UPNP), https://en.wikipedia.org/wiki/XMPP#XMPP_via_HTTP.

Though maybe this could be handled by having one (nested child) span per layer?

**Comment by pyohannes** [comment]
> but there are indeed "things" that call themselves "protocols" and use HTTP as their transport-layer

@Oberon Your concern is valid: `net.protocol.name` alone cannot exhaustively model scenarios where one application layer protocol is used on top of another (XMPP via HTTP, or UPNP via HTTP). Especially with HTTP I think you're right that this can be handled by having a nested child span per layer (this is already recommended for RPC over HTTP [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md#distinction-from-http-spans)).

`net.protocol.*` attributes make most sense when this additional layer of spans is not desired and would just be considered noise, and/or when it's a more obscure protocol for which no dedicated semantic conventions exist.  I think there are already now some semantic conventions where it would be a valuable addition:
* For [messaging](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes), obviously, as it already has `messaging.protocol` and `messaging.protocol_version` defined.
* It can also be used in [database semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#mongodb), to denote application protocols details. E. g. there is [TDS](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec) used by Microsoft products, CouchDB and others use HTTP, and other databases besides MongoDB support the MongoDB protocol. Capturing this via `net.protocol.*` attributes provides useful information, especially for databases that support more than one protocol. Modelling this via separate nested spans would probably be overkill in most instances.
* It could be used on [CloudEvents](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/cloudevents.md) spans, to describe the protocol with which events were transferred (again, nested spans could be used too, but might be overkill).
* `net.protocol.version` could be used in protocol-related semantic conventions where the protocol version is relevant. In HTTP, the version is currently put in `http.flavor`. I'm not sure if this can still be changed, however, I think for future semantic conventions (e. g. AMQP) it can be benefical to have a generic way and consistent way to specify this information.

**Comment by Oberon00** [comment]
> Modelling this via separate nested spans would probably be overkill in most instances.

Exactly in the scenarios where don't want nested spans, we'd need more than one attribute on a single span. Or we could make the protocol/version attributes arrays.  But note that there is no AppendToArrayAttribute API, so the whole protocol stack would have to be known in the same place.

I agree that having a single net.(application_)protocol attribute sounds cleaner, but cleaner is not always simpler in practice. I think adding this attribute for use cases where we don't have a special attribute or even no semantic convention at all totally makes sense. I'm a bit skeptical of replacing existing protocol attributes though.

> http.flavor. I'm not sure if this can still be changed,

I think simple renamings like this should be doable, since we have the schema file mechanism for that.

**Comment by Oberon00** [comment]
Copying my comment from https://github.com/open-telemetry/opentelemetry-specification/pull/2469#issuecomment-1140282545 here:

> With an HTTP-proxy (not just any proxy used with HTTP!), the remote end of your network connection, even from an application perspective, is the HTTP proxy. This has to be handled specifically by the application, e.g. it must use full URLs as the target in the request line [en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers)
>
> As said, I don't think there are many other protocols beside HTTP where this distinction really becomes important. But if we have more examples where the distinction could be useful, I think introducing an net.app.* namespace that has all the other net.* attributes nested under it (except net.transport I guess, which could be net.app.protocol instead https://github.com/open-telemetry/opentelemetry-specification/issues/2548), would make sense.

So we should consider having a net.app.* namespace with protocol (analogous to transport) in there. Or even a separate namespace not nested under net, e.g. comm(unication)?

**Comment by Oberon00** [comment]
@pyohannes I think breaking this up into two steps as you suggest makes a log of sense 👍

**Comment by pyohannes** [comment]
Thanks @Oberon00. I'll work on a PR for introducing `net.app.protocol`.
