### ISSUE TITLE
Is direction dimension a mistake in semantic conventions?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2589]
We have metrics that have a "direction" attribute, for example [disk metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#systemdisk---disk-controller-metrics).

This seems to be in contradiction to the [general guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#general-guidelines) about attributes
>["As a rule of thumb, aggregations over all the attributes of a given metric SHOULD be meaningful,"](https://prometheus.io/docs/practices/naming/#metric-names) as Prometheus recommends.

I am not sure what aggregation is meaningful for "direction" attribute.

Should the attribute be removed and the metrics split into 2, one for read and one for write?

It does look pretty natural to express this dimension as an attribute, it is low cardinality, it groups 2 very related measurements. Is this an indication that the guidelines need to be adjusted or this is an exception from the rule? Or perhaps there is a meaningful aggregation of "direction" that I just don't see?

**Comment by reyang** [comment]
+1, also in most cases the removal of this dimension would result in meaningless value (e.g. what does a "total read/write bytes" mean for a disk?)

In addition, many disk/NICs have extra operations beyond read and write (I just took a screenshot from my laptop):

![image](https://user-images.githubusercontent.com/17327289/171229825-33cf90bb-6d03-4238-8a81-3e62df3c04ba.png)

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan does the aggregation not represent "total" bytes send/received over the network? Is that not meaningful?

Yes, probably meaningful for network (e.g. total bytes/throughput can be interesting to know as a percentage of bidirectional bandwidth available for half-duplex physical connections).

Is it also meaningful for disks? I am not sure what's the meaning of total combined bytes written and read for disk. Sure, both are bytes flowing from/to the same device, maybe that's useful somehow?

I am not against keeping the `direction` if we think it is meaningful (but see also @reyang comment which shows we do not fully understand the allowed values for the dimension).

**Comment by bertysentry** [comment]
I have mixed feelings about this. If you take the network traffic example, you can calculate the bandwidth utilization with something like: `max(rate(system.network.io)) / hw.network.speed`, where the `max()` function applies to each direction of the `system.network.io` metric, for a full-duplex link.

I don't see how we could calculate the same bandwidth utilization metric from `system.network.io.receive` and `system.network.io.transmit`.

Also, as noted by @reyang, having separate metrics is reasonable when you have a strictly defined set of dimensions. It does fit well with network (receive vs transmit), but doesn't even for a simple metric like `system.disk.io`.

Last point: What are the drawbacks of using a *direction* attribute versus a separate metric? As explained above and by others, there are a few minor benefits of using the *direction* attribute, but I can't see anything in the "cons" column. Performance? Readability? Consistency?

**Comment by bertysentry** [comment]
This change will require changes in 7 receivers for consistency:

* activedirectorydsreceiver
* elasticsearchreceiver
* hostmetricsreceiver
* iisreceiver
* kubeletstatsreceiver
* mongodbatlasreceiver
* nsxtreceiver

**Comment by reyang** [comment]
During the [Aug. 16th, 2022 Specification SIG meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#), there were discussions about network metrics - based on the comment [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2589#issuecomment-1142381058) folks believe that Disk I/O should NOT have a dimension/attribute called `direction`, the question is whether Network I/O should do the same or not, and issue #2726 suggested Network I/O should keep `direction`.

Here are what I've found so far about Windows operating systems (NT kernel based):
1. "Network" is a vague term, NT models network performance counters as several things:
    * **Physical Network Interface Card (NIC) Activity** - at such low level, the NIC doesn't necessarily connect to the actual network (e.g. one can have an NIC that is NOT corrected connected, but still valid from the OS kernel / device driver perspective). So it only has device level counters such as "Device Power State" and "Low Power Transitions (Lifetime)".
    * **Network Adapter** https://docs.microsoft.com/en-us/windows/win32/iphlp/managing-network-adapters. On the adapter level, the Rx and Tx value added up to Total https://social.technet.microsoft.com/Forums/en-US/5f8f9a16-3488-4c73-868e-121885702fd8/understanding-the-performance-counters-network-adapter-bytes-totalsec-microsoft-network?forum=operationsmanagergeneral.
    * **Network Interface** https://docs.microsoft.com/en-us/windows/win32/network-interfaces
2. **Process** only has `I/O Read/Write/Other Bytes/Operations`, it doesn't have direct connection to the underlying Network Interface nor Network Adapter. And it does have "Other Bytes" (I can imagine a process trying to listen on a TCP port, which is considered as control bytes but not Rx/Tx).

**Comment by sebastien-rosset** [comment]
Shouldn't `direction` be renamed to something like `hw.io_direction`?

**Comment by bertysentry** [comment]
@sebastien-rosset I don't see a reason to use a specific attribute for hardware metrics. `direction` is specified [at the general level for IO metrics](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/#instrument-naming) so it shall be used in specific semantic conventions that cover IOs as well.

**Comment by sebastien-rosset** [comment]
I created #3129 since it's a different issue
