### ISSUE TITLE
Faas trace attributes: requirement levels need revision

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#2599]
[faas trace semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md)  define multiple attributes as required and some of these choices seem controversial:
- `faas.document.time` - it's required, but it's likely the same time as span start time. Is this attribute really needed? Should it be `optional` ?
- `faas.time` - same concern - it should match span start time, why another one is needed and can it be `optional`?
- `faas.invoked_name` span attribute that SHOULD match `faas.name` resource attribute, seems like duplication, why  `faas.invoked_name` is needed and can it be `optional`?
- `invoked_provider` and `invoked_region` - should they be resource attributes (they are static)? should they be `recommended` instead?

**Comment by Oberon00** [comment]
> faas.invoked_name span attribute that SHOULD match faas.name resource attribute, seems like duplication, why faas.invoked_name is needed and can it be optional?

It SHOULD match the remote side, but that one might not be instrumented, or an error might occur with reaching it or transmission of the remote side's trace.

**Comment by lmolkova** [comment]
Thanks for the clarification!
At least in Azure Functions world clients **never** don't know if they're calling an Azure Function or anything else. It sounds like the whole [Outgoing Invocations)(https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md#outgoing-invocations) is in manual instrumentation land or covers a few edge cases. Requiring anything, in this case, seems difficult.

**Comment by Oberon00** [comment]
> It sounds like the whole Outgoing Invocations is in manual instrumentation land or covers a few edge cases.

No, this was introduced for AWS Lambda, where you have an API call to invoke a function (that can also be automatically instrumented with a hook mechanism). https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html It seems that other cloud providers don't provide this mechanism.

**Comment by jack-berg** [comment]
The language is also inconsistent in the faas trace semantic convention spec. [Here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md#datasource) it says that "it is recommended to set the following attributes", and proceeds to list a table of attributes which are all marked as "required".
