### ISSUE TITLE
semantic_convention: remoting client attributes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#26]

**Comment by Oberon00** [comment]
I guress "remoting" refers to RPC/RMI here?

**Comment by Oberon00** [comment]
Related: #27

**Comment by SergeyKanzhelev** [comment]
@Oberon00 yes. This is from the excel spreadshit that @danielkhan shared before

**Comment by jmacd** [comment]
Closing this as stale, probably addressed in https://github.com/open-telemetry/opentelemetry-specification/pull/349

**Comment by Oberon00** [comment]
Even though the networking attributes added in #349 are certainly useful for remoting, I don't think they cover everything. E.g. I'd assume there should be attributes for the service and method name.

**Comment by arminru** [comment]
@SergeyKanzhelev @jmacd
I agree with @Oberon00 that this should be reopened and addressed. It would make sense to add the RPC method and flavor/system to the semantic conventions.

**Comment by jmacd** [comment]
I believe this was fixed by #349 and #386.

**Comment by Oberon00** [comment]
I think the last comment by @arminru still applies, we only have conventions for the very narrow special case of grpc. But probably this issue could be tracked with #27, if we give that one a better name.
