### ISSUE TITLE
CloudEvents: relax requirement levels

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#2600]
While CloudEvents spec requires most of the required attributes to be present on the event, not all of them may be required for telemetry purposes. 

`event_source` + `event_id` would uniquely identify the event, so let's keep them `required`.

For others requirement level could potentially be relaxed:
~~- [`event_subject` is optional](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#subject) per CloudEvents spec~~
- `event_spec_version` is probably mostly static and rarely changed. Making it `recommended` or `optional` seem to be more reasonable
- `event_type`: can it become `recommended`? 

[Recommended](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#recommended) attributes would still be populated by default unless there are strong reasons not to. Instrumentation may provide a way to disable them explicitly.

**Comment by lmolkova** [comment]
@joaopgrassi what do you think? I can do the change if you're ok with it.

**Comment by joaopgrassi** [comment]
Hi @lmolkova !

> event_source + event_id would uniquely identify the event, so let's keep them required.

👍 

About the others: 

- `event_subject` is optional as you said, so no changes here
- `event_type` as `recommended`: Sounds reasonable to me!
- `event_spec_version`: I'm divided a bit on this one. It's probably static as you said, but if there's cross-systems communications and they use different versions, by using `optional` we might miss the info that could help in observing things? So maybe `recommended` is better?

**Comment by lmolkova** [comment]
> event_subject is optional as you said, so no changes here

ah, right! sorry for the confusion

> event_spec_version

`recommended sounds reasonable and I think we can suggest skipping if default (`1.0`)

**Comment by joaopgrassi** [comment]
>suggest skipping if default (1.0`)

Not sure, do we really need to skip it? What is your concern in always having it? My rationale is it's an required attribute in the CloudEvents spec, so making it optinal/not always present here might be odd since it goes against what it's in their spec. I know we are not the same thing but.. maybe keeping it consistent is a good deal? And if people _really_ think it's unecessary, using `recommended` they can turn it off, right?

**Comment by joaopgrassi** [comment]
Sounds good then! Would like to submit the PR? Or should I do it? Either is fine with me. Feel free to ping me for the approval if you open :)

**Comment by lmolkova** [comment]
@joaopgrassi Thanks! I'll send the PR, I want to merge https://github.com/open-telemetry/opentelemetry-specification/pull/2594 first so I can use new requirement levels here properly.
