### ISSUE TITLE
Context Interaction Section Makes it Seem like Context Should Be Mutable

### ISSUE THREAD

**Issue by Grunet** [open-telemetry/opentelemetry-specification#2624]
**What are you trying to achieve?**
Was trying to implement the 2nd part of [the Context Interaction](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#context-interaction) section for PHP.

What did you expect to see?
I expected the spec to call out that a new context would need to be created with the span that was being passed.

Instead, the spec seemed to imply that the current context should be mutated with the span that was being passed.

**Additional context.**
Here is that spec language that threw me off

"Set the currently active span to the implicit context. This is equivalent to getting the implicit context, then inserting the Span to the context."

Link to [this section of the doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#context-interaction)

Fwiw I'm not sure how the spec words similar discussions of context mutability elsewhere, so if this is just being consistent with that (and me being ignorant of those parts) that seems totally fair to me (and this can be closed)

**Comment by joaopgrassi** [comment]
I think the [context](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/README.md#overview) can help clarify things. There it's clearly stated that the `context` is immutable and its write operations must create a new context. 

That document is linked in this portion of [the Context Interaction](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md?rgh-link-date=2022-06-20T22%3A40%3A12Z#context-interaction)

> If the language has support for implicitly propagated Context (see [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/README.md#optional-global-operations))

But I agree that the way it's phrased there may lead to interpretation that it's mutable. Perhaps we could add note stating this fact and linking to the context document?

**Comment by Grunet** [comment]
Yeah I think I was mostly second-guessing myself cause of the language even though I'd heard that before + all the existing PHP code seemed to be avoiding mutability.

It took me looking at a few other language implementations to convince myself mutability wasn't a thing.

Maybe wording something like this would avoid others from running into this?

"Set the currently active span into a new context, and make that the implicit context. This is equivalent to getting the implicit context, copying it, and then inserting the Span into the copy."

But at the end of the day it's nbd, so if it's not worth the trouble to adjust the language fine by me to close this.

**Comment by rbailey7210** [comment]
Thank you for reporting this. It seems like a good PR. Would you be willing to write it up?
