### ISSUE TITLE
There is no ForceFlush on the MetricReader

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-specification#2632]
[There is no `ForceFlush` method on the `MetricReader`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader-operations). Nevertheless, [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush) it says it must be invoked:

> ForceFlush MUST invoke ForceFlush on all registered MetricReader and Push Metric Exporter instances.

**Comment by reyang** [comment]
I think the intention is "ForceFlush MUST invoke Collect/ForceFlush on all registered MetricReader and Push Metric Exporter instances."

**Comment by jsuereth** [comment]
Was looking at this, it appears it actually *is* handled in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader):

> MetricReader is an SDK implementation object that provides the common configurable aspects of the OpenTelemetry Metrics SDK and determines the following capabilities:
> - Collecting metrics from the SDK on demand.
> - Handling the [ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush) and [Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown) signals from the SDK.

and 

> The SDK SHOULD provide a way to allow MetricReader to respond to [MeterProvider.ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush) and [MeterProvider.Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown). [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#sdk) authors MAY decide the language idiomatic approach, for example, as OnForceFlush and OnShutdown callback functions.
