### ISSUE TITLE
Incompatibility between the W3C Baggage spec version used in the Resource spec and the Baggage spec

### ISSUE THREAD

**Issue by lgfa29** [open-telemetry/opentelemetry-specification#2639]
**What are you trying to achieve?**

When defining the value for the `OTEL_RESOURCE_ATTRIBUTES` environment variable, the [resource specification links to](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable) the version [`fdc7a5c4f4a31ba2a36717541055e551c2b032e4`](https://github.com/w3c/baggage/blob/fdc7a5c4f4a31ba2a36717541055e551c2b032e4/baggage/HTTP_HEADER_FORMAT.md) of the W3C Baggage format, while the OpenTelemetry Baggage specification [doesn't specify any particular version](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#propagation).

This causes an incompatibly in how baggage values are handled between the two specifications because the latest W3C Baggage spec defines that:

> Any characters outside of the baggage-octet range of characters MUST be percent-encoded.
https://w3c.github.io/baggage/#value

But the version used by the Resource spec doesn't have this requirement.

The effect of this difference is that, when using a library that follows the OpenTelemetry Baggage spec (such as [`go.opentelemetry.io/otel/baggage`](https://pkg.go.dev/go.opentelemetry.io/otel/baggage)) to generate the value for the `OTEL_RESOURCE_ATTRIBUTES` environment variable, the baggage values will be encoded by the library but not decoded by the SDK.

**Additional context.**

@MrAlias noticed this difference in https://github.com/open-telemetry/opentelemetry-go/pull/2963.

**Comment by jsuereth** [comment]
It looks like we should take the time to update our specification to account for changes in the Baggage specification.   Feel free to open a PR to address this.

**Comment by lgfa29** [comment]
Thank you @jsuereth, I opened #2670 to update the spec :slightly_smiling_face:
