### ISSUE TITLE
Allow logs to be mutated in LogProcessor

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#2647]
There's currently an inconsistency between [LogProcessor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/logging-library-sdk.md#logprocessor) and the [SpanProcessor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor) concept it was modeled after which severely limits the usefulness of LogProcessor. 

Multiple SpanProcessors can be registered on a TracerProvider, and each is invoked in the order they are registered. [SpanProcessor#onStart](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onstart) accepts a read/write span object. This read/write span is different than the readable span accepted by SpanProcessor#OnEnd, which is again typically different from a third SpanData interface accepted by SpanExporter, as described [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#additional-span-interfaces). The effect of this design is that multiple processors can be registered, with upstream processors having the opportunity to enrich the read/write span with additional data extracted from context, baggage, etc, before a downstream processor batches up as SpanData and exports. 

In contrast, log processors have a single Emit method, which accepts a readable [LogData](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/logging-library-sdk.md#logdata) interface. LogData is the same interface accepted by [LogExporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/logging-library-sdk.md#logexporter). LogData is necessarily read only, since LogExporters need to have stable data to export. However, by having LogProcessor accept the same read only interface, there's effectively nothing useful you can do by registering multiple LogProcessors, because each processor has no ability to change the data.

I think its pretty clear that the intention of the Logging Library SDK spec is to mirror the trace SDK spec when possible. I propose that we fix this inconsistency as follows:

- Introduce a new read/write log interface to mirror read/write span. Read/write log should have a method to obtain a LogData.
- Change LogProcessor#emit to accept read/write log instead of LogData.
- The effect is that multiple LogProcessors can be registered with a LogEmitterProvider. When a log is emitted, the emit(read/write log) method of each LogProcessor is called in order of registration. Upstream LogProcessors can enrich the log with data extracted from context, baggage, etc. Downstream LogProcessor(s) (typically the last) can batch up LogData and export via LogExporter#export(List<LogData>).

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-logs-approvers please review.

**Comment by zenmoto** [comment]
Being able to redact logs is a strong requirement for a lot of organizations and mutable logs would allow that to happen.

**Comment by jack-berg** [comment]
> Being able to redact logs is a strong requirement for a lot of organizations and mutable logs would allow that to happen.

This could also happen in the `LogExporter` interface. In the trace world, processors can only add data and update a more limited number of fields. There is no ability to remove attributes. To the extent that its possible, I think we should try to stay consistent with tracing. In this case, that means read/write log would have the ability to add data and update a limited number of fields, but perhaps not filter attributes.
