### ISSUE TITLE
SpanExporter interface inconsistency

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#2652]
In the specification for [`SpanExporter`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-exporter), the Interface Definition paragraph states:

> ### Interface Definition
> 
> The exporter must support two functions: **Export** and **Shutdown**.

However there are 3 functions listed: **Export**, **Shutdown**, and **ForceFlush**.

Is `ForceFlush` a required method on the SpanExporter interface?

### Additional Context

While implementing the metrics SDK `InMemoryMetricsExporter`, there was some debate in the JS SIG on if we should have a separate `reset` method or if the `forceFlush` method should reset the in-memory state of the exporter. While deciding what to do, we looked at the `InMemorySpanExporter` for inspiration and found that it was using `reset` but did not even implement `ForceFlush`. Since `ForceFlush` is specified, we realized we had to implement it and an issue (https://github.com/open-telemetry/opentelemetry-js/issues/3067) was created to track this. While working on the issue we became confused by the wording of the spec and are unsure if the spec is trying to **require** ForceFlush or specifying behavior for an optional interface. All behaviors of ForceFlush are specified as SHOULD requirements.

**Comment by yurishkuro** [comment]
@dyladan since you already did some leg work studying this portion of the spec and some implementations, do you have a concrete proposal how to address this?

**Comment by dyladan** [comment]
Yeah I think that is most likely the original intent
