### ISSUE TITLE
Make `OTEL_EXPERIMENTAL_SDK_ENABLED` stable

### ISSUE THREAD

**Issue by brunobat** [open-telemetry/opentelemetry-specification#2667]
We would like `otel.experimental.sdk.enabled` java system property to become permanent and be called `otel.sdk.enabled`.
This would be the env. variable: OTEL_EXPERIMENTAL_SDK_ENABLED

This request comes from the Eclipse MicroProfile (MP) Tracing group, which uses the OTel Tracing part. 
We aim to use the properties already defined by OTel, however we cannot perform a stable release requiring the use of experimental features. 
We currently see no reason to not make permanent the behaviour controlled by this property.

This issue was originally discussed here: https://github.com/open-telemetry/opentelemetry-java/issues/4589

**Comment by arminru** [comment]
Hi @brunobat!
This flag/setting is actually not defined at all in the OTel spec and I think that's why the OTel Java SIG uses an `experimental` prefix. If this setting could be relevant for other SDKs as well, it could be proposed in a PR here in the spec to add it as a new feature.

**Comment by tigrannajaryan** [comment]
@brunobat What's the semantics of this attribute?

**Comment by brunobat** [comment]
This explains the experimental...
This attribute is true by default and enables normal execution of OpenTelemetry.
When set to false it will disable tracing, metrics, logs and propagators by setting providers to NOOP.
The current Java implementation can be seen here: https://github.com/open-telemetry/opentelemetry-java/blob/7d80a998460154c93a5a2bcc5eb1fdc90318aab2/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java#L314

**Comment by tigrannajaryan** [comment]
Hmm, I may have misunderstood. I thought this is a semantic convention for an attribute, which doesn't seem to be the case. Is this a name for an environment variable? Please provide the full context and more details.

**Comment by brunobat** [comment]
This is an environment variable allowing or disabling the operation OpenTelementry SDK.
Documented here: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#disabling-opentelemetrysdk

**Comment by tigrannajaryan** [comment]
The current env variables are defined here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md

The convention is to use underscores as word separators.

The proposed new env variable does make sense to me. I can see how one would want to disable the entire SDK (our default is to start sending to localhost OTLP which may not be desirable).

**Comment by tigrannajaryan** [comment]
Triaged as `triaged-accepted`. I am going to unassigned from myself. If anyone wants to take this and do a PR I can reassign.

@open-telemetry/specs-approvers I triaged as `triaged-accepted`, feel free to comment if you think otherwise.

**Comment by jkwatson** [comment]
FYI, as written, `otel.experimental.sdk.enabled` is actually a system property, not an env var. The corresponding env var is `OTEL_EXPERIMENTAL_SDK_ENABLED`.

**Comment by brunobat** [comment]
Correct @jkwatson. Updated my 1st comment. 
@tigrannajaryan I can create a PR to the spec, if it's ok.

**Comment by brunobat** [comment]
This issue now depends on #2729
