### ISSUE TITLE
Should the SDK define a default view ?

### ISSUE THREAD

**Issue by vmarchaud** [open-telemetry/opentelemetry-specification#2671]
**What are you trying to achieve?**

I'm testing out of the latest version of the metrics SDK/API for JS by integrating it in my production setup, i just want to collect a simple latency metrics:
```ts
const histogram = meter.createHistogram('workflow_latency', {
  unit: 'ms'
})
```
I know that i should use a view to define this, but actually the default histogram aggregation (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation) is fine to me for this particular metric. However the SDK currently don't register any view by default, letting me (end user) needing to add a view:
```ts
meter.addView({
    aggregation: new DefaultAggregation()
})
// or simply since default aggregation will be choosen anyway by default
meter.addView({})
```

**What did you expect to see?**

I'm might just be missing something some part of the spec but I'm wondering if we could not recommend SDK to directly add a view with the default aggregation so that end user have explicit boundaries set for their histograms by default ?

**Comment by jsuereth** [comment]
@legendecas @dyladan Can you confirm if this is indeed just a limitation of the current JS implementation or a deficiency in the specification?

**Comment by legendecas** [comment]
I'd find this is an instrumentation-related question.

> However the SDK currently don't register any view by default

This doesn't sound correct to me. There is a [default view](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-sdk-metrics-base/src/view/ViewRegistry.ts#L24) defined in JavaScript SDK per the spec requirements. Users don't need to define any views if they find the default behavior is sufficient for them.

> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view
> 
> If the MeterProvider has no View registered, take the Instrument and apply the default Aggregation on the basis of instrument kind according to the [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader) instance's aggregation property.

**Comment by vmarchaud** [comment]
> If the MeterProvider has no View registered, take the Instrument and apply the default Aggregation on the basis of instrument kind according to the [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md?rgh-link-date=2022-07-19T17%3A57%3A51Z#metricreader) instance's aggregation property.

I saw after my issue that there was a default view in the sdk but i went back on the spec and still didnt find this specific, thanks for pointing it and sorry for the wasted time loss here :/
