### ISSUE TITLE
Add process.parent_pid to semantic convention constants

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-specification#2689]
**What are you trying to achieve?**

Add process.parent_pid to semantic convention constants

**Additional context.**

This issue is related to allowing receiver/hostmetricsreciever reporting parent process ID (PID).  

collector contrib issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12290
collector contrib PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12637

CC: @dmitryax

**Comment by reinasalondra** [comment]
#2620 #2691 
Duplicate of #
