### ISSUE TITLE
Setting multiple Span attributes

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#269]
Currently we allow setting one attribute to a `Span` at a time, but what about adding many of them in a single step? This pattern seems to be happening often (for example, for a `Span` representing an http request):

```python
            span.set_attribute("http.method", method.upper())
            span.set_attribute("http.url", url)
```

If this sounds fine, I'd like to create a PR - this doesn't seem controversial enough to require an entire OTEPS iteration.

**Comment by Oberon00** [comment]
I think that doesn't even need a spec, as this is language specific. For example, the best Java could do is returning the Span itself from setAttribute to allow chaining.

**Comment by carlosalberto** [comment]
@Oberon00 

Yeah, I remember seeing that pattern being advised in the past ;) However, every time you set an attribute, you have to acquire a lock and do a few checks, so we could save some cycles by having that in a single call.

**Comment by z1c0** [comment]
The point about locking is a valid concern (at least for Java and .NET).
I also vote in favor of a batching mechanism here.

**Comment by Oberon00** [comment]
My point that this is highly language-specific still stands. I think at best, the spec can add a sentence like "It is recommended that language implementations provide a way to set multiple attributes at once, e.g. with a SetAttributes(Map<string, Value>) function."

**Comment by carlosalberto** [comment]
A recommendation (or an optional operation) sounds good enough for me. I will create a PR then with the aforementioned changes ;)

**Comment by SergeyKanzhelev** [comment]
@carlosalberto may it be using the same LabelSet object as proposed in Metrics API draft? This will also improve perf when we need to report a metric from the same place - the same set of labels can be re-used

**Comment by Oberon00** [comment]
It's not obvious how LabelSets would apply to Spans. I assume you mean defining a LabelSet like `LabelSet httpAttributeKeys = new LabelSet("http.url", "http.method") and then use it like `span.setLabelledAttributes("GET", "http://...")`? That actually sounds like a nice idea!

**Comment by carlosalberto** [comment]
Same feeling as @Oberon00 

Any opinion on this @bogdandrutu ?

**Comment by SergeyKanzhelev** [comment]
yes, and than you will be able to re-use it for metrics avoiding yet another allocation

**Comment by Oberon00** [comment]
I don't think you would want to use the same label set for both metrics and spans. Or if you want that, maybe that's a case for the correlation context?

**Comment by jmacd** [comment]
This appears to be unnecessary for the specification. Langauges can already support sugar for setting multiple span attributes.
