### ISSUE TITLE
At git tag of v.1.12.0, the 1.12.0 schema file doesn't have the 1.12.0 attribute renames

### ISSUE THREAD

**Issue by jship** [open-telemetry/opentelemetry-specification#2717]
**What are you trying to achieve?**

When checking out the repo at git tag `v1.12.0`, I expected to see the `span`-related attribute renames in `schemas/1.12.0`. `main` at the time of this writing has the following renames listed in `schemas/1.12.0`:

https://github.com/open-telemetry/opentelemetry-specification/blob/11f1fde1c9f5d123bda2ed13b6f94e49f748d740/schemas/1.12.0#L4-L10

Tag `v1.12.0` (at the time of this writing, tag is at commit ae87c81640d18763d4df51b898c55c49e2370328) has an empty `1.12.0` section:

https://github.com/open-telemetry/opentelemetry-specification/blob/ae87c81640d18763d4df51b898c55c49e2370328/schemas/1.12.0#L4

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by arminru** [comment]
Good catch, thank you @jship!
The changes specified for v1.12 here were actually only applied on main and will be released in v1.13 within the upcoming days. They were introduced in https://github.com/open-telemetry/opentelemetry-specification/pull/2614.
We'll fix the schema file before publishing the release.
