### ISSUE TITLE
Remove or rewrite api-tracing section "Runtimes with multiple deployments/applications"

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#272]
> Runtimes that support multiple deployments or applications might need to provide a different Tracer instance to each deployment. 

Not clear what "multiple deployments" means here, could give some examples.

The following references to Provider and ServiceLoader seem out of place completely, unrelated to the API, which is now TracerFactory per OTEP 16.

**Comment by bogdandrutu** [comment]
We should not have a component anymore.

**Comment by carlosalberto** [comment]
I'm a little bit confused here (we should have reviewed this issue long time ago ;) )

@yurishkuro could you comment if this is still an issue, and if it is, could you elaborate?

**Comment by yurishkuro** [comment]
This exact wording has been removed, can close this.
