### ISSUE TITLE
Definition of Boolean for Environment Variables

### ISSUE THREAD

**Issue by brunobat** [open-telemetry/opentelemetry-specification#2729]
Some environment variables need the definition of a Boolean type.
Example: OTEL_SDK_DISABLED
This discussion started in this PR: #2679 
Because this is an important enough subject, we decided to spinoff the definition into this new issue. 
The original discussion was proposing the following definition: 

### Boolean value
Any value that represents a boolean MUST interpret the case-insensitive string `"true"`, meaning `"True"` or `"TRUE"` are also accepted as `"true"`.
An SDK MAY extend this definition and define additional values that are interpreted as true.
Any value not explicitly defined here or by the SDK as a true value, including unset and empty values, MUST be interpreted as false.

Also, a recommendation on the naming of environment variable attributes should also be agreed in order to align boolean property names.

**Comment by dyladan** [comment]
>Any value that represents a boolean MUST interpret the case-insensitive string "true", meaning "True" or "TRUE" are also accepted as "true".

I would suggest this be the _only_ acceptable true value, and not just one possible option.

>An SDK MAY extend this definition and define additional values that are interpreted as true.

I already brought it up in the other PR but I think this is a point of potential confusion. Having SDKs from different languages behave differently makes it more difficult to configure polyglot environments.

>Also, a recommendation on the naming of environment variable attributes should also be agreed in order to align boolean property names.

The only recommendation I have here is that all environment variables should be named such that `false` is the expected default behavior. Example would be to prefer `OTEL_SDK_DISABLED` over `OTEL_SDK_ENABLED`.

**Comment by carlosalberto** [comment]
> I already brought it up in the other PR but I think this is a point of potential confusion. Having SDKs from different languages behave differently makes it more difficult to configure polyglot environments.

I agree with this. I'm wondering whether, for the sake of completeness, any SIG has ever supported a different value for booleans at all?

**Comment by jmacd** [comment]
I support a single boolean value "true", with emphasis on @dyladan's point: **all environment variables should be named such that false is the expected default behavior**.

**Comment by dyladan** [comment]
We may even want to go so far as to log a warning when a boolean env var has any value that isn't `""`, `"true"`, or `"false"` (case insensitivity tbd)

**Comment by ocelotl** [comment]
Should we also define the type for all the rest of environment variables? I mean, should we specify "this variable is to be interpreted as an int, this one as a string, this one as a float, this one as a bool", etc.?

**Comment by carlosalberto** [comment]
@ocelotl We probably should, but let's stick to defining the boolean case first :D

**Comment by brunobat** [comment]
Created the PR including the feedback on this issue.
