### ISSUE TITLE
Project Tracking: Profiling

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2731]
[Profiling Workgroup will complete the description below].

### Description

Describe the goals, objectives, and requirements for the project. This include the motivations for starting the project now, as opposed to later.

### Project Board

Once approved by TC, a project should be managed using a GitHub project board. This project board should be pre-populated with issues that cover all known deliverables, organized by timeline milestones.

A [Technical Committee](https://github.com/open-telemetry/community/blob/main/community-members.md#technical-committee) (TC) member associated with the project can create the board, along with a new project-specific GitHub label to automatically associate issues and PRs with the project. The project lead and all other relevant project members should have edit access to the board.

Once created, please link to the project board here.

### Deliverables

A description of what this project is planning to deliver, or is in the process of delivering. This includes all OTEPs and their associated prototypes.

In general, OTEPs are not accepted unless they come with working prototypes available to review in at least two languages. Please discuss these requirements with a TC member before submitting an OTEP.

### Staffing / Help Wanted

Who is currently planning to work on the project? If a project requires specialized domain expertise, please list it here. If a project is missing a critical mass of people in order to begin work, please clarify.

#### Required staffing

Projects cannot be started until they the following participants have been identified:
* Every project needs a project lead, who is willing to bottom line the project and address any issues which are not handled by other project members.
* At least two sponsoring TC members. TC sponsors are dedicated to attending meetings, reviewing proposals, and in general being aware of the state of the project and it's technical details. TC sponsors guide the project through the spec process, keep the tracking issue up to date, and help to ensure that relevant community members provide input at the appropriate times.
* Engineers willing to write prototypes in at least two languages (if relevant to project). Languages should be fairly different from each other (for example: Java and Python).
* Maintainers or approvers from those languages committed to reviewing the prototypes.

### Meeting Times

Once a project is started, the working group should meet regularly for discussion. These meeting times should be posted on the OpenTelemetry public calendar.

### Timeline

What is the expected timeline the project will aim to adhere to, and what resources and deliverables will be needed for each portion of the timeline? If the project has not been started, please describe this timeline in relative terms (one month in, two weeks later, etc). If a project has started, please include actual dates.

### Labels

The tracking issue should be properly labeled to indicate what parts of the specification it is focused on.

### Linked Issues and PRs

All PRs, Issues, and OTEPs related to the project should link back to the tracking issue, so that they can be easily found.

**Comment by Rperry2174** [comment]
I am now an [official member](https://github.com/open-telemetry/community/issues/1133) @tigrannajaryan

**Comment by austinlparker** [comment]
@mtwo will be the GC Facilitator for this project.

This is a new responsibility the GC is adopting to better support cross-functional projects in OpenTelemetry. There will be a document in the community repo in the future detailing these responsibilities -- in general, the facilitator will help ensure that required TC sponsors are available and assigned, and will be a resource for project maintainers.

**Comment by mtwo** [comment]
SGTM, I'll start attending the weekly meetings
________________________________

**Comment by austinlparker** [comment]
Closing as this is a SIG now.
