### ISSUE TITLE
Question: naming conventions, prefer . (dot) or _ (underscore)?

### ISSUE THREAD

**Issue by jviau** [open-telemetry/opentelemetry-specification#2740]
I have a question regarding naming conventions. When looking at FaaS metrics sematic conventions [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/faas-metrics.md#faas-invocations), I see the names uses a mix of `.` and `_`. So my question is:

Why was a name like `faas.invoke_duration` chosen over `faas.invoke.duration`?

As I add my own metrics, I want to make sure I understand this rationale and know when to use `.` vs `_` for names.

**Comment by jviau** [comment]
I also just noticed it is not consistent: RPC spec follows `rpc.server.duration` [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md#rpc-server).

So I am guessing this is just in progress?

**Comment by reyang** [comment]
The minimum bar is captured by the API spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-naming-rule.

My general observation is that folks intend to use `.` to group things in hierarchical way, and `_` is used to improve readability if a particular term has multiple words.

Some additional things to consider while exporting the data to specific backends, e.g. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#otlp-metric-points-to-prometheus

**Comment by reyang** [comment]
> I also just noticed it is not consistent: RPC spec follows `rpc.server.duration` [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md#rpc-server).
> 
> So I am guessing this is just in progress?

Yes, if you scroll to the very top of this spec, you can see it marked as Experimental instead of Stable, which means it could have breaking changes or even get removed or redesigned in the near future.

**Comment by Oberon00** [comment]
Probably it makes sense to apply the same logic as with attribute naming: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md

**Comment by jviau** [comment]
Thank you for the links and explanation.

@reyang - regarding `rpc.server.duration` vs `faas.invoke_duration`. Both are marked as "Experimental". Would you know, or be able to guess, which direction OTel will settle on? (I personally am more of a fan of `rpc.server.duration`).

**Comment by joaopgrassi** [comment]
My interpretation is also as @reyang mentioned. A dot `.` is for grouping or "namespacing" things together. Your example of `rpc.server.`, it has a dot after server, because server is the grouping of multiple metrics like `duration` and `requests_per_rpc`. 

For the `faas.invoke_duration` I'd imagine that it was chosen like that because `invoke` alone is not a "grouping". If there was more sub-metrics under `invoke` then it would make sense to use what you propose, `faas.invoke.duration`. But since it's just a concept on itself, then it's under the top-level `faas`. An underscore then is how to combine multiple words.

**Comment by Oberon00** [comment]
For FaaS, "invoked" is not really suitable as a namespace IMHO. "faas.invoked.request.size" = the size of the invoked request? That does not make sense. Maybe it would be better to rename this to `faas.invocation.request.size`, `faas.invocation.peer.provider`, etc.
