### ISSUE TITLE
Default boundaries in explicit buckets histograms are not optmized for Latency

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-specification#2759]
**What are you trying to achieve?**

The defaults for the explicit bucket histogram have the first boundary in the interval `(-inf,0]`. Since Explicit Bucket histograms only support non-negative values, this first boundary can only record the 0 value, which is not very useful in practice given that the defaults of the Explicit Bucket histogram are supposed to record latency values. 

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation

The default values also limits the last boundary to `(1000, inf)`, which limits the calculation of percentiles to 1s, which is not very good for latency.

https://github.com/prometheus/prometheus/blob/main/promql/quantile.go#L75

**What did you expect to see?**

I expect the defaults to have something more useful for recording latency values.

```
[5, 10, 25, 50, 75, 100, 250, 500, 1000, 10000]
```

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by jmacd** [comment]
This looks like a mistake in the spec. I was under the impression that the defaults exactly matched prometheus, meaning the last finite boundary at 10.0 (floating) or 10000 (integer).

**Comment by reyang** [comment]
Maybe it should be `[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 1000, 2500, 5000, 7500, 10000 ]` @jmacd? Is there an official place where the Prometheus or OpenMetrics defaults are documented?
