### ISSUE TITLE
New feature: Non Periodic MetricReader for OpenTelemetry metrics

### ISSUE THREAD

**Issue by howardyoo** [open-telemetry/opentelemetry-specification#2767]
# Problem Statement #
OpenTelemetry specification currently have implementation of MetricReader called [PeriodicExportingMetricReader](https://github.com/open-telemetry/opentelemetry-python/blob/0db9d19a0128b9ec84867bc016e5ec915b4fb6ac/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py#L403) or [PeriodicMetricReader](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/PeriodicMetricReader.java) , etc.. which triggers metric `export` based on set time interval.

However, there is a case where the triggering of the export of metrics should be controlled outside of the SDK, without having to define any set intervals within the SDK. If that is the case, the SDK should provide a different type of MetricReader such that it should not export on its own, but rather provide a function to `flush` out its readings to exporters explicitly.

# Proposal #
I would like to propose a simple new metric reader.
This new metric reader should be named as `NonPeriodicMetricReader` or `NonPeriodicExportingMetricReader` depending on the SDK's convention. It will be very similar to how `PeriodicMetricReader` or `PeriodicExportingMetricReader` operates, except for that it will not get triggered in timed intervals. Rather, it will wait until the method `flush` is called by some external code, which will then read and export the metric data on that call.

**Comment by reyang** [comment]
@howardyoo isn't this just a PeriodicMetricReader with interval = Infinite?

**Comment by jmacd** [comment]
In the OTel-Go repository we've occasionally used the term "ManualReader" for this construct, which I see as a minimal implementation of the abstract-base class that we know as "Reader".

**Comment by reyang** [comment]
@jmacd same in .NET https://github.com/open-telemetry/opentelemetry-dotnet/blob/0447871d483cc94612a99c4e62a952e5c5638e83/src/OpenTelemetry/Metrics/MetricReader.cs#L29.

**Comment by howardyoo** [comment]
> @howardyoo isn't this just a PeriodicMetricReader with interval = Infinite?

Not exactly. In that case, PeriodicMetricReader will spawn a thread that sleeps for infinity. Maybe it may not be a huge deal, but it is not an elegant approach. It might make sense if we added some logic for PeriodicMetricReader to accept value `0` as the interval and stop running any sleep (and skip the thread being spawned), which can be alternative approach to this issue.

**Comment by reyang** [comment]
> > @howardyoo isn't this just a PeriodicMetricReader with interval = Infinite?
> 
> Not exactly. In that case, PeriodicMetricReader will spawn a thread that sleeps for infinity. Maybe it may not be a huge deal, but it is not an elegant approach.

The spec doesn't say anything about thread/sleep, it seems to be the implementation detail. Specific implementation can decide to do something "elegant" if they find it valuable.

**Comment by howardyoo** [comment]
> > > @howardyoo isn't this just a PeriodicMetricReader with interval = Infinite?
> > 
> > 
> > Not exactly. In that case, PeriodicMetricReader will spawn a thread that sleeps for infinity. Maybe it may not be a huge deal, but it is not an elegant approach.
> 
> The spec doesn't say anything about thread/sleep, it seems to be the implementation detail. Specific implementation can decide to do something "elegant" if they find it valuable.

Yes, that's correct. I have created this issue in `opentelemetry-specification`, because I saw in the contributing document that issue should be made here, in case the issue covers multiple language implementations. Since the interval reporter was implemented in more than two languages (java, python, and c#), I thought creating it here made sense.

The reason why the threads were brought up was to describe the reason why I (and the team) did not believe using PeriodicMetricReader did not suite the need perfectly, and we couldn't find any alternatives.

I believing having two options: either interval, or non-interval, for users of OpenTelemetry to emit metrics, should be fundamental to the way to produce metrics.

**Comment by jmacd** [comment]
@howardyoo I believe that the SDKs should provide you the facility you're looking for. If they're not, my understanding is that you will be provided a MetricReader base class to extend.  For me, it's these words:

```
MetricReader is an SDK implementation object that provides the common configurable aspects of the OpenTelemetry Metrics SDK and determines the following capabilities:

Collecting metrics from the SDK on demand.
Handling the [ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush) and [Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown) signals from the SDK.
```

So my understanding is that MetricReader == an on-demand reader, which is what you're asking for, which is generally speaking how most SDKs implement a Prometheus exporter (i.e., by reading on demand). Although I am not familiar with every OTel SDK, I am fairly sure this is already possible in .NET and Java SDKs. If you still believe it is not possible to create a manual MetricReader, please re-open issues in the specific repository where you need this functionality clarified.

Here is where the new Golang metrics SDK implements this functionality: https://github.com/open-telemetry/opentelemetry-go/blob/new_sdk/main/sdk/metric/manual_reader.go#L46

**Comment by reyang** [comment]
Here is my suggestion: have a concrete issue on a specific implementation, explain what's the problem, why is it a problem, discuss with the project maintainers and see if they agree or not, see if it should be an implementation detail or it needs to be covered by the spec. If it turned out to be something that should be covered by the spec, reopen this issue and link to the issue/discussion on the specific implementation.

**Comment by howardyoo** [comment]
> Here is my suggestion: have a concrete issue on a specific implementation, explain what's the problem, why is it a problem, discuss with the project maintainers and see if they agree or not, see if it should be an implementation detail or it needs to be covered by the spec. If it turned out to be something that should be covered by the spec, reopen this issue and link to the issue/discussion on the specific implementation.

Thanks for the suggestion. It all makes sense, that this isn't actually a specification, or more on the implementation details. I will go ahead to create issue on the repo, which may be more appropriate.

**Comment by howardyoo** [comment]
> @howardyoo I believe that the SDKs should provide you the facility you're looking for. If they're not, my understanding is that you will be provided a MetricReader base class to extend. For me, it's these words:
> 
> ```
> MetricReader is an SDK implementation object that provides the common configurable aspects of the OpenTelemetry Metrics SDK and determines the following capabilities:
> 
> Collecting metrics from the SDK on demand.
> Handling the [ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush) and [Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown) signals from the SDK.
> ```
> 
> So my understanding is that MetricReader == an on-demand reader, which is what you're asking for, which is generally speaking how most SDKs implement a Prometheus exporter (i.e., by reading on demand). Although I am not familiar with every OTel SDK, I am fairly sure this is already possible in .NET and Java SDKs. If you still believe it is not possible to create a manual MetricReader, please re-open issues in the specific repository where you need this functionality clarified.
> 
> Here is where the new Golang metrics SDK implements this functionality: https://github.com/open-telemetry/opentelemetry-go/blob/new_sdk/main/sdk/metric/manual_reader.go#L46

Yes, the MetricReader is there, but in python language, it has some abstract functions that needs to be implemented, so we definitely need to extend it as base class and implement those, FYI.
