### ISSUE TITLE
Tracestate arg should be mentioned in sampler's required args section

### ISSUE THREAD

**Issue by jship** [open-telemetry/opentelemetry-specification#2783]
**What are you trying to achieve?**

Improving the spec's clarity around tracing sampler's required inputs. In #988, verbiage was added to the Return Value section of `ShouldSample`:

> A Tracestate that will be associated with the Span through the new SpanContext. If the sampler returns an empty Tracestate here, the Tracestate will be cleared, so samplers SHOULD normally return the passed-in Tracestate if they do not intend to change it.

A Tracestate parameter is not listed as a required argument in the Required Argument ssection above the Return Value section though.

What did you expect to see?

If sampler's are intended to return a passed-in Tracestate if they do not intend to change it, then a Tracestate argument should likely be listed under Required Arguments.

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by jship** [comment]
On further reading of the spec, perhaps the intent is that the passed-in `Tracestate` arg is covered via the first item under Required Arguments:

> [Context](https://opentelemetry.io/docs/reference/specification/context/) with parent `Span`. The Span’s SpanContext may be invalid to indicate a root span.

If the parent `SpanContext` is valid, then the `Tracestate` from that `SpanContext` could be passed along. Otherwise, a fresh `Tracestate` could be passed along. Is that the spec's intention?

**Comment by Oberon00** [comment]
The tracecontext is available from the Context, via the path Context -> Span -> SpanContext -> tracestate.
