### ISSUE TITLE
Unable to add a histogram which emits decimal values

### ISSUE THREAD

**Issue by SanaChopra** [open-telemetry/opentelemetry-specification#2793]
We want to create a histogram which emits decimal values but we are not able to get it to emit decimals.
What did you expect to see?
Histogram emitting decimal values.
Sample histogram definition used:
`public static readonly Histogram<decimal> QuantityHistogram = ServiceMeter.CreateHistogram<decimal>(MetricConstants.Quantity);
`

**Comment by reyang** [comment]
Is this specific to some programming languages or it's a spec issue?

**Comment by rbailey7210** [comment]
Please open this issue with the relevant language github repo. We don't plan to support decimal in OTLP.
