### ISSUE TITLE
 OpenTelemetry trace error occurred: cannot send span to the batch span processor because the channel is full

### ISSUE THREAD

**Issue by mohit61** [open-telemetry/opentelemetry-specification#2804]
**What are you trying to achieve?**
- I enabled datadog tracing in my project which uses [apollo router](https://github.com/apollographql/router) written in Rust.

What did you expect to see?
- I am getting this error when the load on the server increases, I have 15G memory on my machine, and as the load increases, the memory quickly reaches 5G and I start getting errors
` OpenTelemetry trace error occurred: cannot send span to the batch span processor because the channel is full`
- Below is the memory and cpu usage when the errors start occuring on my 8 core machine
<img width="627" alt="cpu_memory_router" src="https://user-images.githubusercontent.com/32329331/190353265-1e6f6d49-7301-48e3-ae04-708f30f21baa.png">

**Comment by reyang** [comment]
@mohit61 this doesn't seem to be a specification issue. Please file the issue on the repo which corresponds to the component that you are using.
