### ISSUE TITLE
Add process page fault metrics

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-specification#2809]
**What are you trying to achieve?**

I want to add process [page fault](https://en.wikipedia.org/wiki/Page_fault) metrics to the semantic conventions. Here are the specific metrics I have in mind, relative to how Linux reports them:

- The number of major ("hard") page faults that the process has made
  - This is reported in `/proc/[pid]/stat` Linux file, described as `majflt` field in the [man page](http://man.he.net/man5/proc)
- The number of minor ("soft") page faults that the process has made
  - This is reported in `/proc/[pid]/stat` Linux file, described as `minflt` field in the [man page](http://man.he.net/man5/proc)
- The number of major ("hard") page faults that the process's waited-for children have made
  - This is reported in `/proc/[pid]/stat` Linux file, described as `cmajflt` field in the [man page](http://man.he.net/man5/proc)
- The number of minor ("soft") page faults that the process's waited-for children have made
  - This is reported in `/proc/[pid]/stat` Linux file, described as `cminflt` field in the [man page](http://man.he.net/man5/proc)

I propose the following names for the metrics:

- `process.memory.page_faults` with the attribute `type` of either `hard` or `soft`
- `process.memory.child_page_faults` with the attribute `type` of either `hard` or `soft`

**Additional context**

I have read through the discussions on putting information in metric names vs. attributes (#2589 , #2726). I considered various options for the metric names and attributes, including putting the `type` in the metric name and putting the `child` into an attribute (couldn't find a good name for this attribute). Please let me know if you have any thoughts on this.

Related issue to add these metrics in `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

**Comment by astencel-sumo** [comment]
Oops only now have I noticed that there's a similar convention already in place in the `system` namespace. The metric name is `system.paging.faults` with the `type` attribute of `major` or `minor`.

Should this proposal be changed to propose `process.paging.faults`? What about the child page faults?

**Comment by astencel-sumo** [comment]
I'll take no comments as good news and will prepare a pull request to add `system.paging.faults` metric with a `type` attribute of `major` or `minor`. I will not add the child faults for now.

**Comment by rbailey7210** [comment]
Pleased pause for now, we are considering refactoring existing metrics semantic conventions. Please come to ongoing discussions. See https://github.com/open-telemetry/opentelemetry-specification/issues/2753.
