### ISSUE TITLE
Log correlation attributes names and values

### ISSUE THREAD

**Issue by hectorhdzg** [open-telemetry/opentelemetry-specification#281]
I was not able to find any spec for this, are we planning to have something similar to OpenCensus?

https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/LogCorrelation.md

**Comment by SergeyKanzhelev** [comment]
let's try to get to it in v0.3.

**Comment by c24t** [comment]
@SergeyKanzhelev I'm interested in this too, but I don't think we can reasonably get it into the 0.3 release.

**Comment by SergeyKanzhelev** [comment]
@c24t I was thinking we can scope it to the names of attributes we recommend to use to indicate correlation

**Comment by jmacd** [comment]
This appears to call for semantic conventions to express SpanContext in an external system. Looking for a PR on this.

**Comment by jteng** [comment]
+1

**Comment by dyladan** [comment]
This seems very related to https://github.com/open-telemetry/opentelemetry-specification/issues/398

**Comment by tigrannajaryan** [comment]
We have [traceid](https://github.com/open-telemetry/opentelemetry-proto/blob/a17f202fdae65e828ac29fb663b5bc5b64b13290/opentelemetry/proto/logs/v1/logs.proto#L125)/spanid in the OTLP proto and the spec defines [how to record them](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md#trace-context-in-legacy-formats) in text logs.

I think this can be considered resolved. Closing. Feel free to file a new issue if more is needed.
