### ISSUE TITLE
Add `process.memory.utilization` metric

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-specification#2811]
**What are you trying to achieve?**

I want to add a `process.memory.utilization` metric to the semantic conventions. The value would be the amount of physical memory used by the process (`process.memory.usage` according to the convention) divided by the total amount of memory available on the host.

**Additional context.**

Here's a related proposal to add this metric in `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

A similar metric already exists in the `system` namespace: `system.memory.utilization`. It has the `state` attribute, which of course the `process.memory.utilization` metric would not have.

I'm a bit worried that the total memory available on the host does not have a name in the convention, but that would be a separate issue.

**Comment by reyang** [comment]
These all make sense, but please pause for now, we are considering refactoring existing semantic conventions. Please come to ongoing discussions. See https://github.com/open-telemetry/opentelemetry-specification/issues/2753.

**Comment by astencel-sumo** [comment]
Closing this issue as the pull request has been rejected https://github.com/open-telemetry/opentelemetry-specification/pull/2844.
