### ISSUE TITLE
Add `process.disk.operations` metric

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-specification#2812]
**What are you trying to achieve?**

I want to add a `process.disk.operations` metric to the semantic conventions, akin to the existing `system.disk.operations` metric. The metric should have a `direction` attribute with the value of `read` or `write`.

The description of the metric is "The number of disk operations performed by the process". 

**Additional context.**

Here's a related proposal to add this metric in `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

**Comment by reyang** [comment]
These all make sense, but please pause for now, we are considering refactoring existing semantic conventions. Please come to ongoing discussions. See https://github.com/open-telemetry/opentelemetry-specification/issues/2753.

**Comment by astencel-sumo** [comment]
Closing this issue, as the pull request for the semantic convention has been rejected https://github.com/open-telemetry/opentelemetry-specification/pull/2845.
