### ISSUE TITLE
Add SamplingHint in API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#282]
See https://github.com/open-telemetry/oteps/blob/accb510feeecb10c886ef38c44c58639c5c7ea48/text/0006-sampling.md

**Comment by SergeyKanzhelev** [comment]
Text from the original PR with the comment that it needs to be expanded with the scenarios and use cases.

#### SamplingHint

This is a new concept added in the OpenTelemetry API that allows API users to suggest sampling hints
to the implementation of the API:

* DO_NOT_RECORD
  * Suggest to not record any data for this Span. (RecordEvents = false and SampledFlag = false).
* RECORD
  * Suggest to record data for this Span but not propagating the sampled flag in TraceFlags 
  (RecordEvents = true and SampledFlag = false).
* RECORD_AND_PROPAGATE
  * Suggest to record data for this Span and propagate the sampled flag in TraceFlags
  (RecordEvents = true and SampledFlag = true).

The default option for the span creation is to not have any suggestion (or suggestion is not
specified). This can be implemented by using null as the default option or any language specific
mechanism to achieve the same result.

Implementations are not required to respect the SamplingHint, but are encouraged to do so.
Implementations that do not apply any sampling mechanism in the client library are free to
completely ignore this.

**Comment by jmacd** [comment]
Closing this according to the OTEP here: https://github.com/open-telemetry/oteps/pull/79
