### ISSUE TITLE
Should `http.server.active_requests` have a `net.host.port` attribute?

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-specification#2822]
**What are you trying to achieve?**

Currently, the `http.server.active_requests` metric only includes the `net.host.name` attribute; for some reason `net.host.port` was skipped there. Should we fix that discrepancy?

**Additional context.**

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attributes

**Comment by rbailey7210** [comment]
Please discuss in upcoming spec sig meeting
