### ISSUE TITLE
Add `process.signals_pending` metric to semantic conventions

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-specification#2826]
**What are you trying to achieve?**

I want to add a `process.signals_pending` metric to the semantic conventions.

**Additional context.**

If I understand correctly, this metric is useful to see if/when a process stopped accepting signals, which can be useful in investigating issues.

Telegraf exposes this metric in its [procstat](https://github.com/influxdata/telegraf/blob/v1.24.1/plugins/inputs/procstat/README.md) input plugin. Adding a semantic convention for this metric in OT should make migration from Telegraf to OpenTelemetry easier.

Related proposal to add this metric in the `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

**Comment by reyang** [comment]
These all make sense, but please pause for now, we are considering refactoring existing semantic conventions. Please come to ongoing discussions. See https://github.com/open-telemetry/opentelemetry-specification/issues/2753.
