### ISSUE TITLE
Clarify that the JSON log example is the spec is NOT the OTLP JSON format

### ISSUE THREAD

**Issue by wdengw** [open-telemetry/opentelemetry-specification#2856]
**What are you trying to achieve?**
Find out what is the right JSON format. 

What did you expect to see?
The right format to follow

**Additional context.**
OTel log format document and its java implementation has a mismatch.  In the document,  [JSON log example](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#example-log-records), resource attributes are added directly under Resource tag.
```
{
  ...
  "Resource": {
    "service.name": "donut_shop",
    "service.version": "2.0.0",
    "k8s.pod.uid": "1138528c-c36e-11e9-a1a7-42010a800198",
  },
  ...
} 
```
In OpenTelemetry-java the [implementation](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java), Resource class holds Attributes, and resource attributes are added into Attributes.  Will the output be
```
{
  ...
  "Resource": {
    "Attributes": {
      "service.name": "donut_shop",
      "service.version": "2.0.0",
      "k8s.pod.uid": "1138528c-c36e-11e9-a1a7-42010a800198",
    },
  },
  ...
} 
```

Which is the correct one to follow?

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by reyang** [comment]
@wdengw during the triage meeting, we consider this as a Java implementation issue, we need your help to follow up with the Java SIG. Meanwhile, we agree that the spec should have some clarification that the current JSON example is not the OTLP JSON format, we'll repurpose this issue and make updates to the spec. Assigning to @tigrannajaryan.

**Comment by jack-berg** [comment]
The java implementation of OTLP JSON is correct. This [test](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging-otlp/src/test/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingLogRecordExporterTest.java#L96-L160) demonstrates the OTLP JSON encoded of a complete payload. The referenced example in [Example Log Records](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#example-log-records) is NOT valid OTLP JSON format; however, it also doesn't claim to be OTLP JSON so I fail to see the problem.

**Comment by wdengw** [comment]
@reyang and @jack-berg, Thank you for the clarification!  To summarize,  the JSON log format example in the Spec is the correct one to follow as for application Log data.

**Comment by tigrannajaryan** [comment]
>To summarize, the JSON log format example in the Spec is the correct one to follow as for application Log data.

No. The example in the Spec is just an arbitrary example of JSON logs. It is a standard that needs to be followed. If you are looking for a standard format then OTLP/JSON is one such standard (not yet finalized): https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#json-protobuf-encoding

**Comment by reyang** [comment]
I've updated the issue title to avoid confusion.

We should follow in the PR by either clarifying that the example is NOT OTLP JSON, or change the example to OTLP JSON, or avoiding JSON at all (e.g. maybe YAML?).

**Comment by wdengw** [comment]
Change the title changed my original question.  Please answer the following questions
1.  Is the JSON log format example a valid example that is compliant with the OpenTelemetry Logs Data Format?  
2. Is the OTLP JSON output compliant with the OpenTelemetry Logs Data Format?  
3. What is this teams recommendation for writing JSON application logs to file which is Logs Data Format compliant,  one of the above two, or both?

**Comment by tigrannajaryan** [comment]
>What is this teams recommendation for writing JSON application logs to file which is Logs Data Format compliant

Use this: https://github.com/open-telemetry/opentelemetry-specification/blob/main/experimental/serialization/json.md but note it is experimental and can change.

**Comment by tigrannajaryan** [comment]
> * Is the JSON log format example a valid example that is compliant with the OpenTelemetry Logs Data Format?
> * Is the OTLP JSON output compliant with the OpenTelemetry Logs Data Format?

There is no such thing as OpenTelemetry Logs Data Format. We have OpenTelemetry Log Data Model and we have OTLP Logs Format which is an implementation of OpenTelemetry Log Data Model.

**Comment by wdengw** [comment]
@tigrannajaryan  Deleting the JSON log example clarified it.  Case closed.
