### ISSUE TITLE
Drop support for jaeger-thrift

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-specification#2859]
I'd like to propose that we drop support for the `jaeger-thrift` exporter. The [upstream repo](https://github.com/jaegertracing/jaeger-client-java) has been marked deprecated and they're actively encouraging folks to use OpenTelemetry instead. They're also refusing security patches. 

Furthermore, [the docs indicate](https://www.jaegertracing.io/docs/1.35/features/) 

```
Since v1.35, the Jaeger backend can receive trace data from the OpenTelemetry 
SDKs in their native OpenTelemetry Protocol (OTLP)].
```

Overall, I think this just makes sense and reduces an overwhelming number of choices for end users.
Also curious what @pavolloffay thinks.

**Comment by yurishkuro** [comment]
I'm not opposed to this overall. But to add to what @anuraaga said (https://github.com/open-telemetry/opentelemetry-specification/issues/2859#issuecomment-1273513761):
  * Should there be some public announcement that this deprecation is happening?
  * I think there needs to be a waiting period after the deprecation announcement before the functionality can be removed from the SDKs, to give organizations time to migrate (changing an exporter in 1000s of services is not a one-day affair)
  * it is not clear to me that simply dropping the UDP exporter is the right move. UDP export mode has its own problems, but also has some benefits (e.g. the SDK does not spam your logs in dev simply because no receiver is running). Overall I think UDP mode has more problems than benefits, but it would be good to do some survey of the end users on how they feel about not having the UDP-to-local-agent export path.

**Comment by breedx-splk** [comment]
@yurishkuro thanks for chiming in on this and being open about it. 👍🏻 

> * Should there be some public announcement that this deprecation is happening?

Probably? Did you have something specific in mind and/or can we ask the comms SIG for help?

> * I think there needs to be a waiting period after the deprecation announcement before the functionality can be removed from the SDKs, to give organizations time to migrate (changing an exporter in 1000s of services is not a one-day affair)

Yeah, totally agree. I guess another thing to keep in mind is that users would only be facing this exporter change if/when they were upgrading an sdk or agent, which is maybe also not a 1 day affair. Point being, they're already in there making changes. 

I guess the next question is then how long? 6 months? 12 months? Something else?

> * it is not clear to me that simply dropping the UDP exporter is the right move. UDP export mode has its own problems, but also has some benefits (e.g. the SDK does not spam your logs in dev simply because no receiver is running). Overall I think UDP mode has more problems than benefits, but it would be good to do some survey of the end users on how they feel about not having the UDP-to-local-agent export path.

Interesting...I hadn't anticipated log spamming to be a consideration here! 🙃 I wonder what a good mechanism to surveying users could be. It looks like the slack channel #jaeger has a lot of users. As with any sizable install base, there  are likely to be folks who are reluctant to change for various reasons and we'll have to balance that.

**Comment by yurishkuro** [comment]
I would go with a tweet from OTEL account pointing to this issue and asking for votes / comments. Then we can decide about the waiting period. Changing from sending data to a local host agent to exporting to a remote gRPC collector could be a significant architectural change that requires establishing some discovery/lb mechanism that the orgs may not have needed before.

**Comment by breedx-splk** [comment]
@yurishkuro I have met with the comms sig and now I am working on a blog post and will engage in #jaeger channel in CNCF slack as well. 

One clarification: This issue was initially scoped to only the thrift based jaeger exporters, but #2858 is really about deprecating all flavors. Since that has a larger scope, I will point users there for comments/feedback.

**Comment by anuraaga** [comment]
> significant architectural change that requires establishing some discovery/lb mechanism that the orgs may not have needed before.

Happen to still be seeing this issue so wanted to add one small point - the idea was to replace a jaeger agent with a sidecar OTel collector I think, not a remote one. Switching to remote would be a huge architectural change and probably blocked in a lot of cases, but I think we were hoping that swapping the local host agent binary would not have anywhere near as much friction. Just in case this helps with the comms @breedx-splk

**Comment by breedx-splk** [comment]
> > significant architectural change that requires establishing some discovery/lb mechanism that the orgs may not have needed before.
> 
> Happen to still be seeing this issue so wanted to add one small point - the idea was to replace a jaeger agent with a sidecar OTel collector I think, not a remote one. Switching to remote would be a huge architectural change and probably blocked in a lot of cases, but I think we were hoping that swapping the local host agent binary would not have anywhere near as much friction. Just in case this helps with the comms @breedx-splk

Thanks @anuraaga, I appreciate that. I don't have a strong sense of how widespread the implementation of the two architectural models are (jaeger agent vs. "direct" ingest). If users currently leverage a Jaeger agent, I suppose they will probably need to switch to a collector....that is, unless the agent also supports OTLP (it sounds like it doesn't?)

**Comment by yurishkuro** [comment]
> This issue was initially scoped to only the thrift based jaeger exporters, but https://github.com/open-telemetry/opentelemetry-specification/pull/2858 is really about deprecating all flavors.

@breedx-splk I still find it acceptable to deprecate all flavors, we just need to give people more time to migrate away.

**Comment by breedx-splk** [comment]
@yurishkuro On the [otel blog post PR](https://github.com/open-telemetry/opentelemetry.io/pull/1892), @austinlparker brought up a good question about cross-posting with the Jaeger blog. Any chance you can assist with that? 🙏🏻

**Comment by yurishkuro** [comment]
@breedx-splk any responses to the survey?

**Comment by pavolloffay** [comment]
What exactly is this issue deprecating? Is the intent to deprecate all APIs using `jaeger.thrift`? 

There are a couple of APIs using `jaeger.thrift`: 

* collector 14268/http
* agent 6832/udp
* agent 6832/udp


If that is the case I would maybe prefer to move these APIs to a separate receiver.

**Comment by yurishkuro** [comment]
I believe the intent is to only deprecate support in the SDK, not in the backend.

**Comment by yurishkuro** [comment]
What is the downside of keeping support through 2023 and perhaps move to contrib in 2024? Are the implementations of Jaeger exporters cloned into OTEL repos or use original Jaeger repos as dependencies?

**Comment by breedx-splk** [comment]
> What is the downside of keeping support through 2023 and perhaps move to contrib in 2024? Are the implementations of Jaeger exporters cloned into OTEL repos or use original Jaeger repos as dependencies?

I can't speak for every language, but at least Java uses the original jaeger client repos as a dependency. I think that's true of at least a couple other languages too. The downside then is that when a vuln is discovered, the instrumentation will have no simple remediation and will need to reimplement the client functionality.

This is a major motivation for the deprecation in the first place.

**Comment by breedx-splk** [comment]
Would love to get consensus on a number of months so that we can take #2858 out of draft. What do folks think? 

I'm still leaning toward 6 months deprecation, with spec removal in July 2023.

Seems like a reasonable amount of time...and even after that , teams can choose not to upgrade.

**Comment by breedx-splk** [comment]
Ok,  #2858 is ready for review.

**Comment by EricBuist** [comment]
This is a bad idea as Jaeger all in one doesn't accept GRPC at all. I'm searching since more than half an hour, cannot find any accurate information about the GRPC port. Seems for GRPC, we have to deploy the full Jaeger stack as separate services (collector, reporter, and so on), but there is no simple examples of this. Everything has to be read through large documents and guessed through. Yes, removing support for Thrift in favor of GRPC is a good idea, but Jaeger should do the same before.

**Comment by yurishkuro** [comment]
@EricBuist yes, all-in-one accepts OTLP, and the docs show how to start it to do that:

https://www.jaegertracing.io/docs/1.42/getting-started/#all-in-one
