### ISSUE TITLE
Please publish the 1.13.0 schema

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#2865]
**What are you trying to achieve?**
Usage of the 1.13.0 semantic convention schema file.

What did you expect to see?
The file in the advertised location (https://opentelemetry.io/schemas/1.13.0)

**Comment by tigrannajaryan** [comment]
The fix should be in the website repo: https://github.com/open-telemetry/opentelemetry.io/issues/1846

**Comment by tigrannajaryan** [comment]
We need a check in our release procedure to block the release if the schema file is not published.

**Comment by tigrannajaryan** [comment]
Added checks to prevent this in the future: https://github.com/open-telemetry/opentelemetry-specification/pull/2868

**Comment by tigrannajaryan** [comment]
Schema files for 1.13 and 1.14 are now published. https://github.com/open-telemetry/opentelemetry.io/issues/1846 is fixed.

https://github.com/open-telemetry/opentelemetry-specification/pull/2868 is still open for review, will ensure this doesn't happen again.
