### ISSUE TITLE
Add more semantic convention attributes of Apache RocketMQ

### ISSUE THREAD

**Issue by aaron-ai** [open-telemetry/opentelemetry-specification#2880]
Add more semantics convention attributes of Apache RocketMQ.

1. `messaging.rocketmq.message_group`: message group is essential for FIFO message. Messages that belong to the same message group are always processed one by one within the same consumer group.
2. `messaging.rocketmq.delivery_timestamp`: the timestamp in milliseconds that the delay message is expected to be delivered to consumer.
3. `messaging.rocketmq.delay_time_level`: the delay time level for delay message, which determines the message delay time.

**Comment by aaron-ai** [comment]
Thanks for reply. We use either of `delay_time_level` and `delivery_timestamp` to determine the specified delay time for delay message, it depends on the version of RocketMQ client.

* `delay_time_level`: as you saw in https://rocketmq.apache.org/docs/4.x/producer/07message3, 
* `delivery_timestamp`: https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerDelayMessageExample.java

**Comment by carlosalberto** [comment]
@jsuereth I was wondering whether you have any opinion regarding adding general **trace** attributes (special attention to the timestamp value).
