### ISSUE TITLE
Define what changes are "breaking" for Trace telemetry stability

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#2883]
Similar to #2864 we need to define / propose what changes to Traces are considered breaking and what are allowable.

**Comment by carlosalberto** [comment]
Marking as "needs more info" - looking forward to the discussion regarding this item.

**Comment by jsuereth** [comment]
@tedsuo FYI - we're hoping to discuss this on Monday in the WG.

For reference here's two things I put together for metrics:

1. An investigation into aspects of the protocol, with some thoughts on what can/needs to be enforced: [sheet]
2. A verbal description of "what's in", "what's out" for stability guarantees and a few things we should discuss. (https://docs.google.com/spreadsheets/d/1KB8kcW-hJa7dJ8oKeoCuS6TQAXW4Qs7216y-WkR96NI/edit#gid=0) [doc](https://docs.google.com/document/d/1Nvcf1wio7nDUVcrXxVUN_f8MNmcs0OzVAZLvlth1lYY/edit#heading=h.e71xzqqz0b5t)

I'm about to do something similar for Logging.   Let me know if you need any help fleshing this out.
