### ISSUE TITLE
JSON File format example contradicts the text

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2887]
The [text says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/experimental/serialization/json.md#telemetry-data-requirements):
>Files must contain exactly one type of data: traces, metrics, or logs.

Then the [last example](https://github.com/open-telemetry/opentelemetry-specification/blob/main/experimental/serialization/json.md#examples) in the file has all 3 data types.

So, which is it? One type only or can mix?

**Comment by tigrannajaryan** [comment]
@atoulme assigning this to you since you authored the format.

**Comment by tigrannajaryan** [comment]
FYI @reyang @aabmass @Aneurysm9 @carlosalberto @djaglowski since you reviewed [the PR](https://github.com/open-telemetry/opentelemetry-specification/pull/2235).

**Comment by atoulme** [comment]
Thanks! I'll delete the example.

**Comment by atoulme** [comment]
I have opened a PR to follow up, thanks Tigran! https://github.com/open-telemetry/opentelemetry-specification/pull/2889
