### ISSUE TITLE
Track JVM memory usage after GC

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#2900]
In talking about JVM gc metrics, the java SIG has concluded that it would be valuable to track memory usage after garbage collection. Discussion available [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6362#issuecomment-1262848079).

The JVM provides access to determine the memory usage by different memory pools as of the most recent garbage collection event. By recording this, we can analyze it over time to see if there is:

 1. Evidence of memory leak. The post-gc usage would grow over time, since garbage collection would be unable to reclaim certain chunks of memory.
 2. Evidence that the memory pool size is inadequate. If the post-gc heap is high as a percentage of the total memory limit, you may way to allocate more memory to avoid overly frequent garbage collections.

**Comment by carlosalberto** [comment]
Overall it seems good and doesn't seem polemical, specially as we already have Java GC metrics (and these metrics are process-specific).

cc @jsuereth just FYI ;)
