### ISSUE TITLE
Track JVM gc time

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#2902]
Related to #2900.

Its valuable to track the time spent in garbage collection, how many garbage collection events took place, and the type of garbage collection events that took place (different garbage collector implementations have various phases which happen concurrently or in parallel). 

I proposed [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6362) that we use a histogram to collect this data:

| Name | Description | Unit | Unit UCUM | Instrument Type | Value Type | Attribute Key | Attribute Values  |
|---|---|---|---|---|---|---|---|
| process.runtime.jvm.gc.time | Time spent performing JVM garbage collection actions | Milliseconds | `ms`                                      | Histogram | Int64 | gc | Name of garbage collector |
| | | | | | | action | The collection action performed |

Recording gc event times as a histogram would enable the following analysis:
* Total time spent on garbage collection.
* Count of garbage collection events.
* Min, max, average, percentiles of garbage collection time events.
* The attributes allow you to characterize gc time by the types of events. With a little prior knowledge you can analyze all gc spent concurrently vs stop the world.

**Comment by carlosalberto** [comment]
Similarly to #2900, it makes sense given the existing Java GC metrics - I'm mostly curious about the "action" attribute as it's not well explained in the Java docs themselves, so your examples help (and even more examples would be appreciated).

**Comment by carlosalberto** [comment]
cc @jsuereth @jmacd
