### ISSUE TITLE
Add additional attributes for mongo DB spans

### ISSUE THREAD

**Issue by avzis** [open-telemetry/opentelemetry-specification#2907]
**What are you trying to achieve?**
I want to add to the database semantic conventions additional attributes for mongo DB spans.
The value of adding these fields is to help users get more information from the traces which would allow for easier troubleshooting.

The additional attributes that I want to add are related to operations done on the DB.

For an `INSERT` request: 
Save the value `document` which holds the value that is inserted.

For a `DELETE` request:
Save the value `criteria` which holds the filter criteria that is used to find the item to delete.

For an `UPDATE` request:
Save the values of `filter` and `update` which holds the filter criteria that is used to identify the item that we want to update, and the value to update.

**Comment by carlosalberto** [comment]
Hey @avzis - was wondering why `db.statement` is not used here? e.g. it is used for Redis commands such as `SET mykey "WuValue"` which _seems_ to have all the information you need.

**Comment by avzis** [comment]
Hey @carlosalberto, thank you for the response.
I tried to check the `db.statement` value, and from what i've seen it only saves the request name, and not the values.

Now the question is wether we should update the implementation of `db.statement`, or add a new db value? (for example `db.request_attributes` or something like that)

**Comment by carlosalberto** [comment]
I think this is indeed a bug in the instrumentation itself, as [the Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes) requires that `db.statement` does report the full statement:

```
SELECT * FROM wuser_table; SET mykey "WuValue"
```

**Comment by avzis** [comment]
opened a bug:
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1462
