### ISSUE TITLE
Add `db.redis.arguments` for requests and responses

### ISSUE THREAD

**Issue by haddasbronfman** [open-telemetry/opentelemetry-specification#2908]
**What are you trying to achieve?**

I want to add to the database semantic conventions additional attributes for `redis` spans.
The value of adding the metadata is to help users get more information from the traces which could allow for easier troubleshooting.

I propose the following names for the attribute:
- `db.redis.arguments`

**Comment by carlosalberto** [comment]
Hey @haddasbronfman - would you mind mentioning examples/use cases?

**Comment by tigrannajaryan** [comment]
Does this need to be Redis specific? I see for example a very similar request that is more generic: https://cloud-native.slack.com/archives/C01N7PP1THC/p1668007675690439

**Comment by haddasbronfman** [comment]
I wrote it specifically for Redis, but you're right there might be more databases that this attribute can fit to.
How can we proceed from here?

**Comment by tigrannajaryan** [comment]
> I wrote it specifically for Redis, but you're right there might be more databases that this attribute can fit to. How can we proceed from here?

See if you can generalize it and make applicable to other database and name appropriately (e.g. `db.statement_arguments` or similar).

**Comment by carlosalberto** [comment]
So in theory we should be reporting the arguments as part of the statement, as per [the Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes):

```
SELECT * FROM wuser_table; SET mykey "WuValue"
```

So we should poke the instrumentation authors. @haddasbronfman what instrumentation/language/version are you using?

**Comment by haddasbronfman** [comment]
@carlosalberto you're right. I opened this issue: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1294
to handle this.
We can close this one.
