### ISSUE TITLE
Move towards Log API/SDK stabilization

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-specification#2911]
[OpenTelemetry's vision for supporting logs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#introduction) is clear:

> We embrace existing logging solutions and make sure OpenTelemetry works nicely with existing logging libraries, log collection and processing solutions.

A number of prototypes exist demonstrating the Log API's utility in implementing [log appenders](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/api.md#how-to-create-log4j-style-appender) for existing logging libraries.

* [Java Log4j2 appender](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library)
* [Java Logback appender](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library)
* [.NET Serilog appender](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Extensions.Serilog)
* Possibly others in Python or Javascript maybe? (share links if anyone knows)

We have also received end user feedback suggesting a demand for a stable release of these log appenders.

I believe the API and SDK components as specified are nearly sufficient and we should consider making them stable. The `LoggerProvider` and `Logger` APIs are necessary for developing log appenders. The SDK components (i.e., log processors, exporters, etc) nicely mirrors the trace specification.

Below I've attempted to capture a list of remaining issues. If folks have additional things to add, please share!

## Remaining issues

- [x] Java: Log API and SDK prototype implementation
- [x] Java: [Log4J appender](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library) implementation. An example using Java agent [is here](https://github.com/open-telemetry/opentelemetry-java-docs/tree/main/javaagent).
- [x] .Net: Log API and SDK prototype implementation
- [x] .Net: [Serilog appender](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Extensions.Serilog) implementation. .Net maintainers to link to example also showing trace context injection
- [x] Python: Log API and SDK prototype implementation
- [x] Python: logging handler implementation and [usage example](https://github.com/open-telemetry/opentelemetry-python/blob/main/docs/examples/logs/example.py).
- [x] https://github.com/open-telemetry/opentelemetry-python/issues/3134
- [x] #2941
- [x] #3002
- [x] #3031
- [x] #2927
- [x] #2969
- [x] #2861
- [x] Settle on a name (Logs API vs SPI vs Bride API, etc)
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3247
- [x] #3022
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3115
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3268
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3301
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3386
- [x] https://github.com/open-telemetry/opentelemetry-specification/pull/3397
- [x] https://github.com/open-telemetry/opentelemetry-specification/pull/3385
- [x] https://github.com/open-telemetry/opentelemetry-specification/issues/3394
- [x] https://github.com/open-telemetry/opentelemetry-specification/pull/3383
- [x] Mark Logs [API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/api.md) and [SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md) stable

**Comment by tigrannajaryan** [comment]
One thing we need to decide now: in a hypothetical scenario where we eventually come to a decision that we don't need an "Events API" at all would the current structure of LoggerProvider/Logger API work fine on its own even if we delete everything related to "Events" from the API?

We may decide to support "Events" using some other form of helpers instead of making it a sibling API of Logger so we need to be prepared for such deletion.

**Comment by alanwest** [comment]
> I think this means the entire Get a Logger needs to be marked experimental for now. At least in some languages adding/removing a parameter is a breaking change.

Marking `Get a Logger` stable is core to the premise of decoupling logs from events. I think this topic warrants a separate issue/PR, but my initial thought is the `event_domain` parameter just needs to be removed from the `Get a Logger` API. That would effectively decouple the `Get a Logger` API from anything event related. A new experimental API would need to be proposed in support of events.

> would the current structure of LoggerProvider/Logger API work fine on its own even if we delete everything related to "Events" from the API?

Yes, this is my hope.

> I think there is less pressure for stabilizing the SDK spec. Do need to decide on for example batching processor defaults right now? Seems like a low priority decision.

Ideally we move towards stabilizing the SDK to the extent possible as well. A stable SDK spec allows for a stable release of OTLP log exporters.

**Comment by jack-berg** [comment]
I've opened #2955 to discuss issue 5 in this list:

> Consider the mutability of the ReadWriteLogRecord interface: Is everything mutable or only some things?

**Comment by tigrannajaryan** [comment]
@jack-berg I added 2 items for Java in the **Remaining issues** in the description. Please check the boxes when/if it is done.

**Comment by tigrannajaryan** [comment]
@open-telemetry/dotnet-maintainers I added 2 items for .Net in the **Remaining issues** in the description. Please check the boxes when/if it is done.

**Comment by tigrannajaryan** [comment]
@open-telemetry/python-maintainers I added 2 items for Python in the **Remaining issues** in the description. Please check the boxes when/if it is done.

**Comment by jack-berg** [comment]
> Java maintainers to link to example also showing trace context injection

@tigrannajaryan could you elaborate on this? There's [test code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.17/library/src/test/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/OpenTelemetryAppenderConfigTest.java#L103-L115) that validates trace context inject. Not sure if you're looking for something different / more specific.

**Comment by tigrannajaryan** [comment]
> > Java maintainers to link to example also showing trace context injection
> 
> @tigrannajaryan could you elaborate on this? There's [test code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.17/library/src/test/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/OpenTelemetryAppenderConfigTest.java#L103-L115) that validates trace context inject. Not sure if you're looking for something different / more specific.

@jack-berg ideally we would want a minimal standalone example, but test code is probably also good enough. I just wanted to make sure we clearly demonstrate that trace context injection works with the current design. Please feel free to tick the boxes for Java.

**Comment by srikanthccv** [comment]
> Python: logging handler implementation. Python maintainers to link to example also showing trace context injection

Handler implementation [here](https://github.com/open-telemetry/opentelemetry-python/blob/a99cc21152ef1a129fc28ec539e73cbe4ffa8e75/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py#L318). Where do we link the example? Here is an example that demonstrates https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples/logs

> Python: Log API and SDK prototype implementation

[API](https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-api/src/opentelemetry/_logs) and [SDK](https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs) prototype implementation. The above example shows how to use API + SDK + Handler + Exporter to glue everything up to send data to the collector 

I think both items can be ticked.

**Comment by srikanthccv** [comment]
> @open-telemetry/python-maintainers I added 2 items for Python in the **Remaining issues** in the description. Please check the boxes when/if it is done.

@tigrannajaryan I can't tick the boxes because of a permissions issue. Please tick the two items for Python.

**Comment by tigrannajaryan** [comment]
> > @open-telemetry/python-maintainers I added 2 items for Python in the **Remaining issues** in the description. Please check the boxes when/if it is done.
> 
> @tigrannajaryan I can't tick the boxes because of a permissions issue. Please tick the two items for Python.

I have just tried the latest Python example and can confirm it works as expected, including the trace context in logs. I marked Python items, done. Thanks.

**Comment by jack-berg** [comment]
> ideally we would want a minimal standalone example, but test code is probably also good enough. I just wanted to make sure we clearly demonstrate that trace context injection works with the current design. 

There's a working example [here](https://github.com/open-telemetry/opentelemetry-java-docs/tree/main/javaagent) as well that uses the same instrumentation, but applies it automatically using the java agent. It exports spans/metrics/logs to a collector running with the logging exporter. If you exercise the the app by invoking its endpoint, it will log a message in the context of a span, which you can see in the logs of the collector. 

I'm going to check the boxes because while its always good to have more examples, I think the [docs](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library) and the test code are a good enough description.

**Comment by tigrannajaryan** [comment]
>.Net: Log API and SDK prototype implementation
> .Net: [Serilog appender](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Extensions.Serilog) implementation. .Net maintainers to link to example also showing trace context injection

@alanwest can you please tell if any of these are done? If not I will create separate issues for tracking.

**Comment by tigrannajaryan** [comment]
@CodeBlanch please ping me after you check .net prototype so that I can mark the relevant checkboxes.

**Comment by CodeBlanch** [comment]
@tigrannajaryan Here is the .NET prototype (main-logs branch):

* API: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Api/Logs
* SDK: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry/Logs
* Serilog appender: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Extensions.Serilog
* EventSource appender: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main-logs/src/OpenTelemetry.Extensions.EventSource

I did those a while back before the split out of the Events API but as far as LoggerProvider/Logger/LogRecord it is all there and the spec met our needs for the prototype 👍

**Comment by reyang** [comment]
A critical performance requirement from OpenTelemetry C++: need a way to tell if certain log level is enabled for a given logger.
   For example: `logger.IsEnabled(LogLevel.Info)`

This might be done at a higher level API, the problem is that there is **no** such well-established API in C++. It is unclear what does "Log API stable" mean for OpenTelemetry C++ if the SIG couldn't ship something that is usable. In addition, some higher level APIs would need the lower level support indicating whether certain log streams should be enabled or not.

@alanwest @tigrannajaryan @open-telemetry/cpp-maintainers

**Comment by alanwest** [comment]
> This might be done at a higher level API, the problem is that there is no such well-established API in C++.

I believe should be done at a higher level API. There has been much debate over whether OTel should design a logging API for end-user consumption. Maintainers from other language SIGs have been adamant that OpenTelemetry should not be in the business of designing yet another logging API as many languages already have well-established logging frameworks. 

#2966 was meant to clarify that the purpose of the API OpenTelemetry offers is to support the integration of existing logging frameworks with OpenTelemetry via log appenders.

I'm not knowledgeable of the C++ ecosystem, but I assume there's history behind why C++ does not have an established logging framework. Should this be a discussion for the C++ language community not the OpenTelemetry community? Alternatively, maybe the C++ OpenTelemetry community could take a stab at designing the logging framework their community has lacked - if they were to do this, there's no reason it needs to be governed by the OpenTelemetry specification.

**Comment by tigrannajaryan** [comment]
> A critical performance requirement from OpenTelemetry C++: need a way to tell if certain log level is enabled for a given logger. For example: `logger.IsEnabled(LogLevel.Info)`
> 
> This might be done at a higher level API, the problem is that there is **no** such well-established API in C++. It is unclear what does "Log API stable" mean for OpenTelemetry C++ if the SIG couldn't ship something that is usable. In addition, some higher level APIs would need the lower level support indicating whether certain log streams should be enabled or not.
> 
> @alanwest @tigrannajaryan @open-telemetry/cpp-maintainers

I think this is a very good question. I will open a separate issue to discuss this.

**Comment by trask** [comment]
> Alternatively, maybe the C++ OpenTelemetry community could take a stab at designing the logging framework their community has lacked - if they were to do this, there's no reason it needs to be governed by the OpenTelemetry specification.

This sounds very reasonable since we haven't heard of any other languages needing/wanting this.

**Comment by lalitb** [comment]
From performance prospective in C++, it is important to check the log-level at the Logging API level before we prepare the log-data, and invoke the actual logging. The application owner should be able to configure the log-level as the SDK configuration, which could be validated in the library using (say)`Logger.IsEnabled(loglevel)` before invoking logging. The configured log-level may also be used in LogProcessor/Exporter for another layer of filtering. Even with a logging framework, it is important to have this validation done at logging backend API.

**Comment by reyang** [comment]
> I believe should be done at a higher level API. There has been much debate over whether OTel should design a logging API for end-user consumption. Maintainers from other language SIGs have been adamant that OpenTelemetry should not be in the business of designing yet another logging API as many languages already have well-established logging frameworks.
> 
> #2966 was meant to clarify that the purpose of the API OpenTelemetry offers is to support the integration of existing logging frameworks with OpenTelemetry via log appenders.
> 
> I'm not knowledgeable of the C++ ecosystem, but I assume there's history behind why C++ does not have an established logging framework. Should this be a discussion for the C++ language community not the OpenTelemetry community? Alternatively, maybe the C++ OpenTelemetry community could take a stab at designing the logging framework their community has lacked - if they were to do this, there's no reason it needs to be governed by the OpenTelemetry specification.

@alanwest @trask trying to make sure we're on the same page - which one would you suggest:
1. OpenTelemetry will not define user-facing logging API, OpenTelemetry C++ maintainers should drive a C++ specific user-facing logging API design/implementation, and such action would be considered as okay rather than a violation from the spec perspective.
2. OpenTelemetry will not define user-facing logging API for now, and that could be added later (after Stable). OpenTelemetry C++ should hold on its logging effort.
3. OpenTelemetry should define user-facing logging API and make it clear that the API is only intended for language implementations which do not have an established logging API, those with established APIs should either a) avoid introducing yet another API at all or b) should compliment the established APIs if there is a known gap.
4. Another proposal that is not covered by 1/2/3.

**Comment by yurishkuro** [comment]
There seems to be a layering confusion here. Right now OTEL is not planning to provide a logging API in any language, the contention is that most languages already have a variety of logging frameworks in broad use. So OTEL only comes in as an "exporter" layer that is integrated into concrete existing logging frameworks (those that actually allow substituting the exporters - most do). By the time the data gets to the exporter layer, all concerns like `Logger.IsEnabled(loglevel)` should already be behind, taken care of by the logging framework itself. So why is this a blocking issue for C++?

> This might be done at a higher level API, the problem is that there is no such well-established API in C++.

There is no well-established _single_ API in Go, Javascript, Java, etc. either, so again, why is this different for C++?

@reyang I must be missing something here.

**Comment by reyang** [comment]
> There seems to be a layering confusion here. Right now OTEL is not planning to provide a logging API in any language, the contention is that most languages already have a variety of logging frameworks in broad use. So OTEL only comes in as an "exporter" layer that is integrated into concrete existing logging frameworks (those that actually allow substituting the exporters - most do). By the time the data gets to the exporter layer, all concerns like `Logger.IsEnabled(loglevel)` should already be behind, taken care of by the logging framework itself. So why is this a blocking issue for C++?

OpenTelemetry C++ needs to integrate with lower level logging mechanisms such as [LTTng](https://lttng.org), [user_events](https://docs.kernel.org/trace/user_events.html) and [ETW](https://learn.microsoft.com/windows-hardware/drivers/devtest/event-tracing-for-windows--etw-). Most of these lower level mechanisms provide a way to tell if there are subscriber(s) to particular type of logs/events or not. I think we can use #3185 for further discussions.
 
> > This might be done at a higher level API, the problem is that there is no such well-established API in C++.
> 
> There is no well-established _single_ API in Go, Javascript, Java, etc. either, so again, why is this different for C++?
> 
> @reyang I must be missing something here.

See my reply here https://github.com/open-telemetry/opentelemetry-specification/issues/2911#issuecomment-1421727126. I'm trying to get clarity - what does "Logging API spec stable" mean for the OpenTelemetry C++ group and the user of OTel C++?

**Comment by trask** [comment]
> @alanwest @trask trying to make sure we're on the same page - which one would you suggest:
>
> 1. OpenTelemetry will not define user-facing logging API, OpenTelemetry C++ maintainers should drive a C++ specific user-facing logging API design/implementation, and such action would be considered as okay rather than a violation from the spec perspective.

this would be my vote (and to rename "OTel Log API" -> "OTel Log SPI" or "OTel Log Appender API" to help avoid this confusion)

**Comment by tigrannajaryan** [comment]
> this would be my vote (and to rename "OTel Log API" -> "OTel Log SPI" or "OTel Log Appender API" to help avoid this confusion)

The [current spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/api.md) calls it "log _backend_ API". I do not mind calling it Log SPI if that reflects the intent better.

**Comment by yurishkuro** [comment]
+1 to SPI, I think this would avoid a lot of confusion

**Comment by tigrannajaryan** [comment]
I created a PR to rename Log API to Log SPI: https://github.com/open-telemetry/opentelemetry-specification/pull/3187

**Comment by jack-berg** [comment]
We can mark the "Settle on a name (Logs API vs SPI vs Bride API, etc)" as resolved now that #3197 is resolved.

**Comment by tigrannajaryan** [comment]
I am adding https://github.com/open-telemetry/opentelemetry-specification/issues/3301 as a pre-requisite.

**Comment by trask** [comment]
does Log API/SDK stabilization include [Trace Context in Legacy Formats](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs#trace-context-in-legacy-formats)?

if so, can you add consideration of #3303 as a pre-requisite?

**Comment by jack-berg** [comment]
@trask that's a good callout. Thinking about it more, this seems like its more appropriate to define as part of semantic conventions, or perhaps as a section under [compatibility](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/compatibility). I don't think we should gate the Logs Bridge API / SDK stability on this.

**Comment by tigrannajaryan** [comment]
Added https://github.com/open-telemetry/opentelemetry-specification/issues/3386 as a requirement.

**Comment by tigrannajaryan** [comment]
Added https://github.com/open-telemetry/opentelemetry-specification/pull/3385 to the checklist.

**Comment by tigrannajaryan** [comment]
Added https://github.com/open-telemetry/opentelemetry-specification/issues/3394 to the checklist.

**Comment by jack-berg** [comment]
Replaced #3387 with #3397. Marked #3397 and #3385 as completed.

**Comment by jack-berg** [comment]
@open-telemetry/dotnet-maintainers, @open-telemetry/python-maintainers, @open-telemetry/javascript-maintainers, @open-telemetry/cpp-maintainers: a couple of changes have been made recently to the log bridge API / SDK spec. Can you review #3386, #3397, #3385 and ensure that they are implementable, and confirm by commenting on this issue?

- [ ] cpp
- [ ] dotnet
- [ ] javascript
- [ ] python

**Comment by srikanthccv** [comment]
>Can you review https://github.com/open-telemetry/opentelemetry-specification/issues/3386, https://github.com/open-telemetry/opentelemetry-specification/pull/3397, https://github.com/open-telemetry/opentelemetry-specification/pull/3385 and ensure that they are implementable, and confirm by commenting on this issue?

These changes are implementable in Python.

**Comment by alanwest** [comment]
> Can you review https://github.com/open-telemetry/opentelemetry-specification/issues/3386, https://github.com/open-telemetry/opentelemetry-specification/pull/3397, https://github.com/open-telemetry/opentelemetry-specification/pull/3385 and ensure that they are implementable, and confirm by commenting on this issue?

Looks good from .NET's perspective.

**Comment by brettmc** [comment]
> Can you review https://github.com/open-telemetry/opentelemetry-specification/issues/3386, https://github.com/open-telemetry/opentelemetry-specification/pull/3397, https://github.com/open-telemetry/opentelemetry-specification/pull/3385 and ensure that they are implementable, and confirm by commenting on this issue?

No problems for the PHP implementation.

**Comment by pichlermarc** [comment]
> Can you review #3386, #3397, #3385 and ensure that they are implementable, and confirm by commenting on this issue?

As far as I can tell this should be no problem for the JS implementation. 
cc-ing @martinkuba for confirmation :slightly_smiling_face:

**Comment by dyladan** [comment]
Looks fine to me as well

**Comment by lalitb** [comment]
> Can you review https://github.com/open-telemetry/opentelemetry-specification/issues/3386, https://github.com/open-telemetry/opentelemetry-specification/pull/3397, https://github.com/open-telemetry/opentelemetry-specification/pull/3385 and ensure that they are implementable, and confirm by commenting on this issue?

Looks good from C++ prospective.

**Comment by jack-berg** [comment]
Completed in #3376!
