### ISSUE TITLE
Best way to to support traceresponse and load balancer deferred sampling?

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-specification#2914]
Hi all! Hopefully this is the place for this issue, since I don't have an OTEP in my back pocket. Feel free to bounce me elsewhere (I did [try Slack, first](https://cloud-native.slack.com/archives/C01N7PP1THC/p1667332281372659))!

**What are you trying to achieve?**

Implementing load [balancer deferred sampling](https://w3c.github.io/trace-context/#load-balancer-deferred-sampling) using experimental `traceresponse` header.

**Additional context.**

I’ve been looking into load balancer deferred sampling: https://w3c.github.io/trace-context/#load-balancer-deferred-sampling, which is in the latest Trace Context editor’s draft. TL;DR, your load balancer starts (and maybe finishes) some spans, proxies a request somewhere, waits to hear back from the proxied-to service, then starts/finishes more spans, making a sampling choice based on the proxied-to service’s `traceresponse`  header. I’m wondering if it’s possible to make this work in the load balancer in a spec-compliant way, given that AFAIK sampling decisions [are made when spans are created](https://github.com/open-telemetry/opentelemetry-specification/blob/09b1759648b5c94f70d5bdd4f81d96ec474f23c9/specification/trace/sdk.md#L215). I see this [OTEP](https://github.com/open-telemetry/oteps/pull/115) for adding additional sampling hooks, but it seems dormant.

I think the most compliant thing to do would be to cache all of the span details (start time, end time, attrs, etc.) in the load balancer, then start and finish the spans once the proxied-to service has returned its sampling decision. Less compliant would be to start `RECORD_ONLY` load balancer spans, save their end timestamps somewhere (if you logically should finish the span before getting the `traceresponse` header back), then update the `RECORD_ONLY` spans’ sampling decisions upon reading the `traceresponse` header (this is the non-compliant part, I think!), then finish the spans (using their cached end timestamps).

So my questions are:

* Am I right that these mechanics are a bit unclear given the existing spec?
* Do we need an OTEP to do this more smoothly? If no, do we want to add some guidance in the spec for those grepping it for `traceresponse`?

**Comment by brunobat** [comment]
As far as I know, the `traceresponse` header is not used anywhere in the Spec or the Java impl. 
We have requests for it, for debug purposes.

**Comment by dyladan** [comment]
I believe this is the same as #3811 which has a lot more activity and discussion. Closing in favor of that
