### ISSUE TITLE
Project Tracking: OpenTelemetry configuration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-specification#2920]
### Description

OpenTelemetry specifies code that can operate in a variety of ways based on the end-user’s desired mode of operation. This requires a configuration interface be provided to the user so they are able to communicate this information. Currently, OpenTelemetry specifies this interface in the form of environment variables. This environment variable interface is limited in the structure of information it can communicate and the primitives it can support.

The configuration project intends to produce the specification around the data model for language-agnostic configuration that provides additional flexibility for the end users.

### Project Board

[https://github.com/orgs/open-telemetry/projects/38](https://github.com/orgs/open-telemetry/projects/38)

### Deliverables

1. An OTEP
2. Prototypes in Java, Python, Go, Erlang
3. The specification of the configuration data model
4. A repository containing the schema and schema validation tooling

### Staffing / Help Wanted

End users of OpenTelemetry to help validate the usage and configuration scenarios would be great to have participate in the discussions.

##### Project lead

* @MrAlias
* @jack-berg 

##### Sponsoring TC members

* @carlosalberto 

##### Engineers contributing to the working group

* @MrAlias
* @jack-berg 
* @tsloughter 
* @MikeGoldsmith 
* @codeboten 

##### Maintainers and approvers

* @srikanthccv (python)
* @CodeBlanch (.net)
* @lalitb (c++)

### Meeting Times

Every 2 weeks, on Fridays at 10:30AM PT

### Timeline

3-6 months

### Labels

The tracking issue should be properly labeled to indicate what parts of the specification it is focused on.

### Linked Issues and PRs

All PRs, Issues, and OTEPs related to the project should link back to the tracking issue, so that they can be easily found. 

* https://github.com/open-telemetry/opentelemetry-specification/issues/1773
* https://github.com/open-telemetry/opentelemetry-specification/issues/2891
* https://github.com/open-telemetry/opentelemetry-specification/issues/2739
* https://github.com/open-telemetry/opentelemetry-specification/issues/2472

**Comment by srikanthccv** [comment]
In Python SIG, we discussed implementing something like Django [settings.py](https://docs.djangoproject.com/en/4.1/ref/settings/) for configuration but put it on hold since this idea surfaced. I will be glad to participate in this effort and help the group.

**Comment by svrnm** [comment]
As mentioned on #1773 I am very interested in this topic and happy to participate. I will not be able to attend calls on Fridays, but hopefully there will be some means for asynch communication!

**Comment by carlosalberto** [comment]
I'd like to sponsor this project as a TC member.

**Comment by dyladan** [comment]
Added to calendar.

Doc link: https://docs.google.com/document/d/1uNgWQLQZcSVfBLRXfW9XCVJmKa5NH9R15fSOXhmpGWw/edit
Zoom link in the doc and calendar invite (don't want to paste here in case bots find it)

**Comment by codeboten** [comment]
Thank you @dyladan!

**Comment by CodeBlanch** [comment]
@codeboten I'm interested in joining the working group and can help contribute a .NET prototype (probably will collaborate with @alanwest on it).

**Comment by lalitb** [comment]
no-code configuration would be the requirement for the OpenTelemetry C++ to support dynamic loading of SDK. I can help in prototyping for C++ (though it is not mentioned as part of deliverables).

**Comment by jeremydvoss** [comment]
Does this project include configuration extendibility for vendor specific items? For instance, will Azure be able to configure Connection String and Lightstep configure their access token through this schema?

**Comment by tedsuo** [comment]
Closing as we have moved to project files and project boards as our way of defining and tracking projects.
