### ISSUE TITLE
Current schema version should be excluded from schema_check validation

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#2934]
**What are you trying to achieve?**
I'm trying to rename some attributes and add schema mapping here https://github.com/open-telemetry/opentelemetry-specification/pull/2763/files#diff-13146afa870e358cc26b1d9a83dbf7aa95e784b6042c04e104ff22b7ad4844be

It fails since I'm changing 1.15 and it does not match the published one.

What did you expect to see?

I should be able to add new attribute renames for current schema version in the PR

**Additional context.**
The check was introduced in  #2868

**Comment by arminru** [comment]
@lmolkova Did you close this on purpose or should it be re-opened?
I think it should work if you just use the "expected" next version (1.16.0 in this case) in the PR.

**Comment by lmolkova** [comment]
@arminru thank you! I realized that 1.15 was already released and I needed to create 1.16.0 file, so I closed it on purpose
