### ISSUE TITLE
Make sure it is very clear we are not building a Logging API

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2936]
We are only building a logging "backend" which is supposed to be used via appenders by existing logging libraries. Additionally, we may provide helpers to build "events" that make easier to build LogRecords with specific semantic convention. Such helpers will also call the logging "backend" APIs.

We do not intend to have user-facing logging API in the spec.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers FYI.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-logs-approvers FYI.

**Comment by reyang** [comment]
+1
