### ISSUE TITLE
add openshift platform to all supported cloud providers

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-specification#2970]
**What are you trying to achieve?**

Identifying the Openshift platform, which is operated on different cloud providers.

**What did you expect to see?**

Members of `cloud.platform` like `aws_openshift`, `gcp_openshift`, ... . 

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by carlosalberto** [comment]
Overall good - but would like to know what additions would mean this issue is satisfied (you mention three examples, but I suspect there's more?)
