### ISSUE TITLE
Clarify if HTTP metrics semantic conventions require ALL the metrics to be implemented

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-specification#2972]
What did you expect to see?

The [HTTP metrics semantic convention spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md) should provide clarity "what is considered a compliant implementation", e.g. "an implementation is considered compliant if it has implemented all of the metrics described by this spec" or "an implementation is considered compliant if it has implemented at least one of the metrics described by this spec" or mark some metrics as REQUIRED and say "an implementation is considered compliant if and only if it has implemented ALL the REQUIRED metrics described by this spec".

**Additional context.**

The [current spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#metric-instruments) has vague wording "The following metric instruments MUST be used to describe HTTP operations. They MUST be of the specified type and units."

**Comment by carlosalberto** [comment]
I don't think we have a definition for this anywhere, not even for tracing, right?

**Comment by reyang** [comment]
> I don't think we have a definition for this anywhere, not even for tracing, right?

That's exactly why I opened this issue - in order for us to move semantic convention to Stable, we need to have clarity.

**Comment by jsuereth** [comment]
So thinking about this a good bit.   We want a "T-shaped" API.   The idea being you have a set of *known* consistent http metrics that must be included for baseline observability.   Instrumentation can go deeper (and  we can do this with optional/allowed metrics), but we should have a baseline that is consistent for tooling & expectation purposes.

**Comment by jamesmoessis** [comment]
Would this be a simple boolean? 

```
required ::= true | false 
```

Or would this follow a similar structure to attributes requirement level? i.e. 

```
requirement_level ::= "required"
         |   "conditionally_required" <condition>
         |   "recommended" [condition] # Default if not specified
         |   "optional"
```

**Comment by arminru** [comment]
@jamesmoessis I created https://github.com/open-telemetry/opentelemetry-specification/issues/3176 to discuss the desired levels and their definition (also beyond just HTTP).
