### ISSUE TITLE
Justify why "By" is used instead of "bytes"

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-specification#2973]
[OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#units-and-base-units) recommends "seconds, bytes, joules, grams, meters, ratios, volts, amperes, and celsius. Units should be provided where they are applicable".

The current Experimental version of [OpenTelemetry spec](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#instrument-units) suggests "Units should follow the [Unified Code for Units of Measure](http://unitsofmeasure.org/ucum.html) (need more clarification in https://github.com/open-telemetry/opentelemetry-specification/issues/705)", which leads to weird units such as By (instead of bytes) which is uncommon (is there a production system using such thing?) and counter-intuitive (so far all the preview customers of .NET instrumentation have complaints about it).

The spec has provided two columns which could be confusing (probably should only have one column):

![image](https://user-images.githubusercontent.com/17327289/203385612-781fa6df-24da-4316-962b-a8b77a4b9ada.png)

**Comment by gouthamve** [comment]
This is also inconsistent with Prometheus unit name: https://prometheus.io/docs/practices/naming/

**Comment by carlosalberto** [comment]
Let's discuss this item in the next Spec call.

**Comment by joaopgrassi** [comment]
>The spec has provided two columns which could be confusing (probably should only have one column):

This is going to be fixed when this PR in the semconv tool generator merges https://github.com/open-telemetry/build-tools/pull/79/files

**Comment by reyang** [comment]
FYI - one contributor of OpenTelemetry told me this story yesterday (I guess we don't want OpenTelemetry users to run into such situation?):

![image](https://user-images.githubusercontent.com/17327289/204876833-05bfc2bb-b30d-427f-93bc-24ed5f8e20de.png)

**Comment by reyang** [comment]
Related to #2977.

**Comment by nerdondon** [comment]
Just to be clear what is this issue really about? Isn't `By` just the label used for the unit?  It looks like the unit specifically is the same `bytes`. Is there a material impact if the displayed label or suffix is different from OpenMetrics?

**Comment by jsuereth** [comment]
The main benefit of using UCCM is that 

(a) It's an existing standard
(b) You can internationalize the units however you want from the standard.
(c) It's adaptable to proemtheus standard (i.e. we can convert) but it's also more powerful.

**Comment by tigrannajaryan** [comment]
The decision to use UCUM was made long ago and is now part of OTLP, declared stable: https://github.com/open-telemetry/opentelemetry-proto/blob/e6dfd7f4cefdc2e8844fa3dfcd8b307477d59937/opentelemetry/proto/metrics/v1/metrics.proto#L173

I don't see how we can change this. It would be a breaking change.
