### ISSUE TITLE
Clarify what does "host" mean in the HTTP metrics semantic convention

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-specification#2974]
Is this the binding host from server configuration, or the HTTP request Host header, or there is a more complex set of rules / fallback mechanism?

![image](https://user-images.githubusercontent.com/17327289/203386365-a13cc16d-44df-4fdf-a6e1-545e82553409.png)

**Comment by mateuszrzeszutek** [comment]
FYI: currently the Java HTTP metrics instrumentation uses the same `net.host.name` value that is used in HTTP spans, that is:

> [3]: Determined by using the first of the following that applies
>
> The [primary server name](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-definitions) of the matched virtual host. MUST only include host identifier.
Host identifier of the [request target](https://www.rfc-editor.org/rfc/rfc9110.html#target.resource) if it's sent in absolute-form.
Host identifier of the Host header
