### ISSUE TITLE
HTTP Metrics - what if message size is not available to the application?

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-specification#2976]
The current [semantic convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server) says:

![image](https://user-images.githubusercontent.com/17327289/203389795-56a3f0e6-e85c-412d-97ff-23c08e6be75c.png)

HTTP Message is defined in RFC https://www.rfc-editor.org/rfc/rfc2616#section-4. Most application layer frameworks do not have access to the entire size (they would normally have access to Content-Length header or the actual size of the body).

Ask: clarify what should instrumentation authors do if they don't have access to HTTP Message.

**Comment by trask** [comment]
@reyang is this resolved by #3158 marking this metric as optional?

**Comment by reyang** [comment]
> @reyang is this resolved by #3158 marking this metric as optional?

Yes.
