### ISSUE TITLE
Notation Conventions

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#298]
There are many places in this specification where several words are used to signify the requirements in the specification (i.e. "MUST", "MUST NOT", "REQUIRED", "SHOULD", etc.). However, (as far as I can tell) there is no explicit statement of these words significance nor a consistent formatting guideline (none, bold, italicized, capitalized) of them.

Ideally the specification would define the meaning and notational conventions of these words.

For example, including in the [overview](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md) the following phrase defining these terms according to [RFC 2119](https://tools.ietf.org/html/rfc2119):

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/html/rfc2119).

Additionally, it would be ideal if standardized formatting of these words were defined for contributors and a review of the specification was made to ensure consistency in formatting existed.

Looking to other public specifications like [the open container specifications](https://github.com/opencontainers/image-spec/blob/master/spec.md#notational-conventions), it might also make sense to include a phase outlining explicitly the evaluation criteria for an implementation to be compliant with this specification:

> An implementation is not compliant if it fails to satisfy one or more of the MUST, MUST NOT, REQUIRED, SHALL, or SHALL NOT requirements for the protocols it implements. An implementation is compliant if it satisfies all the MUST, MUST NOT, REQUIRED, SHALL, and SHALL NOT requirements for the protocols it implements.

I'm happy to work on this if it is determined to be a valid issue, but want to make sure it is a welcomed change.

**Comment by SergeyKanzhelev** [comment]
Very welcome change! I'd advice to add it to the README,
