### ISSUE TITLE
Kubernetes Semantic Conventions - composing conventions

### ISSUE THREAD

**Issue by nerdondon** [open-telemetry/opentelemetry-specification#2980]
I'm not sure if I am reading the spec incorrectly so I just wanted to clarify if the semantic conventions for Kubernetes objects are meant to be composable. For example, the `k8s.pod` type only defines `name` and `uid` but a pod also resides in a namespace. Is the `k8s.namespace.name` also meant to apply to `k8s.pod` and other namespaced resources? Likewise for `k8s.cluster.name`, etc.

I think where I'm getting stuck is that the `type` in the spec seems to imply that resources with the applied label will be identified as that class of object but a Pod with a cluster name attribute should not be considered a cluster.

**Comment by arminru** [comment]
Hi @nerdondon!

The `type` is about the type of OTel semantic convention resource, not about the type of the k8s object in this case. This is stated here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#document-conventions

Composing the attributes is fine and actually intended. If you have attributes specifying pod+namespace+cluster combined, it means that the telemetry is emitted from a pod in the specified namespace on a certain cluster. It might also be further combined with a `process.pid` and a `cloud.provider` and `cloud.region`, for example.

**Comment by nerdondon** [comment]
👍 thanks for the clarification
