### ISSUE TITLE
Specify how to uniquely identify a logRecord

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-specification#2989]
**What are you trying to achieve?**

I would like to uniquely identify a logRecord. There are multiple use cases for that (the first one is the one I was looking into initially, but I added more to emphasis the value of such an identifier):

* I have two observability tools where I ingest my log records, each one is "better" in doing one thing vs the other or they are used by different end-users (devs, ops, security, etc.). Now I'd like to provide a connection between the two for a logRecord, i.e. show logRecord A in both tools, or an end-user wants to share some log records with someone else so they can look it up in their tool etc.
* I want to use logRecords for metric exemplars
* I want to have a many-to-many relationship between logs and spans, this is very likely a corner case but worth considering (example: a fatal exception is thrown, bringing down the app, I log that exception but also want to link the exception with all spans affected by that crash)

What did you expect to see?

I was hoping for an equivalent to `spanId` or `traceId`, some kind of `logRecordId` that allows that unique identification. Maybe such a thing already exists or can be inferred from other attributes of a log record, in that case it would be helpful to call that out.

**Comment by tigrannajaryan** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/597

**Comment by svrnm** [comment]
As discussed during the SIG meeting I will close this issue and follow up on #597
