### ISSUE TITLE
Consider deleting Events API and recommend CloudEvents API with a bridge to Otel Log SDK

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2999]
This was raised in the Log SIG this week.
 
@open-telemetry/specs-logs-approvers please comment.

**Comment by tigrannajaryan** [comment]
I haven't looked into the details but apparently CloudEvents have SDKs and APIs in many languages to create events (e.g. https://cloudevents.github.io/sdk-java/api.html). Presumably the events created via their API can be then sent to Otel Log SDK and exported via OTLP exporter. I haven't checked if this is actually doable.

It is not a direct replacement for our Events API, but another way you can use an existing generating API to create Otel data (another way is to use the logging APIs like log4j).

The idea discussed in the SIG was that we can postpone the creation of our own Events API until we learn better from these other APIs what is it that we really want to design ourselves.

**Comment by jkwatson** [comment]
> The idea discussed in the SIG was that we can postpone the creation of our own Events API until we learn better from these other APIs what is it that we really want to design ourselves.

But, if the problem domain is completely different (and it certainly looks like it is, from what I read), then we would be postponing what should be an extremely simple Event API in favor of mapping to something that only barely applies to what we're trying to do.

**Comment by MSNev** [comment]
I don't think we want to "import" or cause to import the CloudEvents API. We should define that a Logs "Events" conforms to (supports) the CloudEvents specification (ie. the identified fields).

This would enable both the basic Event (using event.data) as well as a possible bridge to be added (if / when required).

Simplistically, we define that the CloudEvents specification fields are defined as is but for a Log Event we prefix them with "event." from an OTel Semantic convention perspective.

**Comment by Aneurysm9** [comment]
> I'm confused. CloudEvents seems to have to do with message-driven communication, from what I can grok from the website. This doesn't seem like what we're trying to accomplish with our Event API, which is about describing things that happen at a point in time, not messaging to other systems.

These are the same things AFAICT.  Sending a message is a thing that happens at a point in time.  It is equivalent to a log record.

From a data model perspective the thing that we need, and that CloudEvents does, is to provide a mechanism for identifying when a given record contains data that can be processed according to a schema and, if so, what schema to use for that processing.

From an API perspective the thing we need is a way to ensure that such data can be added to a LogRecord in a uniform manner and that can provide a foundation for creating domain-specific event construction APIs.  The question here is whether the existing CloudEvents APIs can provide that or do we need to define our own baseline event API.

**Comment by jkwatson** [comment]
> > I'm confused. CloudEvents seems to have to do with message-driven communication, from what I can grok from the website. This doesn't seem like what we're trying to accomplish with our Event API, which is about describing things that happen at a point in time, not messaging to other systems.
> 
> These are the same things AFAICT. Sending a message is a thing that happens at a point in time. It is equivalent to a log record.

I do not see this being the case at all. A message being sent to another system is not a log record. It's a message being sent to another system. I mean, you could log that event, but that seems besides the point. Can you please explain how these are the same thing?

**Comment by jkwatson** [comment]
> I think they are different sub-sets that the [CloudEvents spec](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md) encompasses (enables) by supporting multiple types data whether that be messages / events / generic logs.
> 
> I've not looked into the SDK implementations but they _may_ have specific focus on certain types of content.

I think it's notable that their spec never mentions "logs" as a receiver of an event. Maybe you could squint and see it as a possibility, but I certainly wouldn't base our event API on it, or consider it a replacement. It appears to be significantly more complex that I believe we want our basic Event to be.

**Comment by Aneurysm9** [comment]
> > > I'm confused. CloudEvents seems to have to do with message-driven communication, from what I can grok from the website. This doesn't seem like what we're trying to accomplish with our Event API, which is about describing things that happen at a point in time, not messaging to other systems.
> > 
> > 
> > These are the same things AFAICT. Sending a message is a thing that happens at a point in time. It is equivalent to a log record.
> 
> I do not see this being the case at all. A message being sent to another system is not a log record. It's a message being sent to another system. I mean, you could log that event, but that seems besides the point. Can you please explain how these are the same thing?

They're both carriers for event data.  They both have metadata about the event they carry.  As a consumer of an event I don't necessarily care how it got to me, whether it was in a log record or an AMQP message or an HTTP message.  For me this is the most important reason for keeping the logging spec and events separate.  The `LogRecord` is a vessel that can be used to carry events or things that are not events, and only one possible vessel at that.

**Comment by jkwatson** [comment]
> They're both carriers for event data. They both have metadata about the event they carry. As a consumer of an event I don't necessarily care how it got to me, whether it was in a log record or an AMQP message or an HTTP message. For me this is the most important reason for keeping the logging spec and events separate. The `LogRecord` is a vessel that can be used to carry events or things that are not events, and only one possible vessel at that.

Well, I certainly agree 100% with that statement. The Event API should be designed for users to use, regardless of what the end resting place of that event might be. But, that doesn't seem to be any kind of reason to adopt the CloudEvents API, rather than creating a very simple Event API for OpenTelemetry.

I'm not suggesting that someone doesn't provide semantic conventions for CloudEvents and how they might map into logs, although that seems like a completely separate effort from defining our own Event API.

**Comment by MSNev** [comment]
>  but I certainly wouldn't base our event API on it, or consider it a replacement. It appears to be significantly more complex that I believe we want our basic Event to be.

100% agree, our Event API doesn't need to be overly complex or support the entire CloudEvents options, just the bits we need.

With the only consideration being that our definition should "leverage" the work for the portions that we currently need (or could use) without blocking the option to support for a bridge in the future. Thus accelerating (hopefully) the OpenTelemetry semantic conventions for events.

**Comment by MSNev** [comment]
> But, that doesn't seem to be any kind of reason to adopt the CloudEvents API, rather than creating a very simple Event API for OpenTelemetry.

👍

**Comment by tigrannajaryan** [comment]
We also discussed this in the Log SIG and I believe the conclusion is that CloudEvents API bridge can be valuable but is not a replacement for our own Events API.

I am going to close this issue and we can open a separate issue to discuss the CloudEvents API bridge in the future.
