### ISSUE TITLE
Ingest  all the metrics scrape by two prometheus instance into opentelemetry

### ISSUE THREAD

**Issue by vivekcusat** [open-telemetry/opentelemetry-specification#3001]
**What are you trying to achieve?**

I am trying to ingest  all the metrics scrape by two prometheus instance into opentelemetry. 
Any document will be much appreciated. 

What did you expect to see?
All the metrics is from prometheus instance collected and sended to the exporter. 

**Additional context.**
NA

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by pirgeo** [comment]
I think what you might want is an OTel Collector (https://opentelemetry.io/docs/collector/). You can set it up to scrape Prometheus data, and (even though I haven't tried it) I think you should be able to scrape from multiple Prometheus instances (see the Configuration section).

On an unrelated note: You might be interested in joining the [CNCF Slack](https://cloud-native.slack.com/). There are a few channels dedicated to OpenTelemetry as well as the collector, e.g. [#opentelemetry](https://cloud-native.slack.com/archives/CJFCJHG4Q) or [#otel-collector](https://cloud-native.slack.com/archives/C01N6P7KR6W), where you might get an answer a bit quicker than here. Opening an issue here is more for when you have identified a problem with the project or want to propose a feature that is not yet available. For help in setting up OpenTelemetry, I would refer to the docs or the Slack channel linked above.

**Comment by vivekcusat** [comment]
This is my opentelemetry config file. 
[config.docx](https://github.com/open-telemetry/opentelemetry-specification/files/10165284/config.docx)
It is only scraping pod running for prometheus and not collecting the metrics collected by these pods. My app public-web-api-dev having a end point for its metrics exposed on port 8081 public-web-api-dev:8081/metrics. when i configure it in the prometheus reciver it does not labeled with app name.  All the metrics are coming as no-namespace in Datadog.

**Comment by pirgeo** [comment]
I am sorry, but I am not comfortable opening random .docx files from the internet. As I mentioned before, this is probably not the right place to ask for help on how to configure your collector, and you might get more eyes and ears (and help) by asking in the Slack channels I linked above. I am not an expert on the Prometheus scraper on the Collector, but I am sure there are experts in Slack :)

**Comment by dashpole** [comment]
This issue would be more appropriate for the Collector if you still need help, feel free to reopen there: https://github.com/open-telemetry/opentelemetry-collector-contrib
