### ISSUE TITLE
Misleading description of IsRecording() in trace API

### ISSUE THREAD

**Issue by utezduyar** [open-telemetry/opentelemetry-specification#3006]
I believe the text below from the spec misleading. 

```
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md
IsRecording
Returns true if this Span is recording information like events with the AddEvent operation, attributes using SetAttributes, status with SetStatus, etc.
```

The text makes me think that if any of these APIs (AddEvent, SetAttribute..) are called, the recording status will be TRUE. Seems like `IsRecording` returns True if the Span is sampled and the sample hasn't ended. At least the go implementation tells me that. 

```
// IsRecording returns if this span is being recorded. If this span has ended
// this will return false.
func (s *recordingSpan) IsRecording() bool {
	if s == nil {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.endTime.IsZero()
}

```

I believe the current text is valuable but needs to be added in a way that none of these APIs (AddEvent, SetAttribute..) will work (in other terms will be NOOP) after the span is ended. I would be happy to send a patch if I have a point.

**Comment by Oberon00** [comment]
It was meant to say that calling these APIs won't record any information if IsRecording is false, I guess. Wording improvements are welcome.

**Comment by utezduyar** [comment]
Hi my commit has been waiting for "First-time contributors need a maintainer to approve running workflows". Is this something I need to trigger or please let me know if I need to do anything else.
