### ISSUE TITLE
Proposal: Probability sampling algorithm.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-specification#31]
Originates from https://github.com/open-telemetry/opentelemetry-java/pull/337#discussion_r286734518.

In Java we currently use:
> We assume the lower 64 bits of the traceId's are randomly distributed around the whole (long)
  range. We convert an incoming probability into an upper bound on that value, such that we can
  just compare the absolute value of the id and the bound to see if we are within the desired
  probability range. Using the low bits of the traceId also ensures that systems that only use 64
  bit ID's will also work with this sampler.

**Comment by tedsuo** [comment]
OTEP #0006 resolves this, so I am closing.
