### ISSUE TITLE
Attributes on Event and Link

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#310]
What are the real-world examples for attributes on Event and Link?

Assuming they are property bags that intend to work around some missing functionality, we can add them later depending on the feedback rather than supporting this from day 1, but we can never remove them later

**Comment by Oberon00** [comment]
I think the use cases for events with attributes are innumerable, they seem as useful to me as span attributes. For example, refer to the OpenTracing spec at https://github.com/opentracing/specification/blob/master/semantic_conventions.md#log-fields-table (note that events were called "logs" in OpenTracing). But you don't even need to look that far, we already have semantic conventions that require gRPC events with proerties: https://github.com/open-telemetry/opentelemetry-specification/blob/18358d761fe35adc80eb47f38cf05819499dbe1d/specification/data-semantic-conventions.md#events

**Comment by lmolkova** [comment]
Thanks for pointing me to the docs about events, it really helps and yes, it explains why attributes are needed on events.

**Events**
One thing that immediately pops up that events look like a substitute for logs. And once we introduce Logs API we'll regret allowing both: Events and Logs.  Do events serve any purpose that will **not** be covered with logs?

**Links**
What are the scenarios for attributes on links?

**Comment by SergeyKanzhelev** [comment]
Good point that we need to articulate scenarios clearly. 

For Events vs. Logs I'd say we need to file a separate issue.

Very simple scenario for both Events and Links is any messaging system that may attach a `message-id` of the message being sent (represented by Event) or being batch-processed (represented by Link).

**Comment by lmolkova** [comment]
> For Events vs. Logs I'd say we need to file a separate issue.

I'll create one

> Very simple scenario for both Events and Links is any messaging system that may attach a message-id

Yes, that fact that you can stamp arbitrary things makes sense. But why would you want to do it? You already have SpanContext for correlation purposes.

**Comment by Oberon00** [comment]
>> For Events vs. Logs I'd say we need to file a separate issue.
>
> I'll create one

Did you get to creating one?

**Comment by lmolkova** [comment]
There are existing one: https://github.com/open-telemetry/opentelemetry-specification/issues/67

**Comment by carlosalberto** [comment]
We now have a description on Links in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#links-between-spans

I will close this issue, but feel free (maybe @Oberon00?) to re-open if you think there's something we should still clarify as part of this issue.

**Comment by carlosalberto** [comment]
Oh, never mind - reopening as I see it's about `Attributes` in `Links`, not about `Links` per-se.

**Comment by andrewhsu** [comment]
From the sig mtg today, sounds like this one can be closed.
