### ISSUE TITLE
Support units in Instrument selector in Metric View

### ISSUE THREAD

**Issue by asafm** [open-telemetry/opentelemetry-specification#3101]
**What are you trying to achieve?**
I would like to have the ability to say for a view, in its instrument selector: "Select all histogram type, which has the units 'seconds'". 
This will allow me to say: All histograms with milliseconds unit with name matching "pulsar.messaging.*" should have the following buckets - 1, 5, 10, 20, 100, 1000, 5000. 
Another example: All histograms with bytes unit should have the following buckets: 100 bytes, 500 bytes, 1kb, 2kb, and 10kb.

**What did you expect to see?**
In the [section](https://opentelemetry.io/docs/reference/specification/metrics/sdk/#view) describing the instrumentation selector for a view, starting with "The Instrument selection criteria (required), which covers:" another bullet show be added saying "The `unit` of the instrument (optional)".

**Additional context.**

In my opinion, the ability to specify a bucket list based on units (seconds, bytes, milliseconds) combined with instrumentation scope or wildcard on a metric name is a very powerful and useful feature to have. Without it, and without hints API, one finds themself creating so many views, one for each histogram defined or trying to devise a naming scheme that would be matched using the name wildcard.

**Comment by asafm** [comment]
@SergeyKanzhelev What would be the correct way to move forward with this issue?

**Comment by asafm** [comment]
Small note. This is already supported without having spec for it in the Go SDK: https://github.com/open-telemetry/opentelemetry-go/blob/ec13377b6b7cea9ba5e6a2233ad934a411459a58/sdk/metric/view.go#L79-L85:
```go
		matchFunc = func(i Instrument) bool {
			return re.MatchString(i.Name) &&
				criteria.matchesDescription(i) &&
				criteria.matchesKind(i) &&
				criteria.matchesUnit(i) &&
				criteria.matchesScope(i)
		}
```

**Comment by MrAlias** [comment]
> Small note. This is already supported without having spec for it in the Go SDK

The Go SIG understood the following specification statement as allowing this matching:

> [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#sdk) authors MAY choose to support more criteria. For example, a strong typed language MAY support point type (e.g. allow the users to select Instruments based on whether the underlying type is integer or double).

It might be worth explicitly adding unit to the matching if the goal is to have it in every language.
