### ISSUE TITLE
Provide more clear names for the default samplers provided in the SDK

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#314]
Currently, the names are `ALWAYS_ON` (return `true` for every sampling decision) and `ALWAYS_OFF` (return `false` for every sampling decision).  

Having a sampler that is "always on" has ambiguous meaning. Does it mean that it's always making decisions, and that the "always off" is never making decisions?

I would suggest naming that is more explicitly describes the decision that is being made. Perhaps `ALWAYS_RETAIN` and `ALWAYS_DROP` as options that are very clear as to their function and leave no ambiguity.

**Comment by carlosalberto** [comment]
I agree that these names are ambiguous, but I feel `ALWAYS_RETAIN` and `ALWAYS_DROP` is not a 'nice' option. Maybe we can consider other names?

`ALWAYS_SAMPLE` and `NEVER_SAMPLE` perhaps?

**Comment by jkwatson** [comment]
This might be a personal failing, but I have a really hard time remembering that to "sample" means to include, and not to drop. I have very informally polled some colleagues, and we all have the same confusion. I'd love to find language that un-ambiguously meant "to include in the the samples".

**Comment by mwear** [comment]
I've always interpreted it as meaning to collect something. The dictionary definition seems to agree with that as does the [W3C Trace Context spec](https://w3c.github.io/trace-context/#sampled-flag).
<img width="490" alt="Screen Shot 2020-01-27 at 10 59 28 PM" src="https://user-images.githubusercontent.com/2513372/73242070-bf432e80-4158-11ea-868f-5ad06d2e9ca6.png">

**Comment by jkwatson** [comment]
Yes, I was never arguing that it wasn't technically correct. Just that many people are confused by it.

**Comment by dyladan** [comment]
What about `ALWAYS_TAKE` and `NEVER_TAKE`?

**Comment by jkwatson** [comment]
I think the reason I find it confusing is that my mental model is a streaming one. There are a stream of spans flowing through the sampler. Some of them make it through to the next step in the process, and some of them don't. Hence, in my brain, when the sampler takes an action, it's to remove it from the stream, which would mean that it doesn't make it to the next step.

I totally realize that this is my own personal mental model, and the "term of art" is definitely "sample", so I'd be ok with `ALWAYS_SAMPLE`/`NEVER_SAMPLE` even though I have to stop every time I read them to make sure I got it right. :). 

But, I will stand by `ALWAYS_ON` and `ALWAYS_OFF` as being maximally confusing. :)

**Comment by jmacd** [comment]
I personally would use "DROP" and "KEEP".

**Comment by carlosalberto** [comment]
Moving this to the next milestone for now.

**Comment by jkwatson** [comment]
I would endorse `ALWAYS_DROP` and `ALWAYS_KEEP`, for sure.

**Comment by MikeGoldsmith** [comment]
Do we need the ALWAYS prefix on top of drop / keep? I think they are clear enough without.

**Comment by jkwatson** [comment]
I'm fine without it.

**Comment by bogdandrutu** [comment]
I think we settle on these names, please reopen if we need to change, the samplers improved since 6 months ago :)
