### ISSUE TITLE
Description of `host.image.id` and `host.image.version` should not be specific to VMs

### ISSUE THREAD

**Issue by sebastien-rosset** [open-telemetry/opentelemetry-specification#3146]
**What are you trying to achieve?**

Improve description of [Host Resource Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md).

**What did you expect to see?**

AFAIK, a host resource may be a VM, a bare-metal server, a switch, router. Hence it may not be a VM. The description should not be specific to VMs.

`host.image.id`:
```diff
- VM image ID. For Cloud, this value is from the provider.
+ Host OS image ID. For Cloud, this value is from the provider.
```

`host.image.version`:
```diff
- The version string of the VM image as defined in Version Attributes.
+ The version string of the VM or Host OS image as defined in Version Attributes.
```

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by arminru** [comment]
Sounds reasonable to me.
Would you like to create a PR proposing the change so that the spec approvers can take a look?

**Comment by sebastien-rosset** [comment]
> Sounds reasonable to me. Would you like to create a PR proposing the change so that the spec approvers can take a look?

Sure, I will do that.
