### ISSUE TITLE
Guidelines to prevent excessive logging is confusing

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-specification#3147]
From the trace spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/094fe9f34bc2fdb9797c4437c6062dcf61760de0/specification/trace/sdk.md?plain=1#L415-L417

What is this meant to communicate?

> To prevent excessive logging, the log should not be emitted once per span, or per discarded attribute, event, or links.

I want to improve the wording here, though the following are possible interpretations:

1) Whenever something is dropped or truncated on a span we should only log this for a fraction of the occurrences - e.g. 1 in 10 occurrences.
2) For a given span, if multiple things are dropped or truncated only log at most once per span.
3) Something else?

Or is it even important that the spec be prescriptive here? Another option would be to move this to a supplementary guidelines doc like [we have for metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md). We could make a general guidelines doc that suggests that care should be taken when logging potentially high-frequency errors/warnings from the SDK.

**Comment by tigrannajaryan** [comment]
@alanwest will you be able to make a PR for this?
