### ISSUE TITLE
Consider impact of ECS attribute alignment on the HTTP semantic convention stability effort

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3163]
**What are you trying to achieve?**

Make sure we are considering the impact of https://github.com/open-telemetry/oteps/pull/222 prior to marking the HTTP semantic conventions stable.

Relates to #2626 and #2489

**Comment by trask** [comment]
Here's a few things to consider if we want to align attributes with ECS before marking HTTP semantic conventions stable.

### Rename url-ish things from `http.*` to [`url.*`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html)

* `http.scheme` -> [`url.scheme`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-full)
* `http.url` -> [`url.full`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-full)
* `http.target` -> split into [`url.path`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-path) + [`url.query`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-query) + [`url.fragment`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-fragment)

This kinda makes sense to me regardless of ECS alignment, to increase reusability of attribute names in OpenTelemetry.

Though the `http.target` change would be a big breaking change for users (with no schema translation support).

### Rename remaining `http.*` attributes to match ECS equivalents

* `http.method` -> [`http.request.method`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-method)
* `http.status_code` -> [`http.response.status_code`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-response-status-code)
* `http.flavor` -> [`network.protocol`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-protocol) and [`http.version`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-version)
* `http.request_content_length` -> [`http.request.body.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-body-bytes)
* `http.response_content_length` -> [`http.response.body.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-response-body-bytes)
* `http.user_agent` to [`user_agent.original`](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html#field-user-agent-original)
* `http.client_ip` to [`network.forwarded_ip`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-forwarded-ip)
* `http.route` (no equivalent?)
* `http.request.header.*` (no equivalent?)
* `http.response.header.*` (no equivalent?)
* `http.resend_count` (no equivalent?)

### Rename `net.peer.*` and `net.host.*` things to [`source.*`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html) and [`destination.*`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html)

* `net.peer.name` -> [`source.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-address) or [`destination.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-address) as appropriate
* `net.peer.port` -> [`source.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-port) or [`destination.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-port) as appropriate
* `net.host.name` -> [`source.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-address) or [`destination.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-address) as appropriate
* `net.host.port` -> [`source.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-port) or [`destination.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-port) as appropriate
* `net.sock.peer.name` -> 
* `net.sock.peer.addr` -> [`source.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-nat-ip) or [`destination.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-nat-ip) as appropriate
* `net.sock.peer.port` -> [`source.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-nat-port) or [`destination.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-nat-port) as appropriate
* `net.sock.host.addr` -> [`source.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-nat-ip) or [`destination.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-nat-port) as appropriate
* `net.sock.host.port` -> [`source.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-nat-port) or [`destination.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-destination-nat-port) as appropriate
* `net.sock.family` -> 

An alternative would be to keep `net.peer.*` and `net.host.*` (instead of adopting `source.*` and `destination.*`), but rename to better align, e.g.

* `net.peer.name` -> `net.peer.address`
* `net.host.name` -> `net.host.address`
* `net.sock.peer.addr` -> `net.peer.nat.address`
* `net.sock.peer.port` -> `net.peer.nat.port`
* `net.sock.host.addr` -> `net.host.nat.address`
* `net.sock.host.port` -> `net.host.nat.port`

These `net.*` changes require much more investigation as I have glossed over many details and nuances.

**Comment by AlexanderWert** [comment]
> ### Rename url-ish things from `http.*` to [`url.*`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html)
> * `http.scheme` -> [`url.scheme`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-full)
> * `http.url` -> [`url.full`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-full)
> * `http.target` -> split into [`url.path`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-path) + [`url.query`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-query) + [`url.fragment`](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-fragment)
> 
> This kinda makes sense to me regardless of ECS alignment, to increase reusability of attribute names in OpenTelemetry.

👍 

> ### Rename remaining `http.*` attributes to match ECS equivalents
> * `http.method` -> [`http.request.method`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-method)
> * `http.status_code` -> [`http.response.status_code`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-response-status-code)
> * `http.flavor` -> [`network.protocol`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-protocol) and [`http.version`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-version)
> * `http.request_content_length` -> [`http.request.body.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-body-bytes)
> * `http.response_content_length` -> [`http.response.body.bytes`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-response-body-bytes)
> * `http.user_agent` to [`user_agent.original`](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html#field-user-agent-original)
> * `http.client_ip` to [`network.forwarded_ip`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-forwarded-ip)
> * `http.route` (no equivalent?)
> * `http.request.header.*` (no equivalent?)
> * `http.response.header.*` (no equivalent?)
> * `http.resend_count` (no equivalent?)

👍 Makes sense to me!

For the attributes that do not have an equivalent in ECS, I think ECS could adopt those fields (e.g. `http.route`, `http.request.header.*`, `http.response.header.*`, `http.resend_count`).

How about additional attributes in corresponding namespaces that ECS defines but that are not available in OpenTelemetry? Those could be a 'low-hanging fruit' to enrich OTel semantic conventions without any transformations or breaking changes. Examples:

- `http.request.body.content` (For example for the use case of capturing an HTTP request body with a span.)
- `http.request.id` (To reflect request IDs other than the tracing context. For example the `x-amz-request-id` in AWS, `client-request-id` on Azure, etc.)
- [`http.request.mime_type`](https://www.elastic.co/guide/en/ecs/current/ecs-http.html#field-http-request-mime-type)
- `http.response.*`
- [`user_agent.*`](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html)

> These `net.*` changes require much more investigation as I have glossed over many details and nuances.

I think the most fundamental question here is the `*.peer.*` concept vs. explicit namespaces as it is in ECS (`server.* / client.*`, `source.* / destination.*`). With the peer concept the semantics of the attributes change depending on _**where**_ they are collected. For example `net.sock.peer.addr` on a client-side span means that it's the address of the server, but, the same attribute on a server-side span implies it's the address of the client. In ECS this is handled explicitly with `client.address` vs. `server.address` (or `source.address` vs. `destination.address`)


> * `net.sock.peer.name` -> 
> * `net.sock.family` ->

* `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)
* `net.sock.peer.name` -> [`source.domain`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-domain) or [`destination.domain`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-domain) as appropriate

**Comment by trask** [comment]
thx @AlexanderWert

> as they would introduce breaking changes

we haven't declared any semantic conventions stable yet, so while we would love to avoid breaking changes, we do have that opportunity (for a [limited time](https://opentelemetry.io/blog/2023/http-conventions-stability/))

> For the attributes that do not have an equivalent in ECS, I think ECS could adopt those fields (e.g. `http.route`, `http.request.header.*`, `http.response.header.*`, `http.resend_count`).

👍

> What about additional attributes in corresponding namespaces that ECS defines but that are not available in OpenTelemetry? Those could be a 'low-hanging fruit' to enrich OTel semantic conventions without any transformations or breaking changes.

in the short-term I'd like to focus on getting the existing OTel HTTP semantic conventions to stability, but I agree if we go down this route we should have a separate(?) discussion on whether we proactively bring over more ECS attributes.

> I think the most fundamental question here is the `*.peer.*` concept vs. explicit namespaces as it is in ECS (`server.* / client.*`, `source.* / destination.*`).

thx for the explanation behind ECS choice here

> * `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)
> * `net.sock.peer.name` -> [`source.domain`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-domain) or [`destination.domain`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-domain) as appropriate

👍 I've updated my comment above to include these

**Comment by reyang** [comment]
@jsuereth FYI

**Comment by lmolkova** [comment]
Thanks @trask for putting it together. Overall the direction makes sense to me, but I have comments on individual attributes:

- `http.target` is currently available on server only, where  `url.fragment` is not available

- `http.version` - we also need version for AMQP and other protocols, can we come up with `network.version` attribute and introduce it in both schemas?

- `http.request.body.bytes` - we have similar attributes in grpc and messaging. Should we unify? also there was an attempt to say we only measure in bytes and remove bytes from names - discussion #1307.

- `http.resend_count (no equivalent?)` - since retries aren't http-specific, there is an opportunity to generalize it too

- `destination.nat.ip` and `source.nat.ip` are no great for UNIX domain socket communication or esoteric things like bluetooth, so  I'd prefer `address` version of these

Clarifications/cleanups:
`net.peer.name` -> `destination.address` only
`net.peer.port` -> `destination.port` only
`net.host.name`-> `source.address`
`net.host.port` -> `source.port`
and so on

**Comment by trask** [comment]
Taking another try at the `net.*` attributes, I'm still not clear on some things on both sides (OTel and ECS).

### HTTP client attributes:

* `net.peer.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
* `net.peer.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
* `net.sock.peer.name` -> this is http proxy address? can it be other things? (@lmolkova)
* `net.sock.peer.addr` -> this http proxy ip? or could also be resolved ip for `net.peer.name`? can it be other things? (@lmolkova)
* `net.sock.peer.port` -> this is http proxy port? can it be other things? (@lmolkova)
* `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

### HTTP server attributes:

* `net.host.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
* `net.host.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
* `net.sock.host.addr` -> @AlexanderWert any ideas where to map this in ECS?
* `net.sock.host.port` -> @AlexanderWert any ideas where to map this in ECS?
* `net.sock.peer.name` -> [`client.domain`](https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-domain)
* `net.sock.peer.addr` -> [`client.address`](https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-address)
* `net.sock.peer.port` -> [`client.port`](https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-port)
* `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

**Comment by trask** [comment]
cc @Oberon00

**Comment by trask** [comment]
> * `http.version` - we also need version for AMQP and other protocols, can we come up with `network.version` attribute and introduce it in both schemas?

this makes sense to me. @AlexanderWert wdyt from ECS perspective?

> * `http.request.body.bytes` - we have similar attributes in grpc and messaging. Should we unify?
> * `http.resend_count (no equivalent?)` - since retries aren't http-specific, there is an opportunity to generalize it too

@AlexanderWert any thoughts about generalizing these fields? any idea what field set they would live in from ECS perspective if they were generalized?

**Comment by reyang** [comment]
> * `http.request.body.bytes` - we have similar attributes in grpc and messaging. Should we unify?

I suggest using the existing ECS one:
1. It is more practical to use an established one than inventing a new version (more from the timeline and risk control perspectives)
2. "body" "payload" "content" - different protocols have different concepts, terms, etc. I remember there is even messaging protocol with three parts - envelope headers, message metadata and message body. Be specific about "HTTP request body bytes" and "the content size in a messaging protocol which covers both metadata and body" seems to bring lots of clarity. Also, I think there is less intention to aggregate/sort different sizes across HTTP and messaging.

**Comment by lmolkova** [comment]
net.peer.name -> [server.address](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
net.peer.port -> [server.port](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)

My understanding that `net.peer.sock` matches `server` namespace ("For TCP events, the server is the receiver of the initial SYN packet(s) of the TCP connection." - if there is a proxy, it would be it) 

`net.peer.name` and port match destination namespace attributes? 

But I'm not sure I understand the difference between destination and source 
"Destination fields capture details about the receiver of a network exchange/packet."

**Comment by trask** [comment]
@lmolkova and I aligned on what we think the mappings are for network attributes.

We definitely need confirmation from @AlexanderWert that our usage of `source.*` and `destination.*` below are correct from ECS perspective.

### HTTP client attributes:

* `net.peer.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
* `net.peer.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
* `net.sock.peer.name` -> [`destination.address`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-address)
* `net.sock.peer.addr` -> [`destination.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-ip), or for unix sockets: [`destination.address`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-address)
* `net.sock.peer.port` -> [`destination.port`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-port)
* `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

### HTTP server attributes:

* `net.host.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
* `net.host.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
* `net.sock.host.addr` -> [`destination.address`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-address)
* `net.sock.host.port` -> [`destination.port`](https://www.elastic.co/guide/en/ecs/current/ecs-destination.html#field-destination-port)
* `net.sock.peer.name` -> [`source.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-address)
* `net.sock.peer.addr` -> [`source.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-ip), or for unix sockets: [`source.address`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-address)
* `net.sock.peer.port` -> [`source.port`](https://www.elastic.co/guide/en/ecs/current/ecs-source.html#field-source-port)
* `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

Consolidating open questions from above into one place:

1. `http.version` - we also need version for AMQP and other protocols, can we come up with `network.version` attribute and introduce it in both schemas?

2. should we generalize `http.request.body.bytes` and `http.resend_count` beyond just http?

   this is still interesting, but not critical

3. if we decide to go with `http.request.body.bytes`, should we add unit in the name of other OTel semantic attributes which have so far avoided this (https://github.com/open-telemetry/opentelemetry-specification/pull/1307)

4. it looks like ECS recommends copying attributes from `client.`/`server.` to `source.`/`destination.`, probably so that more general queries can be run across `source.`/`destination.` fields. we would prefer not to duplicate telemetry on the SDK/Instrumentation side, and leave that for ingestion pipelines if needed.

**Comment by AlexanderWert** [comment]
Thanks @trask for consolidating this.

Some clarification on the `server.*`/ `client.*` vs. `source.*`/`destination.*` fieldsets from ECS:

`source.*`/`destination.*` fields are meant for network packet-based perspective of information. For example, when there is a client `A` that opens up a connection to a server `B`, for that connection A will stay all the time the client, while B is the server. 

Now let's have a look at the network packet level: When `A` sends the request `Req` to `B`, then `A` is the `source` and `B` is the `destination` from the perspective of the network packet `Req`. However, when `B` responds to `A` with a response `Resp`, then the roles change on the packet level, so `B` becomes the `source` and `A` the `destination` from the perspective of the response `Resp`.

So, for the above purposes I think it's more appropriate to use `client.*`/`server.*` fields instead of `source.*`/`destination.*`.

### HTTP client attributes:
 * `net.peer.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
 * `net.peer.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
 * `net.sock.peer.name` -> `server.sock.address`(as new field)
 * `net.sock.peer.addr` -> [`server.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-ip), or for unix sockets: `server.sock.address` (as new field)
 * `net.sock.peer.port` -> [`server.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-port)
 * `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

So based on that I'd propose the following:
 
 ### HTTP server attributes:
 * `net.host.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
 * `net.host.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
 * `net.sock.host.addr` -> [`server.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-ip), or for unix sockets: `server.sock.address` (as new field)
 * `net.sock.host.port` -> [`server.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-port)
 * `net.sock.peer.name` -> `client.sock.address` (as new field)
 * `net.sock.peer.addr` -> [`client.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-ip), or for unix sockets: `client.sock.address` (as new field)
 * `net.sock.peer.port` -> [`client.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-nat-port)
 * `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

**Comment by trask** [comment]
Summarizing the discussion with @AlexanderWert and @lmolkova around network attributes. Let me know if I missed anything.

### HTTP client attributes:
 * `net.peer.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
 * `net.peer.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
 * `net.sock.peer.name`
   * when it represents a proxy -> `server.nat.address` (as a new field in ECS)
   * (is there any other case?)
 * `net.sock.peer.addr`
   * when it represents the ip address of the `server.address` -> [`server.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-ip)
   * when it represents a proxy -> [`server.nat.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-ip)
   * when it represents a unix socket -> `server.socket.address` (as a new field in ECS)
   * (is there any other case?)
 * `net.sock.peer.port`
   * when it represents proxy -> [`server.nat.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-nat-port)
   * (is there any other case?)
 * `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

 ### HTTP server attributes:
 * `net.host.name` -> [`server.address`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-address)
 * `net.host.port` -> [`server.port`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-server-port)
 * `net.sock.host.addr` -> `server.socket.ip` (as a new field in ECS)
   * when it represents a unix socket -> `server.socket.address` (as a new field in ECS)
 * `net.sock.host.port` -> `server.socket.port` (as a new field in ECS)
 * `net.sock.peer.name` -> (remove from OTel, not needed)
 * `net.sock.peer.addr` -> [`client.ip`](https://www.elastic.co/guide/en/ecs/current/ecs-server.html#field-client-ip)
   * when it represents a unix socket -> `client.socket.address` (as a new field in ECS)
 * `net.sock.peer.port` -> [`client.port`](https://www.elastic.co/guide/en/ecs/current/ecs-client.html#field-client-port)
 * `net.socket.family` -> [`network.type`](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type)

**Comment by trask** [comment]
related to #3192, here's the mapping for exception attributes:

* `exception.type` -> [`error.type`](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-type)
* `exception.message` -> [`error.message`](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-message)
* `exception.stacktrace` -> [`error.stack_trace`](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-stack-trace)
* `exception.escaped` -> (nothing corresponding)

**Comment by trask** [comment]
Closing, as I believe this is now superseded by:

* #3181
* #3182
* #3198 
* #3199 
* #3371

**Comment by Oberon00** [comment]
Wouldn't it be good to keep this open as overall tracking issue?

**Comment by trask** [comment]
is there any advice / general practice for when to use tracking issues vs using projects to track? e.g. we are also tracking these issues in the HTTP and general semantic conventions stability projects:
* https://github.com/orgs/open-telemetry/projects/41/views/1?filterQuery=status%3A%22Blocker+for+stability%22
* https://github.com/orgs/open-telemetry/projects/31/views/1?filterQuery=status%3A%22Blocker+for+HTTP+semconv+stability%22
