### ISSUE TITLE
Semantic Convention for Deployments

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/opentelemetry-specification#3168]
Context
-----
I would like to propose a semantic convention for Cloud Native Deployments. This semantic convention will support the observability of deployments by enriching logs and DORA metrics with information about the application and/or microservices under deployment. Furthermore, traces could also be augmented with this data gaining visibility in all the steps the deployment goes through and pinpointing root causes of failure.
 
 
Proposed Attributes
----

 Deployments can have one or more applications. Each application comprises one or more processes, called [Workload](https://kubernetes.io/docs/concepts/workloads/) in K8s terminology. Furthermore, deployments usually also carry additional tasks that set the stage up to be able to serve the newly deployed application(s).
This issue proposes to track `name`, `version`, and `status` attributes for Application(s), Workload(s), and Task(s)
 
Please take a look at #3169 for a more comprehensive description.
 
 
Additional Info
------
 
We started implementing this in [Keptn](https://github.com/keptn/lifecycle-toolkit), an incubating CNCF project. An example of the usage of this data is available here: https://github.com/keptn-sandbox/klt-on-k3s-with-argocd

**Comment by joshgav** [comment]
Nice idea @thisthat! Do you think we might inject emitters for these events into say Jenkins (via the Java instrumentation repo) and Tekton (via the Go repo)? That would help with adoption.

**Comment by thisthat** [comment]
Hey @joshgav, I am not an expert on how these repos work, but I think auto-instrumentation for these attributes is feasible. `deployment.application.name` is the only attribute for which there is no 100% fit since both tools do not have the Application concept. Nevertheless, we could use the pipeline name for it.

**Comment by joshgav** [comment]
Hi folks - I believe this may in fact be the same or at least closely overlap this issue: https://github.com/open-telemetry/oteps/pull/223, PTAL

@aloisreitbauer :eyes:

**Comment by dyladan** [comment]
I think this is being handled by the CI/CD group now in the semconv repo
