### ISSUE TITLE
Generalize the `http.user_agent` attribute to `user_agent.*`

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3180]
**What are you trying to achieve?**

Generalize the `http.user_agent` attribute so it can be used by different semantic conventions.

Related to: https://github.com/open-telemetry/opentelemetry-specification/pull/3097#discussion_r1083891451

**Additional context.**

~ECS already has `user_agent.*` namespace: https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html~

~If we want to follow ECS naming, we could rename `http.user_agent` to `user_agent.original`.~

UPDATE This proposal is being made independent of ECS alignment.

**Comment by MSNev** [comment]
This probably makes sense longer term as browsers are freezing the user agent, so the basic meaning of http.user_agent will diminish over time.

**Comment by trask** [comment]
> This probably makes sense longer term as browsers are freezing the user agent, so the basic meaning of http.user_agent will diminish over time.

any thoughts if there's a better name than `user_agent.original` given the upcoming changes? (or maybe `original` is ok, in the sense it's the original "old" field)

**Comment by mateuszrzeszutek** [comment]
Since we're planning to rename `http.url` to `url.full`, maybe `user_agent.full`? In case you want to parse the agent and split out individual properties (like [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html) does).

**Comment by trask** [comment]
> Since we're planning to rename `http.url` to `url.full`, maybe `user_agent.full`? In case you want to parse the agent and split out individual properties (like [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-user_agent.html) does).

I think we'll only rename `http.url` to `url.full` if we are aligning with ECS, in which case we'd go with `user_agent.original` to also align with ECS

**Comment by trask** [comment]
I think this is a good change regardless of ECS alignment:
* we've already seen the need for generalizing this
* user agent string is being deprecated and replace with user agent components, so this will provide a good home for those under `user_agent.*` in the future
* breaking (renaming) `http.user_agent` should be less disruptive compared to making changes to other `http.*` attributes
