### ISSUE TITLE
Events interoperation with CloudEvents

### ISSUE THREAD

**Issue by rektide** [open-telemetry/opentelemetry-specification#319]
Hello.

Ideally I'd like to see OpenTelemetry align with & perhaps extend the well supported, broadly featured [CloudEvents specification](https://github.com/cloudevents/spec). Concepts such as timestamps are already described in this specification, & it would be wonderful if interoperation were possible across things like CloudEvent's Time, where applicable.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, looks like this one would need more specific proposal of how this would work with CloudEvents spec including specific use case before this can progress. suggest moving to the future milestone for now.

**Comment by austinlparker** [comment]
We believe this has been accomplished with our work on the Events API and Data Model. If there are specific, more narrowly scoped asks around this issue, please open a new issue.
