### ISSUE TITLE
Exception semantic conventions need to be marked stable

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3192]
Opening for now primarily to discuss/track whether this is a blocker for marking HTTP semantic conventions stable.

My initial thought is that we won't be able to declare HTTP instrumentations stable without this, and therefore this is a blocker for HTTP semantic convention stability.

**Comment by trask** [comment]
from @jsuereth 

> My main fear with current exception encoding is inetraction with the length-limit on the actual exception stacktrace string, and whether that will lead to poor experience in debugging exceptions from OTEL

**Comment by jsuereth** [comment]
Adding some more thoughts looking at specifics:

- [ ] We should add a spec compliance metrics where each language SiG can denote whether they have documented their `exception.stacktrace` format.  This is implicitly required in the current convention.  See [this recommendation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#stacktrace-representation) as an option for language SIGs.
- [ ] I'm worried about the interaction of `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT` and `exception.stacktrace`.  I'm not sure users of the value length limit would think about stacktraces as an attribute.  We should entertain if we want to have some special interaction of those two *or* just encourage users not to set length limits, as the current default is unlimited.
- [ ] Should we ask language SiGs to update the semconv specification document with their official layout? This way the documentation for how to leverage the field is centrally located.

**Comment by reyang** [comment]
My vote: it's not blocking HTTP semantic convention.
Reason:
1. exception is not going to be part of the core HTTP metrics (so there is no concern of breaking the metrics streams)
2. exception stack should be opt-in due to the size and potential sensitive information

**Comment by trask** [comment]
until exception semantic conventions are marked stable, we cannot mark any Java HTTP instrumentations as stable.

but I agree this should not be block HTTP semantic conventions themselves from being marked stable.

**Comment by lmolkova** [comment]
exceptions are stable, https://github.com/open-telemetry/semantic-conventions/tree/main/docs/exceptions, closing
