### ISSUE TITLE
Add S3 attributes to the semantic conventions for AWS SDK

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/opentelemetry-specification#3193]
# What are you trying to achieve?

There is a great set of attributes for DynamoDB-related spans in the semantic conventions for the AWS SDK.
Something similar would be also valuable for S3 operations. For example when a span is created for an S3 `getObject` operation it would be interesting and valuable for analysis to know which S3 `bucket` and which `object` is being accessed.

I'm proposing to add relevant S3 specific attributes for the main S3 operations:

### Bucket Operations
| Operation | Proposed attributes |
| --- | --- |
| [create-bucket] |  `aws.s3.bucket` |
| [delete-bucket] |   `aws.s3.bucket` |
| [head-bucket] |  `aws.s3.bucket` |
| [list-buckets] |  --- |

### Object operations
| Operation | Proposed attributes |
| --- | --- |
| [copy-object] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.copy_source` |
| [delete-object] | `aws.s3.bucket`, `aws.s3.key` |
| [delete-objects] | `aws.s3.bucket`, `aws.s3.delete` |
| [get-object] | `aws.s3.bucket`, `aws.s3.key` |
| [head-object] | `aws.s3.bucket`, `aws.s3.key` |
| [list-objects] | `aws.s3.bucket` |
| [list-objects-v2] | `aws.s3.bucket` |
| [list-object-versions] | `aws.s3.bucket` |
| [put-object] | `aws.s3.bucket`, `aws.s3.key` |
| [restore-object] | `aws.s3.bucket`, `aws.s3.key` |
| [select-object-content] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.input_serialization`, `aws.s3.output_serialization` |

### Multipart operations
| Operation | Proposed attributes |
| --- | --- |
| [abort-multipart-upload] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.upload_id` |
| [complete-multipart-upload] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.upload_id` |
| [create-multipart-upload] | `aws.s3.bucket`, `aws.s3.key` |
| [list-multipart-uploads] | `aws.s3.bucket` |
| [list-parts] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.upload_id` |
| [upload-part] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.upload_id`, `aws.s3.part_number` |
| [upload-part-copy] | `aws.s3.bucket`, `aws.s3.key`, `aws.s3.upload_id`, `aws.s3.part_number`, `aws.s3.copy_source` |

[create-bucket]: https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
[delete-bucket]: https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
[head-bucket]: https://docs.aws.amazon.com/cli/latest/reference/s3api/head-bucket.html
[list-buckets]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html
[copy-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html
[delete-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-object.html
[delete-objects]: https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html
[get-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html
[head-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/head-object.html
[list-objects]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects.html
[list-objects-v2]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html
[list-object-versions]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-object-versions.html
[put-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html
[restore-object]: https://docs.aws.amazon.com/cli/latest/reference/s3api/restore-object.html
[select-object-content]: https://docs.aws.amazon.com/cli/latest/reference/s3api/select-object-content.html
[list-multipart-uploads]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-multipart-uploads.html
[abort-multipart-upload]: https://docs.aws.amazon.com/cli/latest/reference/s3api/abort-multipart-upload.html
[complete-multipart-upload]: https://docs.aws.amazon.com/cli/latest/reference/s3api/complete-multipart-upload.html
[create-multipart-upload]: https://docs.aws.amazon.com/cli/latest/reference/s3api/create-multipart-upload.html
[list-parts]: https://docs.aws.amazon.com/cli/latest/reference/s3api/list-parts.html
[upload-part]: https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part.html
[upload-part-copy]: https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html

**Comment by AlexanderWert** [comment]
@willarmiros @iNikem @arminru As you were involved in the `aws.dynamodb.*` semantic conventions, what do you think about this proposal?

**Comment by willarmiros** [comment]
Hi @AlexanderWert - I love it, consider me in support. We also plan to add SQS attributes eventually as well!

**Comment by AlexanderWert** [comment]
Hi @jmacd, 
how can we proceed with that? Does it make sense for me to create a PR for the above, already, or are there any objections with that proposal? 

Thanks!

**Comment by carlosalberto** [comment]
Feel free to create a Pr @AlexanderWert - and let's discuss the details on the PR itself, once people take a look, etc. Thanks!
