### ISSUE TITLE
In-Proc OTLP Exporter AAD Auth

### ISSUE THREAD

**Issue by anirudh264** [open-telemetry/opentelemetry-specification#3204]
I am trying to use the in-proc OTLP exporter and do an AAD Auth against a Microsoft Resource.

I can use the Httpclient to authenticate the first time, but no easy way to refresh the expired token.

**Comment by pirgeo** [comment]
This seems like a language-specific issue. What language are you using?

**Comment by anirudh264** [comment]
.NET, but can't find anything for other languages either.

**Comment by joaopgrassi** [comment]
When configuring the OTLP exporter in .NET, you can provide a custom "HttpClientFactory" that provides `HttpClient` that is used to make the export requests. If you use that, then you can provide HttpClients that are "auth-aware" (see [Message handlers](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers))

For more info, you can ask in the OTel .NET repo for more guidance if you need https://github.com/open-telemetry/opentelemetry-dotnet

**Comment by dyladan** [comment]
@anirudh264 Does @joaopgrassi's answer solve your issue?

**Comment by svrnm** [comment]
@anirudh264 I am closing this issue now, if you still want to discuss this, feel free to reopen it or raise a new issue.
