### ISSUE TITLE
HTTP semcomv depends on other experimental docs

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-specification#3219]
[HTTP semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/trace/semantic_conventions/http.md) explicitly or implicitly depends on the following documents with experimental status which should(? partially?) be marked as stable before HTTP semconv can be marked as stable:

- [span_general.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/trace/semantic_conventions/span-general.md). In particular, the following attributes:
  - `net.peer.name`
  - `net.peer.port`
  - `net.host.name`
  - `net.host.port`
  - `net.sock.family`
  - `net.sock.peer.addr`
  - `net.sock.peer.name`
  - `net.sock.peer.port`
  - `net.sock.host.addr`
  - `net.sock.host.port`
  - `net.transport` #3244
  - #3260
- ~~[attribute_naming.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/common/attribute-naming.md). If this doc changes significantly, we'd need to rename HTTP attributes~~
  - [UPDATE] per @arminru comment below, changes in this doc should not require changes in stable conventions
  - [UPDATE2] https://github.com/open-telemetry/opentelemetry-specification/pull/3220
- [attribute-requirement-level.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/common/attribute-requirement-level.md). If we change the definition of requirement levels, this could cause breaking changes for end-users
  - [UPDATE] https://github.com/open-telemetry/opentelemetry-specification/issues/3235
- [telemetry_stability.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/telemetry-stability.md) - the definition of telemetry stability is experimental.
  - [UPDATE] #3221
- [schemas/README.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/schemas/README.md). Even though [versioning-and-stability.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/versioning-and-stability.md#semantic-conventions-stability) is stable, it relies on [schema transformation](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/schemas/README.md) which is experimental.
  - [UPDATED] #3225

**Comment by arminru** [comment]
Thank you for collecting these dependencies, @lmolkova!

**Comment by arminru** [comment]
> [attribute_naming.md](https://github.com/open-telemetry/opentelemetry-specification/blob/102b00daef366e48d99f672f343fe78f777fd3af/specification/common/attribute-naming.md). If this doc changes significantly, we'd need to rename HTTP attributes

I don't think this necessarily blocks stabilizing the HTTP semantic conventions.
If changes were made there, we could call out that existing, stable conventions will remain as-is.

**Comment by trask** [comment]
@lmolkova thx for putting this list together! do you think the remaining stability dependencies are now tracked by

* #3260
* #3235
* #3225

and if so are you ok with closing this one?

**Comment by lmolkova** [comment]
closing in favor of ⬆️
