### ISSUE TITLE
What happens when a default tracer starting a span 

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#324]
I'm going back over the spec and it has changed a lot. The first thing that most concerns me is:

> Implementations MUST provide a way to create Spans via a Tracer. By default, the currently active Span is set as the new Span's parent. The Tracer MAY provide other default options for newly created Spans.
>
> Span creation MUST NOT set the newly created Span as the currently active Span by default, but this functionality MAY be offered additionally as a separate operation.

I can not reasonably change the opentelemetry-erlang library's default tracer to not set the new span as the active span.

There appears to no longer be a `StartSpan` call mentioned, what happened? Is the goal here to separate a `CreateSpan` and `StartSpan` where the former does not set it to active and the latter does? If so that is not clear but at least would make some sense to offer both, but I can not see having our tracer's `start_span` not setting the new span to the active span, it would be very confusing to the users and force an additional operation be taken by the user for what is the most common use case.

**Comment by Oberon00** [comment]
Please use GitHub's blame view, and you will find that this was already discussed (#287) / is discussed on another issue already (#238). If I understand you correctly, this issue is a duplicate of of #238 but I'm not sure how this is related to the default tracer (What is the "default tracer" for you? The no-op/minimal tracer or the "global" tracer?).

**Comment by tsloughter** [comment]
By "default tracer" I mean the SDK.

It isn't exactly a duplicate of 238, I commented on 238. I don't see discussion on the removal of StartSpan? And the text I quoted and is from 287 is for the API, so maybe the SDK (default tracer) has a different expectation, which I opened this to discuss the SDK as well.

I can close if you think this whole discussion is better kept in 238.

**Comment by Oberon00** [comment]
Ah sorry, you are actually one of the main commenters on #238 even, my bad!

I think the intention of the spec is still that the span should be started (see also the description of the start timestamp parameter in #322), only that it is not active. So the name of the API that MUST be provided to create a span may actually be `StartSpan`.

**Comment by carlosalberto** [comment]
@tsloughter Hey hey, any comment on this?

Moving it to 0.4 for now.

**Comment by tsloughter** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-specification/issues/469
