### ISSUE TITLE
Add metric attribute conventions corresponding to span status?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3243]
From @arminru's https://github.com/open-telemetry/opentelemetry-specification/issues/2419#issuecomment-1081923604:
> The status, on the other hand, is indeed missing and I think it would make sense to introduce a generic metric attribute convention for this that matches the definitions for [Span Status](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status=).

**Comment by trask** [comment]
Discussed in Semantic Convention WG and it only makes sense for some metrics and should probably be deferred to individual semantic conventions where they may or may not already have a dimension that encompasses "status", e.g. `http.status_code` in http semconv.

**Comment by AlexanderWert** [comment]
@lmolkova , @trask 
I had another look. In ECS there's the field [`event.outcome`](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-outcome) that actually represent exactly what we discussed in the Semantic Convention WG: A generic status that can have the values `failure`, `success`, `unknown`.

**Comment by lmolkova** [comment]
adding more context:

## Option 1: Domain-specific error code

Databases and messaging systems do not have cross-domain error codes. They would need to standardize within one semconv and then we'd introduce 
* `messaging.status_code` 
* `db.status_code` 
* `faas.status_code`
* etc

Pros: 
* it's possible to see failure-rate on a dashboard or add alerts for the specific domain

Cons:
* metric is not specific enough. There are no system-specific error codes
* there is little commonality of error codes within specific domain

## Option 2:  General-purpose error code
We'll introduce one common attribute `error.code`, `event.outcome`, `status.code` or anything else.

Pros and cons are the same as in **Option 1**, but we do just one status enum, minimizing inconsistencies and cognitive load.

## Option 3: No common  error codes at all

Each extension defines a custom attribute, so we'll have

* `dotnet.http.client.error_reason`
* `messaging.kafka.status_code` 
* `messaging.rabbitmq.error_reason` 
* `db.mssql.hresult` 
* `db.cosmosdb.status_code` 
* etc

Pros:
- metrics are very specific

Cons:
- no common dashboards/alerts that include error rate


## Proposal: Option1+3

1. introduce *one* general-purpose status:  `error.code`, `event.outcome`, `status.code`. 
2. start with existing values for span status: `ok`, `error`, no value (unset) ?. The list might slowly grow over time and include `timeout`, `cancellation`, etc. We can also allow adding custom values to this list as long as practical cardinality is low.
3. Recommend individual semconv extensions to define tech-specific error code

Example:

- `status.code`: error
- `messaging.kafka.error_code`: `INVALID_FETCH_SIZE`


Pros:
- allows to build common dashboards/alerts with failure rates for specific semconv
- allows to have tech-specific metrics

**Comment by lmolkova** [comment]
Adding more context on how this affects  HTTP semconv stability:

.NET HttpClient is being instrumented with metrics. The native instrumentation can report failure reason when no response was received (`http.response.status_code` was not set).

I expect there are other instrumentations like these, which can provide the reason (DNS issue, connection reset or refused, TLS issue, etc).

**We do not have an attribute to report such a thing in HTTP metrics. Assuming we don't introduce one now, adding it later would be a breaking change.**

**Comment by lmolkova** [comment]
Based on today's SIG discussion, I separated HTTP-specific issue to https://github.com/open-telemetry/semantic-conventions/issues/204 and removing this one from HTTP blockers.

**Comment by lmolkova** [comment]
**Option 4:**

One attribute that has 2 values defined for success and unknown failure, but allows instrumentations to put any values (with low practical cardinality):

`error.reason: ` - success
`error.reason: _OTHER` - unknown error
`error.reason: java.lang.UnknownHostException`
`error.reason: dns_error`
`error.reason: timeout`
`error.reason: INVALID_FETCH_SIZE`

**Comment by lmolkova** [comment]
@AlexanderWert

> In ECS there's the field [`event.outcome`](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-outcome) that actually represent exactly what we discussed in the Semantic Convention WG: A generic status that can have the values `failure`, `success`, `unknown`.

The `event` is a bit confusing because the existing `event` namespace is used to describe OTel events. I wonder if `error.code` or `error.type` would be more descriptive?
