### ISSUE TITLE
Confirming it's ok to mark HTTP semconv stable without marking `net.*` attributes stable

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3260]
The HTTP semconv stability working group believes that it's ok to mark [HTTP semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) as stable without marking any part of [span general semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md) as stable.

But we would like to make sure that there's broader community agreement on this point and discuss if there is any disagreement.

What we believe is that by marking [HTTP semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) as stable, we will be marking the `net.*` attributes that are used in the HTTP semconv as stable **within the context of HTTP semantic conventions**, with the HTTP-specific definitions of them which appear in the HTTP semconv.

This will inherently place a barrier to changing these attribute names in the [span general semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md), but at the same time it leaves some flexibility in the precise definition of these attributes at the more abstract/general `net.*` level.

**Comment by Oberon00** [comment]
I think we should at least split out a part of the net conventions needed for HTTP and mark it as stable.

**Comment by trask** [comment]
Discussed in the spec meeting and there is desire to at least mark attributes in span general that are used by stable HTTP semantic conventions, so it's clear that the changes allowed to them are limited.
