### ISSUE TITLE
Histogram bucket size

### ISSUE THREAD

**Issue by careless6666** [open-telemetry/opentelemetry-specification#3262]
Now when we use prometheus and histograms, we set the sizes of the buckets, this is important in terms of the volume of stored metrics. If you look at the histograms created through the meter, it seems that there is no way to influence the size of the buckets at all. Are there any plans to manage them in the future?

prometheus variant

```
responseTimeSeconds = metricFactory
                .CreateHistogram("my_response_time_seconds", "",
                    buckets: TimeBuckets.Medium,
                    labelNames: new[] {"handler", "protocol", "client_name", "status", "test_type"});
```
new variant
```
responseTimeSeconds = meter.CreateHistogram<double>("my_response_time_seconds", "double");
```

**Comment by pirgeo** [comment]
I think what you are asking here is more or less what the Hints/Advice API will be for. See https://github.com/open-telemetry/opentelemetry-specification/pull/3216.

**Comment by careless6666** [comment]
Yes, that's just what I need
