### ISSUE TITLE
net.peer.name in HTTP client semconv is both Required and also mentions "SHOULD NOT be set if"

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3273]
Currently `net.peer.name` is marked as Required, but in its description it also says

> SHOULD NOT be set if capturing it would require an extra DNS lookup

which seems contradictory.

**Question:** When an HTTP request is explicitly sent to an IP address, e.g. `http://x.x.x.x:8080`, should we be capturing `net.peer.name` of `x.x.x.x`? or not capturing any `net.peer.name`?

cc @lmolkova @Oberon00

**Comment by lmolkova** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/ec84e5dcd77f36e79c0fe9bb1444d62be79dbb38/specification/trace/semantic_conventions/span-general.md?plain=1#L141-L149

I.e. if you know the url which happened to be `http://x.x.x.x` - then `x.x.x.x` becomes peer name.
If you know only x.x.x.x and know it's an IP address, `net.peer.name` should not be set.

It sounds complex. but I don't see a contradiction.

I'm open to reduce complexity and use IP if only IP is available. We can't guarantee low cardinality in edge cases anyway.

**Comment by Oberon00** [comment]
> If you know only x.x.x.x and know it's an IP address, net.peer.name should not be set.

IMHO in the HTTP conventions `net.peer.name` should be set to the IP in this case, since that's also the name that was used to connect and thus in this context "the name of logical remote destination". It also avoid special cases in the backend.

**Comment by trask** [comment]
> IMHO in the HTTP conventions `net.peer.name` should be set to the IP in this case (if the x.x.x.x is what the user passed in the API, or as part of the URL), since that's also the name that was used to connect and thus in this context "the name of logical remote destination". It also avoids special cases in the backend.

fwiw I think this is what the Java instrumentation does today (cc @laurit to correct me if that's not the case)

> Personally, I would even say that `net.peer.name` and `net.peer.port` should not be required and perhaps not even listed explicitly (less than opt-in), since http.url is already required and the other things are redundant information, but probably that was discussed as well on #2469.

These are important for metrics, which I think makes them important for span-to-metrics pipelines.

Also, having metric attributes always be a subset of span attributes makes unifying those signals behind a single "instrumentation api" simpler.

**Comment by mateuszrzeszutek** [comment]
> fwiw I think this is what the Java instrumentation does today (cc @laurit to correct me if that's not the case)

Not Lauri but I'm pretty sure we're always using the logical address for `net.peer.name` - and if the URL contains an IP address, then it's an IP address.
