### ISSUE TITLE
Exporter configuration

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#328]
I still need to do some renaming in the Erlang implementation to match the spec, but I completed implementation of the exporter process yesterday (https://github.com/open-telemetry/opentelemetry-erlang) and had chose a different strategy which I planned to bring up as an otep because I didn't realize there was already a spec that mostly covered it :)

I wanted to still mention it before switching to the current spec in case others think it could be useful as an update/option to the current spec.

Basically the difference is that `maxQueueSize` is not checked when finishing a span and it does not drop a span if it has reached the max. Instead, the exporter continually checks the queue size and if it reaches the configured maximum it kills the current export process, if one is ongoing, and immediately calls the exporter on the current queue. So there will potentially be dropped span, just not as a blocking operation when finishing a span.

---

Sort of unrelated, I think `maxExportBatchSize` should be optional to support. There is already a max queue size and in some implementations it may be more efficient to not do any additional batching.

For example, the Erlang impl stores finished spans in a shared in-memory table, after `scheduledDelayMillis` it points future finished spans to a new table and the former table is passed to the user configured `exporter` (with precautions so that it can't be written to again). The exporter can read as many or as a few of the spans at a time from the table.

Only a reference to the table is passed as an argument, not the actual spans. To support a batch size would entail extra processing and memory usage to read the batch size spans from the table into the process's heap.

Actually, went ahead and opened a PR to make the max export batch size a "MAY" part of the spec: https://github.com/open-telemetry/opentelemetry-specification/pull/327

**Comment by andrewhsu** [comment]
from the spec sig today, curious to know if this issue needs another PR to resolve since #327 was closed?

**Comment by andrewhsu** [comment]
may need more guidance on prioritization, setting to P2 for now

**Comment by tsloughter** [comment]
@andrewhsu I will close this.

I think the SDK spec should be looser on its requirements since there are multiple ways to achieve the same goal that have different implications on performance for different languages/runtimes, but I also don't think this issue is clear on that and would be better done with a new PR, or a new issue if I find it needs more discussion before a PR.
