### ISSUE TITLE
Should HTTP semantic conventions say anything about nested spans?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3281]
For example:

* Should nesting of HTTP server spans not be allowed?

* Should nesting of HTTP client spans be allowed?

**Comment by scheler** [comment]
Just asking out of curiousity. What is the guidance on the span kind proxies should use for the span they emit, if they emit only one span? Or are they required to emit 2 spans, one server and one client?

**Comment by trask** [comment]
Discussed in today's semconv meeting, and closing because the issue primarily because nesting is more of a "cross-instrumentation" issue which should be handled at a higher level (specifically see https://github.com/open-telemetry/oteps/pull/172)

**Comment by trask** [comment]
> Just asking out of curiousity. What is the guidance on the span kind proxies should use for the span they emit, if they emit only one span? Or are they required to emit 2 spans, one server and one client?

hey @scheler, I don't think there's any specific guidance yet for this case, I'd suggest emitting 2 spans myself, as that would fit the current conventions (and probably the majority of backends).
