### ISSUE TITLE
Define arbitrary metric units singularly

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#3295]
Arbitrary units needs to be defined as the singular value they measure. Given a unit is a quantity chosen as a standard in terms of which other quantities may be expressed, defining these as plurals introduces a ambiguity of how many of the quantity constitutes the unit.

Defining a unit as `{request}` clearly implies that __a__ request is represented as 1. Defining the same as `{requests}` could mean that a value of 1 equals a batch of requests.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-specification/pull/3294#discussion_r1127077282_

**Comment by trask** [comment]
Added this to HTTP semconv blockers since HTTP semconv currently uses plural `{requests}`

**Comment by jmacd** [comment]
I feel mixed about this. The UCUM specification uses the example `or “{RBC}” (for “red blood cells”) as pseudo-units` which, while not a specification, has always led me to think pseudo-units should be plural forms. The other example I found is ["Parts-Per"](https://en.wikipedia.org/wiki/Parts-per_notation) notation which uses "parts", again a plural, as the pseudo-unit.

**Comment by MrAlias** [comment]
This example `“{RBC}” (for “red blood cells”)` is inconsistent in the UCUM FWIW:

![20230307_105536](https://user-images.githubusercontent.com/5543599/223523153-77fc9ab4-b2d4-46bb-be42-d649b7791ee0.png)

It means "red blood cell" in the non-unit code table.

As for "parts per N" units, they included to support SI but are provided to be used only where absolutely necessary. They are not endorsed by the UCUM.

More generally, all the other UCUM units are defined singularly (`meter`, `second`, `gram`, ...). Defining a unit plurally would mean that the quantity reported uses as a base non-unity quantities as the standard measurement. Meaning if we defined `{20 requests}` as a unit and reported `2` the value can be interpreted as 40 requests. However if we just define `{requests}` it is an undefined measure which we are using as the base. This ambiguity is removed by clearly specifying in the grammar that we consider the unit to be one request, as in `{request}`, and from there any reported value has a clear gauge it is measuring against.

**Comment by jmacd** [comment]
Thank you @MrAlias.
