### ISSUE TITLE
Consider adopting ECS convention for logging spec's Trace Context in Legacy Formats

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3303]
Currently, the logging spec's [Trace Context in Legacy Formats](
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#trace-context-in-legacy-formats) says:

> the following field names should be used in legacy formats:
>
> "trace_id" for [TraceId](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-traceid), hex-encoded.
"span_id" for [SpanId](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-spanid), hex-encoded.
"trace_flags" for [trace flags](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-traceflags), formatted according to W3C traceflags format.

I think it's worth considering using instead the ECS field names `trace.id`, `span.id` and `trace.flags`.

Related: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7985

cc @AlexanderWert

**Comment by dashpole** [comment]
Is this issue still being considered?  I see https://github.com/elastic/ecs-logging-java/issues/214#issuecomment-1733893266, #3469, and #3518 suggest we are planning to keep the current field names.

I'm interested in seeing https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/logging_trace_context.md reach stability, and this appears to be the only related issue.

@jack-berg @tigrannajaryan

**Comment by tigrannajaryan** [comment]
I think the conclusion in https://github.com/open-telemetry/opentelemetry-specification/issues/3518 was that we keep the names. It has been a while and there is no new evidence that we need to do something else so I suggest that we submit a PR that declares https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/logging_trace_context.md "Stable" and closes this issue.
@dashpole do you want to do it?

**Comment by dashpole** [comment]
PR: https://github.com/open-telemetry/opentelemetry-specification/pull/3909

**Comment by svrnm** [comment]
@open-telemetry/technical-committee please take a look, the PRs related to this have been auto-closed, is this something that is done or that needs additional attention?
