### ISSUE TITLE
Project Tracking: JVM runtime metrics stability

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3311]
### Description

The OpenTelemetry Java community would like to stabilize JVM runtime metrics in order to help native adoption of the OTel Metrics API among key Java frameworks such as MicroProfile.

### Project Board

https://github.com/orgs/open-telemetry/projects/49

### Deliverables

* Mark the [JVM runtime metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics) as stable.
* Update existing OpenTelemetry JVM runtime metrics instrumentation to conform with the stable conventions.

### Staffing / Help Wanted

The goal is to follow @tedsuo's proposed [Semantic Convention Process](https://docs.google.com/document/d/1ghvajKaipiNZso3fDtyNxU7x1zx0_Eyd02OGpMGEpLE/edit#heading=h.xc2ft2cddhny).

* __Stage 1__: Working Group Preparation
* __Stage 2__: Stabilizing the Specification
* __Stage 3__: Implementation (we expect this to be a very short or non-existent)

#### Required staffing for Stage 1 and 2

* @trask project lead
* @jack-berg technical committee sponsor
* domain experts:
  * @breedx-splk
  * @jonatan-ivanov
  * @kittylyst
  * @PeterF778
  * @fstab
  * @donbourne
  * @zeitlinger
  * @vijaysun-omr

### Meeting Times

April 17 - May 26 (6 weeks):

* Tuesdays 10:00-10:30 Pacific Time
* Thursdays 9:00-10:00 Pacific Time (this is the regular weekly Java meeting)
* Fridays 8:30-9:00 Pacific Time

### Timeline

__Stage 1__ (Working Group Preparation) is happening now.

__Stage 2__ (Stabilizing the Specification) will begin as soon as we have adequate staffing for this project, and we coordinate a weekly meeting times (currently targeting mid-april).

__Stage 3__ (Implementation) will begin as soon as the JVM runtime metrics are marked stable, and it should be relatively short since we only need to update conformance to the specification for a single language.

### Labels

The tracking issue should be properly labeled to indicate what parts of the specification it is focused on.

### Linked Issues and PRs

All PRs, Issues, and OTEPs related to the project should link back to the tracking issue, so that they can be easily found.

**Comment by edburns** [comment]
Hello @tigrannajaryan just checking in. Any update on this one?

**Comment by trask** [comment]
hi @edburns! we are still in the "staffing" phase for this working group / project

poking folks who may be interested...

@brunobat @breedx-splk @donbourne @Emily-Jiang @fstab @jackshirazi @jeanbisutti @jsuereth @jonatan-ivanov @kittylyst @laurit @mateuszrzeszutek @PeterF778 @rapphil @roberttoyonaga @tylerbenson @zeitlinger

please ping back on this issue this week, I will send out a meeting time poll next week for folks who would like to participate

**Comment by breedx-splk** [comment]
I'll join the working group again. Thanks!

**Comment by jonatan-ivanov** [comment]
Please sign me up too. Thank you!

**Comment by kittylyst** [comment]
I'm in too! Thanks for thinking of me.

**Comment by PeterF778** [comment]
Please count me in. Thanks!
Peter Findeisen

________________________________

**Comment by fstab** [comment]
Please sign me up too. Thank you!

**Comment by trask** [comment]
@jack-berg @breedx-splk @jonatan-ivanov @kittylyst @PeterF778 @fstab (and anyone else who still wants to join!) please add your availability to https://strawpoll.com/polls/jVyG8xKxYn7

the goal is to schedule two 30-minute meetings a week for 6 weeks, starting next week.

we'll set aside some time in the weekly Thu Java meeting to touch base on this work also.

@open-telemetry/technical-committee since this is a language-specific working group, I'm comfortable moving forward with only one Technical Committee member (@jack-berg)

@Emily-Jiang @donbourne it would be great if someone from MicroProfile is able to join this working group

**Comment by zeitlinger** [comment]
Please include me as well - thanks.

**Comment by trask** [comment]
thank you all for voting!!

results are in, and we will be meeting:
* Tuesdays 10:00-10:30 Pacific Time
* Thursdays 9:00-10:00 Pacific Time (this is the regular weekly Java meeting)
* Fridays 8:30-9:00 Pacific Time

for the next 6 weeks.

the google calendar is updated with these meetings: https://calendar.google.com/calendar?cid=Z29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

and you can subscribe to the google calendar invites by joining this google group https://groups.google.com/g/opentelemetry-calendar-java

we will use the [`#otel-java`](https://cloud-native.slack.com/archives/C014L2KCTE3) slack channel for async discussions

**Comment by vijaysun-omr** [comment]
My email address is not registered on the CNCF slack it seems, and so I cannot join the slack channel that was mentioned on today's call at the moment.

**Comment by donbourne** [comment]
Same -- my email address is not registered on CNCF slack.  Anyone know how to get an invite to that?

**Comment by trask** [comment]
@vijaysun-omr @donbourne you should be able to create an account here: http://slack.cncf.io/, let me know if that works, thx!

**Comment by donbourne** [comment]
Thanks @trask , that worked!

**Comment by edburns** [comment]
Checking in again on this @trask any update?

**Comment by trask** [comment]
hi @edburns, sorry for the late reply! we just released the very first stable semantic convention ([HTTP](https://opentelemetry.io/blog/2023/http-conventions-declared-stable/)).

the Java SIG discussed the JVM semconv stability timeline yesterday, and we are going to see if we can finish this effort in time for our mid-December Java release

**Comment by trask** [comment]
JVM metrics will be stable with the next semantic convention release, which will hopefully be later this week.

**Comment by donbourne** [comment]
@trask , I think @vijaysun-omr has a minor correction coming later today... about OpenJ9 vs. J9 terms

**Comment by vijaysun-omr** [comment]
Yes it is just a minor correction that maybe @trask can just make, "OpenJ9" is the name to use rather than "J9"

**Comment by trask** [comment]
Closing, JVM runtime metrics semconv is now stable, and OpenTelemetry Java Instrumentation 2.0.0 is released which now emits them!
