### ISSUE TITLE
Add a Glossarry to explain the specification vocabulary

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#332]
We are using certain vocabulary in the specification that is not defined anywhere. It would be very useful to have a Glossary document that describes all concepts as they are understood by OpenTelemetry Specification. An incomplete list of concepts that likely need clarification because they are used throughout the specification:

- API
- SDK
- Trace
- Span
- Tracer
- Metric
- Meter
- Attribute
- Resource
- Label
- Context
- Distributed Context

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev I think it would be good to include this in the next milestone. What do you think?

**Comment by jmacd** [comment]
This is an excellent proposal. When it comes time to get specific, I've tried to avoid using "Metric" without a qualifier, as it has a lot of connotations. The spec uses "Metric instrument" to refer to the thing you handle in a program, "Metric exporter" to refer to the thing that outputs data. "Metric" by itself is not very meaningful.

**Comment by tigrannajaryan** [comment]
Apparently we have parts of this already specified in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md
I haven't seen this document before.

**Comment by Oberon00** [comment]
It seems we did part of this by now.

**Comment by andrewhsu** [comment]
Looks like we also have a `glossary.md` file https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md as well as the `overview.md`
