### ISSUE TITLE
Promethus Exemplar Compatibility

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-specification#3325]
Prometheus has decided to [support exemplars on all metric types](https://github.com/prometheus/prometheus/issues/11982).  This is [not in compliance](https://github.com/OpenObservability/OpenMetrics/issues/241#issuecomment-1383967346) with the OpenMetrics spec and presents compatibility concerns given that [our compatibility requirements](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#exemplars-1) align with OpenMetrics and Collector compatibility testing [breaks with the latest Prometheus RC](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19636).  Additionally, the [`SummaryDataPoint` type in OTLP](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L576) does not include support for exemplars, which will prevent successfully converting metrics from Prometheus to OTLP and back.

**Comment by jsuereth** [comment]
@fstab Please include me in future communications.  I think having a call between Prometheus / OpenMetrics / OTEL would be good.  I don't see any reason why we can't add exemplars to Summary metrics for prometheus compatibility.

Also, I'm glad to see support expanded for other metric types!

**Comment by codeboten** [comment]
Has there been any progress on this issue? Seeing as it's been a few months since it was raised

**Comment by jsuereth** [comment]
Revisiting this issue.

- It appears like the only "breaking" change was a compliance test were we were attempting to enforce that sending exemplars *fails* on prometheus (i.e. a negative test).  AFAICT, this never would have broken users of OpenTelemetry sending exemplars to prometheus.
- Regarding Exemplars themselves, we can just update the Prometheus<->OpenTelemetry specification here to resolve the issue.


I do *not* think we want to expand Summary to support exemplars, but if we see demand from the Prometheus community we can entertain this.

**Comment by dashpole** [comment]
I don't have any plans to implement exemplars for summary metrics, and I haven't personally heard any interest from users.  I'm not opposed to the addition, as it might be useful in niche situations, but it does seem like more effort than it would be worth at this point.

**Comment by jsuereth** [comment]
Closing this as unplanned.  We can reopen in the future if we feel summary metrics need exemplar support in OTLP.
