### ISSUE TITLE
Getting exception while using PeriodicExportingMetricReader from export library

### ISSUE THREAD

**Issue by Chiraguthra** [open-telemetry/opentelemetry-specification#3356]
Hi Team,

After importing following
**from opentelemetry.sdk.metrics.export import (
    ConsoleMetricExporter,
    PeriodicExportingMetricReader,**

metric_reader = PeriodicExportingMetricReader(OTLPMetricExporter(endpoint="http://localhost:4317", insecure=True), export_interval_millis=60000)

getting following exception every 60 seconds. Though its not impacting functionality and able to export metrics successfully, but still getting following error in logs.

**Exception: Invalid type <class 'NoneType'> of value None
File "/usr/local/lib/python3.8/dist-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 299, in _translate_attributes**

Could you please help here, what could be wrong in configuration ?

Thanks.

**Comment by pirgeo** [comment]
Hi, this is the OpenTelemetry Specification repository. It seems your error is a Python error, so please try https://github.com/open-telemetry/opentelemetry-python or join [the OpenTelemetry Python channel](https://cloud-native.slack.com/archives/C01PD4HUVBL) on the CNCF slack. In my experience, the Slack channel is usually the easiest and quickest way to get help.

**Comment by arminru** [comment]
https://github.com/open-telemetry/opentelemetry-python/issues/3246 was created instead
