### ISSUE TITLE
`http.server.active_requests` and `http.status_code`

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-specification#3357]
I have a question about `http.server.active_requests` from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#metric-httpserveractive_requests

`http.server.active_requests` is an up/down counter with a bunch of tags. One of the tags is the response status code. How does that work with an up/down counter? Response status code isn't known when the counter is incremented, so it can only be applied when the counter is decremented.

If the response status code is added to the tag collection when decrementing the counter, won't that result in two different values, one always increasing, and the other (with the response status code) always decreasing?

**Comment by mateuszrzeszutek** [comment]
Also it looks like the active requests counter does not have the `net.protocol.name` & `net.protocol.version` attributes (unlike all the other HTTP metrics); it used to have `http.flavor` before we made the change to `net.protocol.*`.

cc @trask @lmolkova

**Comment by trask** [comment]
Discussed in Semantic Conventions WG yesterday, and there are two actions we should take:

* remove `http.status_code` attribute from `http.server.active_requests` metric
* add a note to [general metric semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md) about UpDownCounter metrics needing to ensure the same attribute set is always recorded on both up/down
