### ISSUE TITLE
Should file configuration schema live in a separate repository?

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#3379]
As discussed [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3360#discussion_r1157370325) the file configuration scheme will likely have versioning and stability guarantees that are different that the [spec's](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md). Also, there will eventually need to be additional build steps that confirm that changes to the schema are syntactically correct and allowed, similar to the build steps in place for [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/.github/workflows/build-check.yaml).

This suggests that it may be appropriate for the the configuration schema to live in its own repository. A counterargument is that separating the schema from the specification text that references it may cause confusion and require more coordination when making changes that impact both.

Do we want to move the file configuration schema to its own repository? If so, when is the appropriate time to move it?

**Comment by reyang** [comment]
Q: Do we want to move the file configuration schema to its own repository?
My vote: YES.

Q: If so, when is the appropriate time to move it?
My vote: Now (ideally before we start).

**Comment by jack-berg** [comment]
I opened this community issue [#1425](https://github.com/open-telemetry/community/issues/1425).

I don't think #3360 should be blocked by this because the schema is trivial at this point, so will go ahead and merge it. Let's hold off on additional schema changes until the new repo is set up.
