### ISSUE TITLE
TracerFactory and processors/exporters.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#339]
I searched through the discussion on named tracers, and couldn't find anything related to registration of exporters/processors. It is mentioned that **configuration** should be available to all the named tracers, so they can consume it, but that's it.

For example:

```java
Tracer tracer = tracerFactory.get("mainApp");
tracer.addSpanProcessor(new MySpanProcessor());
...
Tracer tracer = tracerFactory.get("myInstrumentedLibrary71");
tracer.addSpanProcessor(new MySpanProcessor());
```

In the second piece, do we expect to not share any processor by the different tracers **at all**, OR to inherit or share them in one or another way? I *feel* this is something that would be nice to have clear and documented ;)

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#span-processor

**Comment by bogdandrutu** [comment]
addSpanProcessor should be a method on the `TracerFactory` based on the specs I linked.

**Comment by carlosalberto** [comment]
Ah, my bad ;( Thanks for pointing that out. Somehow I had missed it. Closing this issue.
