### ISSUE TITLE
Mark ExplicitBucketBoundaries hint API as stable

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3391]
**What are you trying to achieve?**

Mark ExplicitBucketBoundaries hint API as stable since this will be required for emitting HTTP semantic conventions now that we are changing `http.server.duration` and `http.client.duration` unit from milliseconds to seconds (see #3390).

**Comment by trask** [comment]
ya, the HTTP semconv stability WG would be very grateful if any other languages besides Java can implement since it is required for HTTP semconv stability

**Comment by trask** [comment]
@reyang will be prototyping in .NET ❤️ 

we will need to prototype in one more language

cc @open-telemetry/python-approvers @open-telemetry/cpp-approvers @open-telemetry/javascript-approvers @open-telemetry/go-approvers 🤞

**Comment by MrAlias** [comment]
Go might be able to prototype this in a few weeks if we stabilize the metric API first.

**Comment by trask** [comment]
related #3621

**Comment by trask** [comment]
related #3622

**Comment by dyladan** [comment]
JS prototype looks fine to me

**Comment by MrAlias** [comment]
I think we need resolutions to the following issues before we can proceed with this:

- [ ] https://github.com/open-telemetry/opentelemetry-specification/issues/3621
- [ ] https://github.com/open-telemetry/opentelemetry-specification/issues/3622

**Comment by trask** [comment]
Just checking in on this, I think we only have 2 of the 3 required prototypes needed to mark this stable:

* [Java](https://github.com/open-telemetry/opentelemetry-java/pull/5217)
* [JS](https://github.com/open-telemetry/opentelemetry-js/pull/3876)

**Comment by MrAlias** [comment]
@trask: Go prototype https://github.com/open-telemetry/opentelemetry-go/pull/4341

**Comment by albertored** [comment]
A little late but also Erlang/Elixir implementation is in PR https://github.com/open-telemetry/opentelemetry-erlang/pull/628
