### ISSUE TITLE
Consider removing include_trace_context from "Get a Logger" API

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3394]
include_trace_context parameter has been a source of confusion (see for example [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3387/files#r1165490278)).

I suggest to remove it for now. It is supposed to be an optional parameter, so it can be added later as an optional parameter after we understand its behavior and interaction with the rest of context functionality better. We have a precedent of adding optional parameters to Stable APIs in the past, so it is OK to do so after the Bridge API is declared Stable.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-logs-approvers @scheler @MSNev FYI.

**Comment by jack-berg** [comment]
I think we should remove it.

If you look at the git history, the parameter was originally added as part of the event API in #2676. Note that we didn't have an explicit `Context` parameter at the time.

Later in #2941 we split out the events API from the logs API, but kept the `include_trace_context` parameter.

Later in #2927 we added an explicit `Context` parameter, and didn't do a good job of defining how that context parameter interacts with `include_trace_context`.

As mentioned [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3387/files#r1165714401) I don't see how `include_trace_context` is anything but syntactic sugar for explicitly setting `Context` to empty. And I can't see how it serves any purpose at all in languages that require explicit context injection.
