### ISSUE TITLE
Is custom random generation a requirement for SDK or not?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#34]
See https://github.com/open-telemetry/opentelemetry-java/issues/325. 

> The random generation of the Trace/Span id will be in the SDK. Main reason is that for example to support Amazon X-Ray the TraceID needs to be a specific format for example, also that is an implementation detail.

The question is whether it is a requirement for SDK to allow custom ID generators.

**Comment by SergeyKanzhelev** [comment]
from @tedsuo - taking dependency on the format of TraceID is dangerous practice and we may want to discourage it. So making it a requirement to spec may not be desirable. Perhaps it can be optional feature.

**Comment by jmacd** [comment]
We believe this is not a requirement, now that the sampling hint has been removed from the API. An SDK is free to use its own generator.
