### ISSUE TITLE
add optional "service.domain" resource attribute

### ISSUE THREAD

**Issue by loomis-relativity** [open-telemetry/opentelemetry-specification#3401]
**What are you trying to achieve?**

The company I work for operates a complex SaaS product with a large number of interacting microservices. These are organized hierarchically into systems that provide a distinct low-level features of the platform. For engineering purposes, using the `service.name` to identify individual components and `service.namespace` for grouping works well. However, when viewing the platform from the customer's perspective, further grouping into high-level features is desirable. A new, optional attribute would allow for another level of grouping.

**The proposal is to add a `service.domain` attribute with a string value to the "Service (Experimental)" attributes.**

**Additional context.**

- Is an empty `service.domain` value allowed?

Yes. Like `service.namespace`, the empty string for the `service.domain` attribute is allowed. This is interpreted as a valid, empty domain; this is equivalent to omitting the `service.domain` attribute entirely.

- Does `service.domain` participate in creating a unique service identifier?

No. The proposal is that the globally unique identifier for a service stays as the triplet `service.namespace`/`service.name`/`service.instance.id`. The `service.domain` attribute allows for grouping of services/namespaces without affecting the identity of the service.

- Why standardize this in the specification?

Such an identifier can be added as a company-specific attribute. However, we believe that the need for grouping services in larger organizations will be a common requirement. Having this defined within the specification allows vendors to build general visualizations to take advantage of this grouping; something that they're hesitant to do without it being part of the specification.

- Why the name `service.domain`? 

Our company uses [Backstage](https://backstage.io/) to catalog the services within the platform for our engineers. The name comes from Backstage's three-level organization: component (`service.name`), system (`service.namespace`), and domain (`service.domain`). In addition, "domain" is used elsewhere within the specification (e.g. `event.domain`) to signify a high-level grouping.

**Comment by tigrannajaryan** [comment]
Can you please add an example of a `service.domain`? Is it totally orthogonal to `service.namespace`?

**Comment by cyrille-leclerc** [comment]
At Grafana, we thought about similar concepts to associate services to on call teams.
Interestingly, we felt that if this metadata will be slightly different from existing resource attributes because the value of this attribute is likely to be changed without redeploying the services (eg reorg of teams) and thus be more a query time attribute provided.

**Comment by loomis-relativity** [comment]
> Can you please add an example of a `service.domain`?

The values of `service.domain` will depend on how the organization wants to segment their services. We have considered having `service.domain` represent organizational boundaries (e.g. `ai` department), geographic deployments (`europe`), or high-level features of the platform (e.g. `authn`). 

In our case, we've decided on using high-level features. Having these attributes within the telemetry makes it easier for us to roll up performance/health information by feature. This, in turn, helps customer support verify whether customer incidents correspond to anomalies in the platform. 

> Is it totally orthogonal to `service.namespace`?

I don't think this should participate in the identity of a service, so yes, it should be completely orthogonal to `service.namespace`.

**Comment by tigrannajaryan** [comment]
> The values of `service.domain` will depend on how the organization wants to segment their services. We have considered having `service.domain` represent organizational boundaries (e.g. `ai` department), geographic deployments (`europe`), or high-level features of the platform (e.g. `authn`).

What happens if you want to record more than one of these? Do we allow `service.domain` to be a list of key/value pairs?

Thinking more about this based on the comments above, this sounds more like a need to record arbitrary non-identifying attributes of the Service. To me this is yet another reason to introduce Entities as a first-class concept (a Service would be an entity and you can record `department`, `geography` and `features` as non-identifying attributes on it - without necessarily placing the attributes under the `service.` namespace). cc @jsuereth 

>Interestingly, we felt that if this metadata will be slightly different from existing resource attributes because the value of this attribute is likely to be changed without redeploying the services (eg reorg of teams)

This is precisely how @jsuereth and I see Entities - we allow non-identifying attributes to change over time.

>thus be more a query time attribute provided.

I don't see why this is a query time vs collection time dichotomy.

**Comment by cyrille-leclerc** [comment]
>> @cyrille-leclerc: thus be more a query time attribute provided.
> @tigrannajaryan: I don't see why this is a query time vs collection time dichotomy.

It's related to our persistence of time series that is insert only. 
As you rightly said "non-identifying attributes to change over time" and thus we need to persist them in a different storage and join them at query time.

**Comment by loomis-relativity** [comment]
`service.node.roles` appears to cover this use case within the Elastic Common Schema; closing this issue.
