### ISSUE TITLE
JVM metrics use attributes which aren't namespaced

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3417]
Currently JVM metrics use attributes that aren't namespaced:

* `pool`
* `type`
* `gc`
* `action`
* `daemon`

One of the goals of using namespaced attributes everywhere is that they could also be used (and make sense) in logs.

This topic (whether metric attributes should be namespaced or not) is also being discuss in #3342.

cc @bertysentry @jsuereth

**Comment by mateuszrzeszutek** [comment]
About `daemon`: we already have `thread.id` and `thread.name` span attributes, renaming it to `thread.daemon` would be a simple and fitting change.

**Comment by trask** [comment]
I opened #3424 to specifically discuss `pool.name`

**Comment by trask** [comment]
Some (verbose) options for the other 3:

* `type` -> `process.runtime.jvm.memory.type`
* `gc` -> `process.runtime.jvm.gc.name`
* `action` -> `process.runtime.jvm.gc.action`

**Comment by bertysentry** [comment]
I'm repeating myself, but I'm concerned that prefixing all metric attributes with namespaces, like `process.runtime.jvm.*` is getting us something clumsy to use, even from a UI/UX perspective. PromQL, NRQL or equivalent queries will just get much longer:

```
process.runtime.jvm.memory.committed{process.runtime.jvm.memory.type="heap",process.runtime.jvm.memory.pool="..."}
```

vs

```
process.runtime.jvm.memory.committed{type="heap", pool="..."}
```

We should consider that the attribute is *"attached"* to the metric, which already has a proper namespace. Duplicating the namespace on each attribute seems therefore counter-productive and doesn't add any value (except when there is a similar attribute in Spans or Logs semantic conventions). 

Also, I don't see other observability platforms following the same pattern (Prometheus, Datadog, New Relic, to name a few).

> **Note**
> Going even further, I would have recommended to remove the `process.runtime.` prefix, because it doesn't add any useful information. Nobody can query something like `process.runtime.*.memory.committed` to get the memory on *any* type of runtime. Therefore `jvm.memory.committed` was enough to uniquely qualify the metric.).
> The above query would have become `jvm.memory.committed{type="heap", pool="..."}` which is even better. But this is another discussion 😉

**Comment by trask** [comment]
I sent #3431 to try to get community feedback on the (more general) concept of namespacing metric attributes.

In that PR I went with "minimal" namespacing, which I think would correspond here with:

* `pool` -> `pool.name`
* `type` -> `memory.type`
* `gc` -> `gc.name`
* `action` -> `gc.action`
* `daemon` -> `thread.daemon`

**Comment by jack-berg** [comment]
> In that PR I went with "minimal" namespacing, which I think would correspond here to something like:
>
>pool -> pool.name
type -> memory.type
gc -> gc.name
action -> gc.action
daemon -> thread.daemon

I like these options!

**Comment by trask** [comment]
Updating based on @PeterF778's https://github.com/open-telemetry/opentelemetry-specification/issues/3424#issuecomment-1516914756

* `pool` -> `memory.pool.name` and `buffer.pool.name`
* `type` -> `memory.type`
* `gc` -> `gc.name`
* `action` -> `gc.action`
* `daemon` -> `thread.daemon`

**Comment by trask** [comment]
we are unsure about `memory.pool.name` vs `pool.name`

**Comment by PeterF778** [comment]
My preference would be with `memory.pool.name`

**Comment by trask** [comment]
rambling thoughts/questions...

what if we had an event "retrieve connection" (from a connection pool), would we want attribute `connection.pool.name` or `pool.name`?

are there other attributes that make sense under `connection.*` or other connection pool attributes that make sense under `connection.pool.*`? (comment from @zeitlinger in WG meeting)

then there's the question about whether "memory pools" are the same or different enough from "object pools" to warrant separate naming (they are both pools of resources, but the interaction with them tends to be different)

luckily we only have to decide (from a stability perspective) what to name the memory pool attribute for now. from this perspective it seems the more conservative option may be to introduce `memory.pool.name` instead of introducing a more broad `pool.name`.

**Comment by PeterF778** [comment]
I think that the snippets `connection.pool `or `memory.pool `do not really reflect any hierarchy, they are just tokens with a qualifier. Perhaps we should use `connection_pool` and `memory_pool` instead.

**Comment by bertysentry** [comment]
I agree with @PeterF778. Let's not confuse namespaces and multi-word attributes.

A [namespace](https://en.wikipedia.org/wiki/Namespace) is useful to the spec writer in a given domain (let's say the semantic conventions for process metrics) to avoid naming conflicts with another domain it doesn't know (e.g. the semantic conventions for HTTP).

As metrics attributes cannot conflict with attributes with the same name but for another metric (see @tigrannajaryan's [comment on another PR](https://github.com/open-telemetry/opentelemetry-specification/pull/3431#issuecomment-1520885889)), and there is no traces/logs conventions for the JVM, I don't think we need to change `gc` to `gc.name`, or `type` to `memory.type`.

**Comment by trask** [comment]
> I think that the snippets `connection.pool `or `memory.pool `do not really reflect any hierarchy

#3431 proposes `memory.page_fault.type` attribute

> there is no traces/logs conventions for the JVM

we are trying to learn from ECS about log conventions, and a lot of what they do is provide a dictionary of common attributes which can be used on logs. something like `gc.name` and `memory.type` could be used to log GC events, for example

> I don't think we need to change `gc` to `gc.name`, or `type` to `memory.type`

I think #3431 is the testbed for whether metric attributes should be namespaced or not. I think we'll need to wait and see what the resolution is on that PR (it may require @open-telemetry/technical-committee to vote if it is contentious). I would guess JVM metric attributes will just follow suit (one way or the other) once that PR is decided.

**Comment by zeitlinger** [comment]
Despite waiting for #3431, I've already created a [draft PR](#3464) which renames the attributes as proposed in this issue.

**Comment by jack-berg** [comment]
> pool -> memory.pool.name and buffer.pool.name

How about `memory.pool_name` and `buffer.pool_name`? I don't think we anticipate having other attributes under `memory.pool.*` so seems unnecessary to create a pool namespace.

**Comment by trask** [comment]
> I don't think we anticipate having other attributes under `memory.pool.*` so seems unnecessary to create a pool namespace.

`memory.pool.size`?

**Comment by zeitlinger** [comment]
in the meeting, we decided to keep `memory.pool.name`, because the attributes can also be used in other signals - and `memory.pool.size` could be useful in a log message.

**Comment by trask** [comment]
Should we go ahead and namespace JVM metrics, given that we see benefit to using them to emit low-level GC events also?

**Comment by trask** [comment]
Replaced by https://github.com/open-telemetry/semantic-conventions/issues/61
