### ISSUE TITLE
Decide which JVM metrics should be included in initial stability

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3419]
If we don't want to include some of them in the initial stability we can split them out into a separate section in [runtime-environment-metrics.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md) titled "JVM Metrics (experimental)".

**Comment by trask** [comment]
The `process.runtime.jvm.buffer.*` don't seem critical for initial release if we want to leave them out.

**Comment by roberttoyonaga** [comment]
What do we think about stabilizing the [JFR gathered metrics?](https://github.com/open-telemetry/opentelemetry-specification/pull/3352) There's some useful ones like network IO, monitors, etc. But they would only apply to JDK17+.

**Comment by trask** [comment]
* `process.runtime.jvm.memory.usage`
* `process.runtime.jvm.memory.limit` (`.max`?)
* `process.runtime.jvm.memory.usage_after_last_gc`
* `process.runtime.jvm.gc.duration`
* `process.runtime.jvm.threads.count`
* `process.runtime.jvm.classes.loaded`
* `process.runtime.jvm.classes.unloaded`
* `process.runtime.jvm.classes.current_loaded`
* `process.runtime.jvm.cpu.utilization`

`.system` is confusing under `.process`

* `process.runtime.jvm.system.cpu.utilization`
* `process.runtime.jvm.system.cpu.load_1m`

No:

* `process.runtime.jvm.memory.init`
* `process.runtime.jvm.memory.committed`
* `process.runtime.jvm.buffer.usage`
* `process.runtime.jvm.buffer.limit`
* `process.runtime.jvm.buffer.count`

**Comment by vijaysun-omr** [comment]
Could you please clarify the thinking behind `process.runtime.jvm.memory.committed` being in the "No" list ?
