### ISSUE TITLE
Use uniform terminology for Span and Resource attributes

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#342]
We currently use the term "attribute" to describe arbitrary key/value pairs that can be added to `Span` [1], while for a similar concept of key/values pairs on `Resource` we use the term "label" [2].

I propose to make the terminology uniform and use the term "attribute" universally.

A separate question is whether we want to also support `Resource` "attributes" to support all data types that `Span` "attributes" allow (currently only string "labels" are allowed for `Resource`).

[1] - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#set-attributes
[2] https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-resource.md

**Comment by jmacd** [comment]
Sounds good. This leaves "label" with a special meaning exclusive to the metrics API.

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan I like how you differentiate bigger issue from this smaller improvement. I like the idea of merging those. I believe Resource labels came from some metrics work. But it doesn't look natural in OpenTelemetry

**Comment by Oberon00** [comment]
Is the remainder of this issue a subset of #446 ?

**Comment by bogdandrutu** [comment]
Closing this as the rest of the discussion happens in #446
