### ISSUE TITLE
Capture policy regarding non-exposure of generated Protobuf structs in the end user API

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3420]
This is related to https://github.com/open-telemetry/opentelemetry-go/issues/3455 which requests Go SDK to stop exposing the generated code in the API.

We don't have a policy or clarification anywhere that explains why this is prohibited.

My initial thoughts is that allowing has this benefit:
- It is convenient and avoids the creation of a wrappers that often 1 to 1 mirror the Protobuf structs. In the Collector we did wrappers and it certainly has non-negligible engineering cost (has its own generator for wrappers).

Downside:
- You take dependency on the generator behavior. If generator starts generating a different code your output can break. This is similar to taking a dependency on a library and using library's symbols in your own API. (BTW, we don't prohibit the later too).
- [ADDED] You force consumers of your API to take direct dependency on Protobuf library. With the separation of API and SDK that we have this can be avoided if the generated Protobuf structs are not part of the API you expose to your consumers. **Note:** This argument does not apply to SDKs, since the generated Protobufs structs and Protobuf library have to be dependencies of the SDK, by virtue of being required in the OTLP Exporter at the very minimum.

@bogdandrutu I would like to hear your thoughts on this topic since you have a strong opinion about this.

**Comment by dyladan** [comment]
@tigrannajaryan this was fixed in go and I don't think it's affecting any other languages. Do you think this is still needed?

**Comment by tigrannajaryan** [comment]
I think we can close it.
