### ISSUE TITLE
Allow metric instrument names to contain `/` characters

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#3422]
**What are you trying to achieve?**

Create instruments/metrics with names like `composer.googleapis.com/environment/database/auto_failover_request_count`:

- containing `/` characters
- exceeded 63 characters.

These types of metrics are very common in Google Cloud Monitoring ([examples](https://cloud.google.com/monitoring/api/metrics_gcp), notice the domain prefix is part of the metric) and we would like it to be possible to create such metrics with OTel instrumentation.

**What did you expect to see?**

It should be possible to create such an instrument e.g. in Python
```py
from opentelemetry.sdk.metrics import MeterProvider
MeterProvider().get_meter("foo").create_counter("composer.googleapis.com/environment/database/auto_failover_request_count")
```
However it fails with
```py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/aaronabbott/repo/opentelemetry-js/venvtmp/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/__init__.py", line 97, in create_counter
    instrument = _Counter(
  File "/usr/local/google/home/aaronabbott/repo/opentelemetry-js/venvtmp/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/instrument.py", line 56, in __init__
    raise Exception(_ERROR_MESSAGE.format(name))
Exception: Expected ASCII string of maximum length 63 characters but got composer.googleapis.com/environment/database/auto_failover_request_count
```

[As required by the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/metrics/api.md#instrument-name-syntax)

> - Subsequent characters must belong to the alphanumeric characters, '_', '.', and '-'.
> - They can have a maximum length of 63 characters.

**Additional context.**

Looks like this was introduced in https://github.com/open-telemetry/opentelemetry-specification/pull/1557 by @reyang and the oldest reference I could find to these requirements was in https://github.com/open-telemetry/opentelemetry-specification/pull/601 by @jmacd.

**Comment by MrAlias** [comment]
I'm pretty sure the original restriction is to ensure compatibility with Prometheus. If we drop the restriction it could mean our instrument names cannot be converted to Prometheus data.

**Comment by tsloughter** [comment]
Except for the length, right?

Might be better to open a separate issue about the 63 character length.

**Comment by reyang** [comment]
@aabmass here is my suggestion to move this forward:
1. List out the options you could think of.
2. Provide your suggestion, including which option you would suggest, what's the plan (e.g. if we "just remove the length restriction", it could break existing exporters/backends).

**Comment by aabmass** [comment]
> I'm pretty sure the original restriction is to ensure compatibility with Prometheus. If we drop the restriction it could mean our instrument names cannot be converted to Prometheus data.

We already allow `.` (and use it extensively in semantic conventions) which [prometheus doesn't allow](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). The [compatibility spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata-1) says to convert any invalid characters to `_` which we already do in this case.

I believe someone was from OTel contact with Prometheus folks about trying to allow additional characters.

**Comment by aabmass** [comment]
> 2\. what's the plan (e.g. if we "just remove the length restriction", it could break existing exporters/backends).

I don't think Prometheus has any length restrictions so collector exporters may already receive such metrics from a Prometheus receiver and probably others.

I agree it could break SDK exporters but I'm not aware of any that would run into this issue. We could definitely open it up and provide an option to truncate like we do for [attribute value limits](https://github.com/open-telemetry/opentelemetry-specification/blob/c210cf5884cf2c06dc1d1a6a34a4ea76c542841f/specification/common/README.md#attribute-limits). Do you have any specific SDK exporters in mind?

**Comment by reyang** [comment]
> Do you have any specific SDK exporters in mind?

Nope. I haven't spent time looking into the existing exporters.

**Comment by jmacd** [comment]
I support increasing the size limit. I worry that like dots, the slash character is not supported by Prometheus and it would be nice to investigate whether there are any technical reasons why Prometheus could not change their character set. In the case of dot, we could not find a technical reason.

**Comment by lmolkova** [comment]
Related: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/740 - .NET emits its own counters whose names don't fit into 63 characters and have to be abbreviated or truncated to meet 63 char limits, which is a quite small and arbitrary limit.

**Comment by trask** [comment]
we have also had problems with the length limit in Java: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6300

**Comment by trask** [comment]
we continue to get bug reports in Java related to the length restriction: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7448#issuecomment-1582846201

**Comment by reyang** [comment]
Update - I've also got folks asking for names that contain ` ` (SPC) character.

**Comment by B3zaleel** [comment]
> Related: [open-telemetry/opentelemetry-dotnet-contrib#740](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/740) - .NET emits its own counters with names that don't fit into 63 characters and have to be abbreviated or truncated to meet the limit, which seems quite small and arbitrary.

@lmolkova Counters that exceed that limit are disabled and are usually not exported.

**Comment by kes2464** [comment]
How about `:`? [Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) also allows colons if that is a concern.

**Comment by jack-berg** [comment]
@kes2464 can you open a new issue to discuss `:`?
