### ISSUE TITLE
Introduce common "pool.name" attribute

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3424]
Currently, [database metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/database-metrics.md) are using an attribute named `pool.name` (database connection pool name).

The [JVM runtime metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics) are using an attribute named `pool` (memory pool name).

Should we introduce a generic attribute for use across any kind of pool, e.g.

* `pool.name`

or should we introduce more specific attributes for each, e.g.

* `db.client.connection.pool.name`
* `process.runtime.jvm.memory.pool.name`
* `process.runtime.jvm.buffer.pool.name`

or should we do something in-between?

(related to #3417 and #3342)

**Comment by jack-berg** [comment]
>Should we introduce a generic attribute for use across any kind of pool, e.g.

I think this could be a good idea. Could define pool as a generic group of resources (note the lowercase "r", not to be confused with OpenTelemetry Resources). Some examples of use:

- Memory pools
- Object pools (database connections, buffer, any other reused object)
- Thread pools

**Comment by PeterF778** [comment]
I'm not sure that `pool.name` solves the original problem, which I think is _what pool?_ if used out of context, for example in logs. On the other hand, `process.runtime.jvm.memory.pool.name` is awfully long. How about `memory.pool`, `buffer.pool`, `connection.pool` etc.?

**Comment by trask** [comment]
Closing this in favor https://github.com/open-telemetry/opentelemetry-specification/issues/3417#issuecomment-1527730492

**Comment by reyang** [comment]
Before providing opinions, I wish to understand if this is a real problem or not:

1. What are the actual problems we're trying to solve here?
2. Do we think "pool" name is something that can/should be shared? (e.g. a TCP connection pool and a memory pool might be called "A" and "B" respectively, do we think someone want to query/aggregate across these names?)

**Comment by trask** [comment]
the problem is that the JVM runtime metrics [`process.runtime.jvm.memory.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmmemoryusage) and [`process.runtime.jvm.buffer.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmbufferusage) both have a metric attribute named `pool`.

if metric attributes end up required to be namespaced, we will need to rename those, and so we are considering two options:

Option A:
* `pool.name` for both [`process.runtime.jvm.memory.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmmemoryusage) and [`process.runtime.jvm.buffer.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmbufferusage)

Option B:
* `memory.pool.name` for [`process.runtime.jvm.memory.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmmemoryusage)
* `buffer.pool.name` for [`process.runtime.jvm.buffer.usage`](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#metric-processruntimejvmbufferusage)

> Do we think "pool" name is something that can/should be shared? (e.g. a TCP connection pool and a memory pool might be called "A" and "B" respectively, do we think someone want to query/aggregate across these names?)

no, although even `memory.pool.name` and `buffer.pool.name` may not be very aggregable outside of a specific metric, e.g. JVM memory pools and JVM buffer pools have very JVM-specific names

if that's important, we could go with `jvm.memory.pool.name`, or even `process.runtime.jvm.memory.pool.name`

**Comment by ChrsMark** [comment]
@trask +1 for option B. I see it is already discussed and decided at https://github.com/open-telemetry/opentelemetry-specification/issues/3417#issuecomment-1537837196, right?

**Comment by trask** [comment]
From JVM runtime metric WG:

There is general agreement on `memory.pool.name`, but want to confirm with @open-telemetry/technical-committee to make sure they don't have any strong or conflicting opinion
