### ISSUE TITLE
See what Java runtime metrics can learn from .NET runtime metrics

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3428]
OpenTelemetry .NET runtime metrics are defined at https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.Runtime

OpenTelemetry JVM runtime metrics are defined at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics

I didn't find much overlap, but would appreciate a second (and third) look.

I did find a couple of metrics which seem to be measuring the same thing more or less:
* .NET defines `process.runtime.dotnet.gc.collections.count` while Java defines `process.runtime.jvm.gc.duration` (as histogram which includes count)
* .NET defines `process.runtime.dotnet.thread_pool.threads.count` while Java defines `process.runtime.jvm.threads.count`

cc @open-telemetry/dotnet-contrib-approvers 
cc @open-telemetry/java-instrumentation-approvers

**Comment by breedx-splk** [comment]
The .net `process.runtime.dotnet.gc.allocations.size` (cumulative since process start) seems interesting at first glance. Watching that over time when troubleshooting GC/memory issues seems useful. I am not sure that we can easily get that same thing? Having heap usage is probably sufficient.
