### ISSUE TITLE
Project Tracking: Community Security Compliance SIG (Draft)

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-specification#3430]
### Description

I would like to propose the creation of the SIG Security. The Security SIG would be responsible for establishing the patterns to be adopted by other SIGs and repositories, as well as serve as a go-to place for security inquiries.

Security standards are critical to building enterprise trust in the project. Customers are increasingly asking about guarantees around the community closing security vulnerabilities in our assets. There is no set community standard of how we triage security vulnerabilities, accept reports from users, and then have the fixes released across our various SDKs and assets. 

This would NOT be a security response team (although we can kick off a discussion around that if needed).

### Project Board

Once approved by TC, a project should be managed using a GitHub project board. This project board should be pre-populated with issues that cover all known deliverables, organized by timeline milestones.

A [Technical Committee](https://github.com/open-telemetry/community/blob/main/community-members.md#technical-committee) (TC) member associated with the project can create the board, along with a new project-specific GitHub label to automatically associate issues and PRs with the project. The project lead and all other relevant project members should have edit access to the board.

Once created, please link to the project board here.

### Deliverables

A description of what this project is planning to deliver, or is in the process of delivering. This includes all OTEPs and their associated prototypes.

In general, OTEPs are not accepted unless they come with working prototypes available to review in at least two languages. Please discuss these requirements with a TC member before submitting an OTEP.

* Security standards for community Github actions/workflows/automations/secrets and repo settings
* A community bug / security vulnerability reporting mechanism
* Community triage process / and standard for [grading](https://nvd.nist.gov/vuln-metrics/cvss) of security vulnerabilities

### Staffing / Help Wanted

Software security experts that have experience in establishing norms around how an enterprise accepts and resolves security vulnerabilities in their software. 

Language maintainers or approvers as they will be tasked with implementing the changes and following through on the process.

#### Required staffing

Projects cannot be started until they the following participants have been identified:
* Every project needs a project lead, who is willing to bottom line the project and address any issues which are not handled by other project members.
* At least two sponsoring TC members. TC sponsors are dedicated to attending meetings, reviewing proposals, and in general being aware of the state of the project and it's technical details. TC sponsors guide the project through the spec process, keep the tracking issue up to date, and help to ensure that relevant community members provide input at the appropriate times.
* Engineers willing to write prototypes in at least two languages (if relevant to project). Languages should be fairly different from each other (for example: Java and Python).
* Maintainers or approvers from those languages committed to reviewing the prototypes.

tbd project lead
@jpkrohling domain expert
@cpanato domain expert
@cartersocha contributor
@tylerbenson java sig implementation

@reyang technical committee sponsor
**tbd** technical committee sponsor

Need: more security domain experts
Need: maintainers or approvers from several language sigs to participate 

### Meeting Times

Once a project is started, the working group should meet regularly for discussion. These meeting times should be posted on the OpenTelemetry public calendar.

### Timeline

What is the expected timeline the project will aim to adhere to, and what resources and deliverables will be needed for each portion of the timeline? If the project has not been started, please describe this timeline in relative terms (one month in, two weeks later, etc). If a project has started, please include actual dates.

**TBD**

### Labels

The tracking issue should be properly labeled to indicate what parts of the specification it is focused on.

### Linked Issues and PRs

https://github.com/open-telemetry/community/issues/1333

**Comment by reyang** [comment]
I'm willing to sponsor this effort from the Technical Committee.

We need to pick a proper name to avoid future confusion - I think there will be 1) this workstream to provide security/compliance guidelines for OpenTelemetry offerings (libs, collector, tools) 2) another workstream on security telemetry and schema https://github.com/open-telemetry/oteps/blob/d02a3e2e75dc934fb38c5db88eb41fbe85730af4/text/0199-support-elastic-common-schema-in-opentelemetry.md#the-goal.

**Comment by tylerbenson** [comment]
I'm willing to help on the Java side.

**Comment by cartersocha** [comment]
Will re-open in the community repo
