### ISSUE TITLE
Rename "process.runtime.*" metrics to "runtime.*"?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3432]
This would help with less verbose metric names, of which there are many, at least under `process.runtime.jvm.*` and `process.runtime.dotnet.*`.

We could go even further and have top-level for each language runtime, e.g. `jvm.*`, `dotnet.*`, though that may create top-level conflicts as there are probably a lot more runtimes than I'm aware of.

It doesn't seem like there's a strong argument for `runtime.*` being under `process.*`, since `process.*` itself isn't under `system.*`.

(sorry to be exploring more changes, but don't want to leave any rock unturned as we are currently working towards JVM runtime metric stability)

**Comment by reyang** [comment]
I prefer the current one since it encourages hierarchical view/organization (e.g. one can say "only show "process.*" metrics in the dashboard):

```
metrics
  +-- process
        +-- runtime
  +-- hardware
        +-- cpu
        +-- disk
  +-- kernel
        +-- driver
```

**Comment by trask** [comment]
Closing based on @reyang's feedback
