### ISSUE TITLE
Include "socket family" and/or OSI layer 3 "network type" in HTTP semconv?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3438]
from @AlexanderWert's https://github.com/open-telemetry/opentelemetry-specification/issues/3371#issuecomment-1519512541:

> > net.sock.family -> network.type: This sounds different from net.transport. It sounds like it would be set to LTE or Ethernet, etc (something currently stored in net.host.connection.type). Can we come up with a better name (network.sock_family)?
> 
> I think OTel's `net.sock.family` and ECS' `network.type` describe slightly different things (though related):
> 
> * `net.sock.family` refers to [Linux Address Families](https://man7.org/linux/man-pages/man7/address_families.7.html) which is not tied to a specific OSI Model layer (e.g. IPv4 / IPV6 is OSI Layer 3, while Bluetooth is Layer 2).
> * `network.type` refers to the [OSI Layer 3](https://osi-model.com/network-layer) explicitly as you can see in the [ECS description](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-type).
> 
> So, as those are describing different things, how about having both (`network.sock_family` and `network.type`)?
> 
> Regarding the name `network.type`, actually, the name describes what it is: the `type` of the OSI `network` layer (Layer 3).

the question remains, do we want to include either or both `network.type` and `network.socket.family` in the HTTP semantic conventions as part of initial stability?

**Comment by lmolkova** [comment]
`network.type` and `network.transport` should be enough to cover HTTP cases, but not [IPC](https://en.wikipedia.org/wiki/Inter-process_communication) communication (unix domain sockets, local IO, pipes, etc), or non-OSI stacks such as bluetooth. 

I believe we should relax ECS definitions beyond OSI and extend `network.transport` and `network.type` enums.
The alternative is that we maintain different attribute sets for OSI protocols and others and then it'd be hard to consume and understand this telemetry.

Current `net.transport` OTel attribute  already made an attempt there with `pipe` and `inproc` transports - we can keep extending it and define `unix` for local domains or `rfcomm` for bluetooth.  
[Python](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib%20NET_TRANSPORT&type=code) and [JS](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/565a2b2c6fde88af3f5401ef6a5a9643d0d66349/plugins/node/opentelemetry-instrumentation-net/src/utils.ts#L22) instrumentations already use set `unix` for `net.transport`.

With this correction, we can remove `net.sock.family`.

**Comment by lmolkova** [comment]
Ah, and `unix` was in `net.transport` enum, until someone removed it in #2614 🤐

**Comment by lmolkova** [comment]
> Last time I checked net.transport was a closed enum with a value "other" that would cover "everything else"

it'd still be nice to re-introduce `unix` (if we end up removing `net.sock.family`)
