### ISSUE TITLE
Naming consistency: "length" vs "size" vs "bytes" when for payload size

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3439]
Sometimes `length` is used:
* `http.request_content_length`
* `http.response_content_length`

Sometimes `size` is used:
* `message.compressed_size`
* `message.uncompressed_size`
* `http.server.request.size` (metric)
* `http.server.response.size` (metric)
* `http.client.request.size` (metric)
* `http.client.response.size` (metric)

Sometimes `size_bytes` is used:
* `messaging.message.payload_compressed_size_bytes`
* `messaging.message.payload_size_bytes`

ECS uses `bytes`
* `http.request.body.bytes`
* `http.response.body.bytes`

`size` makes the most sense to me personally, as `bytes` seems like it could be the actual bytes.

**Comment by lmolkova** [comment]
related: https://github.com/open-telemetry/opentelemetry-specification/issues/1053

**Comment by trask** [comment]
it looks like `.size` is a pretty good option given some existing ECS attributes are using it as well:

* [`package.size`](https://www.elastic.co/guide/en/ecs/current/ecs-package.html#field-package-size)
* [`file.size`](https://www.elastic.co/guide/en/ecs/current/ecs-file.html#field-file-size)
* [`email.attachments.file.size`](https://www.elastic.co/guide/en/ecs/current/ecs-email.html#field-email-attachments-file-size)
