### ISSUE TITLE
Where to capture HTTP forwarded proto (original url.scheme)?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3442]
[`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header provide a way to get the original `url.schema` that was used on the client side.

This is useful data, because often TLS is terminated before it reaches the application server, and so the SERVER span on the application server reports `url.scheme` of `http` (unsecured), which can cause users to worry that their traffic is unencrypted.

In #3402 we are now proposing to capture the ip (and optional port) from [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) into `client.address` (and `client.port`).

It would be nice to capture the `proto` field (original `url.scheme`) somewhere at the same time, so that we don't need to re-parse the Forwarded header for it later.

**Comment by AlexanderWert** [comment]
> It would be nice to capture the proto field (original url.scheme) somewhere at the same time, so that we don't need to re-parse the Forwarded header for it later.

How about a new field `url.original.scheme` (or `url.scheme.original`). The `url.*` namespace seems to be a good place for this information since the Forwarded `proto` describes an aspect of a URL.
