### ISSUE TITLE
Rename `process.runtime.jvm.buffer.*` metrics

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3483]
Rename `process.runtime.jvm.buffer.*` metrics to `process.runtime.jvm.buffers.*` based on guidance from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#pluralization (also similar to `system.processes.*`).

Also suggesting a couple other renames because buffer "usage" and "limit" don't seem super clear that they're about memory. And also these proposed names match the underlying MBean attributes.

So in total, proposing:

* `process.runtime.jvm.buffer.count` --> `process.runtime.jvm.buffers.count`  (maybe `.active` instead of `.count`, or maybe just dropping the `.count`, depending on outcome of other discussions)
* `process.runtime.jvm.buffer.usage` --> `process.runtime.jvm.buffers.memory_usage`
* `process.runtime.jvm.buffer.limit` --> `process.runtime.jvm.buffers.total_capacity`

Not adding this to JVM metric stability project since we are not planning to include these metrics in the initial stability.

**Comment by breedx-splk** [comment]
I like this. Just one small nitpicky bikeshedding tweak around `process.runtime.jvm.buffers.total_capacity`. 

I think the former `limit` carries with it some idea about maximum capacity, or upper achievable bounds. On the other hand, `total` seems to imply some summarized aggregation and can lose the fact that it's a boundary. With that, I'm proposing:

* `process.runtime.jvm.buffer.limit` --> `process.runtime.jvm.buffers.max_capacity`
