### ISSUE TITLE
Trace exception recording was never stabilized

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#3495]
Tracing specification used to rely on semantic conventions to define how to record an exception as a Span Event. With #3489 this normative language moves back into the tracing specification.  We will need to:

- Verify that the current language is enforced across SDKs
- Mark this part of the specification as stable

There were some unresolved "post-GA" issues that may need to be tackled for this:

- #764
- #1008

Additionally related, #3198

**Comment by austinlparker** [comment]
Is this still germane @jsuereth ?

**Comment by svrnm** [comment]
@jsuereth please take a look

**Comment by trask** [comment]
resolved by #3769, @jsuereth please reopen if I missed something, thanks
