### ISSUE TITLE
Document Java API: describe SpanData class

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#35]
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. Most of APIs are ready to be documented in a form of cross-language specification. 

SpanData class and it's operations needs to be described

**Comment by jmacd** [comment]
I'm proposing to exclude SpanData from the API.

https://github.com/open-telemetry/opentelemetry-specification/issues/71
