### ISSUE TITLE
Add option to export metrics to multiple backends

### ISSUE THREAD

**Issue by sk-** [open-telemetry/opentelemetry-specification#3514]
**What are you trying to achieve?**
We are evaluating different metrics backends, however currently there does not seem to be any way to export the metrics to multiple backends at the same time other than using the OtelCollector.

By paraphrasing https://github.com/open-telemetry/opentelemetry-js/issues/532
> this is handy if transitioning from one vendor/OSS project to another for the [metric] backend. You might want to export to both during the transitional phase.

**Additional context.**

This is currently possible for traces. See for example the documentation added in https://github.com/open-telemetry/opentelemetry-js/pull/537

**Comment by joaopgrassi** [comment]
Maybe this should be discussed in OpenTelemetry JS? AFAIK you can do this by configuring another exporter on the MeterProvider.

**Comment by llc1123** [comment]
Calling `MeterProvider.addMetricReader` multiple times should work?

**Comment by sk-** [comment]
Cool thanks, attaching multiple readers sounds like the solution I was looking for.
