### ISSUE TITLE
Default histogram bucket bounds are too big for seconds durations

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-specification#3525]
https://github.com/open-telemetry/opentelemetry-specification/pull/2770 changed histogram buckets to match Prometheus SDK values. However, the OTel values are 1000 times bigger. That made sense when OTel semantic conventions recommended milliseconds for durations compared to Prometheus's seconds.

OTel recently decided to change its semantic conventions to use seconds for durations to be in line with Prometheus. The side effect of not changing the bucket bounds default at the same time is now the buckets are too large. The smallest bucket captures everything that takes 0-5 seconds instead of 0-5 milliseconds.

I guess most histograms measure short durations, e.g. less than 10 seconds. With the current defaults, those histograms will need to override the bucket bounds because they're not appropriate. If most people need to change the defaults then maybe they aren't the right defaults.

Should the bucket sizes reduce by 1000?

**Comment by JamesNK** [comment]
I just noticed there is an open PR for this: https://github.com/open-telemetry/opentelemetry-specification/pull/3509

**Comment by reyang** [comment]
Discussed during [May 29th, 2024 TC Metting](https://docs.google.com/document/d/1hOHPCu5TGenqTeWPB9qQB_qd33uITZBcvK1FnWxYJAw/edit#heading=h.25gaxviql9wu), here is the decision:
1. We do not intend to change the default bucket bounds.
2. Instrumentation authors are advised to use [advisory parameters](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameters).
3. In addition, semantic conventions have specific guidance on what buckets should be used while providing advisory parameters. https://github.com/search?q=repo%3Aopen-telemetry%2Fsemantic-conventions+%22advisory-parameters%22&type=code
