### ISSUE TITLE
Restructure Metrics SDK View section

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3532]
I think that we can restructure a little to make the spec more consistent and readable. 

Under `MeterProvider` section we could simply have something like:

```markdown
### View Registration

The SDK MUST provide the functionality to register [`View`](#view) instances with a `MeterProvider`.
```

The rest could be moved to a dedicated `## View` section similarly to other configuration components like exporters, readers.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-specification/pull/3524#discussion_r1214108607_

**Comment by tigrannajaryan** [comment]
@pellared is there any further restructuring needed beyond https://github.com/open-telemetry/opentelemetry-specification/pull/3524 ?

**Comment by pellared** [comment]
> @pellared is there any further restructuring needed beyond #3524 ?

I do not follow the question. The issue was created as part of #3524 review to make further improvements.  See https://github.com/open-telemetry/opentelemetry-specification/pull/3524#discussion_r1214108607

**Comment by tigrannajaryan** [comment]
> > @pellared is there any further restructuring needed beyond #3524 ?
> 
> I do not follow the question. The issue was created as part of #3524 review to make further improvements. See [#3524 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3524#discussion_r1214108607)

OK. I misunderstood what this issue was about.

**Comment by svrnm** [comment]
@pellared is this still open?

**Comment by pellared** [comment]
It is still open, yet its priority and impact is low so it can be closed as nobody cared for 1 year. It is just an editorial refinement proposal.

**Comment by svrnm** [comment]
thanks, @pellared, I removed the `triage:*` label for now, such that we can take another look in the next triage meeting
