### ISSUE TITLE
How to properly link spans that outlive their parent in a distributed scenario?

### ISSUE THREAD

**Issue by pdolezal** [open-telemetry/opentelemetry-specification#3548]
🤔
We have long-running background jobs. Such a job is created upon an external HTTP request and its execution is triggered by a scheduler when all resources required for the job are available. A job to be executed gets a supervisor process which checks and controls the job periodically or upon external events. The processing is distributed, the state of a job is maintained in a database, so that a job or supervisor could recover from a crash.

🎯
We would like to have a well-formed and properly linked trace(s) that would capture the whole lifecycle of a job, including all actions of its supervisor.

💭
We tried to manage the trace manually according to the documentation: we store the `Context` of the span representing the job's lifetime in the database as a part of the job's execution state and supervisors restore it to create child spans for their activities when they wake up. We managed to get the traces to quite an acceptable shape. But we found a few unclear points, maybe because of our ignorance or maybe because of the specification/API does not offer a clear way to deal with such a situation, and no attempt we tried was completely successful. The best what we achieved still produces warnings in Jaeger UI, which we could not get rid of and which is rooted probably deeply in the way how the spans are linked in our case.

The current solution follows this sequence:

1. An HTTP request creates a job. The request has an associated span, provided by Quarkus in our case. We extract the `Context` of the request and store it in the database.
2. Later, after the job is scheduled, its supervisor wakes up, loads the state from the database and restores the `Context` and creates a new span with the context as the parent.
3. The previous point repeats with some period until the job is finished.

🤕
Jaeger then shows quite nicely the HTTP request with all the supervisor's spans as its children and with the appropriate timeline graph. Unfortunately, it also shows warnings complaining about clock skew. I guess this is because we use the HTTP span as the parent for the supervisor's spans that outlive their parent – I suppose this is not anticipated and child spans should not outlive their parents. This is the impression that I got from various figures, but I don't read that explicitly anywhere AFAIK.

We tried doing better and tried a couple of other ways:

* We created a new span dedicated to the supervisor's activities: so the span was started, its `Context` was persisted and finally it was ended after the job terminated and its state was deleted from the database. For some reason, such a span was lost and all the child spans were referring to an unknown parent span.
* When a supervisor woke up, we created a new trace and its root span got a link to the HTTP request's span. That produced no warnings, but we got a bunch of traces that were seemingly unrelated – except for the link to the HTTP request's trace. Hardly usable and helpful, moreover Jaeger made it even worse: it was easy to find the HTTP request's trace and we could see the links from the supervisor (if we found them), but there were no backlinks from the HTTP request's trace to the supervisor's activities.

😮
Perhaps it is an intentional design decision, but `SpanBuilder::addLink` is extremely inconvenient when one does not have the actual `Span`, but just the `Context`. How is this supposed to work? I found no better way than combining `Context.makeCurrent()` and `Span.current().getSpanContext()` to get the `SpanContext` to create the link.

🙏
Anyway, thank in advance for any advise what we should do better… and if there is a gap in the API for such use cases, it would be great to cover it – I suppose we are not the only ones to fall in that gap.

**Comment by Oberon00** [comment]
I think this might be a Java-specific problem. You may be looking for `Span.fromContext`. https://github.com/open-telemetry/opentelemetry-java/blob/v1.27.0/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L40-L44

Or are you proposing that addLink should accept a full context? (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links) That would probably make sense, I wonder why we did not change this back then in #875, maybe an oversight. However, it does seem hard to change this now and even adding an overload might be more trouble than worth it for some languages.

**Comment by pdolezal** [comment]
Thanks for pointing to `Span::fromContext`. I somehow missed that way 😵‍ Then `spanBuilder.addLink(context)` is just nice to have, since `spanBuilder.addLink(Span.fromContext(context))` looks acceptable.

Regarding linking the spans, which causes us most troubles, I'm still not sure what the proper way is.

* Do we do the right thing when we restore the `Context` of the original request's span from the database for later operations? It seems to me that we should not do that since the span ends with the request, while it gets new and new children after that. Unfortunately, I'm not aware of any statement in the specification that would require spans not to outlive their parent, which would make it clear.
* Should we then rather create a new span tree, as we tried, and use links to capture the relationship as the specification suggests? If this is the case, I suppose Jaeger should support links better, otherwise the links are effectively useless.

**Comment by jmacd** [comment]
Closing, since we believe this can be addressed with `addLink()`.
