### ISSUE TITLE
Drop jaeger exporter

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-specification#3551]
Remove the jaeger exporter from the specifications.

This is a follow up on:
* https://github.com/open-telemetry/opentelemetry-specification/pull/2858

which announced:

```
Jaeger exporter support will be removed from OpenTelemetry in July 2023.
```

**Comment by carlosalberto** [comment]
Ping @yurishkuro

**Comment by yurishkuro** [comment]
+1

**Comment by yurishkuro** [comment]
To clarify, this refers to the SDK exporter. Are we still going to keep the exporter in the collector, and the corresponding part of the spec describing the translation? In theory those can be removed too, we would just migrate the code into Jaeger directly.

**Comment by yurishkuro** [comment]
How are we going to track updates to documentation?
