### ISSUE TITLE
Project Tracking: System Semantic Conventions stability

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-specification#3556]
### Description

The OpenTelemetry Collector community would like to stabilize system semantic conventions including system metrics in order to help the adoption of the OTel [hostmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/65a1dea390881aad43f5252d730ece36d9c094b5/receiver/hostmetricsreceiver).

### Project Board

See: https://github.com/orgs/open-telemetry/projects/55/views/3

#### Roadmap

- https://github.com/open-telemetry/semantic-conventions/issues/127
- (@ChrsMark) https://github.com/open-telemetry/semantic-conventions/issues/130
- (@mx-psi) https://github.com/open-telemetry/semantic-conventions/issues/131
- (@frzifus) https://github.com/open-telemetry/semantic-conventions/issues/73
- (@dineshg13) https://github.com/open-telemetry/opentelemetry-specification/issues/2287
- https://github.com/open-telemetry/opentelemetry-specification/issues/2801
- (@braydonk) https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417
- https://github.com/open-telemetry/semantic-conventions/issues/226

#### done

- (@frzifus) https://github.com/open-telemetry/semantic-conventions/issues/98

##### Optional

- https://github.com/open-telemetry/opentelemetry-specification/issues/2813 
- https://github.com/open-telemetry/opentelemetry-specification/issues/3341

#### Finally
- Stabilize existing semantic conventions (system metrics)

### Deliverables

- Mark the [system semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/37ab6b056172ad36d31ce217927e47bbe031d831/specification/metrics/semantic_conventions/system-metrics.md#semantic-conventions-for-system-metrics) as stable.
- Update existing OpenTelemetry Collector hostmetricsreceiver to conform with the stable conventions.

### Staffing / Help Wanted

The goal is to follow @tedsuo's proposed [Semantic Convention Process](https://docs.google.com/document/d/1ghvajKaipiNZso3fDtyNxU7x1zx0_Eyd02OGpMGEpLE/edit#heading=h.xc2ft2cddhny).

- **Stage 1**: Working Group Preparation
- **Stage 2**: Stabilizing the Specification
- **Stage 3**: Implementation

#### Required staffing

- @mx-psi, @frzifus project leads
- @jsuereth technical committee sponsor
- domain experts:
  - @MovieStoreGuy
  - @dmitryax
  - @gbbr
  - @sallyom
  - @ChrsMark
  - @kaiyan-sheng
  - @braydonk
  - @bertysentry
  - @dineshg13
        
### Meeting Times

July 10 - August 21 (6 weeks):

- Wednesday at 8:30-09:00 Pacific Time

*cncf-slack* [#otel-system-metrics-wg](https://cloud-native.slack.com/archives/C05CTFE9U4A)
*meeting-notes* [google-doc](https://docs.google.com/document/d/1p5TH57t43XpxA48onLzX4PIr3g6ydYKCtR_AUlsCnQk)

### Timeline

**Stage 1** (Working Group Preparation) is happening now.

**Stage 2** (Stabilizing the Specification) will begin as soon as we have adequate staffing for this project, and we coordinate a weekly meeting times (currently targeting mid-july).

**Stage 3** (Implementation) will begin as soon as the system metrics are marked stable, and it should be relatively short we only need to update conformance to the specification for a single collector package.

### Labels

*The tracking issue should be properly labeled to indicate what parts of the specification it is focused on.*

### Linked Issues and PRs

*All PRs, Issues, and OTEPs related to the project should link back to the tracking issue, so that they can be easily found.*

**Comment by frzifus** [comment]
Sure, done. :)

**Comment by braydonk** [comment]
I work on the [Google Cloud Ops Agent](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent) which packages the OpenTelemetry Collector for metrics collection, and the hostmetrics specification is very important to us. I also help support other teams at Google that are leveraging the collector and collecting hostmetrics.

I would love to join this working group and contribute to the specification, providing the perspective of both a vendor and user.

**Comment by frzifus** [comment]
Thats great, added you :slightly_smiling_face:

**Comment by jsuereth** [comment]
As mentioned in the Specification meeting, do we have a back-log of issues to triage or work through as part of this working group?  Could we add that in this proposal?

**Comment by frzifus** [comment]
We will try to deliver by the end of the week. We will compile the scope in a google doc and move it here.

cc @mx-psi

**Comment by bertysentry** [comment]
I'm definitely interested in helping in this wg

**Comment by frzifus** [comment]
Hi @bertysentry, @dineshg13 - added you both :)

@jsuereth synced with @mx-psi and we linked the roadmap.

**Comment by jsuereth** [comment]
This is approved to run by TC.   

@mx-psi @frzifus Are you able to set up the calendar invites and meeting notes?

I'll get you a project status board and move the issues listed to it to start.

**Comment by frzifus** [comment]
Sure, we will figure out how that works. :+1:

**Comment by dmitryax** [comment]
We also need to find a way to capture "available" memory reported by Linux kernel (>3.16) https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417

**Comment by braydonk** [comment]
I'd be interested in helping with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417

**Comment by ChrsMark** [comment]
I can look into the https://github.com/open-telemetry/semantic-conventions/issues/130.

**Comment by tigrannajaryan** [comment]
Project is setup, closing the issue. If anything else is needed please reopen or create a new issue.
