### ISSUE TITLE
Define configuration for enabling sqlcommenter

### ISSUE THREAD

**Issue by tammy-baylis-swi** [open-telemetry/opentelemetry-specification#3560]
It would be great if there was a convention for how to enable `sqlcommenter` for those OTel libraries that have it implemented.

At the moment I see some Python and JS instrumentation libraries do this with a boolean, though the naming is inconsistent. Examples:
* [SQLAlchemy instrumentation](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/sqlalchemy/sqlalchemy.html) uses `enable_commenter`
* [Django ORM instrumentation](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/django/django.html) uses `is_sql_commentor_enabled`
* [pg instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-pg#postgresql-instrumentation-options) uses `addSqlCommenterCommentToQueries`

If instead we had `OTEL_SQLCOMMENTER_ENABLED` (or similar) then this could be adopted by existing libraries and more libraries as `sqlcommenter` is implemented. It could also be exposed as an environment variable used in auto-instrumentation and manual instrumentation.

**Comment by carlosalberto** [comment]
cc @open-telemetry/configuration-maintainers

**Comment by austinlparker** [comment]
This is blocked by the configuration SIG - adding it to their board.

**Comment by austinlparker** [comment]
> > This is blocked by the configuration SIG
> 
> What do you mean blocked?

This was proposing an env var, and I thought config SIG was saying 'no new env vars for now', but more generally I think the new config stuff would cover how to do this in a generic sort of way?

**Comment by jack-berg** [comment]
No env vars for now is right, but someone who is motivated can push to define this as part of the config data model defined in [opentelemetry-configuration](https://github.com/open-telemetry/opentelemetry-configuration). My understanding is sqlcommenter is instrumentation. There's a section of the configuration schema [dedicated to instrumentation config](https://github.com/open-telemetry/opentelemetry-configuration/blob/cc7cd375d893e440afdc294a00f98038ebaa4eab/examples/kitchen-sink.yaml#L439).

**Comment by trask** [comment]
> No env vars for now is right, but someone who is motivated can push to define this as part of the config data model defined in [opentelemetry-configuration](https://github.com/open-telemetry/opentelemetry-configuration). My understanding is sqlcommenter is instrumentation. There's a section of the configuration schema [dedicated to instrumentation config](https://github.com/open-telemetry/opentelemetry-configuration/blob/cc7cd375d893e440afdc294a00f98038ebaa4eab/examples/kitchen-sink.yaml#L439).

this can be accomplished now directly in the https://github.com/open-telemetry/opentelemetry-configuration, so closing this issue
