### ISSUE TITLE
What should log integrations set Scope name to?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3562]
Related to https://github.com/open-telemetry/opentelemetry-php/issues/1049

Log integrations/bridges can set Scope's Name to the integration's name (e.g. "opentelemetry-log4j", "opentelementry-monolog", etc). 

Alternatively integrations can see if the bridged library has a concept that is similar to our Scope and use it as the Scope name. Many logging libraries accept some sort of logger identifier or name when you create a logger (e.g. Monolog calls the concept a Channel, log4j has Logger name, etc). Should we use this value as the Scope Name when it matches conceptually?

@open-telemetry/specs-logs-approvers Which of these 2 approaches is the right approach? We need to have a recommendation for integrations/bridges.

**Comment by jack-berg** [comment]
I thought we had this conversation a while back and decided that the scope name should be set to the logger name (if it matches conceptually), since the idea of the scope name was heavily influenced in design from logger names. 

Issue #1215 has more context.

**Comment by Oberon00** [comment]
I would think that the scope name should identify the instrumenting/reporting library, e.g. opentelemetry-log4j-integration. The logger name would be a separate thing that should be stored somewhere else

**Comment by tigrannajaryan** [comment]
> I thought we had this conversation a while back and decided that the scope name should be set to the logger name (if it matches conceptually), since the idea of the scope name was heavily influenced in design from logger names.
> 
> Issue #1215 has more context.

Sounds good. I was not able to find any corresponding recommendation in the spec. Do we have one? If not let's add it to the spec to make it clear.

**Comment by tigrannajaryan** [comment]
I think we have a contradiction [here in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#how-to-create-a-log4j-log-appender):

>The log appender implementation will typically acquire a [Logger](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#logger) from the global [LoggerProvider](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#loggerprovider) at startup time, then call [Emit LogRecord](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#emit-a-logrecord) for LogRecords received from the application.

If the Logger is obtained once, at startup time then the bridge has to set the scope name to something static. The bridge cannot use a value that is only available when the log record is emitted by the logging library.

Now this is not a normative language and it says "typically" so we have some leeway here.

The problem is that I am not sure how the bridge can ensure the right scope name is used. Is the bridge supposed to obtain a new Logger for every log record it emits? Are we sure this will not have a performance impact (we don't necessarily design GetLogger API to be fast).

**Comment by jack-berg** [comment]
> The problem is that I am not sure how the bridge can ensure the right scope name is used. Is the bridge supposed to obtain a new Logger for every log record it emits? Are we sure this will not have a performance impact (we don't necessarily design GetLogger API to be fast).

This is indeed how the implementation works in java. Here's an [old PR](https://github.com/open-telemetry/opentelemetry-java/pull/4891) where I describe that exact scenario and the importance of optimizing its performance, and [here's another PR](https://github.com/open-telemetry/opentelemetry-java/pull/4913) where I optimize the hot path.

**Comment by tigrannajaryan** [comment]
> > The problem is that I am not sure how the bridge can ensure the right scope name is used. Is the bridge supposed to obtain a new Logger for every log record it emits? Are we sure this will not have a performance impact (we don't necessarily design GetLogger API to be fast).
> 
> This is indeed how the implementation works in java. Here's an [old PR](https://github.com/open-telemetry/opentelemetry-java/pull/4891) where I describe that exact scenario and the importance of optimizing its performance, and [here's another PR](https://github.com/open-telemetry/opentelemetry-java/pull/4913) where I optimize the hot path.

@brettmc do you think you can also implement this in a reasonably performant way in PHP?

**Comment by Oberon00** [comment]
One potential problem when using (only) the logger name as scope name could be that there might be name clashes. For example, an application might use some abstraction to forward logging calls to different logging frameworks using the same logger name. Isn't this something that might happen in Java? I might have misremembered it though.

**Comment by mateuszrzeszutek** [comment]
> Isn't this something that might happen in Java?

I think it's unlikely, but still possible -- especially in scenarios where multiple isolated classloaders are involved, e.g. webapps on application servers.

**Comment by Oberon00** [comment]
I was actually not thinking about different classloaders but different logging frameworks which might have different OTel instrumentations receiving calls from the same logger abstraction (one name). It may not be a problem. It just means that we must not use any scope attributes (e.g. actual instrumentation library name / instrumented framework name would be nice as a scope attribute, but might be dangerous then)

**Comment by tigrannajaryan** [comment]
@Oberon00 I understand. You are referring to the fact that our spec says:

>It is a user error to create Loggers with different attributes but the same identity.

If different bridges try to do create loggers with the same name AND also populate different attributes we end up with undefined behavior.
