### ISSUE TITLE
OpenTelemetry Specification 1.21.0 release accidentally published Schema file for Semconv

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#3572]
With the semantic convention Split of 1.21.0, we assumed that removing the direct push of schema into opentelemetry.io repository would prevent publishing new schema files and we left 1.21.0 in-place.

However, the opentelemetry.io website now directly depends on this repository as a sub-module.  As such, 1.21.0 schema is now publicly available *and* out of date with any particular tag of either the specification or the semantic conventions.

We have a few options:

- Just delete the file from serving and this repository
  -  It's unlikely anyone has depended on this file so far
  - We can easily disable the file from being served.
- Mark `1.21.1` as a dead release for semantic conventions and move to `1.22.0` for the next release.

I'd prefer to do the first.

**Comment by jsuereth** [comment]
We've dropped the 1.21.0 schema from the website, taking option 1.  Thanks @chalin for the rapid response!

**Comment by tigrannajaryan** [comment]
Sounds good to me. We are still in experimental phase for schema, so I think it is acceptable.
