### ISSUE TITLE
Recommendation of metircs for monitoring memory-usage of all the currently running processes

### ISSUE THREAD

**Issue by zhchai** [open-telemetry/opentelemetry-specification#3575]
**What are you trying to achieve?**
Monitor memory-usage of all the currently running processes, I am using 1 instrument to monitor all the running processes, but mostly the processes can be generated and exit runtimely.
Do you have recommendation for such scenario?

What did you expect to see?
If the process exit, its measurement should be stopped.

**Additional context.**
https://github.com/open-telemetry/opentelemetry-cpp/issues/2199

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.
No

**Comment by zhchai** [comment]
@jack-berg do you have any recommendation on this?

**Comment by zhchai** [comment]
@marcalff I see your comment on https://github.com/open-telemetry/opentelemetry-cpp/issues/2184
```
After additional analysis, there is no real use case for removing instruments individually.
```
do you have any recommendation for this case? or metric is not suitable for variable set monitoring?

**Comment by austinlparker** [comment]
This is a use case of #3985, closing this issue in favor of that one
