### ISSUE TITLE
Update security reporting policy

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3595]
TC and GC discussed and decided that we want to make Github security reporting capabilities the primary reporting channel.

We will need to update the [policy](https://github.com/open-telemetry/opentelemetry-specification/security/policy) document and make sure all repos have the vulnerability reporting feature enabled (including [new repos](https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md)).

cc @open-telemetry/governance-committee @open-telemetry/technical-committee

**Comment by yurishkuro** [comment]
PR to the policy attached.

**Comment by yurishkuro** [comment]
I enabled "Private vulnerability reporting" on all repos. Wish GitHub would have org-level settings that would override individual repo defaults.

**Comment by yurishkuro** [comment]
turns out GitHub does support bulk security settings updates, but the vulnerability reporting is not one of them, perhaps because it itself is in beta: https://docs.github.com/en/enterprise-cloud@latest/code-security/security-overview/enabling-security-features-for-multiple-repositories
