### ISSUE TITLE
Clarify MetricProducer "Produce() does not have any required parameters"

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-specification#3601]
**What are you trying to achieve?**

The [MetricProducer](https://github.com/open-telemetry/opentelemetry-specification/blob/71813887597d18e3535dd56d2a18ecae7299daad/specification/metrics/sdk.md#metricproducer) spec indicates the following for the [`Produce()`](https://github.com/open-telemetry/opentelemetry-specification/blob/71813887597d18e3535dd56d2a18ecae7299daad/specification/metrics/sdk.md#produce-batch) method:

> `Produce` does not have any required parameters, however, [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/71813887597d18e3535dd56d2a18ecae7299daad/specification/overview.md#sdk) authors MAY choose to add parameters (e.g. timeout).

It is unclear whether this means that SDK authors may add *required* parameters, or if `Produce()` must not have *any* required parameters. 

If the former, it should be clarified that "authors MAY choose to add required or optional parameters" (or something similar).

If the latter, it should be clarified that "authors MAY choose to add *optional* parameters".

This question arose in the Go metrics sdk for MetricProducer: https://github.com/open-telemetry/opentelemetry-go/issues/3668. The `Produce()` function in Go [has a required `context.Context` parameter](https://github.com/open-telemetry/opentelemetry-go/blob/e0852d609c4a4205d550e2de45afdbf80d43557b/sdk/metric/reader.go#L110). 

Ref https://github.com/open-telemetry/opentelemetry-specification/issues/3599

**Comment by dashpole** [comment]
It is the former: `authors MAY choose to add required or optional parameters`.

**Comment by aabmass** [comment]
Another point here, we have this requirement https://github.com/open-telemetry/opentelemetry-specification/blob/8ae0f6fb1d752abfd780a73b6abb351608231d91/specification/metrics/sdk.md?plain=1#L1398-L1400

I take that as the Produce function must accept the Resource in this case. I think at least that requirement should be moved into the `Produce()` subsection

**Comment by dashpole** [comment]
> I take that as the Produce function must accept the Resource in this case.

The original intent was that Resource would be passed once when the MetricProducer is constructed, and then used to set the resource returned by all Produce() calls.  We can make it more flexible if there is a design you think works better for JS.

**Comment by aabmass** [comment]
1. The MetricProducer is something that a user or library implements, so the `MUST` requirement is not actually a requirement for the SDK
2. What should the MetricReader do when the Resource returned by a registered MetricProducer is different from the SDKs resource? In JS's case, the result of a collection is a [*single* ResourceMetrics](https://github.com/open-telemetry/opentelemetry-js/blob/87f21ef8aecaa1e52ff9200a99497276ffa2956b/packages/sdk-metrics/src/export/MetricData.ts#L96) i.e. one Resource. So I could merge the Resources or only use the SDK's resource. I like the latter here but I don't think that complies with spec.

**Comment by dashpole** [comment]
> The MetricProducer is something that a user or library implements, so the MUST requirement is not actually a requirement for the SDK

That is correct.  It is technically a requirement for the bridges.  `MetricProducer implementations SHOULD accept configuration for the AggregationTemporality of produced metrics.` also is meant for bridges, rather than SDKs.  The SDK spec probably isn't the right place for it to live, but there isn't a great alternative.

> What should the MetricReader do when the Resource returned by a registered MetricProducer is different from the SDKs resource? In JS's case, the result of a collection is a [single ResourceMetrics](https://github.com/open-telemetry/opentelemetry-js/blob/87f21ef8aecaa1e52ff9200a99497276ffa2956b/packages/sdk-metrics/src/export/MetricData.ts#L96) i.e. one Resource. So I could merge the Resources or only use the SDK's resource. I like the latter here but I don't think that complies with spec.

I think the spec is silent on the SDK's behavior if it gets a resource from the bridge.  I think the latter is acceptable.  We initially had more specific language saying that the MetricReader MUST override the resource from a producer with its own, but decided to drop it to leave that open to SDK authors.

**Comment by aabmass** [comment]
Ok, so if I implement the SDK to drop the resource from a bridge, then

> `MetricProducer` MUST accept configuration for the [Resource](../resource/sdk.md). 

seems unnecessary since I'll just throw it away. Maybe we can switch this to a SHOULD?

**Comment by dashpole** [comment]
> I can open a separate issue if you agree David

I agree it should be SHOULD.  Feel free to open a separate issue.
