### ISSUE TITLE
Clarify if MetricProducers can be registered with config instead of a method

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#3611]
The spec defines a [`MetricProducer.RegisterProducer()`](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.23.0/specification/metrics/sdk.md#registerproducermetricproducer) function for binding metric producers to a reader. It says

> RegisterProducer is expected to be called during initialization, but MAY be invoked later.

While implementing this in JS (https://github.com/open-telemetry/opentelemetry-js/pull/4007), we already have a (stable) [`setMetricProducer()`](https://github.com/aabmass/opentelemetry-js/blob/7255da994fe79f115ceb9b1260fb171cf9313706/packages/sdk-metrics/src/export/MetricReader.ts#L76-L84) (singular) function which is expected to bind the reader **specifically to an SDK instance**. In order to implement the spec, I decided to instead add a MetricReader constructor argument accepting any additional MetricProducers.

- Is this OK spec wise? I imagine it is.
- Can/should we update the spec to make this more open ended? We have more vague wording for this kind of thing elsewhere e.g. "X SHOULD provide a way to ..."

Wanted to discuss this for https://github.com/open-telemetry/opentelemetry-specification/issues/3599 @dashpole

**Comment by dashpole** [comment]
I think we should update the spec to make this more open-ended.  I don't recall "late registration" being the reason we landed on the current design, so I think it is fine to relax that.
