### ISSUE TITLE
Miscellaneous additional semantic convention attribute names

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-specification#362]
As I am working on various implementations I have found a number attribute names that are not currently specified or have an existing open issue.

**http.user_agent** - present in OpenCensus, absolutely required by systems my team is currently working on

**iam.user** - username value from basic authentication or subject from access/identity token, absolutely required by systems my team is currently working on

**iam.role** - scope/authorities from access token, not needed by my team but useful for completeness of the specification

**message_bus.destination** - present in OpenTracing, absolutely required by systems my team is currently working on

Also needed is more standardization of "component" attribute values. This already a issue to standardize on **db** for database spans. Other needs we have found are:

**messaging** - asynchronous messaging systems
**rpc** - instead of **grpc** or if grpc is kept then also needed is **rmi**, **thrift**, etc.
**cluster** - or maybe **streaming** for internal cross node communications on streaming platforms

**Comment by jmacd** [comment]
I agree about the four suggested labels. As for the component question, see #336. I feel that `component` is not well defined (or needed). OTOH, I'd like to specify a standard attribute for the name and version supplied to named tracers and meters.

**Comment by kbrockhoff** [comment]
All these items have been addressed by other PRs.
