### ISSUE TITLE
Consider allowing a simpler API for histogram default buckets

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-specification#3621]
### Context

This is feedback from a Go prototype of the [Instrument Advice API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument):

* Tracking issue: https://github.com/open-telemetry/opentelemetry-go/issues/4162
* Prototypes: https://github.com/open-telemetry/opentelemetry-go/pull/4341, https://github.com/open-telemetry/opentelemetry-go/pull/4340

### Feedback

When prototyping in Go, "Advice" itself seemed unnecessary for allowing histogram bucket boundaries to be configured on histogram instruments.  The simplest, cleanest API was to make bucket boundary configuration a "top-level" configuration option exclusive to histograms, rather than nested within an "Advice" concept.

The ask in this issue is to at least **allow** API implementations to exclude the notion of Advice, and instead allow directly configuring the subfields of Advice on the instruments they apply to.

cc @jack-berg @MrAlias @MadVikingGod

**Comment by MrAlias** [comment]
"When prototyping in Go, 'Advice' itself seemed unnecessary for allowing histogram bucket boundaries to be configured on histogram instruments" should be "When prototyping in Go, 'Advice' itself seemed unnecessary for allowing histogram bucket boundaries to be configured on **_anything but_** histogram instruments", right?

**Comment by MrAlias** [comment]
> I meant to say that configuring buckets directly, rather than nested inside of advice, was simpler. I.e. advice was not necessary for allowing buckets to be configured on histograms.
> 
> Your statement is also correct that histogram bucket boundary configuration didn't make sense to include as options for non-histogram instruments.

Gotcha 👍

**Comment by trask** [comment]
just fyi, I've added this to the spec meeting agenda for discussion since it's potentially a blocker for #3391 which is a blocker for HTTP semconv stability

**Comment by jmacd** [comment]
> The ask in this issue is to at least allow API implementations to exclude the notion of Advice, and instead allow directly configuring the subfields of Advice on the instruments they apply to.

This seems reasonable.
