### ISSUE TITLE
Can a span have more than one span.recordException()

### ISSUE THREAD

**Issue by umarkhan17** [open-telemetry/opentelemetry-specification#3640]
**What are you trying to achieve?**
I am trying to record multiple exceptions for a span
What did you expect to see?
Multiple exceptions in a span
**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by trask** [comment]
hi @umarkhan17!

> Can a span have more than one span.recordException()

yes, I believe so.

what language SDK are you using? maybe you are seeing a language-specific SDK bug?

**Comment by umarkhan17** [comment]
Was just curious, i tested it out today, yeah, a span can have more than one exception.
