### ISSUE TITLE
Consider a new name for Metrics `Meter` interface

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#365]
See this [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/347#discussion_r349836588):

> On the "The/A" distinction: For me, the name Meter is an odd one, in that I think of a "meter" as a thing that measures something, rather than a source of very many things that measure a wide variety of things. I know we're trying to avoid the Factory word, but having this be a singular english noun is quite confusing to me. Meters would be more evocative.

I agree that `Meter` is somehow not quite right. It has the nice property of ending with -`er` like Tracer, but otherwise the word "Meter" in common language does not describe a measuring device. I've been using "Instrument" to describe the things returned by this interface, but even "Instrumenter" isn't much of a word. Maybe "Meters" is OK, but I'd actually prefer "Metrics" in one form for this concept.  As is being discussed in #354 for Tracers, maybe something like "MetricsSource" or "MetricsRoot" works?

**Comment by jmacd** [comment]
Another reason to avoid "Meter" is that it's used in other libraries to mean something quite different.

https://metrics.dropwizard.io/4.1.1/manual/core.html#man-core-meters

**Comment by bogdandrutu** [comment]
>Another reason to avoid "Meter" is that it's used in other libraries to mean something quite different.

We've already decide that this is not very important, because the same reason can be applied to `Gauge` and that is probably more important than `Meter`.

**Comment by jkwatson** [comment]
Somehow I missed this issue getting created. 

Currently, the Java APIs, the `Meter` is the "factory" class for creating builders (sigh, java) for the various `Metric` implementations. Hence, `Metrics` feels like an excellent, easy-to-grok place to go to create your `Metric`s, whereas `Meter` is just confusing (to me). 

Part of that confusion is as @jmacd mentioned, because I'm used to working with Micrometer metrics, which has `Meter` as the base interface for all the various kind of instruments provided.

**Comment by jmacd** [comment]
Just to pile on, I would say there is a substantial difference between the confusion from `Meter` as compared with `Gauge`. The OTel Gauge is the same kind of thing -- an instrument -- as it is in many APIs. The OTel Meter is a different kind of thing -- a reference to the SDK -- than in the Micrometer / DropWizard APIs.

**Comment by jmacd** [comment]
I don't think we've made progress. I'm inclined to close this.

**Comment by jkwatson** [comment]
I guess so. I still think it's a confusing name for what it is, but if no one else is on board with changing it, then we should close it. I'd love to have some users provide some feedback, rather those of us living in the echo chamber.
