### ISSUE TITLE
Proposal: extend Sampler interface so that shouldSample receive the Instrumentation Scope as input

### ISSUE THREAD

**Issue by albertored** [open-telemetry/opentelemetry-specification#3656]
I would like to propose an addition to the arguments of the [`shouldSample`](https://github.com/open-telemetry/opentelemetry-specification/blob/7b4c60c6edb52c676d53ced730b6af4ded509068/specification/trace/sdk.md#shouldsample) function of the Sampler interface. In particular, I would like to have also the Instrumentation Scope as an argument.

This will help custom samplers to achieve some specific sampling decisions, for instance my use case is being able to drop all spans generated by a specific instrumentation library.

**Comment by MrAlias** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/1588?

**Comment by albertored** [comment]
Yes, sorry, I searched for it but didn't find it
