### ISSUE TITLE
Proposal to add system.linux.memory.available

### ISSUE THREAD

**Issue by ItsLastDay** [open-telemetry/opentelemetry-specification#3659]
**What are you trying to achieve?**

Linux kernel exposes a memory metric called `available`, which helps to understand how much memory is really available for the userspace apps. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417.

This value is unique to Linux, hence the `system.linux` prefix: see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19149#issuecomment-1467634451.

**What did you expect to see?**

`system.linux.memory.available` - Gauge metric of integer type, meaning number of bytes available. No attributes.

**Additional context.**

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417#issuecomment-1668082340

cc @dmitryax @braydonk

**Comment by jsuereth** [comment]
Can you please open this bugs in the semantic-conventions repository?

**Comment by ItsLastDay** [comment]
Sure, done: https://github.com/open-telemetry/semantic-conventions/issues/257.

Should I close this issue then?
