### ISSUE TITLE
[metrics] Allow SDKs to change ExplicitBucketBoundaries default based on unit?

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-specification#3672]
**What are you trying to achieve?**

The default ExplicitBucketBoundaries don't work well for http durations in seconds. The Hint API solves this well, but for the .NET SDK it is going to take us some time (~15 months) to work with the dotnet/runtime team to add that support into our API layer for Hints API and get it into the next annual release (.NET 9 ~11/2024).

We're currently looking for ways to give users a good experience until we have the Hint API available. Issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4797

What I thought might be an interesting idea\tweak is to let SDKs adapt the default explicit histogram bucket boundaries based on the unit of the instrument. Eg: https://github.com/open-telemetry/opentelemetry-specification/compare/main...CodeBlanch:metrics-ExplicitBucketBoundaries-defaults?expand=1

Opening this issue to get feedback, gather ideas, etc.

Update 1:

* Discussed on the [spec SIG 8/29/23](https://zoom.us/rec/play/67hGHXsxpRNmC886RSUdSl0ozzvfuXJdAz8N2KKZo-d183vV4o9nGYQaG3TFVW_k7dEhmTeCQeY1hT3d.Ee8iVGIK_32a-3ee?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FjHoENvt9De5f-YClPJ6i5uTpGzjEWIU4SWjJo6Gel6nfnE9VDKWKoYSGf_Xe4MoB.6yg6Uwm20vJncDfQ). Three potential solutions were proposed:
      1. Let the spec define different defaults based on the unit (original proposal).
      2. Let the spec define environment variables to make the defaults configurable.
      3. Introduce logic into the .NET SDK to hardcode the known instruments using seconds and switch the defaults.
      4. Introduce some configuration into the .NET SDK to let users control it.

**Comment by aabmass** [comment]
Related https://github.com/open-telemetry/opentelemetry-specification/issues/3525

**Comment by CodeBlanch** [comment]
@jack-berg As far as what environment variables might look like, what do you think of this?

OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_BEHAVIOR = [GLOBAL_DEFAULT|VARY_BY_UNIT]
OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_VALUES = *=[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ];s=[ 0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ]

Thinking in .NET we would default to VARY_BY_UNIT mode. Users who want the existing behavior could switch to GLOBAL_DEFAULT mode. Users who may want to customize the values or add units other than seconds would utilize OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_VALUES.

**Comment by MrAlias** [comment]
> @jack-berg As far as what environment variables might look like, what do you think of this?
> 
> OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_BEHAVIOR = [GLOBAL_DEFAULT|VARY_BY_UNIT] OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_VALUES = *=[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ];s=[ 0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ]
> 
> Thinking in .NET we would default to VARY_BY_UNIT mode. Users who want the existing behavior could switch to GLOBAL_DEFAULT mode. Users who may want to customize the values or add units other than seconds would utilize OTEL_METRICS_EXPLICITHISTOGRAM_DEFAULTBUCKET_VALUES.

Given these are going to be .NET specific features, shouldn't these be prefixed with `OTEL_DOTNET_*` to match the existing specification on this type of configuration?

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#language-specific-environment-variables

**Comment by austinlparker** [comment]
Is this still an issue?

**Comment by reyang** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/3525#issuecomment-2137665490

**Comment by danielgblanco** [comment]
@reyang is this still something we want to consider?

**Comment by dyladan** [comment]
Based on the resolution of https://github.com/open-telemetry/opentelemetry-specification/issues/3525 I think this is also wontfix?

**Comment by tigrannajaryan** [comment]
Closing. Can re-open if there is anything new to consider.
