### ISSUE TITLE
HTTP semantic conventions invade "host" Resource namespace

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#369]
We have "host.*" attributes [defined](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-resource-semantic-conventions.md#host) for Resources.

There is also [HTTP semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md#http-server-semantic-conventions) which use "http." prefix for vast majority of attributes except for "host.port" and "host.name". I believe for consistency reason and to avoid namespace clashing these 2 attributes need to be renamed to use "http." prefix.

**Comment by tigrannajaryan** [comment]
@Oberon00 I believe you are the author of HTTP semantic conventions, can you please take this?

**Comment by Oberon00** [comment]
Actually, these are renamed in #295 to use the `net.` prefix.

**Comment by arminru** [comment]
> Actually, these are renamed in #295 to use the `net.` prefix.

\* #349

**Comment by Oberon00** [comment]
I think this is done now.
