### ISSUE TITLE
Proposal: error, high latency type trace data sampling.

### ISSUE THREAD

**Issue by tttoad** [open-telemetry/opentelemetry-specification#3690]
I'd like to have a way to ensure that a specific tracing(error, high latency，etc) is sampled when setting a low sample rate.

Why not use tail-based sampling?

Spans are not always sent to the same agent, and the delivery time for two spans can vary greatly. Especially for cross-cluster calls. And most of the data do not need to be collected, sent to a center agent, too waste of resources.

Proposal:
Provides the ability for the parent span to obtain the sampling identifier of the child span. Like Baggage, data is provided by the  span of the error type and passed back to the root span.
Although this can lead to incomplete tracing data, the wrong portion of the trace will be preserved.
It can be used as a complement to tail sampling, so that when a span of an error type is lost or delayed in being sent to the agent, its parent span is not lost.
Within the same service, the child span can be associated with the parent span in the StartSpanFromContext function. (Ignore the span of the FollowsFrom reference). 
Between services, we can use the response header to get the sampling identifier.

**Comment by albertored** [comment]
Maybe this can be solved with support to the traceresponse header?
https://github.com/open-telemetry/opentelemetry-specification/issues/2914

**Comment by tttoad** [comment]
> #2914

Not really. I want to complete the markup in the client's SDK.
When Span.Finsh(),Search for sampling markers in the tags of child span,  and copies them to the tag of the current span.

**Comment by austinlparker** [comment]
This has been explored many times (backpropagating sampling status in-process) but there are many issues: for example, async traces, etc. While the collector as a tail sampling solution may be complex, it accomplishes the goal.
