### ISSUE TITLE
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#full-normalization

### ISSUE THREAD

**Issue by Bush5580** [open-telemetry/opentelemetry-specification#3691]
**What are you trying to achieve?**

What did you expect to see?

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by Bush5580** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#full-normalization

**Comment by arminru** [comment]
It is unclear what you're trying to bring up here. If this is related to the OpenTelemetry Collector or its -contrib distribution, please open an issue there rather than in the specification. Thank you.
