### ISSUE TITLE
Prometheus spec: Should it be possible to disable target_info 

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-specification#3702]
**What are you trying to achieve?**
Similarly to how it [is possible](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md?plain=1#L268) for `otel_scope_info`, I think the prometheus spec should explicitly mention that exporter can have a configuration option to disable the `target_info` metric.

In fact, [the prometheus remote write exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md?plain=1#L61) already has this option coded.

For the sake of consistency I believe that the specification should include the following line in the end of [this section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md?plain=1#L385C1-L385C1):

```
Prometheus exporters SHOULD provide a configuration option to disable the
`target_info` metrics.
```

What did you expect to see?

I would like that the spec explicitly mention that exporter can provide a configuration option to disable the `target_info` metric.

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by rapphil** [comment]
@open-telemetry/wg-prometheus

**Comment by dashpole** [comment]
I support this change
