### ISSUE TITLE
OpenCensus shim: Consider loosening summary requirement

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-specification#3708]
**What are you trying to achieve?**

The OpenCensus compatibility specification currently requires bridges to support summaries: https://github.com/open-telemetry/opentelemetry-specification/blob/4f23dce407b6fcaba34a049df7c3d41cdd58cb77/specification/compatibility/opencensus.md?plain=1#L227

This implicitly requires SDKs to support summaries if they want to have an OpenCensus shim. This is a relatively major change, as exporters also need to be able to handle the summary metric type. I think the tradeoff is best weighed by the language SIG, and would prefer loosening the requirement.

Options:

* Change MUST to SHOULD for summary metrics in the OpenCensus specification.
* Caveat summary support with "MUST ... If the SDK's data model supports summary metrics"

@jsuereth

**Comment by dashpole** [comment]
Current state:

* Java [supports summaries](https://github.com/open-telemetry/opentelemetry-java/blob/bdeb1e95cd24748523592877d82d64212496e96e/opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/internal/metrics/MetricAdapter.java#L258)
* Go [does not support summaries](https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/doc.go#L59)
* JS [does not support summaries](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/shim-opencensus/src/metric-transform.ts#L59)

**Comment by aabmass** [comment]
> * JS [does not support summaries](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/shim-opencensus/src/metric-transform.ts#L59)

After looking through the repo, I don't think OpenCensus JS implementation can [actually _produce_ summaries](https://github.com/search?q=repo%3Acensus-instrumentation%2Fopencensus-node%20percentileValues&type=code), so I think JS is OK here.

If we think it's important for the MetricProducer to support it for bridging other SDKs, maybe it should be called out in the spec somewhere.

**Comment by aabmass** [comment]
I believe it's the same for OpenCensus Python, I don't see anywhere that summaries are [actually produced in the code](https://github.com/search?q=repo%3Acensus-instrumentation%2Fopencensus-python+%2F%28%3F-i%29Summary%5C%28%2F+-path%3Atests&type=code). Also https://github.com/census-instrumentation/opencensus-python/issues/567

**Comment by dashpole** [comment]
This does not block the Go SIG's OC bridge, based on https://github.com/open-telemetry/opentelemetry-go/issues/4587#issuecomment-1761768189, so i'm closing this for now.
