### ISSUE TITLE
Clarify if the OTLP exporter has to support all protocols and protocol related env vars

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3720]
Is it necessary for the OTLP exporter to intentionally support `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`?

This requirement would create a dependency for the OTLP exporter on all the libraries utilized for implementing the transport protocols (such as the HTTP client, JSON parser, protobuf parser, and gRPC client). This means that users who only require the HTTP protocol might not want to introduce any gRPC dependencies to their application. In certain programming languages, like Go (as mentioned in this [paper](https://research.swtch.com/deps)), it is customary to minimize the number of dependencies. This approach also helps reduce the overall "security surface" of the components. It's important to note that if a gRPC library used by the exporter had a CVE, the entire exporter would be considered vulnerable as well (since most security static analysis tools solely check dependencies and not how the code is structured).

Currently, most languages (such as [C++](https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/otlp), [Go](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp), [Java](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp), [Python](https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter), [JavaScript](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages), and [Ruby](https://github.com/open-telemetry/opentelemetry-ruby/tree/main/exporter)) follow the principle of minimizing the number of dependencies, with a separate OTLP exporter implementation for each protocol. Many of these languages also have additional "configurator" components that enable the creation of exporters selected via environmental variables (for instance, `OTEL_TRACES_EXPORTER` and `OTEL_EXPORTER_OTLP_PROTOCOL`).

However, in some languages, an OTLP exporter supports multiple protocols ([.NET](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol), [Erlang](https://github.com/open-telemetry/opentelemetry-erlang/tree/main/apps/opentelemetry_exporter), [PHP](https://github.com/open-telemetry/opentelemetry-php/tree/main/src/Contrib/Otlp), [Rust](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp)). It's worth mentioning that for Rust, [optional dependencies](https://doc.rust-lang.org/cargo/reference/features.html) are supported, and it makes complete sense to structure it that way.

I believe that the decision of how `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL` should be supported should be made by the language Special Interest Group (SIG).

I suggest updating the specification to indicate that `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL` **SHOULD** be supported, with a footnote explaining that the support for these environment variables could be provided through separate components.

**Comment by pellared** [comment]
Duplicates https://github.com/open-telemetry/opentelemetry-specification/issues/3721 (I wanted to have a label)

**Comment by Oberon00** [comment]
@pellared Next time, we can add the labels later on
