### ISSUE TITLE
Clarify if the OTLP exporter has to support all protocol related env vars

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3721]
https://github.com/open-telemetry/opentelemetry-specification/blob/541b2ffe54ca416732aac5015c6b57ac3a678ae0/specification/protocol/exporter.md

**Problem statement**

Is it necessary for the OTLP exporter to intentionally support `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`?

**Analysis**

This requirement would create a dependency for the OTLP exporter on all the libraries utilized for implementing the transport protocols (such as the HTTP client, JSON parser, protobuf parser, and gRPC client). This means that users who only require the HTTP protocol might not want to introduce any gRPC dependencies to their application. In certain programming languages, like Go (as mentioned in this [paper](https://research.swtch.com/deps)), it is customary to minimize the number of dependencies. This approach also helps reduce the overall "security surface" of the components. It's important to note that if a gRPC library used by the exporter had a CVE, the entire exporter would be considered vulnerable as well (since most security static analysis tools solely check dependencies and not how the code is structured).

Currently, most languages (such as [C++](https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/otlp), [Go](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp), [Java](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp), [Python](https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter), [JavaScript](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages), and [Ruby](https://github.com/open-telemetry/opentelemetry-ruby/tree/main/exporter)) follow the principle of minimizing the number of dependencies, with a separate OTLP exporter implementation for each protocol. Currently, the specification does not align with these OTLP exporters, making them non-compliant. Most of these languages have additional (separate) "configurator" components that enable the creation of exporters selected via environmental variables (for instance, `OTEL_TRACES_EXPORTER` and `OTEL_EXPORTER_OTLP_PROTOCOL`).

However, in some languages, an OTLP exporter supports multiple protocols ([.NET](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol), [Erlang](https://github.com/open-telemetry/opentelemetry-erlang/tree/main/apps/opentelemetry_exporter), [PHP](https://github.com/open-telemetry/opentelemetry-php/tree/main/src/Contrib/Otlp), [Rust](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-otlp)). It's worth mentioning that for Rust, [optional dependencies](https://doc.rust-lang.org/cargo/reference/features.html) are supported, and it makes complete sense to structure it that way.

**Proposal**

I believe that the decision of how `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL` should be supported should be made by the language Special Interest Group (SIG).

I suggest updating the specification to indicate that `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL` **SHOULD** be supported, with a footnote explaining that the support for these environment variables could be provided through separate components.

**Comment by yurishkuro** [comment]
Sorry, I am missing the connection between "all env vars" (for different OTEL signals) vs. "all protocols".

On the latter, I do not believe this requires unnecessary coupling of dependencies. The SDK can be organized in such a way that when an exporter for specific protocol is imported into user app, it registers itself with the SDK. So if I only import HTTP exporter, then the only valid value for the env variable would be "http", using "grpc" would raise an error.

**Comment by pellared** [comment]
A few questions for clarification.

> The SDK can be organized in such a way that when an exporter for specific protocol is imported into user app, it registers itself with the SDK. 

Do you mean the SDK or the Exporter? The specification expects the env var support from the OTLP exporter implementation itself.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md?plain=1#L9

Still, I think get your idea and I have an idea how it could be implemented. I changed your recommendation a little - do you agree with it?

> **The exporter component** can be organized in such a way that when an exporter for specific protocol is imported into user app, it registers itself with the **the exporter component**. So if I only import **HTTP protocol driver**, then the only valid value for the env variable would be "http", using "grpc" would raise an error.

I do not think that the SDK should know anything about the OTLP exporter env vars.

**Comment by yurishkuro** [comment]
+1 to the quoted framing.

It's probably worth implementing the registration mechanism at the SDK level such that it's only done once, not in different way by every exporter. For example, at the SDK level we can have the same mechanism for selecting which _exporter_ to use (OTLP or Debug, for instance). This would also work well with the upcoming configuration mechanism - without it the Configurator class (or whatever) would need to import _everything_, which will defeat the min-deps purpose you're trying to achieve here.

**Comment by pellared** [comment]
Just o double-check.

SDK should have registration mechanism for `OTEL_TRACES_EXPORTER`, `OTEL_METRICS_EXPORTER`, `OTEL_LOGS_EXPORTER`.

OTLP exporters should have registration mechanism for `OTEL_EXPORTER_OTLP_PROTOCOL` `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL` `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`.

**Comment by pellared** [comment]
@yurishkuro, just to double-check.

SDK should have registration mechanism for `OTEL_TRACES_EXPORTER`, `OTEL_METRICS_EXPORTER`, `OTEL_LOGS_EXPORTER`.

OTLP exporters should have registration mechanism for `OTEL_EXPORTER_OTLP_PROTOCOL` `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL` `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`.

**Comment by chameleon82** [comment]
Should `OTEL_EXPORTER_OTLP_PROTOCOL` be validated if `none` is specified for `OTEL_{SIGNAL}_EXPORTER` ?

Should otlp (grpc or http) be explicitly added as a dependency as a default exporter?

**Comment by pellared** [comment]
> Should `OTEL_EXPORTER_OTLP_PROTOCOL` be validated if `none` is specified for `OTEL_{SIGNAL}_EXPORTER`?

IMO it is not necessary. In such scenario the  `OTEL_EXPORTER_OTLP_PROTOCOL` will not be used.

> Should otlp (grpc or http) be explicitly added as a dependency as a default exporter?

No. See https://github.com/open-telemetry/opentelemetry-specification/issues/3721#issuecomment-1761709128. For example if given language's OTLP implementation uses `http/protobuf` as a default protocol and the user would NOT register the HTTP protocol driver then the OTLP exporter factory may return an error saying that given protocol is unknown.

**Comment by pellared** [comment]
I created a draft PR https://github.com/open-telemetry/opentelemetry-specification/pull/3722 for initial feedback.

**Comment by pellared** [comment]
We discussed this matter at the Go SIG meeting.

The Go SIG would prefer to manage the exporter environment variables through a distinct package: https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport. This approach is akin to [Java Autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure). The rationale behind this decision is as follows:

1. If users aim to utilize the `OTEL_EXPORTER_OTLP_PROTOCOL` and `OTEL_TRACES_EXPORTER`, we aim to support all the values specified in the documentation. We want to ensure that users are not prone to encountering runtime errors if a protocol driver hasn't been registered in the code.
2. 
 Simultaneously, we wish to avoid applications to depend on all exporter implementations defined in the specification.

I intend to participate in the next Specification SIG meeting to deliberate on this matter with a broader audience.

**Comment by yurishkuro** [comment]
> manage the exporter environment variables through a distinct package

Yeah, that's the appropriate solution. My concern is whether this approach was also taken by other SDKs or did they follow the spec verbatim and bundled this into the core exporter -  it's now hard to unbundle without breaking behavior.

**Comment by pellared** [comment]
> Yeah, that's the appropriate solution.

I created https://github.com/open-telemetry/opentelemetry-specification/pull/3730

> My concern is whether this approach was also taken by other SDKs or did they follow the spec verbatim and bundled this into the core exporter - it's now hard to unbundle without breaking behavior.

I did my best to describe how all languages implemented the OTLP configuration options.
