### ISSUE TITLE
OTLP protocol for JavaScript running inside a browser

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3724]
The following

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md?plain=1#L148-L155

probably does not make sense for JavaScript running inside a browser.

I guess `http/json` is the way.

_Originally posted by @reyang in https://github.com/open-telemetry/opentelemetry-specification/pull/3722#discussion_r1362843832_

**Comment by svrnm** [comment]
https://github.com/open-telemetry/opentelemetry.io/pull/3133 -- as far as I am aware the WebTracer does http/protobuf 
(cc @scheler @open-telemetry/javascript-approvers)

**Comment by pichlermarc** [comment]
Yes, in JS we support exporting http/protobuf from the browser for traces and logs; metrics coming soon.

**Comment by pellared** [comment]
Closing then.
