### ISSUE TITLE
[Security recommendation] Enabling Allstar for monitoring organization-wide policies

### ISSUE THREAD

**Issue by EjiroLaurelD** [open-telemetry/opentelemetry-specification#3733]
[Allstar](https://github.com/ossf/allstar) was proposed as a way to achieve consistency across the repositories in the org with regards to security policy. 
It is a policy-based security tool that can help us to enforce security requirements and best practices across our organization. It can be used to enable and configure a variety of security tools and settings, such as CodeQL, static code analysis tools, and repository security settings.

I am proposing that we enable Allstar for this repository. Allstar will automatically configure a variety of security tools and settings for this repository. This will help us to improve the security of this repository and our organization's software as a whole.

Please let me know if you have any questions or concerns.

Parent issue: https://github.com/open-telemetry/sig-security/issues/21
cc @codeboten @jpkrohling

**Comment by jack-berg** [comment]
I believe this should be closed for the same reason https://github.com/open-telemetry/opentelemetry-helm-charts/issues/931 was closed. Please re-open if I'm misunderstanding.
