### ISSUE TITLE
Consider adding a statsd exporter standard in the spec

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-specification#374]
Any plan to add a statsd exporter for metrics?

**Comment by jmacd** [comment]
(I can't speak for the community here, but I've been involved in the SDK specification.)

The original project v1.0 scope did not mention a statsd exporter. The challenges with statsd are:
(1) that there is not a firm specification for it
(2) if using "plain" statsd, there's not a well-established (standard) way to handle labels, e.g., see https://github.com/prometheus/statsd_exporter
(3) if using "dogstatsd" statsd, the specification is still not very clear, but at least we know how to handle labels

@cory-signalfx has spoken up about this, see https://github.com/open-telemetry/opentelemetry-proto/issues/59#issuecomment-554458106

In the Go SDK I've included a common statsd implementation and a dogstatsd exporter, but there are questions about whether dogstatsd qualifies as vendor support (if it does not use the datadog client), especially considering there are open-source implementations of dogstatsd.

If you're interested in helping out, particularly if you're looking for "plain" statsd support and want to talk about how to handle labels, I'm interested.

**Comment by jmacd** [comment]
See https://github.com/open-telemetry/opentelemetry-go/tree/master/exporter/metric/dogstatsd

**Comment by jmacd** [comment]
The reason we can't do this is that statsd (and dogstatsd) do not have a formal specification.

**Comment by jmacd** [comment]
@jbarciauskas I've asked in the past whether DataDog is interested in producing a specification.

**Comment by jmacd** [comment]
We will not pursue a statsd implementation until there is a specification to follow. Let's revisit this discussion when there is a specification to follow.

**Comment by pauldraper** [comment]
The StatsD spec is here: https://github.com/statsd/statsd and has been for a decade.

If you're looking for some overwrought thing, you'll be disappointed, but the beauty of StatsD is in the utter simplicity of its specification.

(Speaking of Datadog, they did add an extension to StatsD. That obviously is not included.)
