### ISSUE TITLE
Generalize attribute naming recommendations

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#3746]
The [attribute naming](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md) document provides a lot of useful guidelines that we seem to be implicitly following in metric naming conventions. Note that there's a dedicated [metric semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming) document which seems to expand / build on the general naming recommendations.

In the 10/27 Event WG we discussed the desire to merge the [event.domain and event.name](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md) attributes into a single `event.name` field, modeled after metric names which have the same types of namespacing and uniqueness requirements we want to achieve.

We would want the same (or much of?) the same attribute naming advice to apply to event names as well.

Can / should we generalize the attribute naming document such that it applies to metric names and event names? @open-telemetry/specs-semconv-approvers are we implicitly applying the attribute conventions to metric names today or are they somehow different?

**Comment by pyohannes** [comment]
This was discussed in today's semantic convention SIG call.

> Can / should we generalize the attribute naming document such that it applies to metric names and event names?

Yes. We agreed that both documents have the same aim, and ideally there should just be once consistent source of truth. It should also apply to metric names (and already aims to do, as it mentions pluralization guidelines). Ideally, we can merge the attribute naming document from the spec repository and the metrics semantic conventions document from the semantic convention repository.

There also was some discussion about where this document should live. The semantic convention repository seems like a better place, as opposed to the spec repository.

**Comment by jack-berg** [comment]
The `semantic-conventions` repo seems like an appropriate home to me. And actually, the [attribute requirement level](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md) seems to also belong in `semantic-conventions`.

What do you think about a two stage approach?

1. Moving [attribute-naming.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md) and [attribute-requirement-level.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md) to [semantic-conventions/docs/general](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/general), being careful to retain git history.
2. Merging `attribute-naming.md` and relevant portions of [metric.md](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming).

**Comment by pyohannes** [comment]
> What do you think about a two stage approach?
>
> 1. Moving [attribute-naming.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md) and [attribute-requirement-level.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md) to [semantic-conventions/docs/general](https://github.com/open-telemetry/semantic-conventions/tree/main/docs/general), being careful to retain git history.
> 2. Merging attribute-naming.md and relevant portions of [metric.md](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-naming).

Sounds good to me. @open-telemetry/specs-semconv-maintainers?

**Comment by jack-berg** [comment]
This is resolved in #3758, [semantic-conventions#493](https://github.com/open-telemetry/semantic-conventions/pull/493) and [semantic-conventions#473](https://github.com/open-telemetry/semantic-conventions/pull/473).
