### ISSUE TITLE
Clarify that OTLP exporter options can be set as code

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#3748]
Currently specification/protocol/exporter.md is _de facto_ about how the configuration options must be exposed as env vars, but we should add a super-clear note that is done **in addition** to they exposed via code too.

**Comment by jack-berg** [comment]
I think this is covered by this [language](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-configuration.md#programmatic):

> The SDK MUST provide a programmatic interface for all configuration. This interface SHOULD be written in the language of the SDK itself. All other configuration mechanisms SHOULD be built on top of this interface.

To your point, it could be helpful to reinforce this in the `specification/protocol/exporter.md` document.

**Comment by tigrannajaryan** [comment]
@carlosalberto closing since it already seems to be covered. Please reopen if needed.
