### ISSUE TITLE
TRACKING: Stabilize instrument advisory parameter: "Attributes"

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-specification#3751]
**What are you trying to achieve?**

Stabilize [Instrument advisory parameter: Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-advisory-parameter-attributes).

**Additional context.**

These advisory parameters are important for the Java Instrumentation, where we have a unified API for recording spans/metrics (e.g. HTTP server spans / HTTP server metrics), and so we pass in a single set of attributes (the span attributes), and use this advisory parameter when we construct the metrics in order to provide a default attribute filter, and then users can create a metric view to override the default and stamp more or less of the span attributes onto the metric.

**Comment by trask** [comment]
Likely prototypes are the main blocker here. Have any other languages besides Java implemented this experimental advisory parameter yet? thx

**Comment by MrAlias** [comment]
Go has not implemented this yet.

**Comment by trask** [comment]
oops, closing, looks like I opened two issues for this (#3785)
