### ISSUE TITLE
Question about Exporter in spec-compliance-matrix.md

### ISSUE THREAD

**Issue by lmcmazh** [open-telemetry/opentelemetry-specification#3754]
**What are you trying to achieve?**

For Exporters section in spec-compliance-matrix.md (https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters), the following 4 Zipkin interfaces: JS showing blank box, which means status not known?
Zipkin V1 JSON	
Zipkin V1 Thrift	
Zipkin V2 JSON	
Zipkin V2 Protobuf

But I do see opentelemetry-exporter-zipkin package under https://github.com/open-telemetry/opentelemetry-js/tree/main/packages, what does this imply?

Also for OTLP, the matrix shows JS does support it, but the packages are under experimental: https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages, so if it is under experimental, is it safe to use it or not yet?

For Jaeger exporter, I saw it has been removed from the matrix, the package of opentelemetry-exporter-jaeger are still there, it will be ended March 2024 as it mentioned? It also suggest to use the experimental package for OTLP.

So we just want to confirm if experimental package for OTLP are good enough to use? how about zipkin package? is it really supported for JS?

**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.

**Comment by trask** [comment]
hi @lmcmazh! I'd recommend opening this issue in the https://github.com/open-telemetry/opentelemetry-js repository.

**Comment by lmcmazh** [comment]
sure, thanks a lot!

**Comment by arminru** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-js/issues/4246.
