### ISSUE TITLE
Tracking: Exemplar Specification - Stabilization

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#3756]
This bug is tracking issues that must be resolved before Exemplars can be declared stable.

- [x] #3669 
- [x] #3674
- [x] #2421
- [x] #2205
- [x] #3812
- [x] Exposing `ExemplarReservoir` for users to override its behavior. (This unblocks feature requests like #2922)
- [ ] Revert #2414 or otherwise enable exemplars by default w/ SHOULD/MAY requirement.
- [x] #3943

**Comment by jack-berg** [comment]
Added `Clarify that exemplars are best effort and changing defaults are non-breaking` per this conversation: https://github.com/open-telemetry/opentelemetry-specification/pull/3870#discussion_r1483140692

**Comment by reyang** [comment]
The TC discussed this during the Mar. 13th, 2024 meeting:

1. There is only one blocking issue (more details can be found from #3756), @jack-berg is working on it #3943.
2. After PR #3943 is merged, we should be ready to move this PR forward. We're targeting mid Apr. for the Metrics Exemplar spec to be marked Stable (spec release will happen early May).
