### ISSUE TITLE
Tuple types are referenced from `InstrumentationScope` but not crisply defined anywhere

### ISSUE THREAD

**Issue by acruise** [open-telemetry/opentelemetry-specification#3770]
re: https://github.com/open-telemetry/opentelemetry-specification/blob/fd76183557effd39288018dcea198356d2334ae9/specification/logs/data-model.md?plain=1#L431-L433

e.g. if this is to be represented in JSON, which of these should be valid?
* `["com.example.scope", "1.0.0"]`
* `{"scope":"com.example.scope","version":"1.0.0"}`
* `{"scope":"com.example.scope","version":null}`
* `"com.example.scope"` (version omitted?)

Plus it's not clear (at least from this context) that there's a well-known definition of `Version`, it should be hyperlinked if it exists. :)

**Comment by tigrannajaryan** [comment]
The [data-model.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) file defines a logical model and intentionally does not specify a concrete representation in a particular format (e.g. JSON). For concrete representation see https://github.com/open-telemetry/opentelemetry-proto that defines both a JSON and Protobuf format for the log data model.

The Name and Version are opaque strings. The format of the version string is intentionally left out, any string is considered a valid value.

**Comment by tigrannajaryan** [comment]
If there is further questions please feel free to reopen.
