### ISSUE TITLE
ZPAGES no longer supported in opentelemetry-cpp

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-specification#3786]
opentelemetry-cpp removed the ZPages implementation:

* https://github.com/open-telemetry/opentelemetry-cpp/issues/2292

As a result, the file `experimental/trace/zpages.md` needs to be updated, as it contains:

```
Within OpenTelemetry, zPages are being developed in C++.
```

**Comment by tigrannajaryan** [comment]
Do any other SDKs implement zpages? I don't think zpages got much momentum. If that is the case we should consider removing them altogether from the spec.

**Comment by jack-berg** [comment]
@marcalff can you open a PR to remove the c++ reference from the zpages page?
