### ISSUE TITLE
Do we need a term "payload" for the events?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3787]
We reference "Payload" in a few places in [events spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md). It seems to be the synonym of the Body. We need to decide it Payload is any different, if it is it needs a definition otherwise we should probably get rid of it.

**Comment by austinlparker** [comment]
Resolved by https://github.com/open-telemetry/semantic-conventions/pull/566/
