### ISSUE TITLE
Duration of OpenTracing Shim Support

### ISSUE THREAD

**Issue by karusher** [open-telemetry/opentelemetry-specification#3795]
Hi,

I'm working on a project that is migrating from the Jaeger client to OpenTelemetry. We're trying to decide whether to use the OpenTracing shim or OpenTelemetry directly.

Can you please tell us how long the shim will be supported? This will help us decide which way to go.

Thank you.

**Comment by yurishkuro** [comment]
There are no specific sunsetting plans for the shims right now. What time horizon are you looking for?

My personal experience with migrating the Jaeger backend itself from OT to OTEL was that the shim was useful as an intermediate solution that allows you to introduce OTEL SDKs first as the underlying implementation, and then gradually upgrade the instrumentation from OT to OTEL proper. The latter can be done incrementally, at least in Go there was a reasonably good interop between the shim and OTEL proper (some glitches with baggage).

**Comment by karusher** [comment]
Thank you for the reply.

I was hoping for a time horizon of five years. However, I realize that might be unrealistic.

Do you have any guess as to what the future may hold?

**Comment by austinlparker** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#long-term-support

As the shims are part of the SDK, we guarantee support for components up to one year after a release, including the shims. Conservatively I would expect support to last for longer than that, but we can't make any guarantees.
