### ISSUE TITLE
Document Java API: Tracing operations API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#38]
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. 
Most of APIs are ready to be documented in a form of cross-language specification. 

Tracing API needs to be described

**Comment by SergeyKanzhelev** [comment]
@c24t as discussed offline - assigning to you

**Comment by SergeyKanzhelev** [comment]
@songy23 while @c24t is on vacation - can you take this one?

**Comment by songy23** [comment]
I'll take a look.
