### ISSUE TITLE
Project Tracking: OpenTelemetry Collector v1

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-specification#3819]
### Description

Quite a few of our users are happy using a non-v1 Collector, as evidenced by talks delivered by eBay or VTEX. On the other hand, other companies have internal policies forbidding the usage of software that hasn’t reached v1.

Other companies, hearing the success stories of the “early adopters”, tried to use the Collector, but due to a lack of guidance, ended up using components that weren’t ready for prime time and were frustrated.

Our main goal with this project is to define what's the scope for Collector v1, defining which use-cases we want to satisfy first, followed by stabilizing the components that are required for that. Once we are there, we'll focus on documentation for those components and use cases.

We believe we are close to a v1 of the Collector, given that users are using it in production already. Therefore, we are confident we can deliver a v1 this year.

Teams involved in this:
* @open-telemetry/collector-approvers 
* @open-telemetry/collector-contrib-approvers 
* @open-telemetry/collector-maintainers 
* @open-telemetry/collector-contrib-maintainer 
 
### Project Board

To be created.

### Deliverables

The current goal (subject to change) is to have deliverables covering our two current distributions: core and contrib. Deliverables should be linked from the main opentelemetry.io website. 

#### Must-haves
* Binaries for Windows, MacOS, and Linux for amd64 and x86
* Multi-arch container images

#### Nice to have
* OS-specific packages for Linux (deb, rpm, …)

### Staffing / Help Wanted

@jpkrohling is the GC sponsor for this and has the buy-in from other Collector leaders, including core and contrib approvers/maintainers (listed above).

### Meeting Times

For the public discussions, we are using the Collector SIG meeting slot.

### Timeline

To be defined, but this project should be completed in 2024.

**Comment by jpkrohling** [comment]
Relevant milestones: 

* https://github.com/open-telemetry/opentelemetry-collector/milestone/31
* https://github.com/open-telemetry/opentelemetry-collector/milestone/54
* https://github.com/open-telemetry/opentelemetry-collector/milestone/57

**Comment by jpkrohling** [comment]
@yurishkuro, would you please add the required labels to have this item show up on the project board?  
https://github.com/orgs/open-telemetry/projects/29/views/1

**Comment by yurishkuro** [comment]
I don't think project boards are driven by labels, you add issues directly to them. I don't know which labels you have in mind.

**Comment by jpkrohling** [comment]
I can't seem to be able to change that board at all, it might be restricted to TC members only. @arminru, given that you added my other issue there (https://github.com/open-telemetry/opentelemetry-specification/issues/3824). would you mind sharing what was needed?

**Comment by arminru** [comment]
@jpkrohling I had to add it manually. The board is set up so that all spec approvers (including TC) have write access.
There's no label-driven automation to add issues automatically to the board but this could be set up if desired.

**Comment by jpkrohling** [comment]
Closed in favor of https://github.com/open-telemetry/community/pull/1887

**Comment by jpkrohling** [comment]
Reopening, as we'll use this issue to track at the GC level.
