### ISSUE TITLE
Not clear whether values in `OTEL_EXPORTER_OTLP_HEADERS` should be URL encoded

### ISSUE THREAD

**Issue by pyohannes** [open-telemetry/opentelemetry-specification#3832]
**What are you trying to achieve?**

We're trying to share the same values for `OTEL_EXPORTER_OTLP_HEADERS` across different languages. However, while [Python requires header values to be URL encoded](https://github.com/open-telemetry/opentelemetry-python/pull/2103/files#diff-ea5a84ee652d1dc0b4c5b9f113d50f8262e764605c35d339fcb8f460c733a9c6R28), Java and .NET cannot deal with URL encoded values. I didn't yet check other languages.

**Additional context.**

The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specifying-headers-via-environment-variables) refers to the W3C Baggage specification for details about the format of `OTEL_EXPORTER_OTLP_HEADERS`:
> The `OTEL_EXPORTER_OTLP_HEADERS`, `OTEL_EXPORTER_OTLP_TRACES_HEADERS`, `OTEL_EXPORTER_OTLP_METRICS_HEADERS`, `OTEL_EXPORTER_OTLP_LOGS_HEADERS` environment variables will contain a list of key value pairs, and these are expected to be represented in a format matching to the [W3C Baggage](https://www.w3.org/TR/baggage/#header-content), except that additional semi-colon delimited metadata is not supported, i.e.: key1=value1,key2=value2. All attribute values MUST be considered strings.

The W3C Baggage spec [requires values to be URL encoded](https://www.w3.org/TR/baggage/#value):
> A value contains a string whose character encoding MUST be UTF-8 [[Encoding](https://www.w3.org/TR/baggage/#bib-encoding)]. Any characters outside of the baggage-octet range of characters MUST be percent-encoded. Characters which are not required to be percent-encoded MAY be percent-encoded.

I wonder whether it was the original intent of requiring URL encoding for `OTEL_EXPORTER_OTLP_HEADERS`, or whether that's an unintended side-effect of referencing the W3C Baggage spec.

**Comment by jack-berg** [comment]
I think the spec is clear and its just a bug in the case of java not dealing with URL encoded values. For proof, consider that the resource specification contains similar language for how key / values are encoded: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable

And in otel java, we perform url decoding on resource attribute values: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L70

We should just do the same thing for `OTEL_EXPORTER_OTLP_HEADERS`.

**Comment by pyohannes** [comment]
> I think the spec is clear and its just a bug in the case of java not dealing with URL encoded values.

Looking at different exporter implementations, it seems that implications of referring to W3C Baggage aren't all that clear:

| Language | URL-encoded `OTEL_EXPORTER_OTLP_HEADERS` | non URL-encoded `OTEL_EXPORTER_OTLP_HEADERS` |
| -- | -- | -- |
| .NET | :x: | :heavy_check_mark:  |
| .C++ | :x: | :heavy_check_mark: |
| Go | :heavy_check_mark: | :heavy_check_mark: |
| Java | :x: | :heavy_check_mark: |
| Python | :heavy_check_mark: | :x: |

What's not clear to me is whether the desired behavior is the one implemented in Go (both encoded and non-encoded headers are supported) or the one implemented in Python (only encoded headers are supported).

I assume that languages currently not supporting encoded headers will do what Go does and support both, as otherwise this would be a breaking change.

Note that this isn't an esoteric use case, as authentication headers contain spaces.

**Comment by dyladan** [comment]
JS also url-decodes OTEL_EXPORTER_OTLP_HEADERS

**Comment by pyohannes** [comment]
@dyladan But JS still accepts non URL-encoded values in `OTEL_EXPORTER_OTLP_HEADERS` (like Go does)? It doesn't strictly require proper URL-encoding like Python?

**Comment by dyladan** [comment]
It does not strictly require it in JS

**Comment by jack-berg** [comment]
👍 

FWIW, in the proposed [java fix for this](https://github.com/open-telemetry/opentelemetry-java/pull/6164/commits/56ef0813a1f2e90f1573d1f686141206bcab132f), I just added a test to confirm that non-url encoded values continue to work as well. So with the fix,

**Comment by pyohannes** [comment]
> 2. Support both URL-encoded and non URL-encoded values (which is not strictly required by the spec).

This seems to be the feasible way to go. If there are no objections, I can create PRs for languages currently not supporting URL encoded values to:
* Add support for URL encoded header values to conform with the specification.
* Keep support for non URL encoded values to not break users.

**Comment by pyohannes** [comment]
PRs for implementing the solution described in https://github.com/open-telemetry/opentelemetry-specification/issues/3832#issuecomment-1911827015 have been submitted for .NET, Java, PHP, Rust, and C++. For Erlang and Swift I don't know the current state of support of URL encoded values, however, I raised this issue in the relevant Slack channels.

Given this, I'll close this issue.
