### ISSUE TITLE
Clarify handling empty (null) values in Logs Data Model

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3835]
The Logs Data Model tells nothing about handling empty (null) values (e.g. for attributes).

See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any

I think that the specification should include some clarification similarly to: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute.

I think that in "maps" an empty (null) value SHOULD be an acceptable value (only the key MUST be not null or empty). It is pretty common to have empty field values in complex structures and users would most likely preserved empty data e.g. in log attributes.

Take into consideration that it some languages it is not possible to define an API that would not accept a "null value" (e.g. zero value in Go). The implementation would have to take care of the empty value passed by the caller. Moreover, from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute:

> However, if it is impossible to make sure that no null values are accepted (e.g. in languages that do not have appropriate compile-time type checking), null values within arrays MUST be preserved as-is

CC @open-telemetry/specs-logs-approvers 

Related PR: https://github.com/pellared/opentelemetry-go/pull/7

**Comment by yurishkuro** [comment]
The common part is already pretty detailed about what to do with empty attributes. What specifically do you think is missing for 🪵?

**Comment by pellared** [comment]
Common attributes definition is different from log attributes. I was thinking about putting similar description to Logs Data Model.
