### ISSUE TITLE
Discrepancy between status names

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-specification#384]
The specification [follows](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#statuscanonicalcode) the standard GPRC codes. Nevertheless, `UnknownError` and `InternalError` in this specification do not match `UNKNOWN` and `INTERNAL` as [defined](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) in GRPC.

**Comment by Oberon00** [comment]
I think the OpenTelemetry names are better, as INTERNAL is indeed meant to indicate an internal error.

**Comment by carlosalberto** [comment]
> I think the OpenTelemetry names are better

Agreed. The lack of an `Error` suffix could easily cause confusion ;)
