### ISSUE TITLE
Clarify that log attributes are NOT standard attributes

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3849]
**What are you trying to achieve?**

Currently, logs attributes are different from standard (resource, trace, metrics) attributes.
However, there may be a desire to make unify them as some languages already use standard attributes for defining log attributes.

I want to have clarification that log attributes are distinct from standard attributes before stabilizing OTel Go Bridge API.

My proposal is to [explicitly call out](https://github.com/open-telemetry/opentelemetry-specification/pull/3816#issuecomment-1895151447) that log attributes are different. 

**Additional context.**

Follow-up to: https://github.com/open-telemetry/opentelemetry-specification/pull/2888#issuecomment-1904888370

Prior PRs:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3816
- https://github.com/open-telemetry/opentelemetry-specification/pull/2888

There seem to be no consensus whether the standard attributes should be expanded to support complex types.

I don't believe we'll reach a consensus on limiting log attributes to only accommodate types defined by standard attributes. This would be also a breaking specification change. 

I also want to point out that the Bridge API does anyway require the ability to support complex types for log record body. Therefore, the log attributes can be defined using the types used for modelling body. 

Moreover, OTLP already supports complex types for attributes so there is no technical need to limit the log attribute values.

Related issues:
- https://github.com/open-telemetry/opentelemetry-specification/issues/3835
- https://github.com/open-telemetry/opentelemetry-specification/issues/3836

**Comment by trask** [comment]
> I don't believe we'll reach a consensus on limiting log attributes to only accommodate types defined by common attributes. This would be also a breaking specification change.

Deprecation would be an option

**Comment by pellared** [comment]
SIG meeting notes:

By @tedsuo: It may sense to have log attributes to be modeled differently than common attributes as the purpose of Bridge API is to support what existing logging libraries offer.
