### ISSUE TITLE
editorial: Move "Schema File Format Number" sections to `README.md`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3851]
Shouldn't we move the "Schema File Format Number" sections to `README.md`? Version number handling should be something "generic".

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-specification/pull/3845#discussion_r1471512766_

**Comment by jack-berg** [comment]
Discussed this and decided we want to keep the format specification complete. I.e. a reader should be able to fully understand the schema file format version based on the contents of a particular schema file format version's specification. When new versions of schema file format version are introduced, we expect the content to be largely the same, with small updates reflecting the changes.
