### ISSUE TITLE
Have SDK TracerProvider expose its Resource

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#3857]
Having the **SDK** `TracerProvider` expose its `Resource` can be useful (e.g. retrieve service name). Some of the SIGs don't expose it (Java, Go, DotNet), and some do (Python, JS, C++). In theory that could be up to the maintainers to decide, as it's more of an good-thing more than a hard requirement, but this _feels_ to me that it would be useful to specify this one.

Thoughts?

**Comment by MrAlias** [comment]
Are there users requesting this? What are they using the resource for?

**Comment by jack-berg** [comment]
We discussed and are reluctant extend the SDK requirements without a better understanding of the use cases. Closing for now, but can re-open this issue (or a new one) if concrete use cases emerge.

**Comment by jmacd** [comment]
For future readers: the objection we have seen, in the past, to exposing resource in the SDK, is that consumers of this information are likely to use it inefficiently. If we are aware of reasons to use the resource at runtime, as we are for certain Sampling decisions e.g., we should prototype SDK-setup routines that establish the resource in-use once at startup, not simply expose the resource.
