### ISSUE TITLE
Loosely defined behavior when parsing unset environment variables

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry-specification#3864]
The [Parsing empty value](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#parsing-empty-value) SDK env variables specification, says that env variables with empty values should be interpreted the same way as unset:

> The SDK MUST interpret an empty value of an environment variable the same way as when the variable is unset.

But I couldn't find any similar specification defining the behavior for interpreting unset env variables. 

**Additional context.**

The question came up when adding the env resource detector to Envoy proxy. Initially, the detector was throwing an exception when the variable was unset/empty (which the Envoy community initially thought that was the best way forward). Now revisiting this decision, we want to [prevent the detector throwing errors](https://github.com/envoyproxy/envoy/pull/32229), as it impacts things like service meshes (e.g., Istio)

Then, a question in the PR came: if the env variable is set, but empty it should still throw an error. Then pointing to the spec section above makes it unclear what it should be done, since there's no definition for unset. 

**What did you expect to see?**

It seems all SDKs I looked, don't throw errors when the env variable is unset, which makes sense. Then this makes unset/empty the same thing. IMO this should be also written to the spec to avoid any confusion. 

- [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/resource/resource_detector.cc#L19)
- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/ResourceConfiguration.java#L62C23-L62C42)
- [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Resources/OtelEnvResourceDetector.cs#L26)
- [PHP](https://github.com/open-telemetry/opentelemetry-php/blob/main/src/SDK/Resource/Detectors/Environment.php#L21-L23)
- [Go](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/resource/env.go#L54)
- [Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/env/env.go#L45-L51)
- [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-resources/src/detectors/EnvDetectorSync.ts#L57)
- [Python](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L309-L322)

**Comment by jack-berg** [comment]
> Then pointing to the spec section above makes it unclear what it should be done, since there's no definition for unset.

The definition for empty is presumably runtime dependent. A runtime might return `null`, `nil`, an empty string `""`, or some other equivalent when an environment variable is unset.

Are you looking to have this codified, or something else?

**Comment by jack-berg** [comment]
Closing. @joaopgrassi please re-open if you think some additional clarity is needed in the spec.

**Comment by joaopgrassi** [comment]
Sorry I missed this somehow. 

> The definition for empty is presumably runtime dependent. A runtime might return null, nil, an empty string "", or some other equivalent when an environment variable is unset.

Yeah that makes sense. It is just lacking what it should be done/behavior when any of these happen. Should it throw. should it log error etc. Because "empty" refers that it should behave the same as `unset` but we never tell what is the behavior of `unset`. 

I think it can create different behaviors and probably best if it's clarified.
