### ISSUE TITLE
Stabilize AddLink operation in Trace API

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3865]
**What are you trying to achieve?**

Mark https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#add-link as stable.

**Comment by pyohannes** [comment]
* open-telemetry/opentelemetry-dotnet#5273
* open-telemetry/opentelemetry-java#6084
* open-telemetry/opentelemetry-python#3618
* open-telemetry/opentelemetry-cpp#2380

**Comment by pyohannes** [comment]
cc @carlosalberto, who is working on stabilizing this.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#traces This shows only OTel C++ has implemented this. Most likely this matrix is out-of-date.

@carlosalberto Could you help to make this matrix updated, so it is easy to tell who all have implemented this?

**Comment by jack-berg** [comment]
> Most likely this matrix is out-of-date.

In java, I've only been updating the compliance matrix once we have stable support for something. Not sure this is correct, since it eliminates the spec compliance matrix as a tool for evaluating the stability readiness of experimental features. Maybe I could populate the cell with a symbol which conveys the feature is available but experimental?

**Comment by cijothomas** [comment]
> > Most likely this matrix is out-of-date.
> 
> In java, I've only been updating the compliance matrix once we have stable support for something. Not sure this is correct, since it eliminates the spec compliance matrix as a tool for evaluating the stability readiness of experimental features. Maybe I could populate the cell with a symbol which conveys the feature is available but experimental?

There was no specific guidelines about when should the matrix be filled in - whether it is done after feature is done in stable or just preview/experimental. Your suggestion of using some symbol to indicate experimental/preview is good! (Though we may need to establish and apply that convention for everything else in the matrix already)

**Comment by jack-berg** [comment]
The exemplars example is strange. In java, we turn on exemplars by default even tho they are experimental. We justified this for a variety of reasons, including that exemplars are stable in the data model. However, the APIs for configuring exemplars are still experimental.

So exemplars are a bit of an oddity for java - somewhere in between stable / experimental - but generally I've resisted filling out the compliance matrix until stable.

**Comment by carlosalberto** [comment]
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3698

**Comment by jack-berg** [comment]
We're waiting to decide if #3698 is a prerequisite for stabilization. This was discussed in the 2/13/24 spec SIG, and nobody expressed an opinion that #3698 was blocking. Will give a few more days for anyone to speak up that this is blocking.
