### ISSUE TITLE
Metrics API: instrument name and label name guidelines and limitations

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#387]
Both Prometheus and Dogstatsd specify a set of valid characters for metric names and label names.  The OTel specification should include more language in the specification about this sort of limitation.

Prometheus:

https://prometheus.io/docs/practices/naming/

Dogstatsd:

https://docs.datadoghq.com/developers/guide/what-best-practices-are-recommended-for-naming-metrics-and-tags/
https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics
https://docs.datadoghq.com/tagging/

**Comment by jmacd** [comment]
Some exporters also restrict labels. For example, Prometheus libraries will **panic** if you use the label "quantile". We should specify this sort of restriction somewhere.

**Comment by reyang** [comment]
This should have been resolved by #1578 which has defined the instrument names and also adopted Attributes.
The metrics backend might put more restriction on the attribute name, which could be the details of exporter (for example, key-value-pair fetched from baggage and context will also have such issues if the name won't fit the backend limitation).
