### ISSUE TITLE
Document Java API: Tracer construction

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#39]
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. 
Most of APIs are ready to be documented in a form of cross-language specification. 

Tracing class construction needs to be described. Tracer for specific library. Global Tracer, etc.

**Comment by SergeyKanzhelev** [comment]
@carlosalberto any progress here? We need to wrap up this milestone.

**Comment by pavolloffay** [comment]
@carlosalberto have you started? I wanted to have a look at this one.
