### ISSUE TITLE
Default SDK Configuration mechanisms

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-specification#390]
The default SDK should have a specified mechanism for configuration. This issue is not to track the specification of what is configurable, but rather *how* configuration should be made available to SDK users.

In general, the underlying mechanism should be programmatic. Every piece of the default SDK that requires configuration should have that configuration exposed to code. Declarative options (eg. JSON, YAML, env vars, etc) can then be built on top of that programmatic mechanism, as appropriate to the language of the SDK.

**Comment by jkwatson** [comment]
Note: I am working on a PR to provide the skeleton of this specification.

**Comment by mwear** [comment]
Ruby has a streamlined way to configure the SDK. I think it is similar to what you are proposing here. Take a look at this PR for examples: https://github.com/open-telemetry/opentelemetry-ruby/pull/171.
