### ISSUE TITLE
[editorial] Move the attribute type extension note for better readability

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#3925]
As part of #3858 specification/common/README.md was added to include a NOTE in the **Attributes** section:

> NOTE: extending the set of attribute value types is a breaking change. This was decided after extensive debate, with arguments as follows: ... etc

Consider moving this to the end of the **Standard Attributes** sub-section instead, hopefully making things clearer and in the same location.

cc @mattmccleary

**Comment by mattmccleary** [comment]
Sure, here's a PR to resolve the issue and resolve feedback from Tigran and I.
https://github.com/open-telemetry/opentelemetry-specification/pull/3926

CC: @tigrannajaryan

**Comment by tigrannajaryan** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-specification/pull/3926
