### ISSUE TITLE
Add example of env expansion with non-standard integer notation

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#3959]
Consider the case where the variable `HEX_VALUE` is set to `0xdeadbeef`, and a configuration field such as:

```
string_field: ${HEX_VALUE}
```

where `string_field` has type `string` on the JSON schema. What should its value be? I am not sure which of the following would be correct per the spec:
1. The string with value `0xdeadbeef` (preserving the original presentation format)
2. The string `3735928559` (representing with a standard base 10 format)
3. A type validation error

Having an explicit example of this case on the spec would be useful to understand it.

**Comment by trask** [comment]
cc @open-telemetry/configuration-maintainers

**Comment by mx-psi** [comment]
Fixed by #3975
