### ISSUE TITLE
 Support for escaping environment variable syntax

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#3960]
The current wording on the specification regarding environment variable substitution does not support escaping said syntax. If somebody wants to explicitly set a field to `${ENV}`, they won't be able to do so.

In the Collector we support `$${ENV}` for this. It would be desirable to:
1. decide whether this feature is supported on the Configuration specification
2. define its behavior on the specification.

**Comment by pellared** [comment]
Related (supset?) to https://github.com/open-telemetry/opentelemetry-specification/issues/3914

**Comment by jack-berg** [comment]
Closing as a duplicate of #3914. Adding the collector syntax to the convo in #3914.
