### ISSUE TITLE
Define or recommend YAML schema supported

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#3962]
Current [spec wording](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.31.0/specification/configuration/file-configuration.md#yaml-file-format) says that:

> [YAML](https://yaml.org/spec/1.2.2/) configuration files SHOULD follow YAML spec revision >= 1.2.

This leaves some ambiguity as YAML supports several 'schemas' (ways of interpreting the values that are not explicitly marked with a type tag). The YAML spec [recommends the Core schema](https://yaml.org/spec/1.2.2/#103-core-schema) (although, IIUC, this recommendation is not normative).

To give a concrete example, in Go, the main YAML parsing libraries ([1](https://github.com/goccy/go-yaml), [2](https://github.com/go-yaml/yaml)), both support the YAML 1.1 `0` leading octal syntax notation, where `0123` is equivalent to `0o123` or `83`, while the YAML 1.2 core schema does not. If this is not the case in other languages, differences when interpreting integer literals could lead to hard-to-debug and unintuitive results.

The SDK configuration spec should recommend what YAML schema to use, and if possible explicitly define the recommended behavior with `0` leading integer literals.

**Comment by trask** [comment]
cc @open-telemetry/configuration-maintainers

**Comment by mx-psi** [comment]
#3973 proposes to follow the core schema
