### ISSUE TITLE
pkg/translator/jaeger: Copy the Jeager exporter docs from the specification

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#3980]
Move https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md under `pkg/translator/jaeger`.

Per our [CODEOWNERS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/92d3e8e26335348b2607e529f29421f14b728057/.github/CODEOWNERS#L148) `pkg/translator/jaeger` is owned by @open-telemetry/collector-approvers and @frzifus. As part of said group I am in favor of moving the spec to collector-contrib for now, though personally I would like to see collector-contrib eventually be exclusively for components and move this library to some other repository

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-specification/issues/3964#issuecomment-2031457510_

**Comment by astencel-sumo** [comment]
Created PR to copy the docs to contrib:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32187

**Comment by tedsuo** [comment]
Resolved by #321
