### ISSUE TITLE
Clarify how array attributes should be turned into prometheus attributes

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/opentelemetry-specification#3982]
**What are you trying to achieve?**

We allow attributes to be arrays of a specific type, so otel-go has [attribute.StringSlice](https://pkg.go.dev/go.opentelemetry.io/otel/attribute#Key.StringSlice), and its equivalents for integers, floats and booleans.

However, there doesn't seem to be any specific clarification for those attributes when they are exported to prometheus/openmetrics.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-attributes

Right now, Go calls the `Emit()` method for every attribute in the prometheus exporter, which turns them into a go-specific representation of the array.
I believe we should provide a clearer format for those arrays when they are exported for prometheus/openmetrics.

Some SDKs seem to export those values in JSON format [js](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts#L45-L56).
Most seem to dump the value into a string [python](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py#L375), [java](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverter.java#L475), [go](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/prometheus/exporter.go#L308).

JSON doesn't seem like it would be a good format, as that would be rather verbose, and prometheus doesn't handle parsing it in queries

**Suggestion**

My suggestion would be that exporters MUST export arrays of attribute values as comma-separated list of values.

**Additional context.**

Related discussion: https://github.com/open-telemetry/opentelemetry-go/issues/5136

**Comment by dmathieu** [comment]
cc @open-telemetry/wg-prometheus

**Comment by dashpole** [comment]
The prometheus spec links to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute, which says:

> For protocols that do not natively support non-string values, non-string values SHOULD be represented as JSON-encoded strings. For example, the expression int64(100) will be encoded as 100, float64(1.5) will be encoded as 1.5, and an empty array of any type will be encoded as [].

**Comment by dmathieu** [comment]
The thing is, based on @StarpTech comment in https://github.com/open-telemetry/opentelemetry-go/issues/5136, a JSON-encoded array cannot be split into single entities for querying. So it becomes a giant blob that's unusable except for looking precise values.

**Comment by dmathieu** [comment]
I do believe this issue can be closed. The spec specifies they should be JSON-encoded, we can continue ensuring that in the go repository.
