### ISSUE TITLE
Documentation for creating a custom Instrumentation class.

### ISSUE THREAD

**Issue by sushaanttb** [open-telemetry/opentelemetry-specification#3986]
I had a use case where I wanted to create my own custom instrumentor class. However, I could not find any reference for same in the documentation.
The user in this case is left wondering on the steps for same and it requires a bit of research (for e.g. by having a look at other instrumentation libraries implementation) to understand the process.

As figured out, it's simply just about extending the BaseInstrumentor class from _opentelemetry.instrumentation.instrumentor_  package
and implementing it's abstract methods accordingly.

<img width="818" alt="image" src="https://github.com/open-telemetry/opentelemetry-specification/assets/12629751/663eb442-9db4-4265-8740-c6ec5cc11f63">

I think it would be very helpful for users if there could be respective section for same in the documentation.

**Comment by MrAlias** [comment]
Is this issue meant for the https://github.com/open-telemetry/opentelemetry-python respository?

**Comment by sushaanttb** [comment]
@MrAlias No, this is a general comment, not specifically w.r.t python SDK (that was meant to share only as a ref.) Updated comment accordingly. Also, the reason I am raising it under Spec is as per the "issue raising guidelines" that if the issues is general and not related to any language then it needs to be raised under spec.

@tedsuo Hope it's ok to reopen now?
