### ISSUE TITLE
Clarify the differences between entries in distributedContext and attributes of spans

### ISSUE THREAD

**Issue by huikang** [open-telemetry/opentelemetry-specification#399]
The description of [DistributedContext](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#distributedcontext) says `These values can be consumed from DistributedContext and used as an additional dimension for a metric, or additional context for logs and traces.` However, I feel that the key-value entries could also be set in the attributes in a span. Could anyone help to clarify what key values should be used in distributedContext, while others in span attributes. Thanks.

**Comment by reyang** [comment]
The name has changed to `CorrelationContext`. The difference between CorrelationContext and Span attributes are the scope. Span attributes only works for a particular span, and not propagated within the process or across services.
