### ISSUE TITLE
how can I convert resource attributes to data point attributes in metrics

### ISSUE THREAD

**Issue by windniw** [open-telemetry/opentelemetry-specification#3996]
**What are you trying to achieve?**

how can I convert resource attributes to data point attributes in metrics, and I can search it in prometheus 

logs like this:
```
Resource SchemaURL:
Resource attributes:
     -> aoe: Str(aoeeeeeeeeee)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope example_meter
Metric #0
Descriptor:
     -> Name: example_counter
     -> Description:
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> environment: Str(production)
---
example_counter_total{environment="production"} 264
```
What did you expect to see?

example_counter_total{environment="production",aoe="aoeeeeeee"} 264

**Comment by austinlparker** [comment]
You can do this in the OpenTelemetry Collector using the transformprocessor, or use the `resource_to_telemetry_conversion` option in the prometheus exporter (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter).

This is really more of a support request; If you have further issues, please open them in the appropriate repository. Thanks!
