### ISSUE TITLE
Environment variable to set metrics producers

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-specification#4015]
**What are you trying to achieve?**

I was trying to use the [`autoexport` package](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/exporters/autoexport) in Golang SDK which configures the exporting and SDK through the environment variables in semantic conventions. 

However, I needed to add the Prometheus metrics producer and there was no way to do it when using autoexport. 

I'd like to propose a new environment variable `OTEL_METRICS_PRODUCERS` where users can pass comma separated producer values.

**Additional context.**

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5281 has an implementation of this environment variable. cc @dashpole @pellared 

I know there is a moratorium on new environment variables, but I'd like to atleast merge the above PR as EXPERIMENTAL to unblock my use-case.

**Comment by danielgblanco** [comment]
I believe this needs input from the TC as per this [comment](https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503). I also added this to the Configuration SIG inbox, as they will be interested in this issue.

**Comment by jack-berg** [comment]
From a file configuration standpoint, metric producers are an SDK extension point. We support referencing custom implementations of SDK extension points via the [component provider](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md#component-provider) mechanism. If someone wants to open a PR to https://github.com/open-telemetry/opentelemetry-configuration to extend the schema with the metric producers, I'm supportive.

**Comment by jack-berg** [comment]
This is being added to file configuration in https://github.com/open-telemetry/opentelemetry-configuration/pull/90

Discussed (briefly) in the 5/22 TC and we believe that file configuration should be sufficient and we should not add a new environment variable for this. I.e. under the [moratorium](https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503) this is considered non-essential.
