### ISSUE TITLE
Clarify breaking changes are allowed when there is a major version bump

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#4038]
This sounds too strong IMHO. I think OpenTelemetry follows semver2, breaking changes are still allowed if there is a major version bump.

_Originally posted by @reyang in https://github.com/open-telemetry/opentelemetry-specification/pull/4030#discussion_r1587918308_

**Comment by danielgblanco** [comment]
@reyang is this already accepted by the TC? As the PR already has comments and approvals.
