### ISSUE TITLE
Apply new stability definitions to this repo

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#4051]
[OTEP 0232](https://github.com/open-telemetry/oteps/blob/main/text/0232-maturity-of-otel.md) brought new stability definitions.

We need to apply those to this repository.

I think the following mapping is reasonable, but would like other opinions too:

|Current Spec|OTEP 0232|
---|---
Experimental| Development
Stable|Stable|
Deprecated|Deprecated

Question: do we need to map "Feature Freeze" to some OTEP 0232 level, e.g. "Release Candidate"?

**Comment by trask** [comment]
if it helps, I suspect that the [existing usages of "Feature Freeze" in this repo](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-specification+Freeze+-path%3A%2F%28document-status.md%7CCHANGELOG.md%29%2F&type=code) could probably be removed

**Comment by austinlparker** [comment]
I agree with both the mapping and removing feature-freeze.
