### ISSUE TITLE
DataPoint Flags are not mentioned in the Metrics Data Model

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-specification#4053]
**What are you trying to achieve?**

I am working with the staleness marker added in open-telemetry/opentelemetry-proto/pull/316. It seems to be available on the proto, but not the data model.

**What did you expect to see?**

The staleness marker or datapoint flags more generally mentioned in the data model.

**Additional context.**

I guess what confuses me here is what the relationship between the proto and the data model is. Is the proto meant to be a superset of the data model? How should I interpret the semantics of fields present on the proto but not on the data model?

**Comment by dyladan** [comment]
In the GC triage session we thought this was an interesting question that warranted TC attention:

> I guess what confuses me here is what the relationship between the proto and the data model is.

**Comment by jmacd** [comment]
@pyohannes @zeitlinger As both of you have approached this topic from the perspective of how to report timeseries deletion, I'd like to involve you in thinking about how to update the data model to define how the flags fit the model.

**Comment by mx-psi** [comment]
Thanks for the ping, I had missed it, looks good to me!
