### ISSUE TITLE
If protocol suffix is alloed for  Grpc default value https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/

### ISSUE THREAD

**Issue by michaelkira** [open-telemetry/opentelemetry-specification#4077]
**What needs to be changed?** Describe the update that is required.
In  https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/, the default value for gRPC is with protocol suffix
But such endpoint is dont accepted by telegraf, more details can be found in this issue https://github.com/influxdata/telegraf/issues/15450

Please review protocol suffix is allowed(or disallowed) for the gRPC service

**What is the name + path of the page that needs changed?** The relative path
and page title where you found a problem.
If protocol suffix is alloed for  Grpc default value https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/

**Additional context**: anything else you can think about that would be helpful.

**Comment by MrAlias** [comment]
@michaelkira can you provide a example of your issue? It is not clear what you are doing, what is happening, and what you expect to happen.

The gRPC endpoint should be parsed and the protocol (`http` or `https`) should be stripped before it is used by any setup exporter. Are you not seeing this in an OTel component?

**Comment by cartermp** [comment]
@MrAlias It looks like it's Telegraf behavior: https://github.com/influxdata/telegraf/issues/15450#issuecomment-2147471525

**Comment by MrAlias** [comment]
It looks like this can be closed. A vendor has decided to support a different configuration protocol, there is nothing for OTel to do in this situation.

**Comment by svrnm** [comment]
Hey @michaelkira, I am closing this issue now based on @MrAlias comment, if you think this is not justified, please follow up
