### ISSUE TITLE
Require separation of API and SDK artifacts

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#4084]
**What are you trying to achieve?**

The spec [states today](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/library-guidelines.md#requirements):

> 1. The OpenTelemetry API must be well-defined and clearly decoupled from the implementation. This allows end users to consume API only without also consuming the implementation (see points 2 and 3 for why it is important).

> 2. Third party libraries and frameworks that add instrumentation to their code will have a dependency only on the API of OpenTelemetry client. The developers of third party libraries and frameworks do not care (and cannot know) what specific implementation of OpenTelemetry is used in the final application.

The spirit of the 2nd clause has always been to not require any additional dependencies when taking a dependency on the API library. However, some implementations (e.g. https://github.com/open-telemetry/opentelemetry-swift/issues/486) release both API and SDK as a single artifact that makes it impossible for the user to not pull all the SDK dependencies as well.

I would like to propose the clarification to the spec which makes zero-dependency requirement explicit, by adding this text to the 2nd point:

> To enable this clean separation the API and SDK libraries MUST be provided as independent artifacts.

**Open questions**

Are there other SDKs besides Swift that bundle API and SDK into a single artifact?

**Comment by lmolkova** [comment]
I support the spirit, but we can't have zero-dependency policy:

- Java [opentelemetry-api](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-api/1.39.0) depends on otel-context package (afaik with intent to possibly share otel-context across other observability libs such as micrometer). In a perfect world context could be part of JVM 42+.
- .NET  already exists in the perfect world where [OTel-api](https://www.nuget.org/packages/OpenTelemetry.Api#dependencies-body-tab) is an optional shim over .NET primitives that are still an external dependency to OTel

**Comment by trask** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md makes several mentions of the API and SDK being separate components from a packaging / versioning / support guarantee perspective

**Comment by yurishkuro** [comment]
@lmolkova 
 * I think it's fine to make exception for otel-context, which itself is part of the API
 * I was more interested if any API libs have 3rd party dependencies
 * The proposed wording does not actually say zero-dependencies, let me change the PR title

**Comment by MrAlias** [comment]
> Are there other SDKs besides Swift that bundle API and SDK into a single artifact?

For the negative case, Go does not bundle these into the same artifact.
