### ISSUE TITLE
Update Milestones

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#409]
The current [project milestones](https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md#milestones) contain many proposed deadlines for unreleased releases that have past. Given this is an important indicator of the projects status and one that many groups look to in order to understand the state of the project and possibly when to plan their own work, it seems important that we update these milestones.

**Comment by austinlparker** [comment]
If this gets traction, please let me know so that we can update the website milestones as well.

**Comment by MrAlias** [comment]
It might also be more useful setup the GitHub Projects feature and then back out dates from identified work for each milestone.
