### ISSUE TITLE
Document Java API: DistributedContext API needs to be described

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#41]
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. 
Most of APIs are ready to be documented in a form of cross-language specification. 

Tags API needs to be described

**Comment by SergeyKanzhelev** [comment]
@songy23 can you help describe tags API? Please let me know if you cannot make it

**Comment by songy23** [comment]
Sure I'll take care of it (btw it's `DistributedContext` api now :) )

**Comment by songy23** [comment]
Need one more PR for `DistributedContext` and `PropagationFilter`.
