### ISSUE TITLE
Define OpenTelemetry to Jaeger span Transformation

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [open-telemetry/opentelemetry-specification#414]
Jaeger is one of the recommended exporters that the SDKs should support [1], however there is not a specification about how the transformation from the OpenTelemetry to the Jaeger Spans should work. 

It is already causing some confusion as the implementation in different languages is different, https://github.com/open-telemetry/opentelemetry-python/pull/367#issuecomment-575306955 & https://github.com/open-telemetry/opentelemetry-python/issues/369.

There is an open PR handling this for Zipkin https://github.com/open-telemetry/opentelemetry-specification/pull/380, probably there should also be a similar document for Jaeger.

[1] https://github.com/tigrannajaryan/opentelemetry-specification/blob/master/specification/library-guidelines.md#requirements.

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, allowing changes related to this issue for GA if editorial changes only

**Comment by carlosalberto** [comment]
I'm going to close this one as we indeed added this but we removed it after some time (see #3964), i.e.

> Jaeger exporter support will be removed from OpenTelemetry in July 2023.
