### ISSUE TITLE
Incorrect statement about Views in OpenTelemetry Overview

### ISSUE THREAD

**Issue by alfiejfs** [open-telemetry/opentelemetry-specification#4149]
The overview page has a section on [views](https://opentelemetry.io/docs/specs/otel/overview/#views), where it is incorrectly stated that views can be applied through a `Meter`. I believe the wording is correct on the [metrics SDK page view section](https://opentelemetry.io/docs/specs/otel/metrics/sdk/#view) where only `MeterProvider` is mentioned.

**Comment by MrAlias** [comment]
It is correct they are applied at the meter level. The instrument selection criteria allows for a view to be applied to an entire meter (name/version).

They are configured at the meter provider level.

The specification, as it is currently written is correct. I imagine the confusion comes from the last point about the view being configured at the meter provider level though. Updating the specification to clarify that point seems reasonable.

**Comment by alfiejfs** [comment]
@MrAlias good spot! I agree - I think the wording is just slightly unclear. I will amend my PR.

**Comment by alfiejfs** [comment]
Upon re-reading, I don't think it is necessary to specify that they can be applied globally or to specific meters at all then. This seems to specific to include in the overview. I think I might be a fan of just specifying that they can be configured through the MeterProvider.
