### ISSUE TITLE
Filter Metrics based on the reported value

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [open-telemetry/opentelemetry-specification#4156]
**What are you trying to achieve?**

I want a way to filter "insignificant" metrics values. 

on PR #4025 I propose the VALUE observed in the metric also be available when filtering. This way I could also filter out values that I believe to be "insignificant". A example of an insignificant metric value is "0" (zero) for the metric "Http Connections".

This filter is optional and the default behavior should be maintained as "log everything including the zero-ed/null-ed metrics"

**Additional context.**

This is very important to me and (I believe) to anyone who pays for ingestion/storage of the logs because the "information convened" by the log message "you have 0 connections" can be interpreted by the absence of a message.

**Comment by arminru** [comment]
@Leonardo-Ferreira depending on the context, e.g. for a service that usually has a certain baseload and is not expected to ever go to zero, having an explicitly reported value of zero HTTP connections could also indicate a problem that resulted in a sudden drop of connections to that service.

Have you looked into the [filter processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor) in the OTel collector? This one should provide a solution for your use case. The [OTTL data point context](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottldatapoint/README.md) provides access to the data point value, allowing for filter expressions based on it to be made.

**Comment by Leonardo-Ferreira** [comment]
I agree, and in that case, the application owner will simply NOT filter based on such values.

I never saw that filter processor before... so basically I could do 
```
processors:
  filter:
    error_mode: ignore
    metrics:
      datapoint:
        - metric.name == "*" and value_int == 0
```
to filter out the zero value from any metric?

**Comment by arminru** [comment]
@Leonardo-Ferreira Exactly!

You might need to add a second clause for `value_double` too if you have floating point instruments as well.

**Comment by mtwo** [comment]
@Leonardo-Ferreira does @arminru's comment solve your issue? If so, can we close this?
