### ISSUE TITLE
Emit Event and event.name attribute ambiguity

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-specification#4233]
Another problem, I see in defining `Emit an Event` method (in scope of this PR) is that there would be an ambiguity what should happen if a user adds an additional `event.name` attribute. Should the `name` parameter or `event.name` attribute have precedence?

PS. The same problem currently exists  in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#emit-event

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-specification/pull/4225#discussion_r1781631410_

**Comment by jack-berg** [comment]
> PS. The same problem currently exists in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#emit-event

https://github.com/open-telemetry/opentelemetry-specification/blame/fbaf8468c599d858df515c88bac58d02c9afdb29/specification/logs/event-sdk.md#L86-L89

> The `Name` MUST be used to set the `event.name` [Attribute](./data-model.md#field-attributes). If the `Attributes` provided by the user contain an `event.name` attribute the value provided in the `Name` takes precedence.
