### ISSUE TITLE
Vague spec: Span attributes may be "numeric"

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#425]
See https://github.com/open-telemetry/opentelemetry-specification/blame/2316771e7e0ca3bfe9b2286d13e3a41ded6b8858/specification/api-tracing.md#L366:

>  (Required) The attribute value, which is either:
> - A primitive type: string, boolean or numeric.
> ...

"Numeric" is very vague. Do we allow integers? How big? Floats? Which precision? Rationals? Decimals? Imaginary numbers? (Python even has [literals](https://docs.python.org/3/reference/lexical_analysis.html#imaginary-literals) for them).

I think it would be best to recommend what (not) to support. For example, the current opentelemetry-proto supports signed int64 and IEEE double.

**Comment by carlosalberto** [comment]
The integer/float case is relatively simple, as it has been implicitly taken for granted, and we should cook a PR making this part clear.

Not sure on the size/precision side though. Should we define that based on the OTel protos? Guess not quite?

**Comment by Oberon00** [comment]
We could take a C++-like approach and guarantee only a minimum set that protocols should support, like "signed  and at least 32 bit int" , "IEEE float or double".

**Comment by carlosalberto** [comment]
> guarantee only a minimum set that protocols should support

This should be good enough, I feel.

**Comment by jmacd** [comment]
The state of the spec is here: https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/common/v1/common.proto

It uses IEEE double and int64. I would be happy if complex numbers and larger numbers were encoded as strings.
