### ISSUE TITLE
Meeting time - can we move it to 9?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#429]
I'm drifting away from specs work as I cannot make 8AM meeting and missing on all the discussions. Looking for feedback on the proposal to shift the meeting to 9AM.

Can we please do thumbs up and down on the 9AM? Leave comment with alternative proposal or feedback on the meeting time.

**Comment by dyladan** [comment]
I think our European friends will not like this. They're already joining this call  after work hours (5-6pm) and moving it an hour later is likely to be very inconvenient for them. Also, a more minor issue, but the new proposed time is the sacred lunch hour for US East timezone.

**Comment by carlosalberto** [comment]
Closing this issue as it looks people prefer 8AM. @SergeyKanzhelev please re-open it in case you still want to change it ;)
