### ISSUE TITLE
Proposal: Dynamic configuration of metrics

### ISSUE THREAD

**Issue by tttoad** [open-telemetry/opentelemetry-specification#4303]
This OTEP is to add support for parsing request information to generate metrics.
Some business-related metrics need to be generated by parsing the request information (e.g., request body, header, response body).

For example.
Counting the number of active users per minute.
The configuration could be as follows.
```
{
	"service": "user-center",
	"config": [{
		"name": "request",
		"key": "user",
		"interval": "60s",
		"type": "counter"
	}]
}
```
Provide a method for end users to pass in request information.
Parse the request information, record the number of times the user field appears and report it once per minute.

I want this configuration to be stored on the remote server, and the client can listen to changes in the configuration to turn on or off the reporting of metrics.
The end user can enable data collection for a metric at any time for the information in the request.
This could be the number of successful or failed requests, the number of requests with a delay greater than 3ms, or the number of requests with the key  equal to `user`.
If the open-telemetry group is interested, I can provide a preliminary design and implementation.

**Comment by trask** [comment]
(transferred to specification repository as part of #4284)

**Comment by jack-berg** [comment]
> I'm not sure if there is currently a feature to automatically parse the request and response parameters to generate metrics.

This seems to be in the purview of instrumentation, not the SDK. The metrics SDK isn't concerned with or aware of HTTP requests and responses, or other domain specific concepts. Its more abstract and lower level.

> Yes, I would like to define the specification for remote dynamic configuration distribution.

Remote configuration is within the scope of the SDK, and is being (loosely) discussed in the OpAmp and Config SIGs (see listing of SIGs [here](https://github.com/open-telemetry/community/?tab=readme-ov-file#special-interest-groups)). But it doesn't really matter that the SDK is remotely configurable if it doesn't contain the feature you're trying to remotely configure.

Given the age of this issue, I'm going to close. Please feel free to re-open and clarify how the request would impact the specification.
