### ISSUE TITLE
Propagators API - Evolution of Jaeger

### ISSUE THREAD

**Issue by rgisiger** [open-telemetry/opentelemetry-specification#4312]
In the [Propagators Distribution section](https://opentelemetry.io/docs/specs/otel/context/api-propagators/#propagators-distribution), it seems that the latest version of Jaeger (version 2) has removed the Jaeger propagator which was using the `uber-trace-id` header, probably in favor of the 2 W3C propagators (TraceContext and Baggage) distributed as part of the OpenTelemetry API.

Thus the Jaeger link is leading to a 404 page.

**Comment by mx-psi** [comment]
Link is here: https://github.com/open-telemetry/opentelemetry-specification/blob/50027a1036746dce293ee0a8592639f131fc1fb8/specification/context/api-propagators.md?plain=1#L363

**Comment by mx-psi** [comment]
This was fixed by #4314. Thanks for reporting!
