### ISSUE TITLE
Removal of multi valued Attributes

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#435]
This is related to https://github.com/open-telemetry/opentelemetry-specification/issues/341

Recently in the Java SIG there have been a few comments regarding whether we need this feature. A comment from the (closed) related issue:

"simple joining on comma is cheaper to index split and join and more supportable vs json arrays. I know folks are already doing this and it requires no more coordination on backend than making a json array."

and

"A concrete non-request tagging use case for array values are things like experiment IDs. Usually these are bounded to much lower cardinality, yet need to be indexed for lookup."

Wondering how much we want to look into revisiting this feature.

**Comment by Oberon00** [comment]
Joining with comma is not always easy, e.g. when the values already contain comma. JSON encoding is possible and can be used as exporter-side implementation for array-valued attributes.

**Comment by thisthat** [comment]
A further point that is worth discussing IMHO is whether we allow/drop `null` or empty strings inside the multi value list/array.

**Comment by Oberon00** [comment]
@thisthat For that discussion, see also #431.

**Comment by jmacd** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/341

**Comment by MrAlias** [comment]
It seems like [the comment referenced](https://github.com/open-telemetry/opentelemetry-specification/issues/341#issuecomment-580165458) in the issue description shows a need to support multi-valued attributes by providing another use-case, not remove that support.

[The other comment](https://github.com/open-telemetry/opentelemetry-specification/issues/341#issuecomment-580165458) referenced offers an alternative encoding of the multi-values in an attribute. I think this alternate encoding discussion appears to be in contrast to the serialized JSON format described [in the related issue](#341) which is at the exporter level.

It seems correct to treat the encoding of the multiple values at the exporter level and leave them in a language-native structure in the API and SDK. This would mean that the API and default SDK would still need to support multi-value attributes.

If, however, the comment on the alternate encoding was intended to change the way the API handles multi-valued attributes that seems to me it would be a different discussion than removing them entirely.

I'm not seeing how these recent comments support or motivate this issue to remove multi-valued attributes. If there are new/old topics that need to be addressed that would motivate this removal can we add them here? If not, can we close this issue?

**Comment by Oberon00** [comment]
I think, we can close this issue with the decision "We're not removing them but will resolve related problems in #459".

**Comment by carlosalberto** [comment]
Closing via #459
