### ISSUE TITLE
Update Getter used for Extraction

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#443]
From [this comment](https://github.com/open-telemetry/opentelemetry-specification/pull/424#discussion_r375458277) in #424:

Jaeger context cannot be parsed using only the  `Getter` interface. Here's an example of Jaeger context:

```
uber-trace-id: <some string, similar to W3C trace context>
uberctx-tenancy: test
uberctx-user: Yuri
```

The trace context has a fixed key name `uber-trace-id`, but baggage is encoded using variable header names `uberctx-{baggage-key}`.

Also, the W3C `tracestate` header may be split into multiple entries (repeated headers).

In the OpenTracing there was an iterator over all headers in order to handle this case, not just a Getter. Consider switching to an iterator-based approach.

**Comment by Oberon00** [comment]
For the repeated-headers, aspect, see #433 (also discussed in the last SIG Spec call)

**Comment by carlosalberto** [comment]
Closing this one on behalf of #433
