### ISSUE TITLE
Inconsistency in approval requirements

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#448]
The OTEPs repo requires 4 approvers. But Specification repo requires only 2. How do we rationalize this? Is it because spec changes are meant to simply reflect an already approved OTEP?  While that may be the case, many of the open Spec PRs are going through extensive editing, not just copying the text from OTEP.

**Comment by dyladan** [comment]
>Is it because spec changes are meant to simply reflect an already approved OTEP

That was the way I always thought of it. I think the idea is not that the OTEP contains the final language, but that getting everyone to agree that an idea is good and well thought out is the more difficult and important part of the process.

**Comment by carlosalberto** [comment]
Hey hey -

So my impression is that OTEPs are expected to be breaking changes, and thus require more approvals, whereas changes to the Specification are supposed to be relatively minor changes.

**Probably** we could change things so OTEP-related changes require more approvals. 

That being said, I'm a little afraid that's gonna cause big stale - I think we are not getting enough eyes/approvals at this moment, and before increasing the required number of votes, I'd like to make sure we get more actual reviews.

**Comment by bogdandrutu** [comment]
@yurishkuro my idea when I setup this was that major issues will be discussed in oteps (hence the need to have 4 approvers) then will simply be "copied" to the specification.

I am happy to increase the number of approvers in the specs to 4 if needed, but I do think that for oteps having 4 is the right decision (also for small fixes as admins we can use the super-power and merge things in oteps with less than 4 - e.g. typos, small clarifications, etc.).

**Comment by bogdandrutu** [comment]
I think we discussed this and stick with 2 approvers for specs because major changes will be previously reviewed in oteps by 4 people then only 2 approvers are enough for specs.
