### ISSUE TITLE
Update api-metrics-user.md and api-metrics-meter.md

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#456]
These two documents will be out of date with the 0.3 spec after the changes to introduce Observer and remove Gauge have merged. This issue is to either update those documents quickly or explicitly mark them out of date.

**Comment by MrAlias** [comment]
#457 added "Out of Date" notices to both files.

I've started work to refactor `api-metrics-user.md` to introduce the Observer and remove Gauge.

**Comment by andrewhsu** [comment]
from the sig mtg, sounds like this may be suitable for bump to v0.5 milestone

**Comment by jmacd** [comment]
This is done.
