### ISSUE TITLE
Terminology: describe DistributedContext terminology

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#46]
Describe from high-level tags concepts

**Comment by SergeyKanzhelev** [comment]
@songy23 can you help describe tags terminology? Note, it has a new name now - https://github.com/open-telemetry/opentelemetry-specification/issues/9

**Comment by SergeyKanzhelev** [comment]
let me know if you cannot take this one

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev @songy23  what is the intent regarding having "tags" vs "attributes"? I see that tracing API spec uses "attributes". Is there going to be a unification of terminology? Is there a reason to have different word for a very similar concept? 

It can be a source of confusion, see e.g. https://github.com/census-instrumentation/opencensus-service/issues/532

**Comment by SergeyKanzhelev** [comment]
Tags were renamed to DistributedContext entries
