### ISSUE TITLE
Metrics: Consider removing the `WithRecommendedKeys` option

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#463]
This option was given as a requirement to support configuration-free good defaults for exporting to Prometheus systems, specifically. However, it's been shown that Prometheus' protocol does not actually depend on this, only its client libraries do. Since we have bypassed Prometheus's client libraries for our OTel SDKs, this is no longer necessary.

At the same time, this issue bleeds into other open discussions, for example relating to whether users should be able to specify custom aggregations for an instrument, whether at the point of definition (i.e., while constructing an instrument) or at a separate point (e.g., while configuring a view).

The group is leaning toward support for a Views API and removing the ability for users to specify aggregations and/or aggregation dimensions at the point of definition.

See this comment: https://github.com/open-telemetry/opentelemetry-specification/pull/430#discussion_r378644458

**Comment by jmacd** [comment]
Discussed this in the SIG today. There is a motion to remove this from the API and include it in the Views API.

**Comment by jmacd** [comment]
See this comment: https://github.com/open-telemetry/opentelemetry-specification/issues/466#issuecomment-586833298

**Comment by c24t** [comment]
@jmacd if we expect to specify custom aggregations in the view can we go ahead and remove `WithRecommendedKeys` now? Or do you want to wait until views are finalized?

**Comment by jmacd** [comment]
I believe Bogdan volunteered to take care of this. If we think it's not a big deal to modify the spec directly, feel free to go ahead. :-)
