### ISSUE TITLE
Metrics: Monotonic option to express cumulatives

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#465]
In the 0.3 spec release, we removed options to say an instrument accepts only non-negative values and to say that an instrument accepts only ascending values. Both of these options are about monotonicity: in Counters, a non-negative input defines a monotonic sum. In Observers, there is a desire to report cumulative statistics (e.g., CPU usage). In both cases, the user should have a way to declare this option so that exporters know how to export these events.

We have discussed introducing new metric instruments instead of options for this, e.g., let `Counter` be restricted to non-negatives, and introduce `UpDownCounter` for counters that rise and fall.

Resolve in the 0.4 release. See the comment: https://github.com/open-telemetry/opentelemetry-specification/pull/430#discussion_r378649201

**Comment by bogdandrutu** [comment]
I missed this decision, but this is critical for systems like Prometheus.

**Comment by jmacd** [comment]
Our current thinking is:
(1) Counter should accept only non-negative values, thus always defines a monotonic sum (and Prometheus will know it)
(2) We can introduce an "UpDownCounter" if users complain about wanting it.
(3) We let "Observer" be unrestricted, not monotonic.
(4) We add "MonotonicObserver" to get the behavior that Prometheus wants.

This is consistent with a general approach of "no instrument options, only optional instruments".

**Comment by jmacd** [comment]
This will close when OTEP 98 is approved and merged into the specification.
Please review: https://github.com/open-telemetry/oteps/pull/98
