### ISSUE TITLE
Clarifying definition of the concepts of "started" vs "active" needed

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-specification#469]
As mentioned by @Oberon00 (https://github.com/open-telemetry/opentelemetry-specification/pull/287#issuecomment-539419469) in the PR that added language to the spec to say that creating a span does not set it to "active", we need a definition of "started" and "active".

I'd send a PR instead of opening an issue but I don't know what the definitions are myself :)

**Comment by SergeyKanzhelev** [comment]
Started is when timer begun. Active when Span set as a current on the "thread".

**Comment by carlosalberto** [comment]
We extensively use `active` in api-tracing.md but I'm wondering if we should change it to `current` instead ;)

**Comment by tsloughter** [comment]
@SergeyKanzhelev got it, mostly :). Being active in the current thread I would think is still what the user expects when starting a span. This sounds more like a low level implementation detail specific only to certain runtime (not even sure which) than part of the API.

Wouldn't the API for implicit context propagation look like:

```
Span = start_span("span name")
set_attribute(Span, "key", "value")

# child of Span
ChildSpan = start_span("child span")
```

Underneath there may be something going on with threads and their scheduling and which context is active on that thread, but to a user I'm not clear on why this matters and needs to be called out in the API (assuming I understand what you mean :)

**Comment by SergeyKanzhelev** [comment]
it  is exactly the point of [this statement](https://github.com/open-telemetry/opentelemetry-specification/blob/e698d8d78007c44975bab849f4a04b3b6165a3f9/specification/api-tracing.md#tracer-operations):

> The Tracer SHOULD provide a way to update its active Span and MAY provide convenience functions to manage a Span's lifetime and the scope in which a Span is active. When an active Span is made inactive, the previously-active Span SHOULD be made active. A Span maybe finished (i.e. have a non-null end time) but stil active. A Span may be active on one thread after it has been made inactive on another.

Couple examples wehn you need to start but not active the span:
- In case when you starting multiple async operations - you don't want to set any one of them as active on the current thread. So you pass the started span as an argument to the async callback to set as active there.
- When you want to save on tls operations and/or have custom thread pool managing logic.

**Comment by tsloughter** [comment]
> So you pass the started span as an argument to the async callback to set as active there.

Ah, interesting, I'd been starting the span in the callback (passing the parent, or to be used as a linked to span instead of a parent, like an extracted span context) instead of passing it as an inactive (but started) span. I see why that would be advantageous.

Now I see the use, tho still think it could use some more clarification in the spec and I think better to say in the Tracer spec section that an operation like `start_span` sets the new child to active while `create_span` will create the child span without setting it to the currently active span.

Passing the new span to the callback also has me thinking a `create_linked_span` makes sense, for creating the new span but not as a child of the currently active span, instead as one that links to the currently active span. 

The api has moved away from defining function names which may be what also makes it harder to discern what to API functions to provide and how they should work.

**Comment by SergeyKanzhelev** [comment]
simple clarification for now and explaining the scenario in spec will definitely make spec better. Would you mind doing it?

**Comment by Oberon00** [comment]
I feel like we had a very similar discussion and arguments already at https://github.com/open-telemetry/opentelemetry-specification/issues/238#issuecomment-538916179

**Comment by tsloughter** [comment]
@SergeyKanzhelev yea, I can try.

@Oberon00 yea, the issue is I don't think the spec was updated after the PR for 238 (#287) which was supposed to clarify the two concepts.

**Comment by toumorokoshi** [comment]
@tsloughter are you still interested in taking this on? Otherwise I can take a stab. 

trying to help GA by tackling p2 issues.

**Comment by tsloughter** [comment]
@toumorokoshi oh, I closed my attempt because it seems the spec already includes language for this https://github.com/open-telemetry/opentelemetry-specification/pull/485#issuecomment-660388796 and forgot to close this issue.

I'll not close this if people think there is more that should be done, but will close it today if not.

**Comment by tigrannajaryan** [comment]
Should this be closed?

**Comment by tsloughter** [comment]
I think so.
