### ISSUE TITLE
Rename Setter.put to Setter.set

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-specification#477]
This will better align naming with `Getter.get`

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md#put

**Comment by bogdandrutu** [comment]
`put` is a Java thing and has the same meaning as the `put` in the map

**Comment by tylerbenson** [comment]
Yes, but we are calling it a `Setter`, and the operand is not necessarily a map.
