### ISSUE TITLE
Injector and Extractor being different interfaces

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#479]
Currently a `Propagator` is expected to contain `inject` and `extract` operations, but OTEP 66 originally exposed different interfaces for them (namely `Injector` and `Extractor`), and some languages might be better offering as different interfaces as well.

Probably we can split them in the Specification, while mentioning that implementors _can_ keep them in a unified interface (like most languages do at this moment) if that suits them.

**Comment by mwear** [comment]
@carlosalberto I can take this, as I think Ruby was one of the hold outs. We've introduced the propagator and composite propagator interfaces, but we build them from individual injectors and extractors. With some minor spec changes we can account for this variation.

**Comment by carlosalberto** [comment]
@mwear Thanks a lot, appreciated!

**Comment by carlosalberto** [comment]
Closing this via #578
