### ISSUE TITLE
StartSpan/activeness unclear after OTEP 66 (Context propagation)

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#488]
Related #485 (see esp. https://github.com/open-telemetry/opentelemetry-specification/pull/485#issuecomment-590358495).

[OTEP 66 states](https://github.com/open-telemetry/oteps/blob/49316bc20167a0a6e2214bbf5806e0e7d763b2d0/text/0066-separate-context-propagation.md#observability-api):

> `StartSpan(context, options) -> context` When a span is started, a new context is returned, with the new span set as the current span.

Whereas the current spec says:

> Span creation MUST NOT set the newly created Span as the currently active Span by default

This seems to be a contradiction to me. The OTEP66 obviously wants the started span to be active on the returned context. Probably we just don't want the returned context active on the new execution context?

OTEP66 is also silent on how EndSpan should behave now. In https://github.com/open-telemetry/oteps/blob/49316bc20167a0a6e2214bbf5806e0e7d763b2d0/text/0066-separate-context-propagation.md#extracting-and-injecting-from-http-headers we have a call `Tracer::EndSpan(context)`. Is this supposed to return a new context? With no span active? The previously (parent or really previous?) active span?

**Comment by jmacd** [comment]
I think of these two operations--starting a span (i.e., creating a new `Span` interface) and activating it as the current span--as logically independent operations. The API for these two SHOULD be different, in my opinion. One API starts and activates, one API just starts.

(In the Go SDK, they're the same API because "active" is just a context variable.)

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, closing this issue because will be addressed with upcoming new design proposals
