### ISSUE TITLE
Associating Spans with a Resource

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-specification#491]
There was a discussion at the spec call about confusion over resources. The topic came up when discussing Library Resources.

The specification has the following to say about resources and spans:

> When used with distributed tracing, a resource can be associated with the TracerProvider. When associated with a TracerProvider, all Spans produced by any Tracer from the provider will automatically be associated with this Resource.

Some SIGs have interpreted this to mean that a TracerProvider should create a resource that is associated with a given tracer and the spans it generates. The implication is that this would happen behind the scenes since resources are part of the SDK and not the API. The Resource that the Ruby SIG is creating is a [Library Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-resource-semantic-conventions.md#library) where the `library.name` and `library.version` attributes are the name and version of the instrumentation used for a named tracer.

There seems to be conflicting information about whether or not this is correct.

There is a PR to add library information to the proto:
https://github.com/open-telemetry/opentelemetry-proto/pull/94

However there is already a resource in the protos:
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L27-L35

What should this resource be if not the library resource associated with the named tracer that is generating the spans?

EDIT: I think this resource is meant to be the process level resource.

**Comment by Oberon00** [comment]
> Some SIGs have interpreted this to mean that a TracerProvider should create a resource that is associated with a given tracer and the spans it generates. 

In my opinion the spec is clear here that there should be one single resource per TracerProvider that should be shared by all tracers.

About the library resources, see #484.

**Comment by mwear** [comment]
@Oberon00 thanks, that along with #484 helps clarify the role of the library resource, at least in terms of how it's currently spec'd.

Given that, and the structure of the protos, I think the resource for ResourceSpans is meant to be the process level resource.

My questions are answered, I'll go ahead and close this.
