### ISSUE TITLE
[meta] Do not "Require branches to be up to date before merging" in the repository settings

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#512]
I think this setting has little benefit since the spec build is unlikely to be broken because of logically but not textually conflicting PRs. On the other hand I can see a few drawbacks:
* it is not possible to allow maintainers to update PRs that originate from an organization repository (as opposed to personal repository)
* every time someone presses update, the diff does not change but the PR uselessly pops up in everyone's notifications.

**Comment by jmacd** [comment]
This sounds sensible.

**Comment by andrewhsu** [comment]
This also sounds like a reasonable thing to me for this specification repo.

**Comment by arminru** [comment]
Please note that the "[Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" option is not available for forks that live in organizations, it's only available for private repositories, so that won't solve the problem of merging being hindered in these cases.

**Comment by carlosalberto** [comment]
TC decided to try this one. Lets see how it goes and adjust if/as needed ;)

**Comment by Oberon00** [comment]
Why was this re-enabled?

**Comment by bogdandrutu** [comment]
Because we fixed the lint check (broken for 2 months) and started to merge PRs that did not pass the lint check (based on master commit that did not include the fix). This was the only option to enforce it everyone to pass the lint check.

**Comment by bogdandrutu** [comment]
See #847 and #845

**Comment by bogdandrutu** [comment]
Closing this issue because we explained the reasoning, and we have clear contributions guidelines that do not have this problem
