### ISSUE TITLE
Rename span.end() to span.finish()

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#514]
This is likely controversial and late in the game. In the spec/PRs everyone tends to write "when span is finished", because "when span is ended" sounds odd. Can we consider renaming this method?

I already got +1 from @carlosalberto :-) (https://github.com/open-telemetry/opentelemetry-specification/pull/485#discussion_r391171105)

**Comment by fbogsany** [comment]
Ruby already calls it `finish`, so 👍 from the Ruby SIG: https://github.com/open-telemetry/opentelemetry-ruby/blob/7f583df9b48a78a08c2dfb742f73287f59721f3b/api/lib/opentelemetry/trace/span.rb#L138

**Comment by dyladan** [comment]
This seems late for something so trivial with such a large impact. Why is ruby's implementation different from all others?

**Comment by mwear** [comment]
`end` is a keyword in a Ruby. We could technically use it as method name, but `finish` is a better solution.

**Comment by yurishkuro** [comment]
@dyladan it is indeed late, but I think given the existing scope of APIs/SDKs, none of which are yet officially in beta, I don't think this is insurmountable. The change itself is likely going to be trivial to apply.

**Comment by MikeGoldsmith** [comment]
I also prefer `Finish` over `End`. It feels like a more natural noun to use to me.

**Comment by Oberon00** [comment]
So if we rename this, what about #318? We can take this opportunity to also rename Span to TelemetrySpan or TracedOperation, etc.

**Comment by yurishkuro** [comment]
Renaming end to finish has a clear value proposition. #318 is much more murky and very much language-dependent. I would not conflate these two tickets.

**Comment by Oberon00** [comment]
> Renaming end to finish has a clear value proposition

More clear than #318?

> #318 is much more murky and very much language-dependent

How so?
An argument for *this* issue was even the language-dependent issue that ruby cannot use `end`. So personally I think the value proposition of #318 is more clear. 😃 

Personally, I'm weakly against both the renamings suggested here and in #318.

**Comment by jmacd** [comment]
I'm in favor of the renaming proposed by Yuri, but I don't think there is a 100% clear winner in this debate. The terms "stop", "end", "finish", and "done" are all common in English and, and any of these would impart the correct meaning to someone fluent. All can be used as verbs or participles. Three can be used as nouns. For the verbs, they also have both transitive and intransitive uses.

**Comment by jmacd** [comment]
I am in favor of this renaming, but "finish" is not a 100% clear winner to me. All of the terms "stop", "done", "end", and "finish" are viable in this context, and there are so many uses of these words in English that I'm not sure which is most common, but then I had a memory.

My high school German teacher had a saying, whenever a student said "I'm done." she would repeat "The roast is done, you're finished." I believe she would support this proposal.

I have noticed, like @yurishkuro, that in our technical discussion that we also use "finish" in the verb sense most often. [I used this kind of argument to rename "Cumulative" to "Counter" in the Metrics API.](https://github.com/open-telemetry/oteps/blob/master/text/0010-cumulative-to-counter.md#motivation)

Grammar nerds and non-english speakers are likely to be familiar with the distinction between transitive and intransitive verbs. Both "end" and "finish" are used as verbs, and in colloquial usager both can be used transitively or intransitively.  (e.g., "I will end this debate", "I will finish this specification" are transitives, or "The beta period ended", "I finished"). Of the _intransitive_ uses (where there is no object), "finish" is the more common usage (as my teacher would say).

In a programming context, when we write
```
span.Finish()
```
or 
```
span.End()
```
I think of these as intransitive uses. The `span` is the subject and the verb has no object. The span is finishing itself, not the span is finishing _something_.

I recognize that we have a situation where OpenCensus chose `End` and OpenTracing chose `Finish`, so we may not be able to resolve this.

**Comment by Oberon00** [comment]
These are all good arguments for why we finish is a better name than end. But I think both are sufficiently clear for everyone. I haven't heard a single complaint about the name `end` before. Yet, renaming this is a huge breaking change for everyone using the tracing API. If we want to give OpenTelemetry the reputation of a stable software project, then I would stay away from this change.

**Comment by Oberon00** [comment]
Another, weaker, argument I can make is that one could confuse a "finished" Span with one that finished going through the whole pipeline Span API -> Span processor -> exporter (which can happen asynchronously at some point after `end` is called.

**Comment by jmacd** [comment]
The fact that `end` is a reserved keyword in some languages is a point in favor of the renaming.

**Comment by pauldraper** [comment]
The pairs are usually start/finish (e.g. a race) and begin/end (e.g. SQL transaction).

**Comment by yurishkuro** [comment]
I added this to the next Spec SIG meeting's agenda

**Comment by Oberon00** [comment]
I think the important question is not whether start or finish is better, but whether the advantages of renaming this outweigh the cost of this breaking change.

I think the disadvantages are bigger here. Even when you don't factor in the cost of doing the renaming in all the repos in the open-telemetry org (including READMEs that are never compiled, etc), somebody out there might actually be (gasp!) *using* this software, and my guess is that they would be quite annoyed when they have to follow this renaming.

**Comment by yurishkuro** [comment]
True, but it can be done in backwards compatible way by marking `end()` as deprecated and not to survive v1.0

**Comment by dyladan** [comment]
I'm with @Oberon00 here. Any change _can_ be done, but the value of this particular change is so marginal that I don't agree it is worth the burden on users.

**Comment by Oberon00** [comment]
@yurishkuro That's not exactly what I would call backwards-compatible. It just moves the breaking change into the future *and* adds additional maintenance overhead for opentelemetry in the meantime.

**Comment by carlosalberto** [comment]
IIRC it was decided it's too late to change this.
