### ISSUE TITLE
Package structure common description

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#52]
There should be some common description of the package structure. See https://github.com/open-telemetry/opentelemetry-node/issues/6 for example of package structure discussion

**Comment by SergeyKanzhelev** [comment]
@mayurkale22 would you be willing to make a stub in documentation on the package structure?

**Comment by mayurkale22** [comment]
Sure, do you expect to see the package structure for the API (for now) with sub-packages and small description of each?

Something like, 
```
opentelemetry/api
   |__ trace/
      |__ propagation/
      |__ samplers/
   |__ metrics/
      |__ stats/
   |__ tags/
      |__ propagation/
   |__ resources/
   |__ utils
```

**Comment by SergeyKanzhelev** [comment]
yes. Something like this.
