### ISSUE TITLE
Document IsRemote flag should not be propagated to children.

### ISSUE THREAD

**Issue by toumorokoshi** [open-telemetry/opentelemetry-specification#523]
The current spec calls out that a span propagated from a remote must set the "IsRemote" flag:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#spancontext

But I don't see anywhere the explicitly specifies this flag should not be populated to child spans. I think not clarifying this creates ambiguity that might be misinterpreted by different implementations:

https://github.com/open-telemetry/opentelemetry-python/pull/516#discussion_r395669540

**Comment by Oberon00** [comment]
See also the closely related #366.
