### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by pauldraper** [open-telemetry/opentelemetry-specification#524]
> In software, observability typically refers to telemetry produced by services and is divided into three major verticals:

> Tracing

> Metrics

> Logging

> OpenTelemetry will not initially support logging, though we aim to incorporate this over time.

I cannot find an OpenTelemetry discussion on logging, so this is it.

Logging seems unavoidably part of the OT scope.

opentelemetry-js has its own [mini logging framework](https://github.com/open-telemetry/opentelemetry-js/blob/d6b2e62a76cedf605f6f132b94eec391bea3c117/packages/opentelemetry-api/src/common/Logger.ts) as part of `@opentracing/api`.

That is...we can't even have the API interface for OpenTelemetry without inventing some little logging framework.

In order from least to most data:

* Metrics are (aggregated) events.
* Logs are events with details.
* Traces are hierarchically related events with details.

Whether you view them as individual metrics with metadata, or 1-span instantaneous traces, logs fit in very naturally to the space OpenTelemetry straddles.

I'd love to see OpenTelemetry help with this third vertical sooner rather than later.

**Comment by arminru** [comment]
Good timing! OpenTelemetry is just forming a SIG for Logs which will take care of that:
https://github.com/open-telemetry/community#log-sig
https://github.com/open-telemetry/community/issues/307
We welcome any involvement, especially if it comes from potential users who'd like to provide input! 🙂

**Comment by tigrannajaryan** [comment]
Logs initiative is now in progress. Closing this.
