### ISSUE TITLE
Redundancy between glossary and "vocabulary" in overview

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#528]
Currently we have both
* https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md and
* https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md

both of which contain definitions of various terms. Sometimes there is even overlap within the terms e.g. the overviews "Instrumentation adapter" vs the glossary's "Instrumentation library" (this is discussed in #476).

In any case, I think we need to put links from the actual spec to the glossary/overview in important places, otherwise I fear these documents become write-only.

**Comment by bogdandrutu** [comment]
@Oberon00 do you want to get this issue?

**Comment by Oberon00** [comment]
I think we should resolve #476 first before tackling this.

**Comment by carlosalberto** [comment]
Hey @Oberon00 this seems to be fixed in a previous PR. Could you confirm?

**Comment by Oberon00** [comment]
I created #804 to resolve this.
