### ISSUE TITLE
Proposal: Split specification directory into multiple subdirectories

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#529]
The proposal is to avoid having one large directory with specifications for all "context", "trace", "metrics" soon to come "logs" etc.

I would like to move every file in a sub-directory, initial structure:
* context/
* trace/
* metrics/
* resource/
* All common "files" can live in the top directory.

This way we can also configure CODEOWNERS per subdirectory, and have a better structure overall.

**Comment by bogdandrutu** [comment]
@open-telemetry/specs-approvers any thoughts?

**Comment by yurishkuro** [comment]
sgtm

**Comment by SergeyKanzhelev** [comment]
I like it

**Comment by arminru** [comment]
Same! For a change like this it would be wise to add a dead link checker first (#493).

**Comment by tigrannajaryan** [comment]
Makes sense to me.

> I would like to move every file in a sub-directory, initial structure:
>     * context/
>     * trace/
>     * metrics/
>     * resource/

Are these going to be at the top-level or under `specification/` directory?

I went with `specification/logs/` subdirectory in https://github.com/open-telemetry/opentelemetry-specification/pull/540 but can move to `logs/` if that's what we want.

**Comment by carlosalberto** [comment]
Lets go with it.

**Comment by bogdandrutu** [comment]
Fixing #493 first as @arminru suggested, then will start moving files with more confidence :)

**Comment by carlosalberto** [comment]
Closing this one as @bogdandrutu already completed it. Re-open if this issue is still needed.
