### ISSUE TITLE
Resource initialization from environment variable

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-specification#535]
In the JS SIG we are adding the ability to create a `Resource` with labels specified by environment variable. This was a feature in OpenCensus, but it is currently unspecified for OpenTelemetry. 

While porting this functionality over, we have kept the same value format, but changed the environment variable name from `OC_RESOURCE_LABELS` to `OTEL_RESOURCE_LABELS`. 

I'm opening this issue as a point of discussion so that we can standardize this behavior between projects.

**Comment by jkwatson** [comment]
In the Java repo, we converted it to `OTEL_RESOURCE_ATTRIBUTES`, so yes, some consistency would be great. :)

**Comment by dyladan** [comment]
Consistency not just in the name but in behavior would be nice.

**Comment by Oberon00** [comment]
Related: #505.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, talked about this and assigned to @james-bebbington . will this be part of the oteps-111 work?

**Comment by james-bebbington** [comment]
> from the spec sig mtg today, talked about this and assigned to @james-bebbington . will this be part of the oteps-111 work?

Yes it should be. I will write up a spec for this shortly

**Comment by tedsuo** [comment]
This issue appears to be addressed. @james-bebbington @mwear can we close it?

**Comment by mwear** [comment]
This was addressed in #811. We've standardized on `OTEL_RESOURCE_ATTRIBUTES`. I'll close this.
