### ISSUE TITLE
Rename CorrelationContext to Baggage (again)

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#536]
The W3C WG is leaning towards changing the `Correlation-Context` header name to `baggage` (https://github.com/w3c/correlation-context/issues/17).

What does this mean for OTel?

**Comment by dyladan** [comment]
This should be closed by #517 no?

**Comment by yurishkuro** [comment]
I think this is a longer-term question than #517. It is both about the header name and the API concept name. W3C WG members raised concerns with the naming "correlation" as confusing  & conflicting with other usages of the word. On the other hand, W3C "baggage" is very much a mechanism for user-supplied data, while OTEP 66 did an about face at the last moment from general purpose k/v bag to a more vague "observability-related correlation labels":

> While Correlations can be used to prototype other cross-cutting concerns, this 
> mechanism is primarily intended to convey values for the OpenTelemetry 
> observability systems. 
> 
> For backwards compatibility, OpenTracing Baggage is propagated as Correlations 
> when using the OpenTracing bridge. New concerns with different criteria should 
> be modeled separately, using the same underlying context propagation layer as 
> building blocks.

So this ticket, to me, is about whether OTel is going to support true baggage (which also completely covers observability concerns), or continue drawing a distinction between real baggage an OTel Correlations (in which case it should not be using the w3c "baggage" header).

**Comment by jmacd** [comment]
I think we should avoid figurative terms like "Baggage". The term itself is loaded with baggage at this point. How about calling this "User Data"?

**Comment by mtwo** [comment]
While the W3C baggage draft needs to become a formal recommendation, the W3C committee believes that it is now ready for implementation. No additional changes are expected.

Myself, @mwear , @dyladan , and @SergeyKanzhelev are on the W3C group

**Comment by tsloughter** [comment]
I think the W3C name should be stuck with to avoid confusion. If it is an implementation of W3C Baggage specification then it should be called "baggage".
