### ISSUE TITLE
Failing markdown-link-check does not break build

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-specification#554]
When looking at the build output to verify #553 doesn't break anything, I noticed that the build log for this one and also previous PRs shows that `markdown-link-check` fails but the build still completes successfully and leaves a green checkmark on the PR.

See this one, for example:
https://circleci.com/gh/open-telemetry/opentelemetry-specification/1888

**Run Tools -- Exit code: 0 -- SUCCESS**
```
#!/bin/bash -eo pipefail
make markdown-lint
make enforce-markdown-link-check
markdownlint -c .markdownlint.yaml '**/*.md'
markdown-link-check FAILED => errors:

Run 'make markdown-link-check' to see the errors exit 1
```

**Comment by arminru** [comment]
@bogdandrutu nevermind, I found the culprit 🙂

**Comment by bogdandrutu** [comment]
Is this still a bug?

**Comment by arminru** [comment]
> Is this still a bug?

@bogdandrutu Only until you press the merge button on #555. 😉

**Comment by bogdandrutu** [comment]
@arminru that button is disabled, what can I do :)?
