### ISSUE TITLE
Span name: Both low-cardinality (grouping key) and human-readable (display name)

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#557]
This came up when I suggested the handler name instead of the route name for the HTTP semantic conventions (#548). I think that the handler name is a better grouping key than the route, but the route is a better display name, as @yurishkuro [pointed out](https://github.com/open-telemetry/opentelemetry-specification/pull/548#discussion_r404397569). So I think we should relieve span name from this double duty. I'll post ideas as separate comments to allow reactions.

EDIT:

Cf. current spec of span name https://github.com/open-telemetry/opentelemetry-specification/blob/e7fe34ad/specification/trace/api.md#span:

> The span name is a human-readable string which concisely identifies the work represented by the Span, for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation. The span name should be the most general string that identifies a (statistically) interesting class of Spans, rather than individual Span instances. That is, "get_user" is a reasonable name, while "get_user/314159", where "314159" is a user ID, is not a good name due to its high cardinality.

I used the term "grouping key" here because I think using the span name as a key to group / sample similar spans is the reason why a Span name should have a low cardinality.

**Comment by Oberon00** [comment]
1) Add a new field "GroupingKey" to the span that defines a grouping key. The span name should be used if this is not set.

**Comment by Oberon00** [comment]
2) Add a semantic convention for a span attribute `grouping_key`.

**Comment by Oberon00** [comment]
3) Define a resource semantic convention `semconv.isgroupingkey:<ATTRIBUTE_NAME>` that defines a given span attribute as being viable as a grouping key (Problem: what if multiple exist? Have the value be an integer priority?).

**Comment by Oberon00** [comment]
I forgot to mention this in the SIG meeting today, but this topic was talked about there, so it seems this is an actual issue.

**Comment by jkwatson** [comment]
Can you define what a grouping key is? I'm not familiar with this term.

**Comment by Oberon00** [comment]
@jkwatson Thank you for that question, I think I accidentally coined that term here. I edited the description to be more clear. The "grouping key" requirement can be found in the spec as a requirement for low cardinality of the span name. I think the intention here was to allow grouping / sampling per span name.

**Comment by arminru** [comment]
@jkwatson You can think of the proposed grouping key as what an SQL query will look at in a "GROUP BY" clause. All spans with the same grouping key will be grouped together on the backend when being analyzed or presented in the UI.
Eventually, however, it is up to the backend to decide in which cases and for which purposes it applies grouping at all. It could also decide to group using another logic or even custom defined rulesets instead of relying on the grouping key (or span name).

**Comment by jkwatson** [comment]
Thanks for the answers, that helps a lot!

**Comment by yurishkuro** [comment]
> I forgot to mention this in the SIG meeting today, but this topic was talked about there, so it seems this is an actual issue.

@Oberon00 can you elaborate? I am not seeing an issue yet, especially since "grouping key" is a concept for machine processing, and why would machines care if they group by extra field or by readable span name (providing there's uniqueness).

**Comment by Oberon00** [comment]
@yurishkuro 
> "grouping key" is a concept for machine processing, and why would machines care if they group by extra field or by readable span name
Exactly! That's the idea behind these suggestions.

>  I am not seeing an issue yet
You can see the issue in the PR comment linked in the description (https://github.com/open-telemetry/opentelemetry-specification/pull/548#discussion_r404397569; actually it was your comment 😄). The issue is that if we just want the span name to be a display name, we can drop the requirement for low cardinality and would potentially have a better human-readability (though not in this case), or we could drop the requirement for (easy) human readability and would have a better grouping key. The span name needs to satisfy both requirements which obviously means there must be compromises made in some cases.

**Comment by yurishkuro** [comment]
Sorry, but I don't see "low cardinality" and "human readable" as conflicting requirements. In Jaeger UI, for example, you can select the Service from a dropdown, and the following dropdown is populated by span names - they have to be _both_ human readable and low cardinality (high cardinality will explode the dropdown and make it unusable).

**Comment by Oberon00** [comment]
"HTTP GET" is a very poor display name (it's also a poor grouping key). "GET domain.example.com" is a good display name, but it's an even worse grouping key.
I think this clearly demonstrates that there are cases where this conflicts.

**Comment by Oberon00** [comment]
If you want to use your groups for display (as opposed to sampling), you'll need a display name for your group. In that case you can use any one display name from within that group and display something like "'GET domain.example.com' and 32323 similar spans"

**Comment by pauldraper** [comment]
To summarize, you dislike the use of span name being both (1) the name for the individual span "instance" and (2) the (low-cardinally) name of the span "class".

I agree. If I'm looking at a single trace, I'd prefer to see

    HTTP GET /accounts/123
        HTTP GET /users/123
        HTTP GET /users/456
        HTTP GET /users/789

instead of

    HTTP GET /accounts/{accountId}
        HTTP GET /users/{userId}
        HTTP GET /users/{userId}
        HTTP GET /users/{userId}

The former is a more informative summary of the span.

Of course the latter form still needed for grouping (e.g. Jaeger dropdown UI).

**Counterargument:**

Span attributes are the place to store instance-specific details.

**Counter-counterargument:**

There are more attributes than can be displayed for all spans in a trace, and there are more span attributes than every backend can be required to understand significant vs. insignificant.

---



For compatibility I propose the opposite: the span "name" should continue to be the low-carnality span "class." And there should be a standardized attribute `name` or `instance` that summarizes the high-carnality span "instance."

**Comment by yurishkuro** [comment]
> And there should be a standardized attribute name or instance that summarizes the high-carnality span "instance."

I think having an optional `display.name` attribute is a reasonable idea (I've seen it being proposed in some Jaeger tickets), but it's certainly not a required field. Tracing UIs have wide flexibility in how they want to display the spans, e.g. many APM vendor tools prominently show the HTTP status code without having to drill down into span details, but surely we're not suggesting that status code should be a recommended part of the display name. Because each span already captures a lot of other attributes, UIs can be intelligent enough to decide which display format is the most useful, and it would not require the application code to duplicate the information it already provides in the span.

**Comment by carlosalberto** [comment]
>  Tracing UIs have wide flexibility in how they want to display the spans, e.g. many APM vendor tools prominently show the HTTP status code without having to drill down into span details

My same feeling.

I like the idea of having an additional, optional attribute (such as `display.name`) that is defined in the semantic conventions, and that UIs *may* want to use for display instead of `Span` name.

**Comment by pauldraper** [comment]
> optional

Agreed. No reason to make it mandatory: there is an obvious fallback in span name.

To add a example :

Since HTTP clients don't have to pattern-match URLs, they frequently are left without a great low-cardinality name and the instrumentation has to choose something poor like 'HTTP GET' or `HTTP GET github.com`. The utility of `display.name` is large in this case.

**Comment by Oberon00** [comment]
So back to the initial description: Will this display.nane allow me to merge #548 then?

**Comment by iNikem** [comment]
> "HTTP GET" is a very poor display name (it's also a poor grouping key). "GET domain.example.com" is a good display name, but it's an even worse grouping key.
> I think this clearly demonstrates that there are cases where this conflicts.

Why "GET domain.example.com" is a bad grouping key?

**Comment by jmacd** [comment]
My $0.02 was given verbally in the last SIG meeting. I'd like to see a span name with message-formatting syntax, like "GET {http.url}". This is both descriptive and low cardinality, and when it comes time to display, the system can format the message.

**Comment by iNikem** [comment]
If you care for one more opinion: span name is certainly a "grouping key" for me. A value that define a "class" of spans, as specification states. It is certainly has less information that possible display name of a single span. Every UI vendor can may his own decisions (probably even different ones for different users of that UI) what specific attribute of the span to use in their UI. Span name defines a unit of work, not a particular invocation of that work.

Taking that into account I think the original proposal of #548 is a good one and we should go with it.

**Comment by pauldraper** [comment]
Span name is definitely a grouping key.

The question is whether backends or instrumentations are in a better
position to display a good name/summary for an individual span.

I believe instrumentations should do choose attributes for a display name;
you believe that backends should understand attributes and generate a
display name.

**Comment by iNikem** [comment]
Correct. Backends have to understand attributes anyway if they hope to present useful information to their users. "Useful" as in "relevant to users' use-cases". You don't make decisions about UI in sql queries.

**Comment by Oberon00** [comment]
@iNikem 
> Why "GET domain.example.com" is a bad grouping key?

Because it can have a very high cardinality. See https://github.com/open-telemetry/opentelemetry-specification/issues/270#issuecomment-539363629

**Comment by iNikem** [comment]
Ah, I thought you were talking about "GET <domain name here>". Using full URL is certainly bad for grouping. Even using path portion is very bad, agreed.

**Comment by iNikem** [comment]
Btw, @Oberon00 , adding to my comment above. I think that "GET domain.example.com" is OK for span name and consequently for grouping key, if it really contains only domain name, without any path info. I assume any given application queries only a fixed number of domains :)

And I again want to express my support for #548. What else has to be done before that PR can be revived and merged?

**Comment by iNikem** [comment]
> And I again want to express my support for #548. What else has to be done before that PR can be revived and merged?

For the record, I have since changed my opinion and think that http route information, if available, makes for a better span name than handler name. My current opinion is based on the following example.

Imagine we have a servlet container running Spring MVC application and having auto instrumentation agent attached. When we create SERVER span from servlet request we have full url, which is too high cardinality for span name, and servlet handler name, like `MainServlet.doGet`. Later Spring MVC kicks in and detects that requests should be handled to a `PersonController.showDetails` based on the request route `/api/v2/persons/{personId}`.

In the situation above I think it is sensible to update SERVER span name to route-based name `/api/v2/persons/{personId}`. But not `PersonController.showDetails` because that would be strange to servlet instrumentation created span.

**Comment by tedsuo** [comment]
Hi all, I've made a display hint proposal to help resolve this, please have a look: https://github.com/open-telemetry/opentelemetry-specification/pull/730

**Comment by yurishkuro** [comment]
> "HTTP GET" is a very poor display name (it's also a poor grouping key).

I want to address this argument. For server-side span, there is no excuse in using "HTTP GET" as a span name. A server always has some kind of mapping from URLs to handlers, that mapping most commonly called "route". The route is good both as display string and grouping key, satisfying the span name requirements.

The situation where "HTTP GET" names become necessary are for the client-side spans emitted by generic instrumentation of HTTP frameworks, which are removed from business logic and only have the (potentially high-cardinality) URL to work with. It is often not that interesting to build aggregations of those spans, so while certainly a poor grouping key those names do not affect the analysis that much. Without aggregation requirement, these spans are only useful to be shown in the Gantt-chart style views, where we're dealing with a single span and the UI can replace/augment the span name with the full URL.

**Comment by pauldraper** [comment]
I think that depends on how you choose to do it.

IMO there isn't a fundamental difference between client tracing and server tracing:

```
client.programming.function
   HTTP GET client
       HTTP GET server
           server.programming.function
```

What is instrumented by whom depends.

If you are using a SOAL client, there an obvious automatic name for the operation. If you are using ApacheHttpClient you will have to choose and add the name yourself.

If you are using a Play server, there is an obvious automatic name for the operation. If you are using com.sun.net.httpserver.HttpServer you will have to choose and add the name yourself.

**Comment by Oberon00** [comment]
@open-telemetry/dotnet-approvers are you aware of this issue? It seems you already made a choice here that runs counter the current direction of this discussion when naming the Name [DisplayName](https://github.com/open-telemetry/opentelemetry-dotnet/blob/310f3150992581b84acf56d27fddf7800d19af8d/docs/trace/getting-started/README.md#user-content-getting-started-with-opentelemetry-net-in-5-minutes:~:text=Activity.DisplayName) (see https://github.com/open-telemetry/opentelemetry-specification/pull/730#issuecomment-673882556)

**Comment by SergeyKanzhelev** [comment]
I suggest to move this issue for Future milestone. This may be added after GA, not a breaking change.

**Comment by Oberon00** [comment]
The issue here is that the purpose of the existing span name is not clearly defined. Sure, you can add a ` display.name`  later on (should it be required). But you cannot as easily undo the compromises made in semantic conventions to make the existing span name a more useful display name and a worse grouping key for that.

**Comment by Oberon00** [comment]
See spec

> The span name is a **human-readable** string which concisely identifies the work represented by the Span, for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation. The span name should be **the most general string** that identifies a (statistically) interesting class of Spans, rather than individual Span instances.

the issue is that optimizing a span name for human-readability will sometimes yield different results from optimizing for "most general string", as demonstrated in #548. In that PR, I agree that the route name is better for human consumption, but I maintain that the handler name is a more general string and still identifies a statistically interesting class of spans.

**Comment by austinlparker** [comment]
Outside of the spec, the span name is generally referred to as the 'grouping key' for operations and instrumenters are advised to avoid high cardinality span names. I agree with your overall point, but I would suggest that #548 could just as simply be resolved by turning the handler class/method name into a semantic attribute on a server span.

+1 to Sergey's point about tabling this until post-GA.

**Comment by SergeyKanzhelev** [comment]
@Oberon00 this problem exists on many platforms already and every platform takes its route to resolve it. OpenTelemetry semantic convention made emphasize on (more) guaranteed grouping. Every app owner/vendor may adjust the span name with custom modules or custom code.

Also our requirement is to have a support for features in some backend. This is not a simple attribute and additional semantic is forced on it. So it would be great to have Jaeger or other backend to demonstrate how to use it.

**Comment by Oberon00** [comment]
I'm perfectly fine with tabling #548 and #730, but this issue is not resolved by either IMHO.

> So it would be great to have Jaeger or other backend to demonstrate how to use it.

How to use what?

I think I'll propose a one sentence PR for this issue before more confusion arises 😉

**Comment by Oberon00** [comment]
I proposed #810 to clarify what I think we should resolve before GA.
