### ISSUE TITLE
OTEL_SAMPLING_PROBABILITY

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-specification#567]
It would be nice to just set something like ~`OTEL_SAMPLING_RATE`~  `OTEL_SAMPLING_PROBABILITY` in an instrumented service's env and that automatically get picked up by the probability sampler.

**Comment by bogdandrutu** [comment]
This should be addressed by https://github.com/open-telemetry/opentelemetry-specification/issues/572
