### ISSUE TITLE
Ambiguous directions for Zipkin exporters

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#568]
Section "Unit of Time" (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/zipkin.md#unit-of-time) says:

> Zipkin times like `timestamp`, `duration` and `annotation.timestamp` MUST be
> reported in microseconds with decimal accuracy. For example, `duration` of 1234
> nanoseconds will be represented as 1.234 microseconds.

Problems:
  * "with decimal accuracy" is an odd expression
  * binary Zipkin formats (thrift, proto) represent timestamps as integer values, so the recommendation "1.234 microseconds" is also odd.

In Zipkin JSON it's probably ok to have a decimal value like 1.234.

**Comment by Oberon00** [comment]
Decimal accuracy could mean that you should not use floating pont arithmetic to compute the value but rather `(nanosecs / 1000) + "." + (nanosecs % 1000)`. That would be totally reasonable. But this needs to be clarified.

**Comment by devinsba** [comment]
Like @yurishkuro says they must be integers, and that's the case in all the encodings. Generally the timestamps are `nanos / 1000`, and durations would be `MAX((endNanos - startNanos) / 1000, 1)`.

**Comment by jkwatson** [comment]
Summoning zipkin guru @adriancole

**Comment by adriancole** [comment]
I agree with things said about non floating point so far, we've even oddly had this discussion on envoy. Not sure why suddenly things are ambiguous, as whole numbers is actually defined in swagger. If questions like this come up again (only here and envoy so far), we can consider re-clarifying in the swagger to remind people that we follow that spec and expect whole numbers (even if some endpoints might choose to be lenient on accepting scientific notation.. I'm not sure if ours is or not actually!)

Here's the other thread where this was answered more completely.
https://github.com/envoyproxy/envoy/pull/10400#pullrequestreview-377354099

**Comment by adriancole** [comment]
here's the swagger anyway.. sorry I mentioned without pasting https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml
