### ISSUE TITLE
OTEL_LOG_LEVEL

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-specification#569]
It would be nice to just set something like OTEL_LOG_LEVEL in an instrumented service's env and that automatically get picked up by the tracer provider.

**Comment by Oberon00** [comment]
Why do you single out the tracer provider here? What exactly do you expect to configure with OTEL_LOG_LEVEL? The logging framework that OTel itself uses (e.g. java.util.logging, Python logging module, etc)?

**Comment by naseemkullah** [comment]
Hi @Oberon00 ,
- I singled out the tracer provider as in my experience working with the js implementation it was it's log level property that controlled the verbosity of otel itself.

- Yes the logging framework used by otel itself.

**Comment by reyang** [comment]
Superseded by #572.
