### ISSUE TITLE
API: add a note that Span is an interface and what are the expectations for alternative implementation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#57]
Current section about the Span doesn't say anything about the fact that is is an interface that may have an alternative implementation

**Comment by jmacd** [comment]
What complications to you imagine wanting to document? I believe the point of an interface specification is that all the expectations are set, i.e., it should not matter what alternative implementation is selected.

**Comment by SergeyKanzhelev** [comment]
With this issue I intended to make sure all cross-language implementations will actually make is an interface, not a final class. Spec must declare it.

Also implications are that you will also need to have a custom implementation of SpanBuilder and it is expected that alternative implementations should keep the same philosophy of write-only Spans.
