### ISSUE TITLE
Separate specification of "Named" interfaces

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#587]
The specification for Named Tracers is identical to the specification for Named Meters. The text specifying Named Tracers is in the Tracer specification, but should be split out so that it can be easily referred to from the Meter specification.

Separate https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#obtaining-a-tracer

**Comment by jmacd** [comment]
The original comment: https://github.com/open-telemetry/opentelemetry-specification/pull/581/files/1b9d8a262ca8061646fbc635adf0b95857375d5f#r420302098

**Comment by tigrannajaryan** [comment]
This appears to ask for an improvement in the spec structure but does not change the semantics. I suggest to remove the `release:required-for-ga` label.

**Comment by Oberon00** [comment]
@jmacd I'd vote for keeping this open but addressing it after GA. It does seem like a nice-to-have improvement.

**Comment by reyang** [comment]
Given we've now mentioned covered meter and tracer in separate docs, I think we can close this issue.
