### ISSUE TITLE
SDK: toSpanData is needed on Span class and it may be called multiple time even before Span was completed

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#60]
As we discussed in https://github.com/census-instrumentation/opencensus-csharp/issues/134 there are scenarios that require reading properties from the incomplete `Span`s. It is needed when one want to put `Span` properties into the `tracestate` for instance.

Some sort of looking inside the `Span` may need to be implemented on API level.

`API` vs `SDK`: This method should be implemented in the same layer as the callback that will be used. E.g. if the callback will be in `API` - hook cannot be relying on safe casting to `SDK`'s `Span` object. Thus should be operating with `API`'s interface of `Span`. If the hook is implemeted in `SDK` - then it's OK to only have this method on `SDK`'s `SpanSDK` class.

CC: @discostu105

**Comment by jmacd** [comment]
In this comment (https://github.com/open-telemetry/opentelemetry-specification/issues/55#issuecomment-499166576), I've argued that instrumentation APIs should not be used to read back their own diagnostics state. It limits implementation strategies too severely, so anything to do with reading diagnostics state at runtime should be limited to the SDK.

**Comment by bogdandrutu** [comment]
API should not expose any reader for the recorded data. This will enforce a specific implementation for the API.

**Comment by SergeyKanzhelev** [comment]
than we need to make sure SDK has callbacks and methods to implement the kind of scenarios @discostu105 requested. Changing title to "SDK"

**Comment by SergeyKanzhelev** [comment]
Closing. @discostu105 please reopen with the specific scenario description
