### ISSUE TITLE
SDK: Resources SDK

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#61]
Explain how the resources API is extended by SDK. Specifically:

- how resources can be associated with Span Protos
- how resoruces can be populated from environment variables

Move this document https://github.com/open-telemetry/opentelemetry-specification/blob/master/work_in_progress/specification/resource/Resource.md to the root folder

**Comment by SergeyKanzhelev** [comment]
Also define which environment variables SDK uses to initialize Resource from out of the box

**Comment by jmacd** [comment]
Current discussion is happening in https://gitter.im/open-telemetry/resources-wg

**Comment by bogdandrutu** [comment]
I think Resource is already in the SDK and the environment variable is discussed in https://github.com/open-telemetry/opentelemetry-specification/issues/572
