### ISSUE TITLE
Consolidate specification of global tracing and metric providers

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#613]
Specification related to the global instances should be consolidated across tracing and metrics, otherwise we have two inconsistent descriptions of how the global instances must work.

Requested here:
https://github.com/open-telemetry/opentelemetry-specification/pull/601#discussion_r427434133

Similar issue: #587 

Related OTEP:
https://github.com/open-telemetry/oteps/pull/74

**Comment by andrewhsu** [comment]
from the issue triage meeting today with TC, allowed for GA for editorial change only

**Comment by reyang** [comment]
This should have been resolved by #1557.
