### ISSUE TITLE
Conflicting information on Resource / Instrumentation Library

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-specification#614]
Conflicting information on Resource / Instrumentation Library

The [SDK Resource Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md) states:

> When used with distributed tracing, a resource can be associated with the TracerProvider when it is created. That association cannot be changed later. When associated with a TracerProvider, all Spans produced by any Tracer from the provider MUST be associated with this Resource.

My interpretation is that the Resource assigned to the TracerProvider, will remain static for the lifetime of the application. Tracers returned by the provider will also reference this Resource as will Spans created by the Tracers.

My confusion comes from the [SDK Trace spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#tracer-creation) which states:

> New Tracer instances are always created through a TracerProvider (see API). The name and version arguments supplied to the TracerProvider must be used to create a Resource instance which is stored on the created Tracer.

[OTEP-83](https://github.com/open-telemetry/oteps/blob/master/text/0083-component.md) added the Instrumentation Library concept, and I thought that the name and version described above belong to the Instrumentation Library, not as another Resource. 

Should the SDK trace spec be updated to say:

> New Tracer instances are always created through a TracerProvider (see API). The name and version arguments supplied to the TracerProvider must be used to create an InstrumentationLibrary instance which is stored on the created Tracer.

or do we need to represent this information both as a Resource and an Instrumentation Resource?

**Comment by jkwatson** [comment]
I think the SDK trace spec is just out of date and should be rewritten as you suggest.

**Comment by bogdandrutu** [comment]
I think your suggestion is correct @mwear

**Comment by arminru** [comment]
For the current state, updating the outdated SDK trace spec with your suggestion would be correct.

If I got the discussion on https://github.com/open-telemetry/opentelemetry-proto/pull/150 right, however, there is a motion to revert [OTEP-83](https://github.com/open-telemetry/oteps/blob/master/text/0083-component.md) by removing `InstrumentationLibrary`. It would be replaced by representing the tracer and meter name+version using span attributes and metric names or labels. In that case, this passage would have to be revised again.

**Comment by bogdandrutu** [comment]
@arminru I would focus to fix the current state for the moment.

**Comment by arminru** [comment]
> @arminru I would focus to fix the current state for the moment.

@bogdandrutu Of course. Just wanted to mention it so it's less likely to be overlooked.
