### ISSUE TITLE
Metric API - clarification on Unbind method on sync instrument.

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-specification#618]
Opening an issue to continue the discussion from: https://github.com/open-telemetry/opentelemetry-specification/pull/601/files#r428864890

Question which require clarification:
Is Unbind() part of public API and every language expected to implement it? 
OR is it a SDK internal stuff, which SDK uses to bind/unbind when user makes direct calling convention.

**Comment by jmacd** [comment]
Unbind was meant to support releasing memory that would otherwise be held indefinitely. It we were to quietly remove a record from the SDK's internals, then the instrument would need support for re-binding itself, right? So, it would have to hold a reference to the labels that were bound. Implementing support for "re-bind" sounds harder than exposing an unbind method. Is there a reason not to support unbinding?

**Comment by cijothomas** [comment]
There is no reason to not support it! - I just wanted to clarify if its part of the spec, or just something which every language may/may not chose to implement internally

In .NET we have UnBind(), but its not meant for users to directly use it. But SDK implementation uses it internally, to clean up those boundinstruments, which are not used in 1 or 2 collection interval. Happy to make it public API, so users can decide when to call it - just want to confirm this.

**Comment by andrewhsu** [comment]
@jmacd @bogdandrutu discussed this at the spec sig mtg today and looking for an owner. I'll assign to myself for now to find an owner, not planning on driving this one.

**Comment by bogdandrutu** [comment]
>In .NET we have UnBind(), but its not meant for users to directly use it. But SDK implementation uses it internally, to clean up those boundinstruments, which are not used in 1 or 2 collection interval. Happy to make it public API, so users can decide when to call it - just want to confirm this. 

I think the idea is that once a user do `Bind` then the element will be available until `Unbind` is called. Doing what you suggested will cause a lot of problems if users call record after the SDK `Unbind`, or you have a complicated logic to resolve that problem.

**Comment by jmacd** [comment]
I see this as an API requirement, not a matter for the SDK specification.  Users must be able to free memory associated with a bound instrument. Note that this is not semantically the same as "Delete()" in the Protometheus API. There is no Delete() support in the OTel metrics API (which implies removal of a timeseries); there is only Unbind (which implies forgetting all state about a timeseries).

The action item here is to add a sentence or two to the API specification.
