### ISSUE TITLE
Expectations on queryability of attributes

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#624]
I'm looking at how to process span attributes (or any attribute, like on resource or events) in a backend. I couldn't find anything in the spec on whether there's any expectation on a backend that these attributes can be used in filter queries. Is it completely up to the backend? I can imagine several scenarios

1) Allow query on any and every attribute. I suspect this will generally be implemented as a post-processing filtering step in an API server as opposed to proper storage indexing of the keys since there's no restriction on cardinality.

2) Allow query on a subset of attributes that is defined in various semantic conventions by OpenTelemetry. As the cardinality can be estimated, these could be indexed as needed. Note that this means user defined attributes would never be queryable as they're not in the spec.

3) Allow query on a subset of attributes completely decided by a vendor.

For reference, in X-Ray we have two type of attributes, annotations and metadata. The former is indexed and queryable, the latter isn't. As the OpenTelemetry API doesn't have this distinction, we lose this signal so I'm wondering if anyone has thought about how to handle the attributes when the cost of indexing an attribute for query is relatively expensive.

**Comment by anuraaga** [comment]
Was hoping to stay up for SIG meeting today but feel eyes drooping so hopefully can get an async response. Anyone able to give any pointers on this? @Oberon00 @bogdandrutu maybe? :)

**Comment by dyladan** [comment]
I think (3) will always be implied to some extent. We can prescribe the data formats and inputs, but in the end it will be up to each backend to index or not index any fields. I don't think you can specify backend functionality here, especially since it is unlikely that all backends will have architectures which are conducive to sharing an indexing scheme.

**Comment by anuraaga** [comment]
Thanks it's what I figured too thanks for confirming!
