### ISSUE TITLE
grpc-trace-bin support for gRPC trace? 

### ISSUE THREAD

**Issue by youngbupark** [open-telemetry/opentelemetry-specification#639]
Looks like current spec describes only W3C traceparent header for span context propagation for now.

However, [Opencensus gRPC spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/gRPC.md#propagation) uses `grpc-trace-bin` header for spancontext propagation.

Does open-telemetry have a plan to support it?

**Comment by carlosalberto** [comment]
While `Binary` is expected to make it (back) into GA, I'm wondering whether we need this specific item too.

Opinion on this @bogdandrutu ?

**Comment by JamesNK** [comment]
How will grpc-trace-bin work?

1. Must both traceparent and grpc-trace-bin headers be present on a gRPC HTTP request?
2. Or is grpc-trace-bin optional from a client's perspective, and servers check for grpc-trace-bin, and if it is not present then use traceparent? (or the other way around)
3. Or are gRPC HTTP requests unique that it uses grpc-trace-bin while other HTTP requests use traceparent?

**Comment by dyladan** [comment]
>Must both traceparent and grpc-trace-bin headers be present on a gRPC HTTP request?

grpc-trace-bin is the binary equivalent of the traceparent. They transmit the same data.

>Or is grpc-trace-bin an optional additional for backwards compatibility. Servers check for traceparent, and if it is not present then use grpc-trace-bin? (or the other way around)

it is required for compatibility with opencensus (at least in js) because that is what OC used.

>Or are gRPC HTTP requests unique that it uses grpc-trace-bin while other HTTP requests use traceparent?

the motivation is simply that gRPC is a binary protocol which can take advantage of the more tightly packed binary format to save some bytes on each request

**Comment by rakyll** [comment]
I think we need to have a separate discussion with gRPC to deprecate grpc-trace-bin and switch them to the TraceContext header.

**Comment by JosemyDuarte** [comment]
Is this still in development? I'm trying to enable distributed tracing from a JS service to a Golang service which communicate via gRPC but it doesn't work as described on [@opentelemetry/instrumentation-grpc](https://www.npmjs.com/package/@opentelemetry/instrumentation-grpc), could `grpc-trace-bin` be the reason? If it so, then how it's @opentelemetry/instrumentation-grpc supposed to work if is not sending `grpc-trace-bin`?

**Comment by hdost** [comment]
Also an interested part here

**Comment by trask** [comment]
In [Java gRPC Instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6), we don't have any special handling for this, which means we (only) use the `traceparent` header when W3C propagator is used.

**Comment by austinlparker** [comment]
Is this related to https://github.com/open-telemetry/opentelemetry-specification/issues/437?

**Comment by jack-berg** [comment]
I believe so. Closing since this is dependent on #437, which was closed for the reasons listed [here](https://github.com/open-telemetry/opentelemetry-specification/issues/437#issuecomment-2233575020).
