### ISSUE TITLE
Standard metric names and semantic conventions

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#651]
The metrics SIG has been working on guidelines for metric naming: https://github.com/open-telemetry/oteps/pull/108

With that OTEP likely to merge soon, we are ready for the next step, which is to produce standard names and semantic conventions for system and runtime metrics that will be common across OpenTelemetry libraries.

Here's a document with a proposal: https://docs.google.com/spreadsheets/d/11qSmzD9e7PnzaJPYRFdkkKbjTLrAKmvyQpjBjpJsR2s/edit#gid=0

Here's a second document with another proposal: 
https://docs.google.com/spreadsheets/d/1WlStcUe2eQoN1y_UF7TOd6Sw7aV_U0lFcLk5kBNxPsY/edit#gid=0

There are a couple of draft and in-progress implementations that await these conventions decisions:

https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/runtime

https://github.com/open-telemetry/opentelemetry-python/tree/master/ext/opentelemetry-ext-system-metrics

We are looking for someone to lead this effort. (CC: @mtwo)

**Comment by jmacd** [comment]
This may also be a useful reference: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/hostmetricsreceiver

**Comment by aabmass** [comment]
@jmacd were you thinking this should be an OTEP or just a PR to the spec repo?

**Comment by jmacd** [comment]
I think there's a chance of a substantial debate happening, which makes an OTEP the best choice. That way it would reside alongside open-telemetry/oteps#108 as well.

**Comment by bogdandrutu** [comment]
A lot of the problems were fixed, and what is left is covered by https://github.com/open-telemetry/opentelemetry-specification/issues/600
