### ISSUE TITLE
db.instance can be optional?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#658]
I am writing some redis instrumentation that uses `lettuce`'s native tracing support, and at least for now it doesn't expose the redis database index to tracing extensions. I have filed an issue to see if it can be added

https://github.com/lettuce-io/lettuce-core/issues/1312

but because in Redis database index is not so common to use, and I can easily imagine other database systems without any concept of an instance / schema, does it make sense to make db.instance optional? Do we expect every single database out there to have this?

**Comment by Oberon00** [comment]
Hi, can you please take a look if #575 would solve your problem?

**Comment by anuraaga** [comment]
Ah sorry for missing that PR yup it looks good to me!
