### ISSUE TITLE
API: Sampling `Decision` may need to update tracestate, not only attributes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#66]

**Comment by jmacd** [comment]
Background question: why should the sampling decision output attributes?
In looking at the prototype Java SDK, I see that there are TraceOptions which include the "is_sampled" bit. I feel the sampling rate belongs there. are TraceOptions serialized into Tracestate?

**Comment by SergeyKanzhelev** [comment]
examples of attribute may be algo used to make a decision and sampling priority. Sampling rate is not a common-enough concept to make it strongly typed or include into `TraceOptions`. However I believe it's a common scenario to put it into `Tracestate`.

TraceOptions are serialized into `trace-flags`: https://w3c.github.io/trace-context/#trace-flags

**Comment by jmacd** [comment]
I have a terminology question. I was under the impression that "Attribute" referred to properties of a span, and that "Tags" referred to contextual properties that would propagate along with trace context. In this thread, I believe we're talking about context tags which a sampling algorithm would output for propagation.

I feel somehow that context tags should be reserved for applications to use, not for tracing systems to propagate internal state. I see the sense in allowing some vendor-specific state in Tracestate, but I worry that we're imagining something generally useful, where all we really need is one floating-point number alongside "is_sampled" to propagate a sampling rate, for systems that use fixed-probability sampling. Sampling algorithms may get quite complex, but I feel that for the most part sampling decisions should be recorded along with span data, not propagated via context.

That said, there are plenty of reasons to allow tracing systems to make decisions about propagating attributes from one node to another to facilitate distributed trace joins (e.g., see Pivot Tracing). In that sense, we should disentangle these things:

1. tracing systems sometimes want to know sampling rates downstream
2. tracing systems sometimes want to inject tags for themselves to use downstream in sampling decisions.

I'd suggest that an optional sampling-rate field in trace-flags or Tracestate will address (1), and an independent-of-sampling mechanism to allow tracing implementations to decide on the contents of a correlation context will address (2). A tracing system could want (2) even when it's not sampling.

**Comment by SergeyKanzhelev** [comment]
this issue is specifically about sampler and how sampler will propagate it's decision and extra arguments to downstream components. Correlation Context will be reserved for apps, so Tracestate is a native place for it.

**Comment by jmacd** [comment]
As I understand it, Tracestate contains Entries of key:value attributes that permit the sampling implementation to propagate its decision and extra arguments to downstream components. Your proposal above allows the sampling implementation to the span ("Return tags which will be attached to the span."). That's the part I'm confused about, since I believe Span attributes should be reserved for apps (like Correlation context).

**Comment by jmacd** [comment]
In other words, I now see that the sampling decision should have a chance to modify Tracestate. But if the sampling decision intends to record any key-value data, I think it should do so in the Tracestate entries.

**Comment by rochdev** [comment]
Just wanted to mention that we have a constraint with client sampling to not do allocations when a trace will be dropped. The way we do it right now is that we take the decision as early as possible (before the root span is even created) and then use a no-op span for any span that is a part of the that trace. The no-op span is a singleton that is reused for all dropped traces. Then propagation is done from the no-op span which will always propagate a decision to drop.

I'm not familiar with `TraceState` so hopefully I'm not deviating from the scope of this issue.

**Comment by lizthegrey** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/180 is now salient, so cross-linking it.

I'm okay with using `Tracestate` rather than `TraceOptions` but I feel uncomfortable with the status quo of not propagating the info at all right now.

**Comment by jmacd** [comment]
Closing this as it is discussed under https://github.com/open-telemetry/oteps/pull/79

**Comment by Oberon00** [comment]
@jmacd To me it looks like the only relation of this issue to open-telemetry/oteps#79 is that both are in the area of sampling...

Closing this issue probably still makes sense because it seems to be stale. @lizthegrey what do you think? I think this was related to https://www.honeycomb.io/blog/dynamic-sampling-by-example/
