### ISSUE TITLE
Thread-Safety Requirements for Metrics

### ISSUE THREAD

**Issue by ankit-bhargava** [open-telemetry/opentelemetry-specification#662]
**Is your feature request related to a problem?**

Currently, the [concurrency guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/concurrency.md) do not list specific recommendations for the Metrics API.  Languages developing their metrics implementations and new developers who may not have much experience with thread-safety therefore have to make assumptions about what should support concurrent calling and where it may be optional leading to a mosaic of policies across OpenTelemetry. 

**Describe the solution you'd like**

It would be helpful to contributors if the OpenTelemetry community discussed which metrics operations can be called concurrently and in what situations (potentially during future SIG meetings) then clearly documented the requirements as has already been done with the Tracing API.  Specifically, concurrency documentation is missing for the Meter and Metric Instrument subsets of the API.  Additionally, interns and contributors who are unfamiliar with thread-safety will benefit from a set of sample conditions under which concurrency issues may arise.  

**Describe alternatives you've considered**

There are no suitable alternatives to this solution as OpenTelemetry strives to maintain consistent behavior across languages.  Clear guidance in the specification is the only way to guarantee that the same principles are followed everywhere.

**Comment by jmacd** [comment]
I believe this is covered (in its draft form) in the SDK specification for metrics. #347.  
It says (or should say, when finished) that instruments support concurrent use. 
It also states that the Accumulator component SHOULD offer high concurrency, but it stops short of mandating a particular approach. I do not wish to force the use of atomic variables onto all languages, for example.
I would like to leave this open to ensure we do cover this topic.
