### ISSUE TITLE
Modeling language exceptions / crashes (e.g., stack traces)

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#667]
I feel like this would be a common request but couldn't find it, please let me know if I missed it. Otherwise, made sure my title has enough SEO-ability as possible ;)

Any thoughts on modeling a language exception for a span? This would likely be added to `Status`, which is currently just code and description.

https://github.com/open-telemetry/opentelemetry-specification/blob/6f47d037b52a9892570a0b0964d6b12f5891a0a3/specification/trace/api.md#status

A stack trace in spans can be very useful, especially for being able to link back to source code from a span. Some vendors have it baked in.

https://cloud.google.com/trace/docs/reference/v2/rest/v2/StackTrace
https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-errors

Not as related, but I've written a proto to model a stacktrace before, admittedly mainly for Java, but it works well in being able to deserialize the exception in an RPC client

https://github.com/line/armeria/blob/master/grpc/src/main/proto/com/linecorp/armeria/grpc/internal_exception_messages.proto

**Comment by anuraaga** [comment]
Found #427 sorry for the noise :)

**Comment by arminru** [comment]
@anuraaga Just for your reference, there are a couple more proposals around in addition to #427. You can find them linked on tracker issue #599.
