### ISSUE TITLE
Proposal - Propagators API: Add IsInjected

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-specification#674]
I have a need in the dotnet library (see https://github.com/open-telemetry/opentelemetry-dotnet/pull/741) to add an `IsInjected` operation to the propagation API. 

I have defined it like this:
```csharp
        /// <summary>
        /// Tests if an activity context has been injected into a carrier.
        /// </summary>
        /// <typeparam name="T">Type of object to extract context from. Typically HttpRequest or similar.</typeparam>
        /// <param name="carrier">Object to extract context from. Instance of this object will be passed to the getter.</param>
        /// <param name="getter">Function that will return string value of a key with the specified name.</param>
        /// <returns><see langword="true" /> if the carrier has been injected with an activity context.</returns>
        bool IsInjected<T>(T carrier, Func<T, string, IEnumerable<string>> getter);
```

I need this because in .NET Framework an HTTP request can be re-submitted through OpenTelemetry for things like redirect or ssl re-negotiation. Basically I have to check if we already instrumented the request so we don't create duplicate spans.

Example: https://github.com/open-telemetry/opentelemetry-dotnet/blob/2943c83737abf789082c832d38548a850eb01cfc/src/OpenTelemetry.Instrumentation.Dependencies/Implementation/HttpWebRequestActivitySource.netfx.cs#L214-L216

/cc @SergeyKanzhelev @cijothomas

**Comment by Oberon00** [comment]
This use case sounds like something that is better solved on the instrumentation level. Isn't there some request context in .NET that stays the same over re-submissions where you could store the boolean?

**Comment by Oberon00** [comment]
I'm not sure if the IsInjected check would be much cheaper than trying Extract and checking if there was something extracted. If so, maybe it would be possible to optimize Extract (e.g. parse tracestate lazily, ...).

**Comment by CodeBlanch** [comment]
> This use case sounds like something that is better solved on the instrumentation level. Isn't there some request context in .NET that stays the same over re-submissions where you could store the boolean?

Not that I have found. I just double-checked the [list](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=netframework-4.8#properties). Most of the properties exposed are just wrappers for headers. We could add our own header "x-isinjected", or something, to know the state, but that would be transmitted which I don't think all users would appreciate. I can imagine a lot of issues "How do I remove x-isinjected header from all my requests?!?!" 😄 

> I'm not sure if the IsInjected check would be much cheaper than trying Extract and checking if there was something extracted. If so, maybe it would be possible to optimize Extract (e.g. parse tracestate lazily, ...).

I like the idea of improving the Extract API so it could do the check efficiently (by deferring the heavy parsing), but I feel like that might be more complicated than just adding the `IsInjected` op? I'll take a stab at it locally and report back.

**Comment by CodeBlanch** [comment]
Update... very easy to implement deferred `Extract`.

```csharp
    public interface ITextFormatActivity
    {
        IDeferredActivityContext Extract<T>(T carrier, Func<T, string, IEnumerable<string>> getter);
    }

    public interface IDeferredActivityContext
    {
        ActivityContext ToActivityContext();
    }
```

Code needing to check "IsInjected" can do this:
`Options.TextFormat.Extract(request, (r, h) => r.Headers.GetValues(h)) != null;`

Code needing actual context can do this:
`var context = Options.TextFormat.Extract(request, (r, h) => r.Headers.GetValues(h))?.ToActivityContext();`

However, it is not for _free_. Previously we returned `struct ActivityContext` so returning `interface IDeferredActivityContext` will require an allocation that _could_ be avoided for all other instrumentation. It also has an addition call, but that is minor and could possibly be inlined.

**Comment by CodeBlanch** [comment]
Ended up removing this from the .NET library. It was too hard to make work, especially with something like baggage/correlation where you can't tell if it wasn't injected due to non-execution of the propagator, or that the propagator executed and there was just nothing to inject.
