### ISSUE TITLE
Proposal: JSON Encoding for OTLP/HTTP

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-specification#678]
Protobuf is a relatively big dependency, which some clients are not willing to take. For example, webjs, iOS/Android (in some scenarios, the size of the installation package is limited, do not want to introduce protobuf dependencies). Plain JSON is a smaller dependency and is built in the standard libraries of many programming languages.

This Proposal will be consistent with the OTLP/HTTP specification except that the payload will use JSON instead of protobuf.

Full information is described in open-telemetry/oteps#122.

**Comment by Oberon00** [comment]
I don't think protobuf is that big of a dependency. Grpc would be but AFAIK protobuf is rather small.

**Comment by tensorchen** [comment]
I consider that JSON will be more friendly to front-end developers (webjs), and I am also concerned that JSON encoding is already used in the implementation of opentelemetry.io.

![image](https://user-images.githubusercontent.com/16510475/86147374-e3ea6a80-bb2b-11ea-9ffe-6c46bd7bc48a.png)

**Comment by tigrannajaryan** [comment]
This is already mostly specified: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#otlphttp

The remaining bit is the hex vs base64 traceid/spanid issue: https://github.com/open-telemetry/opentelemetry-specification/issues/786

Closing this, if there is anything else remaining we can open new issues.
