### ISSUE TITLE
API: Fully separate context propagation

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#70]
Ideally, both in-process and inter-process propagation should be a standalone module that can operate without the involvement of the Tracer.

Placeholder for more discussion.

**Comment by SergeyKanzhelev** [comment]
The issue was postponed to after the initial API completion.

**Comment by tylerbenson** [comment]
My primary concern with this decision is when we do move context, it might be a significant breaking change.  Usage seems to be encapsulated to `unsafe` packages, so maybe it won't be so bad... Just worried about API leakage.

**Comment by pauldraper** [comment]
What is the relationship of this to #237?

**Comment by SergeyKanzhelev** [comment]
@pauldraper seems like a dup, thanks for pointing out. Closing.
