### ISSUE TITLE
Add OTEL_EXPORTER environment variable

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-specification#710]
**What are you trying to achieve?**

To simplify the configuration of auto-instrumentations via environment variables, especially for first time users, add new variable `OTEL_EXPORTER` as a way to configure a list of exporters to use, e.g. `OTEL_EXPORTER=zipkin,prometheus,otlp_metrics`

**Additional context.**
This issue assumes that #666 is merged and we have environment variables recommendation in spec.

**Comment by carlosalberto** [comment]
This would be used *mostly* by auto-instrumentation, right?

**Comment by iNikem** [comment]
> This would be used _mostly_ by auto-instrumentation, right?

I think yes. Although, even more manual instrumentations this may be a convenient way to externalise the configuration/selection of exporters.

**Comment by tigrannajaryan** [comment]
I think this is a nice-to-have, not a must-have for 1.0 GA. I suggest to remove `release:required-for-ga` label.

**Comment by anuraaga** [comment]
To clarify, if the label is removed, a related PR definitely won't be merged? I don't think this, or SERVICE_NAME, are required, but if they're small in scope it could make sense to still hope they get in before GA to improve user experience of the first release.

**Comment by tigrannajaryan** [comment]
If there is a PR that is ready and approved I don't see any reason not to merge it even if the label is removed.

Once a spec freeze is declared that will mean we no longer want to accept substantial changes that are not labeled as `release:required-for-ga`, but I think we are not yet ready to declare a freeze.

**Comment by carlosalberto** [comment]
Changed it to P1 after talking to the Java Instrumentation Maintainers.

**Comment by mtwo** [comment]
@anuraaga, are you able to create a PR for this?

**Comment by trask** [comment]
i discussed with @anuraaga, please assign this to me, thx
