### ISSUE TITLE
Define the terms "in-band" and "out-of-band"

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#711]
These terms are very useful when describing the difference between span data and trace context data, but they are pretty old school from the days of radio signals, so many people do not understand them. Perhaps we could add them to a central glossary and use hyperlinks when using the terms in the rest of the spec (e.g. here https://github.com/open-telemetry/opentelemetry-specification/pull/577/files#diff-c219cbdc98c7d1029765b3f68ac49722R47)

**Comment by Oberon00** [comment]
Yeah, the glossary would be good for that!
