### ISSUE TITLE
Consider removing ExportCode from exporter interface

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#716]
**What are you trying to achieve?**

Simplify the `Exporter` interface by removing features that may not have a real use case.

**Additional context.**

In https://github.com/open-telemetry/opentelemetry-java/pull/1428 we're having trouble finding the use case for the exporter code and wonder if exporters can just accept spans without reporting per-export. Spans are essentially handed off to exporters, so keeping error handling, retrying, metrics, etc internal to the exporters without returning back to the SDK seems to make sense semantically.

Instead, exporters can use the new global error handler to report errors, or we could define a spec for exporter metrics or similar which are defined at the Exporter level as opposed to being per-export return codes. For example, something like Zipkin's `ReporterMetrics`.

https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin2/reporter/ReporterMetrics.java

/cc @jkwatson @huntc

**Comment by Oberon00** [comment]
I think we should consider adding the concept of exporter chains. The outer exporter could deal with things such as recording error metrics and maybe retry, and the nested one would do the actual export.
Of course the error code would only be needed between the inner and outer exporter, but for consistency I would just keep it, and not introduce a dedicated NestedExporter interface.

**Comment by huntc** [comment]
> I think we should consider adding the concept of exporter chains. The outer exporter could deal with things such as recording error metrics and maybe retry, and the nested one would do the actual export.
> Of course the error code would only be needed between the inner and outer exporter, but for consistency I would just keep it, and not introduce a dedicated NestedExporter interface.

I think retry and error handling is the business of an exporter and not to be handled by anything outside of it, including another exporter. For example, a grpc based exporter may well have different retry behaviour to an MQTT based one.

**Comment by Oberon00** [comment]
> I think retry and error handling is the business of an exporter

Yes but it should still be possible for it to delegate repetitive parts to something if it wants. An exporter chain is one (IMHO elegant) way of doing this. Of course the exporter should be in control of whether it wants to be wrapped in something or not, this is not something a user should decide (For example JaegerExporter.create() could return a `new ThreadInterruptTimeout(new RetryOnceExporter(new JaegerExporter()))`).

**Comment by huntc** [comment]
> In open-telemetry/opentelemetry-java#1428 we're having trouble finding the use case for the exporter code and wonder if exporters can just accept spans without reporting per-export. Spans are essentially handed off to exporters, so keeping error handling, retrying, metrics, etc internal to the exporters without returning back to the SDK seems to make sense semantically.

As an updated to my other PR, it is useful to have an async result code that can later be cancelled (which my PR now does). My recommendation is to close this issue.

**Comment by anuraaga** [comment]
Thanks @huntc makes sense to me
