### ISSUE TITLE
"Delta" sums for UpDownCounter are error prone

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#725]
Currently there are some language implementations that "reset" the calculated sum (default aggregation for UpDownCounter) every export interval, and this can cause problems in real world.

The main idea comes from the fact that the consumer of these metrics are almost all the time interested in the final result of the Sum (not in changes over time) and when alerts are used for these metrics most of the time they will be configured based on the total/cumulative Sum. As examples from the [UpDownCounter](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#updownsumobserver) definition:
* count the number of active requests - An alert will be set for "current number of active requests > 100"
* count memory in use by instrumenting new and delete - An alert will be set for "current memory usage > 10GB"
* count queue size by instrumenting enqueue and dequeue - An alert will be set for "current queue size > 1000"
* count semaphore up and down operations - Not sure if an alert is necessary important for this, but will most likely be using the "current" value of the semaphore.

When exporting "deltas" or sums that are reset every export interval, the export pipeline becomes a single point of failure for the alerts, any dropped "delta" will influence the "current" value of the metric in an undefined way (may cause alerts that should fire to not fire, or alerts to fire when they should not). Because of this it is extremely important to send "Cumulative" or a.k.a current value for an UpDownCounter all the time, so that if the export pipeline drops one exported value the alerts will still function correctly.

Because of this argument, I think OpenTelemetry should try to "force" users to configure the library correctly by:
1. Disabling the ability to compute delta sums for UpDownCounters and always export cumulative (current value).
2. Remove support for delta sums from the protocol.

**Comment by jmacd** [comment]
I think we decided this is not a great concern in the OTLP meeting today. I vote to close this issue.
