### ISSUE TITLE
Revisit Default Sampler and Interaction With TraceFlags 

### ISSUE THREAD

**Issue by MitchellDumovic** [open-telemetry/opentelemetry-specification#728]
Should the Default Sampler be changed from `AlwaysOn` to `ParentOrElse(AlwaysOn)`? 

The spec suggests that `AlwaysOn` is the default - currently this is not truly enforced consistently across languages: 
In Go (this might be a bug), the span's parent is always followed unless a different sampler is specified: 

https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/trace/span.go#L394

One thing that I think adds some confusion (at least for me) here is the interaction between the sampler and the Span context's `TraceFlags`. The spec suggests that `TraceFlags` should be passed down from parent to child [here](https://github.com/open-telemetry/opentelemetry-specification/blob/587bebac6ef773cf2540907b335b8478245ef836/specification/trace/sdk.md), but by always sampling by default this may not actually happen in practice.

**Comment by anuraaga** [comment]
Thanks for separating out this issue. +1 to changing default to ParentOrElse(AlwaysOn), it seems the least surprising. With all nodes using the default, they'll be effectively AlwaysOn but changing the sampling can be done at one node, the frontend, without worrying about incomplete traces.

**Comment by MitchellDumovic** [comment]
Discussed at the Spec Sig where there was general agreement that this is a good idea (changing the default sampler from `AlwaysOn` to `ParentOrElse(AlwaysOn)`). Will push up a PR to change this in the spec.
