### ISSUE TITLE
No spec for HTTP specific metrics

### ISSUE THREAD

**Issue by gfuller1** [open-telemetry/opentelemetry-specification#738]
**Problem:** There's no standard around what metric instruments to use or what labels to use for capturing HTTP activity. This can lead to problems when trying to navigate the data or filter it.

**Example:** one instrumented framework captures HTTP information and reports a metric for its duration as `http.duration` and include a label for the response code `response_code`. Another instrumented framework captures HTTP information and reports a metric for its duration as `http.client.request.duration` and includes a label for the response code but it is `status_code`. When someone tries to filter their data for HTTP metrics they will have a poor experience due to the inconsistencies in the data.

**Solution:** Write a spec to describe how to create HTTP metrics.

**Comment by tigrannajaryan** [comment]
After merging https://github.com/open-telemetry/opentelemetry-specification/pull/739 there are now conventions for HTTP metrics. Do we need something else in addition in the spec?

**Comment by jmacd** [comment]
I think nothing else is needed here.
