### ISSUE TITLE
Add instrumentation library info as semantic convention attributes

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-specification#746]
`TracerProvider.getTracer` API defines 2 parameters: instrumentation library name and version. This information is later available as part of OTLP. But at the moment it is not available in any other protocols. Thus any clients/backends who still use Zipkin/Jaeger protocol don't have access to this information.

I propose to add new optional attributes `telemetry.instrumentation.name` and `telemetry.instrumentation.version` to hold instrumentation library information.

**Comment by Oberon00** [comment]
This seems to be an instance of #660. @arminru suggested there (https://github.com/open-telemetry/opentelemetry-specification/issues/660#issuecomment-656086112) do define a reserved attribute name for each piece of data that is not already an attribute.

**Comment by jkwatson** [comment]
Are you asking to have a specification for how some exporters will treat this information? That's not really a "semantic attribute" in that it shouldn't be populated by instrumentation authors. I recommend changing the title of this Issue, and removing the `area:api` tag.

**Comment by jmacd** [comment]
Related attempt to treat these properties as ordinary attributes: https://github.com/open-telemetry/opentelemetry-proto/pull/150

**Comment by Oberon00** [comment]
Since we have no label for exporters, I added the sdk label. But if we are going to reserve the attributes, it's also a semantic convention concern, namely that by convention you should not set these attributes yourself but keep them free for exporter's use.

**Comment by iNikem** [comment]
I have submitted to PRs to address this issue: #800 and #801 . The proposed solution just augments existing protocol conversion rules from OTLP to Zipkin and Jaeger. This covers all possible formats of trace data on the wire and effectively solves this issue.
