### ISSUE TITLE
Is there a get equivalent for attributes?

### ISSUE THREAD

**Issue by aronchick** [open-telemetry/opentelemetry-specification#755]
Hi all! I'm looking to populate all events inside the span with the attributes from the parent span - so, for example, i start a span with the set_attribute("project_id", "foo") and then I'd like to set that as an attribute in the add_event call. I get that I could do this on the backend when I pull everything apart, but it'd be much more convenient to just duplicate now. But, though there's plenty of documentation on how to "set_attribute", there's none I can find on how to "get_attribute". Any suggestions?

**Comment by arminru** [comment]
Hi @aronchick,
no, there's no way to get span attributes from the API.
#669 clarified the requirement for spans that can be read from but those are only part of the SDK on purpose and not exposed in the API.

Can you share which use case you're trying to solve by duplicating the parent's span attributes as events on the child? Maybe we're able to solve that by other means.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, discussed this and the answer is "no", if there is a need, please send a PR to the spec to propose a change.

**Comment by Oberon00** [comment]
To point out two important reason for why get cannot be provided:
* A no-op SDK may be in place. To reduce performance overhead, it will not store attribute values, so it cannot implement get properly.
* A streaming SDK might write attributes directly to a network stream (buffer) and will have no way of reading them back.

**Comment by aronchick** [comment]
Gotcha – can you recommend a solution for later getting an attribute (if it exists) on a span?

I guess what I’m really looking for is a way to pass state, in a variable, to a child span or event being written.

**Comment by bogdandrutu** [comment]
@aronchick try to use CorrelationContext
