### ISSUE TITLE
Attributes restrictions are different between Resource and Spans

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#763]
**What are you trying to achieve?**

Consistency between attributes usage

**Additional context.**

Currently there are trace specific requirements for attributes https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-attributes that most likely should apply to all attributes usages.

**Comment by thisthat** [comment]
Should this issue also cover the consistency with metric labels?
Looking at the different language implementations, Cpp, Go, and Rust implement labels as a mapping from `string` to [`Attributes`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md). Instead, C#, Erlang, Java, Js, Python, and Swift implement metric labels as a mapping from `string` to `string`.

**Comment by Oberon00** [comment]
IMHO, this is a separate issue. The description in this issue is a bit minimal, but I think it covers https://github.com/open-telemetry/opentelemetry-specification/pull/760#discussion_r466596175 and the other paragraphs that are only in Span.SetAttribute but could be in the common attribute definition.

**Comment by bogdandrutu** [comment]
@Oberon00 you are correct, I am referring to this https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-attributes where there are special requirements for attributes in the set-attributes section that most likely should apply for all.
