### ISSUE TITLE
Add a section on compatibility with OpenCensus to Compatibility doc

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-specification#766]
This issue is to track just the OpenCensus part of #114

**Comment by andrewhsu** [comment]
from the issue triage meeting today with TC, this can be kept for tracking for GA for just an editorial change only

**Comment by jsuereth** [comment]
Would mind assigning this to me?  I've already started on something (based on the existing Go/Java shims) here: https://github.com/jsuereth/opentelemetry-specification/blob/wip-opencensus-compatibility/specification/compatibility/opencensus.md

Thanks!
