### ISSUE TITLE
Should SpanProcessor.OnStart/OnEnd be called for non-recording Spans?

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#782]
As discussed in the SIG meeting, this issue is split from #634.

In https://github.com/open-telemetry/opentelemetry-specification/blob/bc272ab52869df2145065d55300d721ff008e34b/specification/trace/sdk.md#shouldsample, the spec describes that when the sampler returns NOT_RECORD, then

> IsRecording() == false, span will not be recorded and all events and attributes will be dropped.

Should the SpanProcessor be notified in this case? If so, should it only be notified for the start event, or also for the end event (OnStart can be invoked immediately without much hassle; OnEnd would preclude implementation of an unsampled span with a default span, because it would need a reference to its SpanProcessor).

I assume we agree that the SpanProcessor must be invoked for not sampled but recorded spans, but this could also be made explicit.

Assigned @alolita as per https://github.com/open-telemetry/opentelemetry-specification/issues/634#issuecomment-672055000

**Comment by cijothomas** [comment]
@alolita I had opened a PR to address this, and hopefully we can close this once its merged.
