### ISSUE TITLE
Why do we need @Nullable Boolean hasRemoteParent in shouldSample?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#79]

**Comment by songy23** [comment]
To support `always-parent` sampler, which I remember may become the default sampler.

**Comment by bogdandrutu** [comment]
Not needed for the moment I think.

**Comment by bogdandrutu** [comment]
Closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-specification/issues/164
