### ISSUE TITLE
Towards 1.0: increasing velocity

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#792]
OpenTelemetry is marching towards version 1.0. We delayed this release for almost a year from the originally planned timeline. There were many reasons for this delay. But now we committed to ship a [stable release this year](https://medium.com/opentelemetry/ga-planning-f0f6d7b5302).

This post highlights two big improvements and some recommendations we want to make in our process. We believe these improvements will increase velocity of spec development and decision making while maintaining the high bar of our commitment for OpenTelemetry stability, compatibility and performance. 

## Don’t let PRs and issues rot

As for any open source project, there are many contributions coming to OpenTelemetry that might not necessarily be aligned with the project immediate goals or long term roadmap. Unfortunately like in many projects, the queue of incoming PRs and issues is often a FIFO. Issues and PRs are being reviewed sequentially. This leads to less time spent on important PRs and a lot of time spent on debates that can be postponed. Even worse, some PRs and issues simply stay inactive as either those issues are not high priority or get lost in the queue of other less important discussions.

We will fix it by assigning every PR to a random Technical Committee member to drive it to conclusion. Every PR should either be accepted (with comments addressed), declined (as out of project scope, inacceptable change or low quality contribution), or postponed (by closing the PR and filing a tracking issue for the next milestone).

Being decisive like this is a tough job. It may feel very personal when somebody's contribution got turned down. As the milestone comes very close we DO believe that this is a necessary change. Later we may want to revisit this approach and give more time for contributions to shape and land in specification.

## Increase the Technical Committee size

We feel it is the right time to increase the size of the Technical Committee. This will spread the load of maintaining the project and allow new members to help shape and adjust the project roadmap.

In the Technical Committee we value ongoing commitment for the project and demonstrated contributions. We recognize that these people demonstrated alignment with the project roadmap, experience, and long ongoing commitment (alphabetical order): 
- Armin (Dynatrace), @arminru
- Christian (Dynatrace), @Oberon00
- Josh (Lightstep), @jmacd
- Tigran (Splunk), @tigrannajaryan 

The plan is to increase the size of TC to 7 members. And we will hold the vote on September 9th. This month, Technical Committee members will pay more attention to the work done by these candidates and other contributors for a fair vote in September.

## Other things

There are many more things you can do to help OpenTelemetry reach 1.0. A few suggestions on how to make better contributions and increase velocity.

When you submit PR - make sure to find a buddy to review and approve it fast. Approval, even from the same company, ensures that the PR was looked at and likely doesn’t have minor issues or mistakes. PRs approved by at least one person would generally be looked at faster.

Reviewing PR - make sure to tell whether the comment or suggestion is blocking or non blocking. With various time zones and a big number of PRs, an unresolved comment that wasn’t meant to be blocking slows down the process significantly.

Chop woods and carry water contributions are very important. There are many areas needing clean up, and help there is much appreciated. When submitting a PR like this - make sure to explicitly highlight this in description. PRs that do not change semantics of specs are very easy to review and will be merged faster.

Do you have other suggestions or want to nominate more people for the Technical Committee vote? Contact us at cncf-opentelemetry-tc@lists.cncf.io.

**Comment by Oberon00** [comment]
Hi, it's probably a bit late for me to say this but: I feel very honored that I've been nominated as a TC member. 😊 Unfortunately, I don't believe I can commit the time that would be expected from someone in this position to the OpenTelemetry project currently. For example, I'm not even a member of any SIG (except that I'm a spec-traces-approver). Since I would not be able to accept the position of a TC member at this time, I have to ask you to please remove me from the September vote.

**Comment by bogdandrutu** [comment]
Unfortunately because some personal issues and schedule issues we have to delay the vote for one day until Thursday 9/10. Hopefully nothing changes but wanted to let you know about this change

**Comment by SergeyKanzhelev** [comment]
Technical committee recognized continued investments and deep understanding of the the project technical direction of all nominees. @arminru, @jmacd, and @tigrannajaryan were unanimously voted to be on a technical committee. Congratulations!

Please e-mail us at cncf-opentelemetry-tc@lists.cncf.io your preferred e-mail address.

**Comment by SergeyKanzhelev** [comment]
We will be discussing effectiveness of the existing processes and improvements we have to make. All updates would be announced separately. This issue is complete and we are full speed ahead towards 1.0 release.
