### ISSUE TITLE
Clarify event timestamp is optional as data or not

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#796]
Currently, the spec defines `Event` as having an optional timestamp

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events

It's unclear whether this means that it's ok to add an event omitting the timestamp entirely, or this means that the API should use current timestamp when an event is added without timestamp.

This originally came up in this discussion

https://github.com/open-telemetry/opentelemetry-java/pull/1434#discussion_r458497420

If an event can have no timestamp, then I would record an exception without timestamp. If an event must have a timestamp, I would always provide a way to record an exception with a user-provided timestamp for symmetry in the API and because it's always possible for a user to provide a better timing than we can provide.

**Comment by arminru** [comment]
In the first paragraph of the section linked above the spec says:
> Events have a time associated with the moment when they are added to the Span.

Therefore I would interpret the optional timestamp mentioned below to be an API parameter to override the default timestamp, which would otherwise be applied by the SDK but would view the timestamp as always present on an event.
If we agree that this is the intention, we should clarify this in the spec and verify that our default SDKs adhere to that.

**Comment by anuraaga** [comment]
Thanks - yeah I'm guessing we'll want to clarify that a default timestamp should be used when not provided. I guess "when they are added to the Span" could probably also be generalized, the point is when the event occurred, not when it's added to our data model (latter is a fallback if we don't have a better recording of the former).

**Comment by bogdandrutu** [comment]
I would like to make sure the text does not encourage users to provide custom timestamp. More like a custom timestamp can be provided if user cannot record the event around the time it happened.

**Comment by bogdandrutu** [comment]
So my proposal is to say that it is optional and also discouraged to use unless no other way to record the event when happened

**Comment by carlosalberto** [comment]
"So my proposal is to say that it is optional and also discouraged to use unless no other way to record the event when happened"

+1 to this.

**Comment by anuraaga** [comment]
Is it an option to replace user timestamp with user time delta, from start of span? I agree that passing in a wall time as the timestamp is never a good idea, but I wouldn't flat out discourage providing a timestamp from closer to when an event happened if it's possible. In particular for frameworks, there can be quite a bit of time between when an event happens and when it's made available to an interceptor, or similar that is the interface for tracing.

If changing the parameter type doesn't make sense we can go ahead and update docs with a warning that a timestamp should only be provided if it's computed using a monotonic clock based on the start time and left out otherwise.

**Comment by bogdandrutu** [comment]
I would not get into that details of how time should be computed. What I am trying to say is if possible to record event when that happened is preferable, otherwise user should provide the timestamp

**Comment by bogdandrutu** [comment]
This way we let the implementation do what is better for that implementation.

**Comment by bogdandrutu** [comment]
@anuraaga do we need any changes in specs based on this discussion? If yes do you mind creating a PR? Otherwise let's close this.

**Comment by anuraaga** [comment]
@bogdandrutu Yeah I think a small clarification to the spec will help, will send a PR for it by early next week. Feel free to assign this issue to me as a reminder :D
