### ISSUE TITLE
Define if user-defined timestamp for events must be between span start and end or not

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-specification#798]
Related spec section:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events

We should specify if the user-provided timestamp has to be between start and end of the span (inclusive) or not. Otherwise it will likely mess up analysis and presentation on some backends since an out-of-range timestamp might be unexpected. If it's out of this range, it should be normalized to either start or end, whichever is closer.

If there are valid reasons for the event timestamp to be before the span started or after it ended, however, this should also be clearly specified in the spec to make potential consumers aware of this and allow proper handling.

**Comment by anuraaga** [comment]
I guess normalizing an event to be before the end time would have to be done in the exporter. Doable, but a weird layer to handle specs that are outside the usual scope of export.

**Comment by arminru** [comment]
Both could be done by the SDK itself as well (checking against span start on `Span.AddEvent`, checking against span end on `Span.End`).

**Comment by anuraaga** [comment]
Ah yeah, there's still time to do stuff in end before handing off to exporter, sorry for the noise :)

**Comment by bogdandrutu** [comment]
SDK should not do this kind of smartness. We should pass everything to the user.

**Comment by bogdandrutu** [comment]
But I would always approve a PR to remove custom times provided by the user where not needed.

**Comment by jmacd** [comment]
Please remember our OpenTracing compatibility promise. OpenTracing supported user-supplied timestamps on Span events and did not specify any range restrictions.

**Comment by carlosalberto** [comment]
To me, this sounds like a SHOULD in the Specification, and optionally the default SDK could provide a SpanProcessor to normalize things like this.

**Comment by bogdandrutu** [comment]
I think it is enough disagreement that we cannot enforce this requirement, and we should pass the timestamps (in the way they were provided) to the SpanProcessor -> SpanExporter and do a normalization if needed. This can be done after GA, and should not be a requirement in the API.

**Comment by carlosalberto** [comment]
>  This can be done after GA, and should not be a requirement in the API.

SGTM.

**Comment by arminru** [comment]
Alright, I'll document this in the spec then so that consumers are not overrun by unexpected out-of-range timestamps.
