### ISSUE TITLE
Consider removing semver: prefix from version or moving to another attribute

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#802]
Currently, we add `semver:` prefix to versions that are semantic versions. It seems to have come from this comment https://github.com/open-telemetry/oteps/pull/38#issuecomment-529155129.

I have the same question, which I don't see answered in the otep, on what would anyone actually do with the semver prefix in practice. On the flip side, it seems to significantly degrade the UX of using the attribute in systems that don't natively recognize this prefix scheme - I would expect querying for traces with something like `version == 1.2.3` to _just work_. Can we remove the prefix or move the type to a subattribute to allow simple queries to work on versions?

**Comment by Oberon00** [comment]
My impression is that that specification part has been mostly ignored and most have been using unprefixed versions anyway so far. I hope someone can prove me wrong, but if not, I support removing the version prefix spec.

**Comment by Oberon00** [comment]
>  what would anyone actually do with the semver prefix in practice

There is a case where this could in theory matter in practice (😉): A hash/commit ID that only has numbers is indistinguishable from a semver version with only the major part displayed (1.0 without traling `.0`).

**Comment by anuraaga** [comment]
Yeah knowing a value is a git hash could allow linking back to a git repo indeed. At the same time, I think we should let the users define what version scheme they want to use - if 00000000 is the version they want, then regardlessly of if it's git or not I think they should be allowed to search by `version == 00000000`. So to me removing the prefix seems obvious and if differentiating semver vs gitver vs plain version is important it could be another attribute that backends may use for better linking experience. Bandwidth is probably not a big factor here since version is almost always on the resource which is relatively low bandwidth.

**Comment by reyang** [comment]
During triage meeting, we need to make a decision whether we want this or not ASAP.

**Comment by anuraaga** [comment]
So, any thoughts? Can I send a PR to remove the version prefix? Let me know what works :)
