### ISSUE TITLE
Consider adding a human-readable error in the OTLP response

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#808]
OTLP/HTTP currently returns error text in Protobuf, which is binary-encoded unless JSON encoding is used. This is not very troubleshooting friendly.

We should consider returning the error text in headers. See original discussion https://github.com/open-telemetry/opentelemetry-specification/pull/794#discussion_r469747367

**Comment by anuraaga** [comment]
One idea is to just copy the code and message as response headers, similar to what gRPC does.

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

**Comment by tigrannajaryan** [comment]
We added error texts to the payload: https://github.com/open-telemetry/opentelemetry-proto/blob/724e427879e3d2bae2edc0218fff06e37b9eb46e/opentelemetry/proto/collector/logs/v1/logs_service.proto#L78

I am closing this since it does not seem to be needed anymore.
