### ISSUE TITLE
messaging and message namespaces too similar

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#812]
We currently have two namespaces that seem very similar, `messaging` for general publish consume message queues and `message` for events on a gRPC span. This similarity is confusing, especially with names like `messaging.message_id` vs `message.id`. I suspect a big reason is the latter doesn't seem to actually be namespaced. Does it make sense to add `grpc.` prefix? Anecdotally, the first revision of my PR to add messaging attributes to Java SDK removed the gRPC ones because at first I thought they're the same 😅

**Comment by Oberon00** [comment]
Note that this issue was created in response to https://github.com/open-telemetry/opentelemetry-specification/issues/726#issuecomment-674463277

**Comment by Oberon00** [comment]
Spec quote from https://github.com/open-telemetry/opentelemetry-specification/blob/v0.6.0/specification/trace/semantic_conventions/rpc.md:

> In the lifetime of a gRPC stream, an event for each message sent/received on
client and server spans SHOULD be created with the following attributes:
>
> ```
>-> [time],
>    "name" = "message",
>    "message.type" = "SENT",
>    "message.id" = id
>    "message.compressed_size" = <compressed size in bytes>,
>    "message.uncompressed_size" = <uncompressed size in bytes>
>```

I think another problem with this is that it does not conform to the usual semantic convention formatting, i.e. it does not use a markdown table.

**Comment by Oberon00** [comment]
I have two questions:

1. Does anyone know of an instrumentation actually supporting these conventions, i.e. producing these message events?
2. Could this be generalized to other streaming RPC systems? Maybe this could even be moved to a general "network message" event semantic convention (except for the ID attribute which is defined in a very gRPC-specific way).

**Comment by bogdandrutu** [comment]
We used this in OpenCensus.

**Comment by Oberon00** [comment]
Do we still need it? Removing this spec part would be the quickest way to solve the problem 😄  Or we can also say that while this does not conform to current best practice, we leave it as-is for OpenCensus compatibility. But we have broken OC compatibility already at most places in our semantic conventions, so I don't think it's a good argument.

**Comment by bogdandrutu** [comment]
@Oberon00 the argument is simple, no way to convert MessageEvent from OC to OpenTelemetry, so we cannot implement the bridge.

**Comment by anuraaga** [comment]
@bogdandrutu What do you think about prefixing the keys with `grpc.`? I don't know if the history of the `gRPC` section [here](https://github.com/open-telemetry/opentelemetry-specification/blob/v0.6.0/specification/trace/semantic_conventions/rpc.md#grpc) is trying to keep open to adding non-gRPC systems to the same spec, but if we don't have any plan for it I'd assume we're keeping it gRPC-specific for GA. In which case, adding that prefix can help a lot with reducing confusion.

**Comment by ktoso** [comment]
Hi everyone, just to chime in from a perspective of actor systems such as [Akka](http://akka.io) or [Orleans](https://dotnet.github.io/orleans/). Those systems also are have RPC calls (and streams) and such events (sent/received) attached to spans match directly as well. I'm not sure if it's worth prefixing the recommended `"message.[...]"` annotation keys with `grpc.` as that needlessly ties the two together and all other runtimes would have to do prefixing as well then I suppose to be consistent. In such spans it is already known from `rpc.system` if it's grpc span or not after all.

**Comment by andrewhsu** [comment]
from the issue triage meeting today with TC, closing this because this is too late for GA
