### ISSUE TITLE
API: Raw vs. other metrics / measurements are unclear

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#83]
Re-posting questions from https://github.com/open-telemetry/opentelemetry-java/pull/226#issuecomment-488206616

* in many other metrics APIs that allow recording gauges, timers, and/or histograms, the recording API is still about recording the raw measure, but behind the scene the library may or may not perform some form of aggregation, like LastValue for gauges, or Histogram for timers. So the distinction between raw measure and Gauge/Histogram is not clear to me, since from instrumentation point of view it's always recording the raw value.
* on the other hand, counters seem to be fundamentally different and can never be captured via raw measure, is that correct? This breaks the mental model for me.
* being able to change aggregation without touching instrumentation is great - I often wanted to see something like queue_length not as a gauge but as a histogram (incidentally tally didn't support histograms for non-timer values)
* application of request-scoped tags is also very tricky. As @bogdandrutu said, there are some stats that don't make sense to be labeled with request-scoped tags, e.g. CPU utilization. For measures where we do want to apply context tags, the ability to define views also provides a place to define context tag rules, potentially on a per-measure basis, e.g. "allow tags A and B for measureX, but only tag B for measure Y" (however, see next item).

**Comment by jmacd** [comment]
@yurishkuro Can you clarify "counters seem to be fundamentally different and can never be captured via raw measure, is that correct?". I think in terms of a raw measurement being a simple numerical value. Whether we call something a count or a gauge depends on the aggregations that make sense. If you're thinking of something as a count, it means you intend to compute a sum or a rate, but you could meaningfully ask for a distribution of a count increments too.

**Comment by yurishkuro** [comment]
@jmacd that's fair

**Comment by tedsuo** [comment]
@yurishkuro I believe the new metric spec (https://github.com/open-telemetry/opentelemetry-specification/pull/250) has changed significantly and addresses these issues. Can we close this issue?

**Comment by yurishkuro** [comment]
I suggest to mark the metrics spec PR as resolving this issue.

**Comment by jmacd** [comment]
I marked this as resolved in the corresponding OTEP but it doesn't show up in this repo. 
See the bottom of https://github.com/open-telemetry/oteps/blob/master/text/0003-measure-metric-type.md
I'm not sure how else to "mark the PR" as resolving this issue, but happy to do so.

**Comment by yurishkuro** [comment]
I don't think you can auto-resolve issues from another repo. But the spec change is in the same repo so will auto resolve it

**Comment by jmacd** [comment]
To be clear, does this mean I should reference the issue from the spec
somehow? Or is there a way to auto-resolve an issue from a GH PR?

**Comment by yurishkuro** [comment]
In the PR description you can say "resolves ####" and the issue will be closed when PR is merged

**Comment by SergeyKanzhelev** [comment]
I believe it is resolved via #299
