### ISSUE TITLE
Semantic attributes for language runtime

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#830]
Looked around and couldn't find these, does it make sense to have semantic attributes for a language runtime? For example

`process.runtime.name` - a name of a runtime, for example Oracle JDK, .Net Core, PyPy
`process.runtime.version` version of the runtime in `runtime.name`

For compiled languages I guess we wouldn't fill them, though putting information about the compiler (if available) could be an option.

**Comment by arminru** [comment]
I think it would make sense to add this 👍
For the runtime name I suggest adding a list of well-known values like we have for the database vendor (`db.system`) in the [semantic conventions for DB calls](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#notes-and-well-known-identifiers-for-dbsystem).
