### ISSUE TITLE
Clarify whether BatchSpanProcessor scheduledDelayMillis is between batches or entire processing of queue

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#849]
Currently we define `scheduledDelayMillis`, `maxQueueSize`, and `maxExportBatchSize`.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#batching-processor

It's not clear to me whether `scheduledDelayMillis` is supposed to be time in between exports of chunks of size `maxExportBatchSize`, or if it's the delay between processing the queue, when processing we export as many batches as we can, and then wait for the delay amount until the next set of batches. The wording in the spec seems closer to the former, but go and java at least seem to implement as the latter.

**Comment by anuraaga** [comment]
Hey - this question came up. Does anyone happen to have any suggestions on how to handle schedule delay?

**Comment by Oberon00** [comment]
> It's not clear to me whether scheduledDelayMillis is supposed to be time in between exports of chunks of size maxExportBatchSize, or if it's the delay between processing the queue

IMHO it has to be the latter, otherwise you would be severely limiting throughput.

**Comment by anuraaga** [comment]
@Oberon00 Yeah I think that makes sense, it actually was a silly question. I think what I meant to ask, was this other one, should we eagerly export batches? Currently Java exports as soon as the queue is over `maxExportBatchSize` regardless of interval - I think doing so could cause BSP to be more active than one might want when at low throughput. At high throughput, I think there isn't a big difference since you'd be continually processing the queue anyways. But there does seem like there could be a middle ground that has degraded performance, not sure though.

**Comment by iNikem** [comment]
+1 in favor of eager exporting

**Comment by dyladan** [comment]
I am also in support of eager exporting. I see 2 obvious ways to do it:

1. When the `scheduledDelayMillis` timer is triggered, export as many batches as required to empty the queue
2. When there are `maxExportBatchSize` spans in the queue, trigger an export even if it means exporting early

**Comment by dyladan** [comment]
@open-telemetry/technical-committee I think this is quite an important issue that likely affects many SDKs. As @morigs pointed out in the related js issue https://github.com/open-telemetry/opentelemetry-js/issues/3094 the current situation effectively works as a rate-limiter which I believe is not be the intended effect. JS would like to implement a fix for this, but we don't want to do something against the spec.

**Comment by yurishkuro** [comment]
imo the export should happen once the desired batch size is reached or the delay timer ticks, whichever is earlier. The former protects against unnecessarily large batches, the latter protects against sitting on the data that trickles in slowly.

**Comment by tigrannajaryan** [comment]
> imo the export should happen once the desired batch size is reached or the delay timer ticks, whichever is earlier. The former protects against unnecessarily large batches, the latter protects against sitting on the data that trickles in slowly.

This. This is also exactly what we do in the Collector if I remember correctly.

If the spec does not describe this behavior I would argue it is a spec bug.
