### ISSUE TITLE
Rename SimpleSpanProcessor

### ISSUE THREAD

**Issue by huntc** [open-telemetry/opentelemetry-specification#858]
Naming anything “simple” is both subjective and uninformative. I propose that we rename SimpleSpanProcessor on this basis. 

Some ideas for a new name:

* SpanProcessorStage
* StreamingSpanProcessor
* SameThreadSpanProcessor
* CurrentThreadSpanProcessor
* DirectSpanProcessor
* CallingThreadSpanProcessor
* SingleSpanProcessor

Criteria to consider:

* Concurrency and resources 
* distinction of batch (single is the antonym to batch)

Perhaps we can vote on comments, including those that think renaming the class is a bad idea.

**Comment by reyang** [comment]
The spec does not contain `SimpleSpanProcessor` https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#built-in-span-processors.

If we do need to align on the class name, I think we need to have "Export" (or "Exporting") as part of the name since this processor is dedicated for exporting spans.

**Comment by Oberon00** [comment]
It has [Simple Processor](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#simple-processor)

**Comment by carlosalberto** [comment]
> My preference is for SingleSpanProcessor

+1 on this name (if we decide to change it, as I personally don't _dislike_ `SimpleSpanProcessor`). My reason is the same as @huntc : to have its name describe it as a counter part to `BatchSpanProcessor`.

Also: maybe do the `Exporter` word inclusion in the name in a follow up?

**Comment by cijothomas** [comment]
I think this issue can be closed as the ship has sailed with the name "SimpleSpanProcessor", and cannot be changed until spec does major version bump!
