### ISSUE TITLE
API: Provided Samplers in the SDK

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#87]
Currently we in the API we provide implementation of the Samplers with alwaysOn and alwaysOff (neverSample).

Proposing:
1. Change the name to more clear names as defined in https://github.com/open-telemetry/opentelemetry-proto/blob/master/src/opentelemetry/proto/trace/v1/trace_config.proto#L53
2. Add the AlwaysParent sampler which probably should be the default Sampler when no implementation linked.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu assigned to you as you are working on sampling PRs.
