### ISSUE TITLE
Use the draft of Baggage w3c spec instead of custom otcorrelation header

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#879]
Follow up from https://github.com/open-telemetry/opentelemetry-specification/pull/857. See related issues

**Comment by SergeyKanzhelev** [comment]
CC: @dyladan @mwear

**Comment by bogdandrutu** [comment]
the reason to use a different name is to protect against backwards incompatible changes in the current w3c spec. If we are confident that it will not happen we can use the w3c name.

**Comment by cijothomas** [comment]
Based on this comment, (https://github.com/open-telemetry/opentelemetry-specification/issues/536#issuecomment-665107640), we should now start using the w3c name, right?

**Comment by bogdandrutu** [comment]
Because changes can still happen, for us to have a way to support this I would suggest that we use the format with a custom name. When the format becomes official we will have a simple change to do: read any of the headers and maybe emit both headers; in 1y remove the support to read both and only emit the new.

If we use the same name and in an unlikely event of the format change we will not be able to make a transition, so I am willing to pay the cost of double writes and transition to avoid the case of never being compatible

**Comment by dyladan** [comment]
In the end, the TC has to decide what level of risk they want to accept here. The W3C talked about this and decided we think it is unlikely that there will be backwards incompatible changes, but that doesn't mean impossible. An advantage of using the W3C header is that when the spec is complete, otel doesn't have to worry about a migration strategy.

**Comment by andrewhsu** [comment]
From the issue triage mtg today, discussed this with @carlosalberto and this one looks like it may be a P1 so we can make sure we have this in before trace spec freeze.

**Comment by andrewhsu** [comment]
@bogdandrutu or @yurishkuro are either one of you able to be assigned this issue?

**Comment by tedsuo** [comment]
I am in favor of adopting this header now, if it looks like it is stable.

BUT. Know ye W3C members: once OpenTelemetry is out in the wild, it shall be YOU who will have to contend with the fact that this header will now be in production everywhere. So please make sure you are prepared for that. We may choose not to adopt a future breaking change, and the current version will become the de facto standard. So it goes both ways.

In all seriousness, given the overlap between OpenTelemetry and the W3C working group, I won't accept any kind of "whoopsies" on this front. A breaking change that cannot be handled effectively will probably result in the situation above. Let us do all we can to avoid that. If the above warning makes you shake in your boots, please retract the offer.

**Comment by andrewhsu** [comment]
from the maintainers mtg today, assigning to @bogdandrutu for initial assignee
