### ISSUE TITLE
What should we call the Tags package?

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-specification#9]
### Current Issue:
* `Tags` in OpenTracing currently maps to `Attributes` in OpenTelemetry.
* `Tags` in OpenCensus are also slightly different: no getters, and they are only available for metrics.

There is a fair amount of evidence that using the name `Tags` to describe this package is confusing to existing users of the previous projects.

###  Potential names:
* `Baggage`
* `Labels`
* `???`
* Live with `Tags` and confuse some people...

###  FAQ: What is the difference between Tags with TTL=0 and Context?
* If you put a value in `Tags`, that value is available via for OpenTelemetry to consume in metrics, traces, and logs. `Context` is purely for propagating application information within a single process: `Context` information not placed directly in `Tags` is not visible to the telemetry system.

### Conclusion:
Currently, there is a preference for calling this `Baggage`.
* Users may want to propagate baggage for reasons beyond just labelling telemetry data. For example, feature flagging in a distributed system.
* The term Baggage helps indicate to users that they are bloating their RPC calls with this information, so they should be careful about what they put in there. The costs associated with using this mechanism is a very important thing for users to understand.

We are planning to go with `Baggage` for now. Please post questions and comments if you feel this name is not accurate.

**Comment by SergeyKanzhelev** [comment]
In https://github.com/open-telemetry/opentelemetry-java/issues/11 we decided DistributedContext

**Comment by SergeyKanzhelev** [comment]
Closing as it was decided. If there are alternative proposals - please file a new issue
