### ISSUE TITLE
API: should types be thread safe?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#91]
See this comment: https://github.com/open-telemetry/opentelemetry-specification/pull/78/files/334747818bf8bca359aa35a6a6b81d1e880ed8b1#diff-79e4e1e0104e6afca76d39aadac18f20

We need to set an expectation on thread safety of APIs

**Comment by bogdandrutu** [comment]
Indeed some classes MUST be thread safe like Span or SpanData. I don't think SpanBuilder should be for example.

**Comment by SergeyKanzhelev** [comment]
closed via #104
