### ISSUE TITLE
API: Consider specifying the maximum value of EntryTTL.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-specification#93]
From discussion: https://github.com/open-telemetry/opentelemetry-specification/pull/73#discussion_r292176134.

**Comment by jmacd** [comment]
This must be addressed as we add OTEP 66 to the specification.

**Comment by jmacd** [comment]
We believe this is no longer needed, as the spec for context propagation has eliminated `Entry`. See #420.
