### ISSUE TITLE
HTTP semantic convention table is too wide

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#933]
See https://github.com/open-telemetry/opentelemetry-specification/blob/821118e5/specification/trace/semantic_conventions/http.md#common-attributes

The table is cut off at the right side on my 1920x1080 screen and you have to awkwardly scroll by selecting. The culprits seem to be the `http.response_content_length_uncompressed` and `http.request_content_length_uncompressed` attributes which have really long names.

![image](https://user-images.githubusercontent.com/849039/92608694-fadcd400-f2b5-11ea-8b17-2d12b2139d10.png)

...

![image](https://user-images.githubusercontent.com/849039/92608749-09c38680-f2b6-11ea-8da4-47578a5060cb.png)

**Comment by arminru** [comment]
Are you sure this warrants being labeled a bug? It's more a visual/UX nuisance in my opinion.
It's rather a bug that Github is only using half of the available screen width even if there are wider tables 😉
Any suggestion on how we could make it fit without having to rename the attribute?

**Comment by Oberon00** [comment]
Since we have no separate label for "minor nitpick", "bug" is the closes thing. The urgency/importance part should be covered by the "after-ga" label.

**Comment by Oberon00** [comment]
Unfortunately, I have no suggestion how to resolve this. If we could manipulate the CSS, we would be able to allow line breaks in code the first column.

Maybe we could leave out the prefix for such attributes, but just `response_content_length_uncompressed` would likely still cause a scrollbar.

Another solution would be to not use a table, but an enumeration like:
* **`http.request_content_length_uncompressed`** (optional number): Brief brief.

  Note note note (no footnote-splitout required).

  **Examples:** 5493

CC @thisthat

**Comment by arminru** [comment]
@Oberon00 It would not only cause a scrollbar but also confusion if the prefix is left out only for some attributes (or suddenly for all of them). A list should work, yes.
I, personally, however, am fine with the current tables (even if one has to scroll on this particular one when viewing it on the Github website).

**Comment by Oberon00** [comment]
This particular table seems fine. Closing this in favor of #1925
