### ISSUE TITLE
Inconsistent Sampling Result Names

### ISSUE THREAD

**Issue by ejsmith** [open-telemetry/opentelemetry-specification#940]
### Current Names
- `NOT_RECORD`
- `RECORD`
- `RECORD_AND_SAMPLED`

Seems like we should pick between present tense or past tense and make it consistent. I am proposing that we use past tense as in it's a decision that has already been made.

`NOT_RECORD` doesn't make sense. It is not correct English.

Related: https://github.com/open-telemetry/opentelemetry-specification/pull/938

**Comment by andrewhsu** [comment]
from the spec sig mtg today, set priority to p3
