### ISSUE TITLE
Remove semantic convention for http.status_text

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-specification#950]
[HTTP semantic convention](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md) defines `http.status_text` as [`HTTP reason phrase`](https://tools.ietf.org/html/rfc7230#section-3.1.2). But even RFC sounds like that reason phrase is an obsolete artefact (emphasis is mine):

> The reason-phrase element exists for the sole purpose of providing a
   textual description associated with the numeric status code, **mostly
   out of deference to earlier Internet application** protocols that were
   more frequently used with interactive text clients.  A **client SHOULD
   ignore** the reason-phrase content

Should we drop this semantic attribute as serving no actual purpose?

**Comment by Oberon00** [comment]
We inherited this attribute from OpenCensus AFAIK. But if the RFC says it SHOULD be ignored then I think there would be a point in doing so. I think it also does not exist from HTTP 2 on.

We could also consider marking the attribute as deprecated (should not be set by instrumentation, but if you get it, this is the meaning).

**Comment by carlosalberto** [comment]
> We could also consider marking the attribute as deprecated (should not be set by instrumentation, but if you get it, this is the meaning).

I'd rather remove it (unless OC really needs it for backwards compatibility).

**Comment by bogdandrutu** [comment]
+1 to remove this

**Comment by arminru** [comment]
Done in #972.
