### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-specification#965]
**What are you trying to achieve?**
Improved error handling, based on [OTEP 136](https://github.com/open-telemetry/oteps/blob/master/text/trace/0136-error_flagging.md).
* Reduce the number of Status Codes.
* Add Status Source.
* Indicate which semantic conventions generate errors.

**Additional context.**
OTEP PR: https://github.com/open-telemetry/oteps/pull/136

This issue supersedes https://github.com/open-telemetry/opentelemetry-specification/issues/706.

**Comment by arminru** [comment]
Classified as p1 since it supersedes the p1 #706 and is quite pervasive.

> Indicate which semantic conventions generate errors.

Should we split this into a separate (p3 or after-ga) issue?

**Comment by tedsuo** [comment]
@arminru I will include the HTTP status codes as part of this issue. I agree a separate issue for the rest of the semantics.

**Comment by carlosalberto** [comment]
@tedsuo @arminru my impression is that we should close this issue, as the core has been implemented/updated - the remaining semantic conventions to be updated can be labeled as "good do have for GA", as they technically won't break the API ;)

**Comment by carlosalberto** [comment]
Closed via #966

**Comment by arminru** [comment]
Follow-up for the semantic conventions: #1003

**Comment by arminru** [comment]
@open-telemetry/technical-committee @tedsuo

I just noticed this issue was closed without adding Status Source (instrumentation | user), which was part of the OTEP and also the issue description ("Add Status Source.") to the spec in #966.

Was this missed or intentionally dropped from GA?

**Comment by carlosalberto** [comment]
@arminru IIRC StatusSource was removed based on public feedback. @tedsuo May remember the details ;)

**Comment by arminru** [comment]
I added #1092 (labeled as after-ga) to keep track of this part.
