### ISSUE TITLE
Trace semantic conventions for (non-traditional) messaging

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-specification#977]
While reviewing the trace semantic conventions for messaging (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md), there is a bias towards more "traditional" message brokers.

This results in attributes being set for messaging with Kafka, AMQP, possibly others, that don't fit these models.

As there are several places where this is a problem, I wanted to ask what the preferred approach for discussing them would be?

Listing each specific instance and linking to the doc in this issue, or creating a PR proposal with suggested changes that can be discussed there?

**Comment by Oberon00** [comment]
You mean there are required attributes that don't apply for these? I don't think non-required attributes that do not apply to Kafka, etc are a problem. But I think it's indeed best if you make a PR, if you already have a solution in mind.

**Comment by kenfinnigan** [comment]
Thanks @Oberon00.

I think there are a few things that mismatch either from the text content, or actual attributes.

I'll work on a PR that attempts to fix them, but if there are ones that raise big issues I will explicitly call them out in the issue first.

Could you assign the issue to me?

**Comment by Oberon00** [comment]
Thank you for taking care of it! 👍
