### ISSUE TITLE
Should SpanProcessors be invoked in the reverse order they were registered?

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#987]
The Go SIG recently had [an issue](https://github.com/open-telemetry/opentelemetry-go/issues/1174) opened related to this question. Customarily span processors for exporters are the first things registered with a TracerProvider. If a user wants to process spans in a custom way they will register a processor with the instantiated TracerProvider. However, given the processors are invoked in the order they were registered, the span will already have been sent to the exporter when the user defined span processor is invoked effectively discarding its operation. This is following [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-processor):

> Span processors can be registered directly on SDK TracerProvider and they are invoked in the same order as they were registered.

It is recognized that a user could instantiate the TracerProvider and then explicitly reverse the registration of the span processors. However, this is not the default workflow and is already proving frustrating or non-intuitive to users.

Should this be changed to reverse order? That would ensure the exporter is the last span processor invoked and all user registered span processors would effect change.

**Comment by iNikem** [comment]
Span is set to exporter during `SpanProcessor.onEnd` operation, right? That method receives already ended span, which is immutable. So regardless of invocation order one SpanProcessor cannot change ended span for another SpanProcessor. How do you imagine it to work?

**Comment by MrAlias** [comment]
> Span is set to exporter during `SpanProcessor.onEnd` operation, right? That method receives already ended span, which is immutable. So regardless of invocation order one SpanProcessor cannot change ended span for another SpanProcessor. How do you imagine it to work?

The ask in the linked issue is around filtering out short lived spans. It is only after the span is ended that the span length is known. If a users wants to filter out these spans and not send them to the exporter they would need to process the span prior to export.

@iNikem are you saying this is unsupported behaviour for OTel?

**Comment by iNikem** [comment]
You can do that, but your SpanProcessor has to be in the chain leading to span exporter, not external to that. Or you can do that in span exporter itself.

**Comment by MrAlias** [comment]
> You can do that, but your SpanProcessor has to be in the chain leading to span exporter...

Gotcha, it sounds like we are talking about the same things then.

If the user instantiates the TracerProvider with an exporter that is wrapped in a span processor *as is the default way to setup a TracerProvider*:

```
---------------------------
| SpanProcessor(Exporter) |
---------------------------
```

And then registers their span processor

```
---------------------------    ----------------------------
| SpanProcessor(Exporter) | -> | SpanProcessor(UserLogic) |
---------------------------    ----------------------------
```

The user logic will currently not have an effect on the span sent to the exporter.  The ask from the user of OTel based on a usability perspective is can the chain be a LIFO execution stack instead of FIFO? That would allow the default way to setup a TracerProvider to be extended directly instead of requiring users to build the processing stack.

**Comment by iNikem** [comment]
Here is the problem. When you register the second SpanProcessor it does not go as in your picture. It goes this:

```
---------------------------   
| SpanProcessor(Exporter) | 
---------------------------  
----------------------------
| SpanProcessor(UserLogic) |
----------------------------
```

At least this is my understanding of SDK spec and of Java implementation. Registering SpanProcessor does not add it to an existing pipeline/chain. It just adds a new processor totally independent from the previous ones.

**Comment by MrAlias** [comment]
Ah! That helps clarify things and refresh my mental model of this. That is also how we built the Go implementation. I should be able to readdress the original issue now. Thanks @iNikem.
