### ISSUE TITLE
Discuss using http.request.* and http.response.*

### ISSUE THREAD

**Issue by danielkhan** [open-telemetry/opentelemetry-specification#99]
For HTTP we often have to distinguish between request and response which leads to long field names like `http.requestheaders` and `http.responseheaders`.

So instead of using `http.requestheaders` it could be `http.request.headers`, `http.response.headers`. 

This might be also applicable to other protocols.

ECS does something similar https://github.com/elastic/ecs/blob/master/schemas/http.yml

**Comment by jmacd** [comment]
Closing this as there are no semantic conventions for request and response headers. Please reopen if you think we should have semantic conventions for request and response headers at this time, or submit a PR to the spec.
