### ISSUE TITLE
Reconsider `required` property for `process.*` semantic conventions

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-specification#997]
Currently we define `process.pid` and "at least one of `process.executable.name`, `process.executable.path`, `process.command`, or `process.command_line`" as required, if _any_ resource attribute in the process namespace is present. I don't think this is a sensible requirement, since there are multiple concerns (or multiple features from a backend's perspective) mixed together in the process namespace. I could well imagine that one might want to report the runtime (added in #882) but has no need for reporting the PID and/or the entire commmand line. This would currently not be "legal", however.
I think we should drop the entire `required` column for the process namespace.

This is related to #653. I do, however, think of the trace semantic conventions more as distinct features, where defining some set of attributes as essential to provide some reasonable output makes more sense than for the process resource attributes.

**Comment by Oberon00** [comment]
I think we should just put process.runtime into it's own resouce type (without changing the names)

**Comment by Oberon00** [comment]
@open-telemetry/technical-committee I think this issue should be allowed-for-ga.

**Comment by andrewhsu** [comment]
from the spec sig mtg today, re-triaged for allowed-for-ga
